### ISSUE TITLE
Gson annotations

### ISSUE THREAD

**Issue by cavarzan** [requery/requery#1]
I notice that generated class files doesn't support annotations like `@SerializableName` from Gson. Support the annotations might be good to reuse classes for API requests or for validations and something like that.

Do you think that this matches with the goal of the project? I've forked the project and will take a look if I can provide support for this kind of annotation in generated fields, I don't know if this can be possible with the `EntityProxy`.

BTW, amazing project! I worked with JPA for 7 years and never found something so completed in android like this.

**Comment by npurushe** [comment]
Thanks for the feedback! So there are two supported approaches to generate the final entity class, you can create an interface with getter style methods representing the entity attributes or you can create an abstract class and add fields representing those attributes. If you use the abstract base class approach that should support what you need, because then you can apply any annotations you like to the field.

**Comment by cavarzan** [comment]
@npurushe amazing! I tried only the interface with annotation, using abstract class worked fine :smile:

**Comment by cavarzan** [comment]
@npurushe just offtopic but I didn't find any reference in code: Can I edit a @Generated value? I'm wrapping the DbEntity to domain entity but the back conversion I didn't find a way to set the generated ID.

**Comment by npurushe** [comment]
@cavarzan Setters are not generated for @Generated values as the source of the value should come from the database. If you make it not @Generated but just a @Key then it will have a setter. What's your use case for overwriting the @Generated value?

**Comment by cavarzan** [comment]
@npurushe Nothing special, just for curiosity. Just one more to stop hehehe... did android has a configuration do fetch all entities in a class? When I map a entity with @ManyToOne (just on one side) the entity is not loaded from queries. Checked in database and has a object saved, but is not loaded.

**Comment by npurushe** [comment]
@cavarzan All non basic attributes are loaded lazily by default. If you call the getter for it is loaded then correct? 

Would you like an option to load relationships eagerly? Something like that will be added soon since that is also an option in JPA (FetchType.EAGER).

**Comment by cavarzan** [comment]
@npurushe even calling the getter the entity is not loaded (I dont know is the transaction is already closed), but eager feature it would be nice.
I notice that if the object was not loaded by requery (created manually), the CascadeAction.NONE is still trying to persist the object, but I will investigate more about it.

**Comment by cavarzan** [comment]
I'm creating entities manually because my repository layer is separated from views, so its differents objects. Maybe this manual creatiion is causing this.

**Comment by npurushe** [comment]
That sounds like it might be the cause, basically if you have a case like this:

```java
Person person = randomPerson();
data.insert(person); 
Phone phone1 = randomPhone(); 
person.getPhoneNumbers().add(phone1); 
data.update(person);  // this is required to establish the relationship between Person and their Phone#
assertSame(person, phone1.getOwner());
```
For example if you create a new Phone() the person it belongs is not realized until you persist it. After you persist it, it will appear always to a call to person.getPhoneNumbers(). You can also then lookup the phone by some key and then call phone.getOwner() that will also work. Basically if its something that was already persisted you should look it up by it's key and not create a new object.
