### ISSUE TITLE
Calling just insert/update without subscribe don't persist the object

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#101]
Let's say I have a list of objects retrieved from an rest api, I want to synchronize this objects with local data ones, for this I iterate over this objects and I check with my database if they exists, then I change some fields and I call the update method for the found entity, if not I create a entity object and I persist with insert method:
```java
List<ModelDTO> models = new ArrayList<>();
for (ModelDTO model : models) {
    getData().findByKey(ModelEntity.class, model.getId()).subscribe(new Action1<ModelEntity>() {
        @Override
        public void call(ModelEntity modelEntity) {
            modelEntity.setName(model.getName());
            getData().update(modelEntity);
        }
    }, new Action1<Throwable>() {
        @Override
        public void call(Throwable throwable) {
            ModelEntity modelEntity = new ModelEntity();
            modelEntity.setId(model.getId());
            modelEntity.setName(model.getName());
            getData().insert(modelEntity);
        }
    });
}
```
But before run the above snippet I already have this declared:
```java
getData().select(ModelEntity.class).get().toSelfObservable().subscribe(new Action1<Result<ModelEntity>>() {
                @Override
                public void call(Result<ModelEntity> modelEntities) {
                    
                }
            });
```
Which listen for any changes in ModelEntity table. But this method does not get called when I call the insert/update methods, it only get called for the time I subscribe returning a result with 0 entities.

I've set the logging enabled to check if the insert/update methods are being called in database, and I found no logs, but I'm sure the methods insert and update are being called.

So my question is, to call EntityStore methods I always need to subscribe after? 

p.s. If I call subscribe for each insert the app freezes because I call notifiyDataSetChanged on table change callback.

**Comment by YuriHeupa** [comment]
Found reason in #81

**Comment by npurushe** [comment]
Yup the observables (singles too) are 'cold' so you have to subscribe. There is a good page on the rxjava [wik](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/creating.md#cold-vs-hot-observables) about them.
