### ISSUE TITLE
Batch upsert

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#103]
Is there a reason why there in `insert(Iterable)` but no `upsert(Iterable)`?

**Comment by npurushe** [comment]
Upsert/Update only takes a single entity at the time right now. Right now only the insert operation has special optimizations for batched operations.

**Comment by PaulWoitaschek** [comment]
What about adding that overload to the API for consistence?
The API could for now just iterate over it.

Another thing is upsert threw an exception about unique ids for me. However with default Android `SqliteDatabase` I can do a on-conflict replace.

**Comment by npurushe** [comment]
Yes I think having the API for consistency is fine and it can be optimized later
