### ISSUE TITLE
NullPointerException: io.requery.util.function.Supplier.get()

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#104]
I cant persist sub objects at all.

`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()'`

I have a class like

```java
@Entity public interface ApiShow extends Persistable {

   @Nullable String getName();
   @OneToOne @Nullable ApiImageEntity getShowImage();
}
```

And the ApiImage like
```java
@Entity public interface ApiImage extends Persistable {

   @SerializedName("url") @Nullable String url();
}
```

However when I call `getShowImage()` I get the above NPE. Is there some heavy misunderstanding on my side or is that a bug?

[Full trace](https://gist.github.com/PaulWoitaschek/1d119811356b4076fc42a989485153e6).

**Comment by npurushe** [comment]
Hi you need to mark one side of the One-to-One relation ship as the 'owning' side. e.g it needs to be marked with @ForeignKey. Some assumptions could be made if you don't put it on the other side possible, will look into that but right now needs to be explicit.

**Comment by PaulWoitaschek** [comment]
What has to be marked with `@ForeignKey`? The whole class? Or a foreign key with the same type as the class key?

Is it possible for the library to check these dependencies at compile time?

**Comment by npurushe** [comment]
Should be placed on the field/member that is the owning side of the relation ship (eg. where the column will in the table). Please see the [example code](https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/model/Person.java)
