### ISSUE TITLE
Result.toObservable() which emits result on subscribe and on further updates.

### ISSUE THREAD

**Issue by vtuan10** [requery/requery#11]
As far as i can see, Result has two toObservable-methods:
- toObservable: Converts the Result to an Observable which, emits an item of result at a time.
- toSelfObservable: Emits only, when a commit affects the query.

Enhancement:
It would be nice to have an Observable, which emits once on subscribe and emits on further updates (like  in StorIO). With this, the first toObservable wouldn't be needed anymore, since we can simulate it with take(1) and flatmap. The second could be simulated by skip(1).

**Comment by npurushe** [comment]
It looks like from their example in StorIO emits a list of items back each time with the results. So it looks like you want the Result<E> itself emitted back on subscribe and on subsequent changes?

I think toObservable() would still be needed for other cases where you just need a sequence of the elements in the result but this looks like it could also be added. Thanks for the feedback.

**Comment by vtuan10** [comment]
Yes, in my usecase I subscribe in the onCreate method of an activity to get my data and create my views according to the data. So I have to get my data once for initialization and then subsribe to it again to get further updates. To have all of this in 1 subscription would be awesome. Maybe I'm just spoiled from StorIO :D

Again thanks for this awesome library :)

**Comment by npurushe** [comment]
Sure :) Do you think something like an overload of toSelfObservable(boolean emit), that if emit true emits right away would fit your use case?

**Comment by vtuan10** [comment]
yes, thats good.

**Comment by npurushe** [comment]
Ok sounds simply enough! Will work on this for the next update

**Comment by npurushe** [comment]
It made sense to make this the default behavior so added in latest snapshot version.
