### ISSUE TITLE
Classes not generated after adding ForeignKey

### ISSUE THREAD

**Issue by julianraj** [requery/requery#110]
I have definitions for section and category as follows:

`@Entity
public class AbstractSection {  
    @Key  
    Integer id;  
    String machineName;
    @OneToMany(mappedBy = "section", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<DbCategory> categoryList;
}`

`@Entity  
public class AbstractCategory {  
    @Key  
    Integer id;  
    @ForeignKey(references = Section.class)  
    Integer sectionId;  
    @ManyToOne  
    Section section;  
}`

This was working fine before I added the foreignKey for sectionId in Category entity.
After I added the foreignKey, the classes are not generated. I need this foreign key for join query to select categories belonging to sections with machineName 'xyz'

Am I doing something wrong here??

**Comment by npurushe** [comment]
Thanks for reporting. If there is an exception in the processor please include it here as well (you can get the exception by running `gradle build --stacktrace`). Currently you cannot have two of the same foreign keys defined as @ManyToOne defines the foreign key itself. You can use the @ManyToOne attribute in queries. like [this](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L751)  although it works on a Section not an int. If you have an example query that would help, maybe there is an enhancement that can be made that will make your query easier.

**Comment by julianraj** [comment]
The query I was trying out is 
`data.select(Category.class).join(Section.class).on(Category.SECTION_ID.eq(Section.ID)).where(Section.MACHINE_NAME.eq("xyz"));`

**Comment by npurushe** [comment]
It is possible. What's the build error that you get when compiling that causes nothing to be generated? Try `gradle build --stacktrace` to get the full output.

**Comment by julianraj** [comment]
This is what I get:
`Caused by: java.lang.IllegalArgumentException: Invalid class name identifier: <error>`

**Comment by npurushe** [comment]
Could you run with `--stacktrace` that should give a full stack trace. Thanks! Most likely `@ForeignKey(references = Section.class` is the problem you can't reference generated code in an annotation. So try changing it to AbstractSection.class

**Comment by julianraj** [comment]
Well `Section.class` was the problem. Replaced it with `AbstractSection.class` and worked like charm.
Thanks :)  :+1:

**Comment by npurushe** [comment]
Sure, closing this for now. Please follow up if there any issues.
