### ISSUE TITLE
Kotlin methods and property fields with getters incorrectly generate columns 

### ISSUE THREAD

**Issue by martino2k6** [requery/requery#114]
With the below example **beta16** generates an entity with `friend` and `enemy` columns, whereas only the `type` field should have been added as a column to the generated entity.

It is worth noting that with the example, as it is, compilation fails since the generated `PersonEntity` overrides `isFriend` and `isEnemy` which have not been marked as `open` for overriding (Kotlin classes and methods are not open for extension by default). Adding the `open` modifier to both of them does make the code compile, however I still don't think that the produced result is correct as only fields marked as `abstract` should be added as columns to the entity.

```kotlin
@Entity
abstract class Person {
    
    @get:Column(nullable = false)
    abstract var type: String
    
    val isFriend: Boolean
        get() = type == "friend"
    
    fun isEnemy() = type == "enemy"
}
```

I'd be quite happy with having a tackle at a fix myself, once agreed as to what the correct approach with regards to Kotlin entity definitions should be.

**Comment by npurushe** [comment]
Thanks for reporting, certainly generating non-compilable code isn't correct. It is tricky to detect getters vs helper methods sometimes. Will be fixed in the next update but as a workaround you can add @Transient annotation to those methods and the processor will skip them.

**Comment by martino2k6** [comment]
Thank you for fixing it, and for the workaround suggestion.

**Comment by npurushe** [comment]
Also noticed you are using abstract classes (not data classes or interfaces) this is not quite working yet, hoping to get it working in the next update. Data classes and interfaces are ok though

**Comment by martino2k6** [comment]
I hadn't thought of interfaces. Keep forgetting that Kotlin allows methods with implementations in them as opposed to Java <8 which doesn't. That should fully cover my case. Thanks for the tip!
