### ISSUE TITLE
toSelfObservable not reacting on updates to relationships

### ISSUE THREAD

**Issue by Pr0bability** [requery/requery#115]
Hello,

I have a problem with toSelfObservable not reacting to updates (and deletes) to things in OneToMany (ManyToOne) relationships. Is this the correct behaviour?

Is deleting a model with OneToMany relationship supposed to automatically delete the models on the Many side of the relationship?

**Comment by npurushe** [comment]
Hi yes currently the self observable will only be triggered if there are changes to the table it is mapped to directly, not relational tables. However this maybe something that can be added, needs some research.

For deleting rows on the@ManyToOne side, yes this will happen if you use the ReferentialAction.DELETE option on the foreign key (which is the default) You can disable that by adding the @ForeignKey annotation and setting a different action like NO_ACTION.

**Comment by Pr0bability** [comment]
For the self observable, it would be something very useful for my application. Right now, I have a table with medications that have an amount, which is calculated dynamically from another table (two actually), and this amount is displayed in the list where I list them. Thus having them updated dynamically would be great.

For the deleting, I don't understand the answer fully. This is what I have,
```java
@OneToMany(mappedBy = "medication", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<HistoryEvent> historyEvents;
```
Yet it seems the history events are not being deleted correctly. The history events are linked as:

```java
    @ManyToOne
    Medication getMedication();
```

**Comment by npurushe** [comment]
By not deleted correctly you mean when you delete the Medication the item referencing Medication (which is HistoryEvent looks like) is not deleted?

**Comment by Pr0bability** [comment]
Yes indeed.

**Comment by npurushe** [comment]
Not deleted from the database? or still having references to those objects in memory? Currently those objects will still be in memory if you had already retrieved the list.

**Comment by Pr0bability** [comment]
Well, I have a self observable on history events that should get updated whether an item is deleted, but it seems it's not observing anything, ie. the events that should have been deleted stay in the RecyclerView.

**Comment by Pr0bability** [comment]
Ok, there was a problem with not adding the HistoryEvent to the list in the Medication, fixing that, it seems it deletes correctly, but the self observer is not reacting to the deletion.
