### ISSUE TITLE
How to add columns to a junction table?

### ISSUE THREAD

**Issue by julianraj** [requery/requery#117]
`@JunctionTable(name = "junctionTable")` creates a junction table with two columns. But what if I want to add extra columns to it? There is `column` field but how can it be used to define DataType?
For example I wand an extra column with name "xyz" and of type Long.

**Comment by npurushe** [comment]
Hi thanks for reporting currently that is not supported, but worth adding I think. Basically I think a way to provided the JunctionTable type will be provided, but then you have to specify the required foreign key fields in it along with the custom fields you want.

**Comment by npurushe** [comment]
The beta17 version a new type() value on @JunctionTable that allows you to provide your own implementation of the join table entity.

**Comment by NilsSun** [comment]
Hello, I'm using Requery 1.0.2. When type of JunctionTable annotation is set with my own join table entity, new columns, which are not foreign keys, are still asked for referenced Class. If the referenced Class is null, the error would happen. The related error code in Requery is "type.getClassType().isAssignableFrom(a.getReferencedClass())".  The code path is "https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/sql/EntityReader.java".

I feel if a.getReferencedClass() is null, the for statement should continue.

The segment of code is below:
case MANY_TO_MANY: {
                @SuppressWarnings("unchecked")
                Class<Q> uType = (Class<Q>) attribute.getElementClass();
                QueryAttribute<E, Object> tKey = null;
                QueryAttribute<Q, Object> uKey = null;
                Type<?> junctionType = context.getModel().typeOf(attribute.getReferencedClass());
                for (Attribute a : junctionType.getAttributes()) {
                    if (type.getClassType().isAssignableFrom(a.getReferencedClass())) {
                        tKey = Attributes.query(a);
                    } else if (uType.isAssignableFrom(a.getReferencedClass())) {
                        uKey = Attributes.query(a);
                    }
                }
                Objects.requireNotNull(tKey);
                Objects.requireNotNull(uKey);
                QueryAttribute<E, Object> tId = Attributes.get(tKey.getReferencedAttribute());
                QueryAttribute<Q, Object> uId = Attributes.get(uKey.getReferencedAttribute());
                Object id = proxy.get(tId);
                if (id == null) {
                    throw new IllegalStateException();
                }
                // create the many to many join query
                return order(queryable.select(uType)
                    .join(junctionType.getClassType()).on(uId.equal(uKey))
                    .join(type.getClassType()).on(tKey.equal(tId))
                    .where(tId.equal(id)), attribute.getOrderByAttribute());
            }
