### ISSUE TITLE
How to do a query with OneToMany attribut ?

### ISSUE THREAD

**Issue by plevavas** [requery/requery#118]
Hi,

I try to do this request with your library : "I want to get the list of 10 most recent TodoList where the owner of a todo in this list is Bob". 

    @Entity
    public class TodoList implements Persistable
    {
        @Key
        public String id;

        @OneToMany
        public MutableResult<Todo> todos;

        public Date created;
    }

    @Entity
    public class Person implements Persistable
    {
        @Key
        public String id;

        public String name;

        @OneToMany
        public MutableResult<Todo> todos;
    }

    @Entity
    public class Todo implements Persistable
    {
        @Key
        public String id;

        @ManyToOne
        public TodoList todo;

        @ManyToOne
        public Person owners;

        public String text;
    }

So, i did this : 

    mData.select(TodoList.class)
                        .where(TodoListEntity.CREATED.lessThan(new Date()))
                        .orderBy(TodoListEntity.CREATED.desc())
                        .limit(10)
                        .get();

But, i have some trouble to do the join with others tables. In a TodoEntity, i don't have access to the event_id, or team_id. Can you give me few clues ? :)

Thanks!

**Comment by npurushe** [comment]
Have a look at this [answer](https://github.com/requery/requery/issues/35#issuecomment-195994071) there is an example there on joining similar to yours. You will have more joins it looks like since you have no owner in your TodoList but should still work fine.

**Comment by plevavas** [comment]
I saw this answer. But, because i use @OneToMany instead of @ForeignKey, I don't know how to do the equals condition. I did something like that : 

    mData.select(TodoList.class)
                    .join(TodoEntity.class).on(TodoListEntity.ID.eq(TodoEntity.EVENT))
                    .join(PersonEntity.class).on(TodoEntity.TEAM.eq(PersonEntity.ID))
                    .where(TodoListEntity.CREATED.lessThan(new Date()))
                    .orderBy(TodoListEntity.CREATED.desc())
                    .limit(10)
                    .get();

But, TodoListEntity.ID and TodoEntity.EVENT have different type. There is a compilation error. Should i use @ForeignKey instead of @OneToMany ?

**Comment by npurushe** [comment]
What is TodoEntity.EVENT in this case? You should usually be joining on keys or the foreign key columns. In this case when you have a @ManyToOne attribute you have to use the actual type which I agree is a problem, there will be an enhancement made to also generate a raw QueryAttribute with just the ForeignKey type (e.g. string or int not an entity type) to make that easier.
