### ISSUE TITLE
Duplicate id Rows

### ISSUE THREAD

**Issue by eugenkiss** [requery/requery#12]
While inspecting the generated database I noticed that there are two id rows for every table with the same content. For example, if I have the following class.

```java
@Entity
public abstract class AbstractUser {
    @Key
    long id;
    String name;
    String profilePicUrl;
}
```

Then the resulting table has the following rows.

```
 id | id | name | profilePicUrl
--------------------------------
 1    1    Alex   http://
 2    2    Tobi   http://...
```

**Comment by npurushe** [comment]
How are you retrieving the rows and column names? The database will not allow you to have to two columns with the same name so that should not be possible. Are you sure they are both named 'id'?

**Comment by eugenkiss** [comment]
I was using Stetho to look at the database content, i.e. via Chrome Devtools. Thinking more about it, I assume the duplicate `id` rows shown are due to some presentational problem in Chrome Devtools resp. Stetho. Interestingly, Chrome Devtools shows tables created by ORMLite with both a `rowid` and `_id` (`_id` is the primary key), however their content is not identical. In any case, false alarm ;).
