### ISSUE TITLE
Call Result.toList() in async way

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#121]
I've created an observable which listen on database changes, on the subscribe I receive the Result instance, but when calling the method `toList()` from the Result it blocks my main thread for a while. i.e.:
```java
getData().select(ModelEntity.class)
                .where(ModelEntity.TITLE.notNull())
                .get()
                .toSelfObservable().subscribe(new Action1<Result<ModelEntity>>() {
            @Override
            public void call(Result<ModelEntity> entities) {
                entities.toList();
            }
        });
```

Is there any way to call this method async?

**Comment by npurushe** [comment]
You can use [Observable.toList()](http://reactivex.io/RxJava/javadoc/rx/Observable.html#toList()) in RxJava to this (using toObservable() on the Result).

**Comment by YuriHeupa** [comment]
I really don't know what I was doing, it's obvious. LOL 
More than 30 hours awake result in this. BTW, thanks!
