### ISSUE TITLE
Stateless entity not working

### ISSUE THREAD

**Issue by tsunamilx** [requery/requery#122]
Based on the example project, I changed all interfaces to abstract classes, it works, but when I add stateless = true to each entity, it throws exception:
io.requery.PersistenceException: 1-1 relationship can only be removed from the owning side 

I need stateless entity due to discussion on this issue #73 .

**Comment by tsunamilx** [comment]
I just realize that with `stateless = false`, GSON can still work, just use concrete class for relationships instead abstract class or interface.

Anyway `stateless = true` seems to be a bug.

**Comment by npurushe** [comment]
Hi thanks for reporting. Looks there is a problem there if you have a 1-1 relationship that is null, since it's not tracked if a field is modified if the entity is stateless might be ok to just ignore it in that case

**Comment by npurushe** [comment]
The beta18 version contains this fix
