### ISSUE TITLE
Inheritance. @Naming doesn't work if derived class is in the separate library

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#124]
If the derived class is in separate library, then for derived properties @Naming is ignored. Default getters and setters are generated. If the super class and derived class are in one library, then @Naming works.

**Comment by vmitiaev** [comment]
I checked @Naming with commit [598ab60](https://github.com/requery/requery/commit/598ab60f814b585b32eb9b5022b59be5c854d2c7). Without changes, user getter and the setter is ignored.

**Comment by npurushe** [comment]
How is your project structured? is the base library source available when compiling the project? Do any of the annotations affect the generated class (e.g. @Column) ?

**Comment by vmitiaev** [comment]
**Seperate library project:**

`@Superclass`
`public abstract class BaseEntity {`

    @Key
    protected UUID id;

    @Column(name = "creation_date", nullable = false)
    protected long creationDate;

    @Column(name = "last_modified_date", nullable = false)
    protected long lastModifiedDate;

    @Column(name = "deleted", nullable = false)
    @Naming(getter = "isDeleted")
    protected boolean deleted;

    public abstract UUID getId();

    public abstract long getCreationDate();

    public abstract long getLastModifiedDate();

    public abstract boolean isDeleted();
`}`


`@io.requery.Entity(cacheable = false)`
`@Table(name = "unit_link")`
`public abstract class AbstractUnitLink extends BaseEntity {`

    @Column(name = "parent_table", nullable = false)
    protected String parentTable;

    @Column(name = "parent_id", nullable = false)
    protected UUID parentId;

    @Column(name = "child_table", nullable = false)
    protected String childTable;

    @Column(name = "child_id", nullable = false)
    protected UUID childId;
`}` - Good class UnitLink with method isDeleted()


**Application project:**

`@Entity(cacheable = false)`
`@Table(name = "access_diagram")`
`public abstract class AbstractAccessDiagram extends BaseEntity {`

    @Column(name = "name", nullable = false)
    protected String name;

    @Column(name = "start_date", nullable = false)
    protected long startDate;

    @Column(name = "end_date", nullable = false)
    protected long endDate;

    @Column(name = "state", nullable = false)
    protected int state;
`}`  - Bad class AccessDiagram with method getDeleted(). @Column - correct generate "name" and "nullable". If to comment out @Naming and to rename the abstract isDeleted method into getDeleted, then all - ok

**Comment by npurushe** [comment]
Yes the annotated elements for the base class are not added in the processing step so the processor doesn't know about them. Will have to see if this can be done somehow through introspecting those elements through the processing api.
