### ISSUE TITLE
Inheritance. keyAttribute and keyAttributes is null if @Key is defined in base class.

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#126]
In case of inheritance for derived class $TYPE (io.requery.meta.Type) is incorrectly generated. keyAttribute and keyAttributes is null. @Key is defined in base class.

**Comment by npurushe** [comment]
Thanks for reporting. Does the generated attribute for the id/key have `setKey(true)` ?

**Comment by vmitiaev** [comment]
setKey(true) isn't generated.

**Comment by npurushe** [comment]
This is for the base library case correct? If so will merge into that issue.

**Comment by vmitiaev** [comment]
For the base libary is case correct. This issue was solved in commit - [16bea7d](https://github.com/requery/requery/commit/16bea7db853f7b554d3fa340e1bd107b482b621d)

**Comment by npurushe** [comment]
Ok thanks will close this one for now

**Comment by npurushe** [comment]
The beta18 version contains this fix
