### ISSUE TITLE
Cascade Upsert

### ISSUE THREAD

**Issue by Glurt** [requery/requery#127]
I've mentioned this before but I would like to upsert an entity and then upsert any entities contained within a relationship. Currently I get the following:
 

> Caused by: io.requery.sql.RowCountException: Expected 1 row affected actual 0
>                                                                           at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:163)
>                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:588)
>                                                                           at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:899)
>                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:697)
>                                                                           at io.requery.sql.EntityWriter.insert(EntityWriter.java:449)
>                                                                           at io.requery.sql.EntityWriter.upsert(EntityWriter.java:490)
>                                                                           at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:263)
>                                                                           at io.requery.rx.SingleEntityStoreFromBlocking$7.get(SingleEntityStoreFromBlocking.java:148)
>                                                                           at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)

**Comment by npurushe** [comment]
The beta18 version contains this fix

**Comment by Glurt** [comment]
How can we get CascadeMode to be UPSERT in _cascadeWrite_? At the moment it's AUTO which then becomes UPDATE because _hasKey(proxy)_ is true.

**Comment by npurushe** [comment]
Oh sorry looks like this is currently not working for SQLite or anything that doesn't upserting via a single statement. Will reopen since there are some more changes required there for those platforms.
