### ISSUE TITLE
Persist using SingleEntityStore without triggering observables listening for changes

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#129]
In my android application I have a ViewPager hosting 3 fragments with each having a recyclerview, the viewpager acts as "filter" for an model data, let's say the first fragment show all these models, second fragment show these models which have a true boolean field and the third show these models with a specific non null field, for this I subscribe for changes on each fragment, for example in fragment 2:

```java
getData().select(ModelEntity.class).where(ModelEntity.STARRED.eq(true))
                .get().toSelfObservable()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .flatMap(modelEntities -> modelEntities.toObservable()
                        .subscribeOn(Schedulers.immediate())
                        .observeOn(AndroidSchedulers.mainThread())
                        .toList())
                .subscribe(new Action1<List<ModelEntity>>() {
                    @Override
                    public void call(List<ModelEntity> modelEntities) {
                        mAdapter.setItems(modelEntities);
                        mAdapter.notifyDataSetChanged();
                    }
                });
```
Every time I insert/update an ModelEntity in database I receive all STARRED in this method. I'm doing this was because I can set the STARRED to true in any other fragment, and calling subscribe will trigger this method which will refresh the list. 

But sometimes I want to persist it in database in any other context and don't trigger any subscribed observable, because I have a service that constantly inserts in database every second, and to the changes be persisted I need to call `subscribe()`, because the observables are cold. Is there any way to persist and avoid triggering observables?

**Comment by npurushe** [comment]
I think I understand your use case. So effectively want a way to insert/update/delete an entity without triggering the observable type change listener?

**Comment by YuriHeupa** [comment]
Exactly! I was trying to create another EntityStore just for this, but don't looks a good approach

**Comment by npurushe** [comment]
Right the listener would be triggered after a transaction. Are you looking to filter out just a specific entity type? or just per operation for any entity?

**Comment by YuriHeupa** [comment]
What you mean with `just per operation for any entity`?

**Comment by npurushe** [comment]
per insert/update/delete call

**Comment by YuriHeupa** [comment]
The first option, I'm looking to filter out just a specific entity type

**Comment by npurushe** [comment]
Looking at this it makes more sense to use the builtin RxJava subscription api's to control this (unsubscribing when needed and then recreating a subscription later after you made your changes).
