### ISSUE TITLE
ManyToMany: "compound-entity" not generated and setters not generated in entities

### ISSUE THREAD

**Issue by vtuan10** [requery/requery#13]
I can't seem to get ManyToMany relationships to work:

```
@Entity
public interface User extends Parcelable {

    @Key
    @Generated
    int getId();


    @ManyToMany(mappedBy = "owners", cascade = CascadeAction.NONE)
    List<Account> getOwned();
    //void setOwned(List<Account> accounts);
}
```
```
@Entity
public interface Account extends Parcelable {

    @Key
    @Generated
    int getId();

    @ManyToMany(mappedBy = "owners", cascade = CascadeAction.NONE)
    List<User> getOwners();

}
```
Gradle always says: ```error: cannot find symbol class AccountEntity_UserEntity```
The class "AccountEntity_UserEntity" is not generated, should we create this ourselves?

Another issue, setters for ManyToMany and OneToMany are not created (if I uncomment the setter-line above, it always says "xEntity is always abstract and does not override ...blabla", the setter is not generated).

**Comment by npurushe** [comment]
Hi you need to specify one of the sides as the 'owning' side of the relationship using the `@JunctionTable` annotation. Will work on adding another check for this at compile time so it's more clear. Also another enhancement might be to pick one side automatically if you're not trying to map to an existing table structure.

**Comment by vtuan10** [comment]
Thanks, it's working. I should have looked into the unittests...

**Comment by nathanieloliveira** [comment]
Hello again @npurushe . I'm havin the same problem as him. It looks like the junction class is generated but entity classes that have the relationship don't have the necessary class import.

My entities are defined like this:
```
@Entity
public abstract class BaseChat {

    @Key @Generated
    int id;

    @JunctionTable(name = "chat_users")
    @ManyToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    Set<BaseUser> users;
}

@Entity
public abstract class BaseUser {

    @Key @Generated
    int id;

    @ManyToMany
    Set<BaseChat> chats;
}
```

error is:
`Error:(190, 25) error: cannot find symbol class Chat_users`
line in generated source is:
`.setReferencedClass(Chat_users.class)`

list of imports:
```
import com.ubervet.model.chat.BaseChat;
import com.ubervet.model.chat.

/* looks like the Chat_users class is not being imported */

import io.requery.CascadeAction;
import io.requery.Persistable;
import io.requery.ReferentialAction;
import io.requery.meta.Attribute;
import io.requery.meta.AttributeBuilder;
import io.requery.meta.Cardinality;
import io.requery.meta.QueryAttribute;
import io.requery.meta.SetAttributeBuilder;
import io.requery.meta.Type;
import io.requery.meta.TypeBuilder;
import io.requery.proxy.EntityProxy;
import io.requery.proxy.IntProperty;
import io.requery.proxy.Property;
import io.requery.proxy.PropertyState;
import io.requery.util.function.Function;
import io.requery.util.function.Supplier;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Set;
import javax.annotation.Generated;
```

**Comment by npurushe** [comment]
Do you have those entity definitions in different packages? what package was Chat_users created in?

**Comment by nathanieloliveira** [comment]
BaseUser is in package com.ubervet.model;
BaseChat is in package com.ubervet.model.chat;
Chat_users was generated in package com.ubervet.model.chat;

I see now, if I put them in the same package it should work

**Comment by npurushe** [comment]
Ok looks like a bug will work on a fix soon. If it is in the same package it will work.

**Comment by nathanieloliveira** [comment]
Thank you.

**Comment by npurushe** [comment]
Closing this one and using the new issue

**Comment by npurushe** [comment]
the beta4 version has the fix for this issue, thanks!
