### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by thinusbaun** [requery/requery#131]
Hi,

I have problem with updating rows using requery. 
I have this code:
```
    for (final String id : favouriteIds) {
            Result<Wine> result = (Result<Wine>) store.select(Wine.class).where(new Condition() {
                @Override
                public Object leftOperand() {
                    return WineEntity.ID;
                }

                @Override
                public Operator operator() {
                    return Operator.EQUAL;
                }

                @Override
                public Object rightOperand() {
                    return id;
                }
            }).get();
            Wine entity = result.firstOrNull();
            if (entity != null) {
                Log.d(TAG, "Putting favourite wine with id: " + id);
                entity.setFavourite(true);
                store.update(entity);
            }
        }
```
but there is no update query executed. Log have only select queries printed.

Thank you for Your help.

**Comment by npurushe** [comment]
What type of `EntityStore` (store) are you using? Depending on the type you man need to call an additional operation to execute the operation (e.g. if using RxJava this returns a `Single`)

**Comment by thinusbaun** [comment]
Hi, 
sorry but I have found mistake in my code. I was using `entity.setFavourite(true)` which was no overriden(it should be `entity.setIsFavourite(true)`), so when i called it entity state wasn't changed to `PropertyState.MODIFIED` so requery wasn't executing update query.
