### ISSUE TITLE
Convert observable of entity changes to a observable of single item changes

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#133]
Currently I have a query that select all entities from my database, with the result I create a new wrapper class passing each entity returned as parameter, this class should be updated with the new value if the entity changes, for this I'm doing something like this:
```java
getData().select(ModelEntity.class)
        .get().toSelfObservable()
        .subscribe(new Action1<Result<ModelEntity>>() {
            @Override
            public void call(Result<ModelEntity> modelEntities) {
                for(ModelEntity ModelEntity : modelEntities.toList()) {
                    Observable<Result<ModelEntity>> entityObservable = getData().select(ModelEntity.class)
                            .where(ModelEntity.UUID.eq(ModelEntity.getUuid()))
                            .get().toSelfObservable();
                    ModelsHandler.add(new ModelWrapper(entityObservable));
                }
            }
        });
```
Inside the `ModelWrapper` class I subscribe for changes, but this looks a ugly approach to me, I think the library should have a properly way to do this, am I wrong?

**Comment by npurushe** [comment]
Why do you need to subscribe to an observable on every item? Currently the way toSelfObservable works is it is not specific to the query but rather the table the source entity is mapped to, so subscribing once is enough to observe all changes.

**Comment by npurushe** [comment]
Closing this for now, please add a comment if the way toSelfObservable is not clear.
