### ISSUE TITLE
Question: Data is not saved

### ISSUE THREAD

**Issue by vanniktech** [requery/requery#134]
I'm creating the `SingleEntityStore` like this:

```java
final DatabaseSource source = new DatabaseSource(familonetApplication, Models.DEFAULT, "dbname", DB_VERSION);

if (BuildConfig.DEBUG) {
    source.setTableCreationMode(TableCreationMode.DROP_CREATE); // use this in development mode to drop and recreate the tables on every upgrade
}

final Configuration configuration = source.getConfiguration();
return RxSupport.toReactiveStore(new EntityDataStore<>(configuration));
```

I provide this `Entity` via Dagger into an abstraction layer and basically I have two methods:

```java
@Override
public void insert(@NonNull final FeatureFlags featureFlags) {
    data.insert(featureFlags);
}

@NonNull
@Override
public FeatureFlags getFeatureFlags() {
    return data.select(FeatureFlags.class).get().firstOr(FeatureFlags.builder().build());
}
```

Also I wrote a little test however the build fails and it does not seem like the value is stored

```java
assertThat(database.getFeatureFlags()).isEqualTo(FeatureFlags.builder().build());

final FeatureFlags updatedFeatureFlags = FeatureFlags.builder().etc().build();

database.insert(updatedFeatureFlags);

assertThat(database.getFeatureFlags()).isEqualTo(updatedFeatureFlags);
```

`FeatureFlags` is an auto value class with a `@Id @Generated int id()`.

What am I doing wrong here?

**Comment by npurushe** [comment]
Hi please see this answer https://github.com/requery/requery/issues/81#issuecomment-208497285

**Comment by vanniktech** [comment]
I changed it now too 

```java
final DatabaseSource source = new DatabaseSource(familonetApplication, Models.DEFAULT, "dbname", DB_VERSION);
source.setTableCreationMode(applicationType.isDebug() ? TableCreationMode.DROP_CREATE : TableCreationMode.CREATE_NOT_EXISTS);

final Configuration configuration = source.getConfiguration();
return new EntityDataStore<>(configuration);
```

However the select does not work, I get a warning `Unchecked calll to select` does my auto value entity need to implement an interface or something?

**Comment by npurushe** [comment]
Not work as in it not compile? Or just the generics warning. In which case your argument to `firstOr()` has to return the same type as specified in `select()`

**Comment by vanniktech** [comment]
Hmm okay just a warning that the generics don't match up though it does work. I'll close this issue then. Thanks for the help :)

For the record those are the warnings:

![screen shot 2016-05-11 at 10 21 08](https://cloud.githubusercontent.com/assets/5759366/15174470/23026050-1762-11e6-9d2c-a9d017d9a8bc.png)

on this statement

```java
return ((Result<FeatureFlags>) data.select(FeatureFlags.class).get()).firstOr(FeatureFlags.builder().build());
```
