### ISSUE TITLE
Kotlin: `EntityModelBuilder` and `type.baseType() == null` causes exception

### ISSUE THREAD

**Issue by hastebrot** [requery/requery#135]
Is it required for `type.baseType()` to not return `null`? I tried to execute Requery in Kotlin and it throws an exception:

~~~
Exception in thread "main" java.lang.IllegalArgumentException
	at io.requery.util.ClassMap.put(ClassMap.java:92)
	at io.requery.meta.ImmutableEntityModel.<init>(ImmutableEntityModel.java:37)
	at io.requery.meta.EntityModelBuilder.build(EntityModelBuilder.java:57)
	at RequeryKt.main(requery.kt:28)
~~~

Using following code (position where the exception occurs hinted in comment).

~~~kotlin
import io.requery.Entity
import io.requery.Generated
import io.requery.Key
import io.requery.Persistable
import io.requery.meta.EntityModelBuilder
import io.requery.meta.TypeBuilder
import io.requery.sql.ConfigurationBuilder
import io.requery.sql.EntityDataStore
import io.requery.sql.SchemaModifier
import io.requery.sql.TableCreationMode
import org.h2.jdbcx.JdbcDataSource

@Entity
abstract class User(
    @Key @Generated val id: Int
)

fun main(args: Array<String>) {
    val dataSource = JdbcDataSource()
    dataSource.setURL("jdbc:h2:mem:simple-db;DB_CLOSE_DELAY=-1")
    dataSource.user = "sa"

    val type = TypeBuilder(User::class.java, "user").build()
    println(type.baseType()) // null

    val entityModel = EntityModelBuilder("simple-model")
        .addType(TypeBuilder(User::class.java, "user").build())
        .build() // exception here.

    val configuration = ConfigurationBuilder(dataSource, entityModel)
        .build()

    val schemaModifier = SchemaModifier(configuration)
    schemaModifier.createTables(TableCreationMode.DROP_CREATE)

    val dataStore = EntityDataStore<Persistable>(configuration)
    dataStore.close()
}
~~~

~~~groovy
compile "org.jetbrains.kotlin:kotlin-stdlib:1.0.1"
compile "io.requery:requery:1.0.0-beta18"
compile "com.h2database:h2:1.4.191"
~~~

**Comment by hastebrot** [comment]
Also: There a some classes missing in `requery-test`.

**Comment by hastebrot** [comment]
So, I got rid of the exception by using:

~~~kotlin
val type = TypeBuilder(User::class.java, "user").setBaseType(User::class.java).build()
println(type.baseType()) // class User
~~~

**Comment by hastebrot** [comment]
Hmm, another exception. I guess the `Type`  also needs a `ProxyProvider`.
~~~kotlin
@Entity
class User(
    @Key @Generated val id: Int
) : Serializable, Persistable

fun main(args: Array<String>) {
    // ...
    val dataStore = EntityDataStore<Persistable>(configuration)
    dataStore.insert(User(1)) // null pointer exception.
    dataStore.close()
}
~~~

**Comment by hastebrot** [comment]
So, I managed to use `ProxyProvider' but as expected another exception occurs.

Is it possible to use `request-processor` to accept a `@Entity` class and return a `ImmutableType`? I don't want to generate classes.

**Comment by npurushe** [comment]
Hi you don't need to create the `Type` instance yourself this code is generated by the annotation processor. Currently reflection is not supported, it's only supported to use the annotation processor generated code. For Kotlin see the instructions [here](https://github.com/requery/requery/wiki/Gradle-&-Annotation-processing) for using the kapt plugin.

**Comment by hastebrot** [comment]
Hi Nikhil, thanks! The annotation processor works good; the code generation is actually pretty easy.

From my first experience requery is looks well-designed, lightweight and configurable. Great work I really like it so far. I'm excited by the `EntityModel` class, I've used Ebean in the past and had to use reflection.

What's missing so far are maybe helpful exception messages here and there. Will see more when I dig deeper in entities and queries.

I'll close this issue as the problem was solved.

**Comment by npurushe** [comment]
Sure great! There will also be more first class support Kotlin in a future update as well.

**Comment by hastebrot** [comment]
FYI: I've translated the Java entity examples from the `io.requery.test.modeljpa` package to a single Kotlin file [1]. The Kotlin plugin for Gradle (using Kapt) generated the Java classes in `build/generated/source/kapt/main` successfully.

[1] https://gist.github.com/hastebrot/3b900fe2bcc3711591cc800c0bc2d281

**Comment by hastebrot** [comment]
Hmm, I need to change all `val`s in the interfaces to `var` in order to set properties in the generated entity  classes. Now the processor says (for example):

~~~
error: PersonEntity is not abstract and does not override abstract method setPhoneNumbersList(List<? extends Phone>) in Person
public class PersonEntity implements Person, Persistable {
       ^
~~~

and

~~~
error: name clash: setPhoneNumbersList(List<Phone>) in PersonEntity and setPhoneNumbersList(List<? extends Phone>) in Person have the same erasure, yet neither overrides the other
    public void setPhoneNumbersList(List<Phone> phoneNumbersList) {
                ^
~~~

**Comment by hastebrot** [comment]
I solved the errors by setting `Group::description`, `Person::phoneNumbersSet` and `Person::phoneNumbersList` back from `var` to `val`.

**Comment by npurushe** [comment]
Thanks interesting Kotlin generates the collection definitions with a bounded wildcard.

**Comment by hastebrot** [comment]
Yes, the Kotlin standard library redefines e.g. `Set` as `Set<out E>` [1] [2], which corresponds to `Set<? extends E>` in Java [3].

[1] http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-set/index.html#set
[2] https://github.com/JetBrains/kotlin/blob/1.0.1/core/builtins/native/kotlin/Collections.kt#L233
[3] https://kotlinlang.org/docs/reference/generics.html#type-projections

**Comment by hastebrot** [comment]
BTW: Entity class generation works for `Set` and `List` work with `var` when we replace e.g. `Set` with `MutableSet`:

~~~kotlin
@get:OneToMany(mappedBy = "owner")
val phoneNumbersSet: Set<Phone>

@get:OneToMany
val phoneNumbersList: List<Phone>
~~~

changed to

~~~kotlin
@get:OneToMany(mappedBy = "owner")
var phoneNumbersSet: MutableSet<Phone>

@get:OneToMany
var phoneNumbersList: MutableList<Phone>
~~~
