### ISSUE TITLE
Feature Request: select column as list or set

### ISSUE THREAD

**Issue by kenkyee** [requery/requery#140]
use case is:
- you have a list of objects by category
- you want to display a category list that can be used to filter your objects

to do this in a normal DB, I'd do a select distinct of a column and order it alphabetically and include a where clause if it's a subcategory.
There's no way to do this w/o pulling all the objects into memory with the current API I think?

**Comment by npurushe** [comment]
This should already work, Did you try something like:
`data.select(<fields>).distinct().where(<conditions>).get().toList()`
?

**Comment by kenyee** [comment]
Went through the wiki and didn't see an example of this in the query examples.  How do you specify fields in the select?

**Comment by npurushe** [comment]
It's the same as any select statement multiple or single attributes can be specified. https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L786

**Comment by kenkyee** [comment]
Thanks...now I feel stupid :-)

The query examples in the wiki should probably include one of those samples...

**Comment by npurushe** [comment]
Sure, the examples will be updated with more content soon.
