### ISSUE TITLE
"Entity" classes are not created anymore.

### ISSUE THREAD

**Issue by danysz** [requery/requery#142]
Hi

I have a project. It was working with requery and everything was fine until 2 hours ago. Now the "Entity" classes are not created anymore. Nothing changed in the build gradle.

project script
`buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}`

module script
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.neenbedankt.android-apt'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile "com.android.support:appcompat-v7:${android_appcompat_library_version}"
    compile "com.android.support:design:${android_design_library_version}"
    compile "com.android.support:support-v4:${android_support_library_version}"
    compile("com.crashlytics.sdk.android:crashlytics:${crashlytics_library_version}@aar") {
        transitive = true;
    }
    compile project(path: ':LogSDK')
    compile 'io.requery:requery:1.0.0-beta18'
    compile 'io.requery:requery-android:1.0.0-beta18' // for android
    apt 'io.requery:requery-processor:1.0-SNAPSHOT'   // use an APT plugin
    apt 'com.android.databinding:compiler:1.0-rc1'
    apt "org.androidannotations:androidannotations:3.3.2"
    compile "org.androidannotations:androidannotations-api:3.3.2"
    compile 'io.reactivex:rxjava:1.0.10'
    compile 'io.requery:sqlite-android:3.12.2-2'
    compile 'io.reactivex:rxandroid:1.1.0'
}`

**Comment by danysz** [comment]
Apologises but I have no idea why the content is not formatted as it should.

**Comment by npurushe** [comment]
I would suggest you build using `gradle build` from the command line to verify your build and that it's just  not a problem with your IDE. Also your versions are out of sync, make sure you use the `1.0.0-beta18` version of the processor as well.

**Comment by danysz** [comment]
I was using beta-18 and I move to snapshot because it stopped working.
I already tried from outside and same result...
I also invalidate caches and restart android studio...

**Comment by npurushe** [comment]
If you use `gradle build` and the processor doesn't run then the build will fail if your code depends on the output. whats the gradle build output?

**Comment by danysz** [comment]
moved to beta 16 and it worked...
moved back to 18 and it's still working...
no idea what solved the issue... really upset...

**Comment by npurushe** [comment]
Sounds strange, maybe an IDE problem? Please report back if you find out more thanks

**Comment by danysz** [comment]
Okay,
It's happening again.
I tried again to move between 18 and 16 but it didn't help.
I think that the issue is happening when I make changes in my Entity interfaces (not the generated files) and something is not configured properly.
The main issue is that I have no idea howcna I check the problem and find the error.

Thanks a lot for any help and advice...
