### ISSUE TITLE
Unable to use (ManyToOne) Entity as part of a compound Key

### ISSUE THREAD

**Issue by dukeyin** [requery/requery#145]
I found my way around #143 but encountered another upsert failure because of my ```@Key``` on the ```@ManyToOne``` Entity:

```
public interface Chart...
    @Key
    @ManyToOne
    Song getSong();

   @Key
    Integer getChart();

    ....
```

After fixing the missing whitespace in the query generator, my upsert then fails on:
```
no such column: song (code 1): , while compiling: update Chart set chart = ? ,song = ? ,... where chart = ? and song = ?
```

The column in the database is named ```songId```, not ```song```, so the fix would be to append "Id" to the query attribute if the field is a Key and an Entity?

**Comment by npurushe** [comment]
Is this a case where you're mapping on to a existing database? You should be able to specify the column name explicitly in this case using @Column.

**Comment by dukeyin** [comment]
Oops, I thought my database was being dropped and recreated, but it wasn't.  So there is not a bug here.
