### ISSUE TITLE
Example using rx callable and flatmap

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#148]
Looking in example source code I found that:
https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/PeopleActivity.java#L76

I was wondering why the example is using an callable for this kind of operation and if there's any other way to do the same?

**Comment by npurushe** [comment]
It's mostly to separate the database populating code from the rest of the UI and not do the work on the main thread. There are multiple ways to do this sure, it could also be done using Futures for example. Check the RxJava documentation for more information.

**Comment by YuriHeupa** [comment]
Ok, thanks for clarification, I'm relatively new with rx java, my first contact with reactive programming was using this wonderful library.

**Comment by YuriHeupa** [comment]
I'm sorry for creating an issue more related to RxJava, but I'm learning more about using this library and reading the documentation.

I think my question is more about the flatmap operation instead of the callable, looking on example source code:
https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/PeopleActivity.java#L77
I've something like on your example, but in the result of subscribe in this case I want to receive as parameter an ArrayList<ModelEntity>, with this approach I receive an Object.class (which is an ArrayList<ModelEntity>), can you help me with this?

**Comment by npurushe** [comment]
In the example the CreatePeople class persists the entities and returns an observable, the purpose of flatmap is to flatten the observable from CreatePeople into the single observable used in PeopleActivity, by subscribing it to it ensures the Observable returned from CreatePeople gets subscribed and run.
