### ISSUE TITLE
"Entity" classes are not created anymore - part 2 (previous one was #142)

### ISSUE THREAD

**Issue by danysz** [requery/requery#151]
Okay,
It's happening again.
I tried again to move between 18 and 16 but it didn't help.
I think that the issue is happening when I make changes in my Entity interfaces (not the generated files) and something is not configured properly.
The main issue is that I have no idea how can I check the problem and find the error.

Thanks a lot for any help and advice...

**Comment by npurushe** [comment]
You need to check the cause of the build failure in Intellij/Android Studio its in the build output window. Otherwise run `gradle build --stacktrace` from the command line to get the output.

**Comment by dukeyin** [comment]
@danysz What version of gradle are you using?  When I built a snapshot of requery, I noticed I needed to use Gradle 2.12, which is newer than what ships with Android Studio.

**Comment by danysz** [comment]
I am using 2.10 and it's working
