### ISSUE TITLE
TableCreationMode.DROP_CREATE is not working

### ISSUE THREAD

**Issue by danysz** [requery/requery#152]
Hi

My code is like this : 
`            DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 1);
            if (BuildConfig.DEBUG) {
                // use this in development mode to drop and recreate the tables on every upgrade
                source.setTableCreationMode(TableCreationMode.DROP_CREATE);
            }
            Configuration configuration = source.getConfiguration();
            mEntityDataStore = new EntityDataStore<Persistable>(configuration);
`

With all that I changed the Entity and the table is not created so whenI try to run a query I get : 

android.database.sqlite.SQLiteException: no such table: Node (code 1): , while compiling: select id, numberOfKeys from Node where id = ?

Any advice please ?

**Comment by npurushe** [comment]
Whenever you make schema affecting changes you need to increment the schemaVersion. Right now you have it fixed at 1 so the table creation code is not run after the first time you run the application.
