### ISSUE TITLE
Raw select picks String datatype if the first row has a null value

### ISSUE THREAD

**Issue by dukeyin** [requery/requery#154]
beta19

I'm using a variant of the EnumOrdinalConverter which stores ```Integer``` (instead of ```int```) so I can use null values.  After going through the results of  ```.raw(...).get().toList()``` I ran into an unexpected type mismatch where 1 of 3 enum fields out of ```tuple.get(index)``` reported itself as a String instead of an Integer.  After looking at my database, it seems this is happening because the first several rows of the dataset have a ```null``` value for that field.  (The other two enum fields that are working correctly are never null.)

**Comment by npurushe** [comment]
On Android correct? Right if the cursor type returns the column is null then that expression type will be set to string, with a value of null. However when you get the value via `get()` it will just be null and shouldn't cause any problem, are you getting an exception?

**Comment by dukeyin** [comment]
I will try to check on this later, but to continue my app I had already changed the logic to use non-null values instead of nulls.

I had actually run into another strange situation between two computers where I saw Integer returned in one emulator, but Long from the other emulator.  (To ignore that, I changed my local variables to ```Number```)

**Comment by dukeyin** [comment]
I just ran into a possibly related issue?

ENUM_FIELD and ENTITY_FIELD are the two parts of my composite ```@Key``` - both are stored in the database as integers.
```
List<MyEntity> results = DaoHelper.entityStore().select(ChartEntity.class).where(MyEntity.ENUM_FIELD.eq(value1).and(MyEntity.ENTITY_FIELD.eq(value2))).get().toList();
// or,
List<MyEntity> results2 = DaoHelper.entityStore().select(ChartEntity.class).where(MyEntity.ENUM_FIELD.eq(value1).and(MyEntity.ENTITY_FIELD_ID.eq(value2.getId()))).get().toList();
```
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
		at java.lang.Class.cast(Class.java:1505)
		at io.requery.sql.GenericMapping.read(GenericMapping.java:289)
		at io.requery.sql.EntityReader.fromResult(EntityReader.java:561)
		at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
		at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
		at io.requery.query.BaseResult.collect(BaseResult.java:78)
		at io.requery.query.BaseResult.toList(BaseResult.java:70)
```

**Comment by npurushe** [comment]
Can you please retry with the beta20 version? thanks

**Comment by dukeyin** [comment]
I tried ```dea14249f9646e2373536828aa618c23719663a6``` but still see a problem with the first select-toList after having run a select toList followed by a delete.

I created this helper method to try to work around the upsert bug:
```
List<MyEntity> matches = entityStore().select(MyEntity.class).where(...).get().toList();

MyEntity myObject;
if (matches.size() == 1) {
	myObject = matches.get(0);
	Integer deleteResult =
		DaoHelper.entityStore().delete(MyEntity.class).where(...).get().value();
}
else {
	myObject = new MyEntity();
	// ... set fields
	myObject = DaoHelper.entityStore().insert(myObject);
}
return myObject;
```
(Is it valid to load an Entity object, delete it from the database, then continue using the same instance of the Entity with the intent to save it to the database later?)

If I call the above helper method a second time on a different row, I get the String cast error (line number shifted since last version):
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
   at java.lang.Class.cast(Class.java:1505)
   at io.requery.sql.GenericMapping.read(GenericMapping.java:289)
   at io.requery.sql.EntityReader.fromResult(EntityReader.java:562)
   at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
   at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
   at io.requery.query.BaseResult.collect(BaseResult.java:78)
   at io.requery.query.BaseResult.toList(BaseResult.java:70)
```

**Comment by dukeyin** [comment]
I'm so sorry @npurushe but it seems I had made a careless error - https://github.com/requery/requery/issues/167#issuecomment-223095538 - and I believe I have selection working now with ```9a76a28c32c13244221cf5c76a342805daab6303```

**Comment by npurushe** [comment]
No problem the beta21 version contains these changes.
