### ISSUE TITLE
Is there a way to auto insert/update relationship?

### ISSUE THREAD

**Issue by tsunamilx** [requery/requery#155]
Let's say, I am using a web api which gives me a list of articles, each article has an author relationship, article is keyed by id, author is keyed by username.

Now I am trying to do
dataStore.insert(articles), this throws unique constraint violation on author username if articles has same author.

So my question
is there a way to auto-detect if the relationship is already existing by the key, then do insert or update accordingly?

**Comment by npurushe** [comment]
Try using the [upsert()](http://requery.github.io/javadoc/io/requery/EntityStore.html#upsert-E-) method

**Comment by tsunamilx** [comment]
I am on Android, SQLite seems not support upsert?

**Comment by npurushe** [comment]
On Android it falls back to attempting an update and then an insert if the affected row count was zero.

**Comment by tsunamilx** [comment]
Just tried, first it says "Can't upsert entity with generated key", I remove @Generate on article id, then tried again, but the same unique constraint violation.

**Comment by npurushe** [comment]
Did the violation happen on the update or insert statement?

**Comment by tsunamilx** [comment]
Looks like on the insert
```
05-24 12:25:38.646 1493-1493/lixiao.requerydemo E/SQLiteLog: (1555) abort at 13 in [insert into Author (username, firstName, lastName, pictureUrl) values (?, ?, ?, ?)]: UNIQUE constraint failed: Author.username
05-24 12:25:38.648 1493-1493/lixiao.requerydemo W/System.err: io.requery.sql.StatementExecutionException: Exception executing statement: insert into Author (username, firstName, lastName, pictureUrl) values (?, ?, ?, ?)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:75)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:56)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityWriter.insert(EntityWriter.java:450)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityWriter.upsert(EntityWriter.java:493)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:912)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityWriter.update(EntityWriter.java:573)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityWriter.upsert(EntityWriter.java:492)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:265)
05-24 12:25:38.649 1493-1493/lixiao.requerydemo W/System.err:     at lixiao.requerydemo.MainActivity.testRelationship(MainActivity.java:66)

```

**Comment by npurushe** [comment]
Is the username the primary key?

**Comment by tsunamilx** [comment]
Yes

**Comment by tsunamilx** [comment]
Here's my entities:

Author
```java
@Entity
public abstract class AbstractAuthor
    implements Parcelable, Persistable {
//
//    @Key
//    @Generated
//    long id;

    @SerializedName("username")
    @Expose
    @Key
    String username;

    @SerializedName("first_name")
    @Expose
    String firstName;

    @SerializedName("last_name")
    @Expose
    String lastName;

    @SerializedName("picture_url")
    @Expose
    String pictureUrl;

    @OneToMany(
        mappedBy = "author"
    )
    List<Article> articles;

}
```

Article
```java
@Entity
public abstract class AbstractArticle
    implements Parcelable, Persistable {

    @SerializedName("id")
    @Expose
    @Key
    long id;

    @SerializedName("title")
    @Expose
    String title;

    @SerializedName("sub_title")
    @Expose
    String subTitle;

    @SerializedName("detail")
    @Expose
    String detail;

    @SerializedName("author")
    @Expose
    @ManyToOne
    Author author;

    @SerializedName("date")
    @Expose
    String date;

    @SerializedName("category")
    @Expose
    @ManyToOne
    Category category;

    @SerializedName("city")
    @Expose
    @ManyToOne
    City city;

    @SerializedName("image_url")
    @Expose
    String imageUrl;

    @SerializedName("url")
    @Expose
    String url;

}
```

Test code:
```java
Author author = new Author();
        author.setUsername("lixiao");
        getDataStore().upsert(author); // This doesn't help

        Article a1 = new Article();
        a1.setId(1);
        a1.setTitle("AAA");
        a1.setAuthor(author);
        getDataStore().upsert(a1); // Error throws here

        Article a2 = new Article();
        a2.setId(2);
        a2.setTitle("BBB");
        a2.setAuthor(author);
        getDataStore().upsert(a2);

```

**Comment by tsunamilx** [comment]
Hi, do you have any news on this issue? 
Right now I am writing own code to check manually whether to insert or update for all relationship, that is quite tedious.

**Comment by npurushe** [comment]
Please retry with the beta20 version, a number of changes were made that should resolve your issue.

**Comment by tsunamilx** [comment]
Unfortunately I got the same problem.

**Comment by francoispluchino** [comment]
The same error occurs when an item is added to a list, and as the master entity is inserted (see #162).

**Comment by francoispluchino** [comment]
I do not know if it helps, but there is a strange behavior with the `OneToMany` relation:

**Entites example:**
```java
public interface User extends Parcelable, Persistable {
    @Key
    String getId();

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    List<Post> getPosts();
}
```
```java
public interface Post extends Parcelable, Persistable {
    @Key
    String getId();

    @ManyToOne(cascade = {CascadeAction.NONE})
    User getUser();
}
```
With this code:
```java
//...
Post post = new Post();
post.setId(UUID.randomUUID().toString());

User user = new User();
user.setId(UUID.randomUUID().toString());
user.getPosts().add(post);
user.getPosts().clear();

singleEntityStore.insert(user);// or upsert
```

**With insert:**
The following error is thrown:
```
io.requery.sql.RowCountException: Expected 1 row affected actual 0
```
While normally, no post should be inserted because the list of posts in user is emptied.


**With upsert:**
The user is inserted in database, but the post is also inserted in database, but without user relation (the value of user field in post is `null` in database).

**Conclusion:**
Therefore, I feel that the store (Unit Of Work / Entity Graph) do not correctly handle instances of entities in the collections.

**PS:** I don't know if it is correlated with this issue, but there is a bug with the `Key` using the `UUIDConverter`: for the insert/update/delete, it's ok, but perform a select query or findByKey, and the store returns an empty list or an error. In 2 cases, it seems that there is a problem with the management of the `Key`, but I will create a new issue if this is not the case.

**Comment by npurushe** [comment]
Thanks for the detailed example code, in your particular case you clear a tracked collection of an element  that is not inserted yet, so that element is put into a set of elements to be deleted. Since it was never persisted it throws an exception since no rows in the database were changed.

**Comment by npurushe** [comment]
See #163 for the UUID conversion problem

**Comment by npurushe** [comment]
Keeping open since original reporter's issue may still be present

**Comment by francoispluchino** [comment]
@npurushe The problem is solved for the `insert` with the 6a4f061dc99a9a791a13c7b7ca57c17a6d9424a4 commit, but always present for the `upsert`:

The user is inserted in database, and the post is also inserted in database, but without user relation (the value of user field in post is `null` in database).

Normally, the `upsert` should have the same behavior as the `insert`.

**Comment by francoispluchino** [comment]
@npurushe It's ok for me now. Thanks!

**Comment by npurushe** [comment]
No problem the beta21 version contains these changes.

**Comment by Rufim** [comment]
problem is in beta23: relationships not saved on insert. Function return entity with zero size insted.
  `EntiryWriter   (453)   proxy.link(context.read(entityClass));` 
afrer that all relationships entity is clearing.

**Comment by npurushe** [comment]
I noticed you are creating your own collection (ArrayList) in the entity class this would get replaced with an ObservableList to track the changes to the collection that maybe the source of the issue. Before you insert which List type is being used?

**Comment by Rufim** [comment]
ObservableList 
  
For example 
public void addCategory(Category category) {
        this.getCategories().add(category);
    }
getCategories() will return ObservableList  in case of new AuthorEntity or ArrayList in case of  Author
BUT if i not already persist (save) entity in database AuthorEntity,getCategories() will return ArrayList also (or exactly proxy.get(CATEGORIES)). So if i set something in this list changes wont be saved. 
i just search way to save and update with only one query but current workling code will looks like that:
` public AuthorEntity doActionAuthor(Action action, AuthorEntity authorEntity) {
        AuthorEntity result;
        if (action.equals(Action.INSERT)) {
            List<Category> categories = authorEntity.getCategories();
            List<Work> works = authorEntity.getRootWorks();
            List<Link> links = authorEntity.getRootLinks();
            result = (AuthorEntity) doAction(action, authorEntity);
            result.getCategories().addAll(categories);
            result.getRootWorks().addAll(works);
            result.getRootLinks().addAll(links);
            action = Action.UPDATE;
            result = (AuthorEntity) doAction(action, result);
            for (Category category : result.getCategories()) {
                for (Linkable linkable : category.getLinkables()) {
                    if (linkable instanceof Link) {
                        ((Link) linkable).setAuthor(authorEntity);
                        category.getLinks().add((Link) linkable);
                    }
                    if (linkable instanceof Work) {
                        ((Work) linkable).setAuthor(authorEntity);
                        category.getWorks().add((Work) linkable);
                    }
                }
            }
        } else {
            result = (AuthorEntity) doAction(action, authorEntity);
        }
        for (Category category : authorEntity.getCategories()) {
            category.setAuthor(result);
            for (Work work : category.getWorks()) {
                work.setCategory(category);
                work.setAuthor(null);
            }
            for (Link link : category.getLinks()) {
                link.setCategory(category);
                link.setAuthor(null);
            }
            doAction(action, category);
        }
        if (result != null) {
            return result;
        } else {
            return authorEntity;
        }

    }

    private Persistable doAction(Action action, Object value) {
        Persistable result = null;
        if (value instanceof Persistable) {
            Persistable entity = (Persistable) value;
            switch (action) {
                case INSERT:
                    result = dataStore.insert(entity);
                    break;
                case UPDATE:
                    result = dataStore.update(entity);
                    break;
                case DELETE:
                    dataStore.delete(entity);
                    break;
                case UPSERT:
                    result = dataStore.upsert(entity);
                    break;
            }
        }
        return result;`

**Comment by Rufim** [comment]
So currently cascade operations has vary little poor support or i just not understand something then please put more detaled examples on wiki how to handle entities with complex relationships

**Comment by npurushe** [comment]
Looking at your code the problem is with using the ArrayList, the requery code is expecting all field collections to be null/uninitialized. If it's not null it won't set the field to a new ObservableList instance and then cannot track any changes in them. If used in that way it works fine [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L620). 

Any specific reason for initializing the collections to an array list? If so can look at a way to support your use case

**Comment by Rufim** [comment]
Thanks! it seems solve my problem. but created new for some reason. 
When i try to delete entity now it says:
 io.requery.sql.RowCountException: Expected 1 row affected actual 0
            at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:167)
            at io.requery.sql.EntityWriter.delete(EntityWriter.java:813)
            at io.requery.sql.EntityWriter.cascadeRemove(EntityWriter.java:943)
            at io.requery.sql.EntityWriter.clearAssociations(EntityWriter.java:849)
            at io.requery.sql.EntityWriter.delete(EntityWriter.java:811)
            at io.requery.sql.EntityWriter.cascadeRemove(EntityWriter.java:943)
            at io.requery.sql.EntityWriter.clearAssociations(EntityWriter.java:849)
            at io.requery.sql.EntityWriter.delete(EntityWriter.java:811)
            at io.requery.sql.EntityDataStore.delete(EntityDataStore.java:336)
            at ru.samlib.client.service.ObservableService.doAction(ObservableService.java:70)
            at ru.samlib.client.service.ObservableService.deleteAuthor(ObservableService.java:81)

**Comment by npurushe** [comment]
Looks like it is already deleted. This may have to do with your cascade rules, but it should not throw for that, I will create another issue to track that

**Comment by Rufim** [comment]
No its still can be loaded from db after  delete.  i restarted my app so it cant be loaded from cache.

**Comment by Rufim** [comment]
Great!! After update to rc1 entity deleted without problem! Thanks!
