### ISSUE TITLE
Generated "is" method for boolean type in entity object 

### ISSUE THREAD

**Issue by cocia** [requery/requery#159]
for example:
```java
protected boolean cached;
```
In generated code this attr method should be:
```java
public boolean isCached(){...}
```
actually it is:
```java
public boolean getCached(){...}
```
This is only a minor difference as java bean name rule.
How do you think it?

**Comment by vmitiaev** [comment]
For myself I solved this problem with the help of @Naming
Example: @Naming(getter = "isCached")

**Comment by npurushe** [comment]
Right @Naming allows you to customize the generated method names

**Comment by cocia** [comment]
I agree @Naming is a good way to change the default method name.
If the default method getter is "isXXX". Some one need to change to other name by this annotation. That could be better. "isXXX" is java bean/entity name rule.
