### ISSUE TITLE
Proguard issues Requery beta19

### ISSUE THREAD

**Issue by vanniktech** [requery/requery#160]
#136 is still not resolved. I upgraded to beta19 and removed `-dontwarn io.requery.**` and we're still getting issues.

> Warning: io.requery.android.sqlcipher.SqlCipherDatabaseSource: can't find superclass or interface net.sqlcipher.database.SQLiteOpenHelper
Warning: io.requery.android.sqlitex.SqlitexDatabaseSource: can't find superclass or interface io.requery.android.database.sqlite.SQLiteOpenHelper
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteConstraintException
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteException
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteException
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteException
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteException
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherConnection: can't find referenced class net.sqlcipher.database.SQLiteException
Warning: io.requery.android.sqlcipher.SqlCipherDatabaseSource: can't find referenced class net.sqlcipher.database.SQLiteOpenHelper
Warning: io.requery.android.sqlcipher.SqlCipherDatabaseSource: can't find referenced class net.sqlcipher.database.SQLiteDatabase
Warning: io.requery.android.sqlcipher.SqlCipherDatabaseSource: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getWritableDatabase(java.lang.String)' in program class io.requery.android.sqlcipher.SqlCipherDatabaseSource
Warning: io.requery.android.sqlcipher.SqlCipherDatabaseSource: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getReadableDatabase(java.lang.String)' in program class io.requery.android.sqlcipher.SqlCipherDatabaseSource

**Comment by npurushe** [comment]
This is fixed by #158 and will be in the next update

**Comment by npurushe** [comment]
beta20 contains the updated proguard rules
