### ISSUE TITLE
Unable to open db error : "unable to open database file (code 14)"

### ISSUE THREAD

**Issue by danysz** [requery/requery#161]
I got error : 
exception: unable to open database file (code 14)
AppData::create pipe(2) failed: Too many open files

Every time I call a query after it I do "query.close()".
What shall I do ?

more info :
I have only one 
 EntityDataStore<Persistable>  in the application class.

    private void initDataStorage(){
        if (mEntityDataStore == null) {
            // override onUpgrade to handle migrating to a new version
            DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 3);
            if (BuildConfig.DEBUG) {
                // use this in development mode to drop and recreate the tables on every upgrade
                source.setTableCreationMode(TableCreationMode.DROP_CREATE);
            }
            Configuration configuration = source.getConfiguration();
            mEntityDataStore = new EntityDataStore<Persistable>(configuration);
        }

    }

**Comment by npurushe** [comment]
Do you have the full stack trace? If the error is `unable to open database file (code 14)` then the file could not be opened and is probably not related to not closing cursors. It fails on app start correct? did you just update the database schema version?

**Comment by npurushe** [comment]
If you have any updates on this issue please post back, thanks
