### ISSUE TITLE
Update from beta 19 to 20 select order by issue

### ISSUE THREAD

**Issue by miomao656** [requery/requery#165]
I upgraded the library and my unit tests break just here, nothing is returned, rows 5 , offset 5

```
ReQuery.getInstance().getDataStore().select(DocumentEntity.class)
        .orderBy(DocumentEntity.UPLOAD_DATE.desc())
        .limit(rows)
        .offset(offset)
        .get().toObservable()
        .toList()
```

**Comment by npurushe** [comment]
Are you sure the data for your selection is in the database? What is the raw sql that is executed (and does that return any results)?

**Comment by miomao656** [comment]
I have a test that gets all the data and it returns all data from db.

**Comment by npurushe** [comment]
Double checked the test output of https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L717 and didn't see any problems with the generated sql

`select id, address, age, birthday, email, homepage, name, picture, uuid from Person where name = ? limit 5 offset 5` 

if you an example or the sql output that reproduces please provide
