### ISSUE TITLE
Generated SQL statements from queries

### ISSUE THREAD

**Issue by hastebrot** [requery/requery#172]
Are there any plans to allow output of generated SQL statements directly without a `StatementListener`?

Some problems are

- `DefaultOutput`  which uses `StatementGenerator` is not easily reachable
- ~~`EntityDataStore` does not provide something like a `Query` as return for `select`, `insert` and `update` by design.~~ The methods in `EntityDataStore` return `QueryElement` objects, but the return types are superclasses of `QueryElement`.

I'm just exploring the API; this could be a totally useless use-case.

**Comment by hastebrot** [comment]
Here is some example code (in Kotlin). It only works for methods in `EntityDataStore` that return a `Result` (`select()`, `insert()`), but not for `Scalar` (`update()`, `count()`).

~~~kotlin
fun <T> generateSql(result: Result<T>,
                    configuration: Configuration): String {
    val query = (result as ObservableResult<T>).unwrapQuery()
    val connection = configuration.connectionProvider().connection
    val platform = PlatformDelegate(connection)
    val queryBuilder = QueryBuilder(QueryBuilder.Options(
        connection.metaData.identifierQuoteString,
        true,
        configuration.quoteTableNames(),
        configuration.quoteColumnNames()
    ))
    val statementGenerator = StatementGenerator.create(platform)
    val output = DefaultOutput(statementGenerator, query, queryBuilder, null, true)
    return output.toSql()
}
~~~

**Comment by npurushe** [comment]
Are you looking to just generate SQL and use it yourself and not execute any of the included requery jdbc code? That could be a possible enhancement depending on the use case

**Comment by npurushe** [comment]
Closing for now if you have more information please update

**Comment by hastebrot** [comment]
>just generate SQL and use it yourself and not execute any of the included requery jdbc code

Yeah, that would be interesting. As bonus requirement it would be nice to have the SQL quere generator as `Stream<String>` to retrieve the queries which were lazily generated (i.e. access to fields that were not in the query, partial objects). I had not played around with partial objects, yet.
