### ISSUE TITLE
OneToMany limitation on upsert

### ISSUE THREAD

**Issue by PipoloyJo** [requery/requery#173]
Hello,

I am currently trying out requery in one of my project, and I am facing a small issue. I am using beta20 for now, since I saw there was an issue with the beta21 and gradle.

I have reproduced my issue on the requery-example and requery-test projects to make it easier for you to understand the issue.

This code is taken from FunctionalTest:

```
@Test
public void testInsertOneToMany() {
    Person person = randomPerson();
    data.insert(person);
    Phone phone1 = randomPhone();
    Phone phone2 = randomPhone();
    phone1.setOwner(person);
    phone2.setOwner(person);
    data.upsert(phone1); // faulty line I introduced, it will try to insert (instead of update) the linked person
    data.insert(phone2);
    HashSet<Phone> set = new HashSet<>(person.getPhoneNumbers().toList());
    assertEquals(2, set.size());
    assertTrue(set.containsAll(Arrays.asList(phone1, phone2)));
}
```

In this upsert the linked person is up-to-date in the DB (all attributes are LOADED, none are MODIFIED), and somehow it ends up trying to insert it, which raises an SQLException on unicity since the person is already stored.

I have debugged the issue until the EntityWriter (line 492):

```
public void upsert(E entity, final EntityProxy<E> proxy) {
...
} else {
    if (update(entity, proxy, false, CascadeMode.UPSERT) == 0) {
        insert(entity, proxy, false, CascadeMode.UPSERT); // We are getting in there but I think we     should'nt
    }
}
```
My personnal usecase is that I have a webservice sending JSON items from its own DB and I am mapping them (with Gson) to my local java requery entities.

When I receive this items I don't know if these are new items or updates of items already stored by the app, that's why upsert was quite handy. I know it cost more, but the sync process I am trying to achieve will take place in the background so we can afford it.

My workaround for now will be to check if the item is already stored in the DB and apply the appropriate operation (insert/update). I am pretty sure that's what upsert aims for.

I am not sure if it is a current limitation of the framework or if I misunderstood something, any help is appreciated.

Thanks for this great framework!

**Comment by npurushe** [comment]
Hi this issue was specifically fixed in the beta21 version. Can you try with that, if you have an issue with that version please post the error you have. Thanks.

**Comment by PipoloyJo** [comment]
Hello,

Just tried the beta21, it applied fine and upsert is now working.

Thank you!

**Comment by npurushe** [comment]
Sure!
