### ISSUE TITLE
[BUG] Delete method not working properly?

### ISSUE THREAD

**Issue by francoispluchino** [requery/requery#174]
With `Blocking Entity Store` or `Reactive Store`, I have the `io.requery.sql.RowCountException: Expected 1 row affected actual 0` exception when I try to delete an entity just after called the `findByKey` method.

```java
User user = reactiveStoreEntity.toBlocking().findByKey(User.class, id);

if (user != null) {
    reactiveStoreEntity.toBlocking().delete(user);
}
```

I do not know if I've missed something, but with `1.0-beta21` version, it no longer works.

**Comment by npurushe** [comment]
I added a test case for that specific case https://github.com/requery/requery/commit/25a0139704fb652060d52fbd0b39a65555d45b6b

Seems to be working fine, are sure you have not already deleted the entity before and still have a reference to it and then deleting it again?

**Comment by francoispluchino** [comment]
Sorry, I have forgot to mention that the problem is present with a `OneToOne` relationship with cascade `CascadeAction.DELETE`.

**Example:**
```java
@Entity
public interface User extends Parcelable, Persistable {
    @Key
    String getId();

    String getUsername();

    @OneToOne(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    @ForeignKey
    Profile getProfile();
}
```
```java
@Entity
public interface Profile extends Parcelable, Persistable {
    @Key
    String getId();

    String getLastName();

    String getFirstName();
}
```
```java
User user = reactiveStoreEntity.toBlocking().findByKey(User.class, id);

if (user != null) {
    reactiveStoreEntity.toBlocking().delete(user);
}
```
I have the `io.requery.sql.RowCountException: Expected 1 row affected actual 0` exception.

I have another `OneToMany` relations with cascade `CascadeAction.DELETE`, but it's ok. Only `OneToOne` relation has a problem on delete action.

**Comment by Pr0bability** [comment]
I have a similar problem in my application, when deleting a Medication entity (#169).

**Comment by npurushe** [comment]
Thanks for reporting fix will be in the next update shortly

**Comment by francoispluchino** [comment]
@npurushe Thank you for your speed!
