### ISSUE TITLE
Missing column is not added on upgrade

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#175]
I've added a new column to my entity, it's a new string, I expected to default Database Source handle the table upgrade, like I read on this [comment](https://github.com/requery/requery/issues/70#issuecomment-205579064) but after running my app again I got the following exception:

Caused by: android.database.sqlite.SQLiteException: no such column: title (code 1)

The application is already in production stage and I need to add a string field to my entity, but looks the default onUpgrade is not handling addition of missing columns

**Comment by npurushe** [comment]
Whenever you make a schema change you need to increment the schema version for the upgrade code to run.
