### ISSUE TITLE
change entity from Interface to Abstract

### ISSUE THREAD

**Issue by danysz** [requery/requery#176]
Hi

I understand that I need to use abstract to be able to use @Transient.
I changed one of my Entities to Abstract and the rest are still interfaces.
Since them I am not able to compile it anymore becuase the *Entity classes are not generated anymore.
Trying to understand why and I will be really happy to get some help.

Here is my class..
```
@Entity
public abstract class AbstractNodeKey {

    @Index("indexKey")
    int keyNumber;

    @Index("indexKeyName")
    String Name;

    @ManyToOne
    @Index("indexKey")
    Node Node;

    ENodeKeyType KeyType;

    int Category;

    @ManyToOne
    Room Location;

    @Transient
    KeyStatusData KeyStatusData;
}
```
Thanks a lot for any help

**Comment by npurushe** [comment]
Hi whenever you make a change that prevents generation from occurring it's highlighted in the gradle message window like so https://github.com/requery/requery/issues/169#issuecomment-223828475. What's the error you are encountering? Posting the `gradle build` output should also show this.

**Comment by npurushe** [comment]
Since this issue is similar to #169 closing for that. If you have more info please update thanks
