### ISSUE TITLE
Foreign Key Constraint Failed

### ISSUE THREAD

**Issue by Glurt** [requery/requery#177]
I've recently picked up the project I was working on and found that you can now upsert many to many relationships which is nice. However I'm running into an issue with the foreign key.

Just to recap, I have Superclass Thing
````
@Superclass
public abstract class Thing implements Persistable {

    @Key
    public String id;

    @Column(unique = true)
    public String name;
    @Column
    public DateTime created;
    @Column
    public DateTime created_utc;
}
````

I then have an Account 
````
@Entity
public abstract class AbstractAccount extends Thing {

@ManyToMany(mappedBy = "subscribedAccounts")
    List<Subreddit> subreddits;
}
````

And I also have Subreddit
````
@Entity
public class AbstractSubreddit extends Thing {

    @JunctionTable(name = "Subreddit_Subscribers")
    @ManyToMany
    List<Account> subscribedAccounts = new ArrayList<>();
}
````

When the user logs in I download all of the information associated with their account along with any subscribed subreddits and add them to the list. I then try to persist the account with its subreddits and run into the following exception.

android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)

I understand the role of a foreign key and this is likely being thrown because the key doesn't exist in either the account or subreddit table but I'm not sure where I'm going wrong. It seems to fail on the first subreddit so I'm guessing that this is being executed before the subreddits are inserted.

**Comment by Glurt** [comment]
I've done some debugging and I've found that the subreddits aren't being inserted because the keyAttribute count in EntityWriter.update is 0, this is because proxy.getState(value) inside the test returns PropertyState.FETCH. 

These items are created using Retrofit and I'm assuming they should be MODIFIED.

Do you know why this might be happening?

**Comment by npurushe** [comment]
In the generated class Account when you modify the subreddits list the state of the subreddits attribute should be MODIFIED as you said. Is it possible that the `subreddits` is overwritten? Before inserting it you should see it's type is `io.requery.util.ObservableList`

**Comment by Glurt** [comment]
Ok so it was an ArrayList but I realised that this was because I had instantiated it as such in the abstract class.

````
@ManyToMany(mappedBy = "subscribedAccounts")
List<Subreddit> subreddits **= new ArrayList<>()**;
````

Removing that it's now an ObservableList but the problem still persists.
I'll keep looking.

**Comment by Glurt** [comment]
The Subreddits are being downloaded from the web as an ArrayList with each Subreddit being created by parsing Json using Gson (that's what Retrofit takes care of). Does an entity need to be created in a certain way in order for the state of each attribute to populated?

**Comment by npurushe** [comment]
See the discussion on #73 there are some possible solutions there. It still an area that maybe be able to be improved upon, however gson is not as flexible as other json libraries like jackson, so it may not be possible to support all requery features when the object is serialized through gson.

**Comment by npurushe** [comment]
Closing for #73 please check that issue for updates thanks
