### ISSUE TITLE
My "sub-" entities are not saved

### ISSUE THREAD

**Issue by colletjb** [requery/requery#178]
Hi, 

I'm currently trying to integrate requery 1.0.0-beta21 into my project.

I have a entity "A" containing a List of entities "B" which also contains entities "C".

I have no clue why, but when i save my entities, on "A"s are saved, "B"s and "C"s are removed from my object. 

```
EntityDataStore<A> aDatastore = new EntityDataStore<>(mDatabaseSource.getConfiguration());
long aId = aDatastore.insert(a).getId();
```

Can someone help me ?

Thanks a lot.

```
public abstract class A {

@Key
@Generated
long id;

@OneToMany(cascade = {CascadeAction.DELETE, CascadeAction.SAVE}, mappedBy = "aObject")
@SerializedName("B")
List<B> mBList;

}

public abstract class B {

@Key
@Generated
long id;

@ManyToOne(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
@SerializedName("A")
A aObject;

@OneToMany(cascade = {CascadeAction.DELETE, CascadeAction.SAVE}, mappedBy = "bObject")
@SerializedName("C")
List<C> mCList;

}

public abstract class C {

@Key
@Generated
long id;

@ManyToOne(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
@SerializedName("B")
B bObject;

}
```

**Comment by npurushe** [comment]
Hi if you're using gson then gson will write to the fields directly and for lists/collections that makes it impossible for the library to keep track of what has changed inside them. So to workaround that set @Entitiy(stateless=true) but this means everything in the collection will persisted regardless if anything changed or not (less efficient).

**Comment by npurushe** [comment]
This issue looks similar to #73 & #177 so closing, please check those issues for more info thanks
