### ISSUE TITLE
How do I add NOT NULL Constraint to Column?

### ISSUE THREAD

**Issue by yuichi-hamasaki** [requery/requery#18]
I use requery in Android app.
io.requery.Column dose not have NOT NULL Constraint attribute.
How do I add NOT NULL Constraint to Column?

**Comment by npurushe** [comment]
By default the nullability is determined by the type used in the model (for instance if you had int, it would be NOT NULL, but Integer it would not be. But I think there should be a nullable attribute in the `@Column` annotation as well. would that work for you? Thanks for the feedback!

**Comment by yuichi-hamasaki** [comment]
Yes. Thank you.

**Comment by npurushe** [comment]
Hi you can use `gradle build --refresh-dependencies` to get the latest snapshot version with the changes. Thanks!

**Comment by yuichi-hamasaki** [comment]
@npurushe 
I confirmed this enhancement  in latest version.
Thanks.
