### ISSUE TITLE
Observable result is never emitted if limit clause is used with flatMap

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#181]
I'm facing a strange issue while using limit clause in my query within a flatmap to convert the result into an list, like the following:
```java
getData().select(ModelEntity.class)
        .orderBy(ModelEntity.CREATED_AT.desc())
        .limit(3)
        .get().toSelfObservable()
        .flatMap(modelEntities -> modelEntities.toObservable().toList())
        .subscribe(modelEntities -> {
            // this is never called
        }, throwable -> {
            // this is never called
        });
```
Callbacks are never called in this way (Just for note, I've about 500 entities in my db)

But if I remove the `limit` clause the list gets emitted, also if I remove the flatMap call leaving the limit there, the Result object gets emitted, but if I use both the list never get emitted and no errors are thrown.

Another test I did was adding a where clause to this snippet to fetch less than 5 items in db, and this way the items get emitted.. 

But I need to make this work with the snippet above, I don't know the reason, I'm using the latest version... 

If you need more info, please feel free to ask.

**Comment by npurushe** [comment]
Thanks for reporting there did seem to be a problem there

**Comment by YuriHeupa** [comment]
This changes will work with #153 ?

**Comment by npurushe** [comment]
Yes

**Comment by YuriHeupa** [comment]
Any plans to release these changes soon?

**Comment by npurushe** [comment]
Could be a couple of days, the snapshot version `1.0.0-SNAPSHOT` on http://oss.jfrog.org/artifactory/oss-snapshot-local/ contains these changes though

**Comment by francoispluchino** [comment]
@npurushe This repository is not updated regularly: last update the May 30, 2016 (more than a week).
@YuriHeupa Instead, use [JitPack](https://jitpack.io/):

```gradle
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

With dependencies:
```gradle
dependencies {
    compile 'com.github.requery.requery:requery:master-SNAPSHOT'
    compile 'com.github.requery.requery:requery-android:master-SNAPSHOT'
    apt "com.github.requery.requery:requery-processor:master-SNAPSHOT"
}
```

It is also advisable to change the resolution strategy to avoid using the cache:
```gradle
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
```

**Comment by npurushe** [comment]
http://oss.jfrog.org/artifactory/oss-snapshot-local/io/requery/ does contain this change

**Comment by francoispluchino** [comment]
If this is the case now, thanks.
