### ISSUE TITLE
QueryRecyclerAdapter with Tuple

### ISSUE THREAD

**Issue by ToxicBakery** [requery/requery#182]
I need to return a model sorted on a count then display the results in a QueryRecyclerAdapter but it does not seem possible to use Tuple as the adapter type. Am I missing something obvious or is this not possible?

**Comment by npurushe** [comment]
Thanks for reporting. Yes currently `QueryRecyclerAdapter` works only with entity types but with some minor changes it can work with the `Tuple` class as well.

**Comment by ToxicBakery** [comment]
Semi related, where do we send "beer" money?

**Comment by npurushe** [comment]
currently not taking donations or anything, thanks though! however if people are ever visiting SF I'll definitely accept a beer
