### ISSUE TITLE
Can't upsert entity with generated key

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#183]
I'm facing an issue while trying to persist an entity with an field anotated with ManyToOne, that entity don't persist with upsert, and it throws this error message: `java.lang.UnsupportedOperationException: Can't upsert entity with generated key`

```java
@Entity
public interface Book extends Parcelable, Persistable {
    @Key @Generated
    int getId();
    String getTitle();
    
    @ManyToOne
    Author getAuthor();
}
```

And this is the entity for many to one relation:
```java
@Entity
public interface Author extends Parcelable, Persistable {

    @Key
    int getId();
    String getName();
    @OneToMany
    Set<Book> getBooks();
}
```

Actually I'm retrieving Authors from remote server, which provide their unique ID, but for related books I don't have an remote ID, so I need to generate it locally, that's the reason I've @Generated in book id field.

This is the snippet to reproduce the error:
```java
AuthorEntity author = new AuthorEntity();
author.setId(remoteId);
author.setName(remoteName);
author.getBooks().clear();
for (BookDTO book : remoteBooks) {
    BookEntity book = new BookEntity();
     #book.setTitle(book.getTitle());
    author.getInsertions().add(book);
}
// This throws the error message
getData().upsert(author).subscribe();
```

I'm wondering if this is a bug or my approach is wrong. How should I handle this situation?

**Comment by npurushe** [comment]
A generated key means the key is created upon insertion of the data, it's not possible to upsert there  because in order to do an update the key value must already be known. Possible solution would be to provide your own id locally for the book values instead of having the database generate it, or upsert the author first without the changed book values, and then insert/update books separately.

**Comment by YuriHeupa** [comment]
Really, sounds right. I'll do some workaround to handle this. Thank you and keep the nice work! 😀
