### ISSUE TITLE
Column names should be in quotes

### ISSUE THREAD

**Issue by gowong** [requery/requery#184]
It doesn't seem possible to use sqlite keywords as column names because they aren't being quoted as instructed by the [sqlite docs](https://www.sqlite.org/lang_keywords.html).

If I have the following entity:
```java
@Entity
public abstract class DbModel {

	@Key
	@Generated
	int id;

	@Column(nullable = false, unique = true)
	int order;
}
```

I get this exception
```sql
java.sql.SQLException: android.database.sqlite.SQLiteException:
near "order": syntax error (code 1): , while compiling: 
create table DbModel (id integer primary key autoincrement, order integer not null unique)
```

`order` should be `"order"` in the create table statement

**Comment by npurushe** [comment]
In order to quote column names and be able to use reserved keywords as columns you just need to do the following:

```java
DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 1) {
                @Override
                protected void onConfigure(ConfigurationBuilder builder) {
                    super.onConfigure(builder);
                    builder.setQuoteColumnNames(true);
                }
            };
```
It's not enabled by default since it may not be desirable to have column names that are reserved in certain cases, although for SQLite it may be ok.

**Comment by gowong** [comment]
Cool, good to know!
Is it possible to throw a compile error or warning when a reserved keyword is used? It took me awhile to go through my logs to figure out the column name was the issue.

**Comment by npurushe** [comment]
It should be emitted as a warning per #102 should see something to the effect of '`Column or index name <name> may need to be escaped`

**Comment by gowong** [comment]
I didn't get that warning, but I have gotten other warnings about foreign keys before so it seems like that specific warning might not be working.
Just curious, what's the reason for not quoting column names by default? Does it cause any issues if they're just always quoted?

**Comment by npurushe** [comment]
The warning wasn't being printed for plain field that is fixed, thanks. As for always quoting need to see if there is any performance impact from doing that in the sqlite parser if not will enable it.

**Comment by gowong** [comment]
Sounds good, thanks!
