### ISSUE TITLE
Android:Pre-defined manual script upgrade feature

### ISSUE THREAD

**Issue by cocia** [requery/requery#185]
Requery has an auto schema updater component : SchemaUpdater. SchemaUpdater can update new schema according to model class changing. 

I think this is good but not enough in real complex app upgrade process. We have to add some manual script to protect user's data belonging to old version.

If Requery could include a pre-defined sql script upgrade component that will be very convenient for developers. It likes a plugin for Requey android version.

For example:
Add sql scrpits to android asserts folder:
sql/requery_upgrade_100_to_101.sql
sql/requery_upgrade_104_to_105.sql

If current upgrade is 
from 99 to 105 
then execute 
requery_upgrade_100_to_101.sql and requery_upgrade_104_to_105.sql

If current upgrade is 
from 100 to 105 
then execute 
requery_upgrade_100_to_101.sql and requery_upgrade_104_to_105.sql

If current upgrade is 
from 101 to 105 then execute 
requery_upgrade_104_to_105.sql

If current upgrade is 
from 102 to 105 
then execute 
requery_upgrade_104_to_105.sql

If current upgrade is 
from 104 to 105 
then execute 
requery_upgrade_104_to_105.sql

After executed manual upgrade scripts, Requery could execute auto SchemaUpdater to make sure model classes are compatible to table schames.

I added my draft implementations for your reference. They are not tested yet.
[requery-android-manual-upgrade-draft.zip](https://github.com/requery/requery/files/311186/requery-android-manual-upgrade-draft.zip)

**Comment by npurushe** [comment]
Closing for now. This is easy enough to do by overriding onUpgrade and provides the most flexibility if something custom needs to be done.
