### ISSUE TITLE
EntityDataStore. Incorrect check size Set<EntityStateListener>.

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#186]
File - EntityDataStore.java, line - 177

        if (configuration.getEntityStateListener().isEmpty()) {
            for (@SuppressWarnings("unchecked")
                 EntityStateListener<T> listener : configuration.getEntityStateListener()) {
                entityListeners.add(listener);
            }
        }

**Comment by npurushe** [comment]
Thanks for reporting!
