### ISSUE TITLE
Use QueryAttribute with List of Objects

### ISSUE THREAD

**Issue by adauvalter** [requery/requery#187]
I have some entity with a list of String and I would like to make some request such as `(Result<ImageModel>) data.select(ImageModel.class).where(ImageModelType.CIRCLES.contains("1234")).get();` to check if list contains some element. How can I use QueryAttribute with a list of objects?

**Comment by npurushe** [comment]
Does the 'in' operator work for your case? For [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L986)

**Comment by adauvalter** [comment]
I think not, because in means, that i have, for example value "hello" and check if `in` in the list "hello, other". But if I have values "1", "2", "3" and check if this values are `in` "1", i should return false. But if I could check if  "1","2","3"  `contains` "1" then

**Comment by npurushe** [comment]
May need some more information. What type of column is ImageModelType.CIRCLES how are you storing it? is it CSV or something else? or if you have an example of the sql you want to see generated that would also help

**Comment by npurushe** [comment]
If you have an update here please post back but closing for now
