### ISSUE TITLE
Observe query on table changes and db connection idle

### ISSUE THREAD

**Issue by mgorski-zlatan** [requery/requery#188]
I'm using RxJava observe query on table changes

`data.select(DbItemEntity::class.java)
.orderBy(DbItemEntity.CHECKED.asc())
.get()
.toSelfObservable()
.subscribeOn(Schedulers.io())
.map { it.map { it.toAppModel() } }
.observeOn(AndroidSchedulers.mainThread())
.subscribe { ... }`

And after that when I made update in db and once again used select, the query didn't finish. In log I get only 'beforeExecuteQuery', 'afterExecuteQuery' didn't occure.
And I get information that connection is idle.

`W/SQLiteConnectionPool: The connection pool for database '/data/data/pl.lizardproject.qe2016/databases/default' has been unable to grant a connection to thread 574 (RxIoScheduler-3) with flags 0x1 for 120.00101 seconds.
                                                                               Connections: 0 active, 1 idle, 0 available.`

My datastore configuration:

`val source = SqlitexDatabaseSource(context, Models.DEFAULT, 1)
source.setLoggingEnabled(true)
val data = RxSupport.toReactiveStore(EntityDataStore<Persistable>(source.configuration))`

**Comment by npurushe** [comment]
How many queries do you have subscribed concurrently? Some possible solutions would be to use a single threaded Scheduler for subscription (instead of Schedulers.io() which is a pool). Also do you have the same problem using regular `DatabaseSource` vs `SqlitexDatabaseSource`? thanks

**Comment by npurushe** [comment]
How are you updating the database using a transaction with several calls to insert/update or just a single call to insert/update?

**Comment by mgorski-zlatan** [comment]
just a single call

**Comment by npurushe** [comment]
Can you post how you're doing your update? ([example](https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/PersonEditActivity.java#L119))

**Comment by mgorski-zlatan** [comment]
You can look at my code in repo - branch 'requery'
https://github.com/The-Lizard-Project/qe2016/tree/requery

**Comment by npurushe** [comment]
Thanks for providing an example project that helped find the problem

**Comment by mgorski-zlatan** [comment]
Thanks a lot too! It works perfect now.

**Comment by dadino** [comment]
I still have this problem.
