### ISSUE TITLE
Prevent generating entities with names that are reserved words

### ISSUE THREAD

**Issue by nishtahir** [requery/requery#189]
It doesn't look like there is any protection in place for preventing this from happening and errors don't point to this as being the problem when It does happen.

**Comment by npurushe** [comment]
This will be generated as a compiler warning, to escape the names you either escape the name directly using the @Table attribute e.g. @Table(name="\"name\"") or quote all table names via [setQuoteTableNames](http://requery.github.io/javadoc/io/requery/sql/ConfigurationBuilder.html#setQuoteTableNames-boolean-)
