### ISSUE TITLE
Make generated classes "friend" classes instead of extending entity class

### ISSUE THREAD

**Issue by nathanieloliveira** [requery/requery#19]
What if the generated code used some kind of mapping to persist our entity instead of putting all the information needed in a class that extends it.

I'm suggesting this because I was trying to make this library (which is good as it is right now, btw) to work together with LoganSquare, the code generated JSON serialization library. The problem arises because you can't serialize a generated entity class as it is not annotated. I don't know if this would be hard to implement or this isn't the purpose of this lib. Maybe add this as an optional way.

Sorry if I wasn't clear enough, English isn't my native language.
Thank you

**Comment by npurushe** [comment]
Thanks for the feedback. I think I understand the problem, I am planning to add something to make this library work with AutoValue objects, basically map onto another generated class that may solve this problem. 

Currently you can define an entity via an interface or create an abstract class. If you use an abstract class then you can add annotations from another library on the field members. This works for something like gson (which uses reflection) but if you use another processing library that generates from those members you will have two generated classes. Which I guess is the problem you haven when combining that library with this one?

**Comment by nathanieloliveira** [comment]
Yes this is exactly the problem.

**Comment by npurushe** [comment]
Hi do you have an example of a class you would want to serialize? I have added basic support for @AutoValue which generates its own class, and now with requery for those classes just a mapping class is generated containing just the attribute and mapping info. However it still may require some other changes to work with other libraries.

**Comment by nathanieloliveira** [comment]
Ideally, it should be possible to support any type of code generation based on your annotated class. I'll try to show an example of what I mean:

Using LoganSquare and Parceler in the example below.

```
@Parcel(Serialization.BEAN)
@JsonObject
@Entity
public class Person {
    @Key @Generated
    int id;

    @JsonField(name = "uuid", typeConverter = UUIDConverter.class)
    @Index(name = "uuid_index")
    @Converter(UUIDToStringConverter.class)
    public UUID uuid;

    // getters and setters generated by the IDE...
}
```

something along those lines.

Usages:
Parceler:
```
Person person = new Person();

Bundle bundle = new Bundle();
bundle.putParcelable("person", Parcels.wrap(person));

Person person = Parcels.unwrap(bundle.getParcelable("person"));
```

LoganSquare:
```
InputStream input = ... ( could be String instead)
Person person = LoganSquare.parse(input, Person.class);

String personString = LoganSquare.serialize(person);
```

I hope this helps.

**Comment by nathanieloliveira** [comment]
Hello @npurushe . I don't mean to bother, but any news on this issue?

**Comment by npurushe** [comment]
Sure the first pass was to add support for @AutoValue which will be fully supported in the next update. The issue with LoganSquare is that it creates an instance of your model class in it's JsonObjectMapper, the problem is that it is not configurable as far as I can see. 

In Parceler you can use @ParcelFactory and create a static method to return the requery generated class instead of the base one so that should already work.

**Comment by nathanieloliveira** [comment]
ok. I'll try switching to GSON for now, ty.
