### ISSUE TITLE
Docs about RxJava are not clear

### ISSUE THREAD

**Issue by dadino** [requery/requery#190]
I'm having difficulties understanding your support to RxJava. From the main readme I thought you had Observables that call onNext everytime something in the db changed (if the query is interested in the change), but then I can only find documentation for Single, that can only emit once (so there are no further notifications of db changes). What's the right way?

Your product seems really good, but the documentation is scattered throughout too many places, I'm still unable to find examples of inserts and deletes and I have to go to the examples to find some good select examples.

**Comment by npurushe** [comment]
Hi the Rx support can be summed up in this way and does support what you're looking for:

[Store operations (insert/update/delete)](https://github.com/requery/requery/wiki/Using-the-EntityStore-interface#rxjava)

Query operations:
[toObservable()](http://requery.github.io/javadoc/io/requery/query/Result.html#toObservable--) - the query results are returned as an Rx Observable sequence
[toSelfObservable()](http://requery.github.io/javadoc/io/requery/query/Result.html#toSelfObservable--) - the result itself is emitted as an Rx Observable and then emitted again if any sql statements are executed affecting the table

**Comment by dadino** [comment]
> [Store operations (insert/update/delete)](https://github.com/requery/requery/wiki/Using-the-EntityStore-interface#rxjava)

This brings me to the EntityStoreInterface page, where I can find no example on insert, update or delete operations.

I've figured out some of the stuff I needed, but an improvement in the documentation could help a lot.

**Comment by npurushe** [comment]
There is an example project using RxJava & Android illustrating many of those https://github.com/requery/requery/tree/master/requery-android/example. That being said there are a large number of supported cases (Rx, pure blocking API, Java 8 CompletionStage etc) it is difficult to provide an example for all API combinations but it will improve over time.

**Comment by npurushe** [comment]
Closing for now, if more info is needed please clarify
