### ISSUE TITLE
how to connect related objects...

### ISSUE THREAD

**Issue by danysz** [requery/requery#194]
Hi

I have an few entities that are related. I will present here only two and I will be really happy to get help for the load..

```
@Entity
public interface Floor extends Parcelable, Persistable {

    @Key
    int getId();

    @Column(unique = true)
    @Index("indexFloorName")
    String getName();

    @ManyToOne
    Connection getConnection();

    @OneToMany(mappedBy = "floor", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Room> getRoomsList();

}
```

```
@Entity
public interface Room extends Parcelable, Persistable  {

    @Key
    int getId();

    @Column(unique = true)
    @Index("indexRoomName")
    String getName();

    @ManyToOne
    @Index("indexRoomName")
    Floor getFloor();

    @ManyToOne
    Connection getConnection();

}
```

```
@Entity
public abstract class AbstractNodeKey {

    @Index("indexKey")
    int keyNumber;

    @Index("indexKeyName")
    String Name;

    @ManyToOne
    @Index("indexKey")
    Node Node;

    ENodeKeyType KeyType;

    int Category;

    @ManyToOne
    Room Location;

    @Transient
    KeyStatusData KeyStatusData;

    @ManyToOne
    Connection connectionId;

}

```

When I load the "Room" using `        Result<RoomEntity> query = AppControlPro.getApp().getEntityDataStore().select(RoomEntity.class).get();
`

The received objects oesn't have the "relevant" floors..

What I am doing wrong ?

Also when I try to use the `NodeKey.getLocation()` I got :

> near "where": syntax error (code 1): , while compiling: select Location from NodeKey where

I don't care to connect them after since everything is loaded in the app memory in few array lists ...

regards

Daniel

**Comment by npurushe** [comment]
Once you have a Floor loaded from a query or findByKey just call getRoomList() on it. For the second question your AbstractNodeKey has no primary key making look ups not possible, a key should be added to it.
