### ISSUE TITLE
strange fail on insert...

### ISSUE THREAD

**Issue by danysz** [requery/requery#195]
Hi

I have an entity 

```
@Entity
public interface Connection extends Parcelable, Persistable {

    @Key
    @Generated
    int getId();

    @Column(unique = true)
    @Index("indexConnectionName")
    String getName();

    @Column(unique = true)
    @Index("indexSSID")
    String getSSID();

    String getIPAddressLocal();

    String getIPAddressRemote();

    int getPortLocal();

    int getPortRemote();

    String getUserName();

    String getPassword();

    Long getVBoxLastUpdate();

    @OneToMany(mappedBy = "connection", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Floor> getFloorsList();
}

```

When I try to call insert on this kind of object for the second time in the "data" of ConnectionEntity the "id" is "0". For the second insert I got error that the "id" alreayd exist of course...
What I am doing wrong ?

Thanks

Daniel

**Comment by npurushe** [comment]
You should only `insert` once, and then if you further modify the object call `update` instead.

**Comment by danysz** [comment]
Of course.. But in the software I make
new connection and it's created with 0 in id...

On Monday, 20 June 2016, Nikhil Purushe <notifications@github.com> wrote:

> You should only insert once, and then if you further modify the object
> call update instead.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/requery/requery/issues/195#issuecomment-227051754>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABlzQAHjnAhvG2UW1c4DZbI1FncKkfGhks5qNiGWgaJpZM4I5HBF>
> .
>


-- 
Best regards

Daniel Szasz
