### ISSUE TITLE
lost all Entity models after "clean project" and can't generate them back

### ISSUE THREAD

**Issue by lectricas** [requery/requery#20]
Hi. I pressed "clean project button" and now my StackTrace gives me:
Error:(43, 13) error: cannot find symbol class TrackEntity
this errors. All generated classes are gone and didn't come back, lol.
Is there any way to fix this issue?

**Comment by npurushe** [comment]
Hi what IDE are using? If it's Android Studio 2.0 make sure you have the latest version as a number of important fixes were made to annotation processing. If not try running `gradle build` on your project and see if there are any errors from processing/compiling in the output and past them here.

**Comment by gholz** [comment]
I'm having the same problem with AS 2.0 and the latest gradle plugin (beta6)

**Comment by npurushe** [comment]
I tried the latest Android Studio beta 6 pressing clean does delete all generated source code, but if you build the project (Build > Make project) everything comes back fine. If you build from gradle are the files regenerated? Also what version of the apt plugin are you using? Thanks

**Comment by npurushe** [comment]
Are your entities in a separate Java jar project or in an Android application or library project? That sounds similar to [this issue](https://github.com/google/dagger/issues/95). Which can be solved by adding 

`provided 'javax.annotation:jsr250-api:1.0'` 

to your dependencies. But in the requery processor @Generated is not added if its not in the processor classpath, (Dagger 2 also ended up doing this). So in a Android app or library project @Generated shouldn't be getting added to any generated code.

**Comment by gholz** [comment]
Found my problem, i was having some conflicts with databinding that ended up messing up all generated classes.

**Comment by npurushe** [comment]
Resolving for now. Please reopen if the problem reoccurs
