### ISSUE TITLE
Abstract Class Implementation

### ISSUE THREAD

**Issue by caralin3** [requery/requery#201]
Hi I was wondering if you could provide an example using an abstract class. I am trying to do that now. I created a Person abstract class, but I'm not sure how to create a user from the generated Person class. Thank you!

**Comment by npurushe** [comment]
An overview of the various entity definition options and examples is [in the wiki](https://github.com/requery/requery/wiki/Defining-Entities)

You can also see a full example model in the test code: https://github.com/requery/requery/tree/master/requery-test/src/main/java/io/requery/test/model

**Comment by caralin3** [comment]
Thank you! How would I use the generated class to create an instance of a person?
