### ISSUE TITLE
PersonEntity Implementation

### ISSUE THREAD

**Issue by mjc00005** [requery/requery#202]
Hi I was wondering if you could provide an example using  PersonEntity. I am trying to do that now but I can not find the class in the example. 
Thank you!

**Comment by npurushe** [comment]
The library uses annotation processing to generate those classes. Simply create an example project with the right dependencies, build it then the classes will be visible in the IDE. See the [wiki](https://github.com/requery/requery/wiki) for more info

**Comment by mjc00005** [comment]
I download the  whole example porject with every modules (requery, requery-android, ... ) and it is not compile in Android Studio.  Do I need to modify anything?

thank you

**Comment by npurushe** [comment]
Please include any build error, if you're just using the example project change the example to just use requery from maven instead of building it locally
```gradle
dependencies {
    compile 'io.requery:requery:1.0.0-beta23'
    compile 'io.requery:requery-android:1.0.0-beta23' // for android
    apt 'io.requery:requery-processor:1.0.0-beta23'   // use an APT plugin
}
```
