### ISSUE TITLE
Inference of @ForeignKey in @JoinColumn

### ISSUE THREAD

**Issue by hastebrot** [requery/requery#203]
Is it possible to make @ForeignKey for @OneToOne/@JoinColumn optional? Background is that I want to restrict my entity beans to JPA 1.0 annotations.

**Comment by npurushe** [comment]
What's the reason for using JPA 1.0? It's quite old (10 years) and generally not supported anymore, probably it has too many annotations missing to be supportable.

**Comment by hastebrot** [comment]
Ebean seems to require JPA 1.0; I dually use Ebean and Requery while migrating to latter. I'll try to update the dependency to JPA 2.0/2.1. Makes sense to update it.
