### ISSUE TITLE
Android data binding annotation is not available

### ISSUE THREAD

**Issue by iamjay** [requery/requery#207]
In the documentation https://github.com/requery/requery/wiki/Android, it says to add an annotation to enable data binding, @BindingResource(Binding.BR_CLASS). But the annotation is not defined anywhere. In the example, this annotation is also not used https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/model/Person.java.

Is the documentation outdated?

**Comment by npurushe** [comment]
Hi yes sorry @BindingResource is not needed it is determined automatically at compile time. The wiki page has been updated, thanks!
