### ISSUE TITLE
inferred type does not conform to equality constraint

### ISSUE THREAD

**Issue by Rufim** [requery/requery#208]
When  i try to compile this code 
` joinAndOr = dataStore.select(AuthorEntity.class).distinct()
.leftJoin(CategoryEntity.class).on(CategoryEntity.AUTHOR_ID.equal(AuthorEntity.ID))     .leftJoin(WorkEntity.class).on(WorkEntity.AUTHOR_ID.equal(AuthorEntity.ID).or(WorkEntity.CATEGORY_ID.equal(CategoryEntity.ID)))         .leftJoin(LinkEntity.class).on(LinkEntity.AUTHOR_ID.equal(AuthorEntity.ID).or(LinkEntity.CATEGORY_ID.equal(CategoryEntity.ID)));`
i got error on compilation
ObservableService.java:24: error: method on in interface JoinOn<E> cannot be applied to given types;
                .leftJoin(WorkEntity.class).on(WorkEntity.AUTHOR_ID.equal(AuthorEntity.ID).or(WorkEntity.CATEGOR
____________________^ 
Y_ID.equal(CategoryEntity.ID)))
.leftJoin(WorkEntity.class).on(WorkEntity.AUTHOR_ID.equal(AuthorEntity.ID).or(WorkEntity.CATEGORY_ID.equal(CategoryEntity.ID)))
 required: Condition<V,?>
  found: LogicalCondition<CAP#1,CAP#2>
  reason: inferred type does not conform to equality constraint(s)
    inferred: CAP#3
    equality constraints(s): CAP#3,CAP#4
  where V,E are type-variables:
    V extends Object declared in method <V>on(Condition<V,?>)
    E extends Object declared in interface JoinOn
  where CAP#1,CAP#2,CAP#3,CAP#4 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
    CAP#3 extends Object from capture of ?
    CAP#4 extends Object from capture of ?

**Comment by npurushe** [comment]
Hi would you be willing to share your entity definitions, at least the parts used in the query?

**Comment by Rufim** [comment]
Of course.  you could see therm here. https://github.com/Rufim/Samlib/tree/master/Client/src/main/java/ru/samlib/client/domain/entity

**Comment by npurushe** [comment]
Interesting if you cast the argument passed to `on` to `io.requery.query.Condition` does it compile?

**Comment by Rufim** [comment]
Yes. seems it works like that. I will close this issue.
