### ISSUE TITLE
Only works with java8?

### ISSUE THREAD

**Issue by prsolucoes** [requery/requery#21]
This library only works with java8?

If yes, what i need change on android studio to make it works?

Thanks.

**Comment by npurushe** [comment]
Hi you need oracle JDK8 on your computer to run the processor that's it, for Android Studio see this [link](http://stackoverflow.com/questions/30631286/how-to-specify-the-jdk-version-in-android-studio). The library and code can be used on Android api level 15 and above. Have a look at the example Android [project](https://github.com/requery/requery/tree/master/requery-android/example). Basically just add the dependencies as listed in the README and set your source/target compatibility to VERSION_1_7 and you can use this library.
