### ISSUE TITLE
Android: R class not generated since 1.0.0-beta17

### ISSUE THREAD

**Issue by greenrobot-team** [requery/requery#210]
The Android R class is no longer generated so the `processDebugResources` task fails.

To reproduce, clean and rebuild with the library integrated into an Android project.

I already had a look at the changes between beta16 and beta17, but so far nothing pops out.

**Comment by npurushe** [comment]
Hi I'm not able to reproduce this. In general the library/processor doesn't do anything that can affect that gradle task. Can you post the output of `gradle build --stacktrace` that would indicate where the problem is.

**Comment by greenrobot-team** [comment]
You can find the code at https://github.com/greenrobot/android-database-performance/pull/14 (I disabled all but the requery module). The PR has a stacktrace of the build command, though it does not appear to contain anything useful.

**Comment by greenrobot-team** [comment]
Update: looks like this can be solved by adding a dummy string resource. So this is likely a bug with the Android gradle plugin. Sorry to bother you!
