### ISSUE TITLE
AutoValue Entity: Map<String, List<Package>> fails

### ISSUE THREAD

**Issue by vanniktech** [requery/requery#212]
I have a method:

`public abstract Map<String, List<Package>> promos();`

but the generated code (see below) of requery won't compile.

```java
public static final QueryAttribute<FeatureFlags, Map<String, List<FeatureFlags.Package>>> PROMOS = 
    new MapAttributeBuilder<FeatureFlags, Map<String, List<FeatureFlags.Package>>, String, List<FeatureFlags.Package>>("promos", Map.class, String.class, List<FeatureFlags.Package>.class)
```

The problem lies in this `List<FeatureFlags.Package>.class`

I'm using beta18 version. Is there any way to work around this?

**Comment by npurushe** [comment]
Maps aren't supported directly and if they were it would be a map of a relation and the key would be a column in the mapped type to that entity, not to a list. How are you expecting that to be mapped into the database column?

**Comment by vanniktech** [comment]
Using a custom Converter. (We'll just encode it in a JSON and then decode it again)

**Comment by npurushe** [comment]
Ok I see the problem is with the generic types it will just have to mapped to the Map class

**Comment by vanniktech** [comment]
Will this get into the new release? beta24 I presume.

**Comment by npurushe** [comment]
Yes should be
