### ISSUE TITLE
Query with List<Integer> 

### ISSUE THREAD

**Issue by DivineChaos** [requery/requery#213]
Greetings

I have the following model

`@Entity
public abstract class AbstractProduct implements Persistable, Parcelable, Serializable{

    @Key
    int id;
    String name;
    String description;
    String price;
    String displayPrice;
    String slug;
    String metaDescription;
    String metaKeywords;
    int shippingCategoryId;
    int masterId;
    boolean hasVariants;
    boolean favourite;
    boolean extras;  // PartsGroups

    @Convert(IntegerListConverter.class)
    ArrayList<Integer> menuIds;

    @Convert(IntegerListConverter.class)
    ArrayList<Integer> categoryIds;
}_`

Now i would like to make a query that returns all Products, who's menu ID list contains the int 97.
Something like: `List<Product> = dataStore.select(Product.class).where(**Product.MENU_IDS.contains(97)**).get().toList();`

How would I do this ?

**Comment by npurushe** [comment]
You can look at this answer (http://stackoverflow.com/questions/17559051/sql-like-operator-not-working-for-comma-separated-lists) but ultimately if you need those kind of queries you should be using separate tables instead of storing everything in one column.

**Comment by DivineChaos** [comment]
I see. Truthfully, I am using these lists in stead of ManyToMany relations, because I ran into trouble trying to implement them. I have never worked with databases, so it has been quite challenging for me to get comfortable with the library. I will take another look at Many2Many. 

Thank you for the response !
