### ISSUE TITLE
How to define index with multiple columns

### ISSUE THREAD

**Issue by cocia** [requery/requery#215]
How to define index with multiple columns?

From project README.MD, I get this demo:
````java
    @Index(name = "name_index")              // table specification
    String name;
````

But from you anotation Index defined is this. It doesn't have a name attribute.
````java
@Documented
@Target({ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Index {
    String[] value() default {""};
}
````

**Comment by npurushe** [comment]
You can just omit the name attribute and use @Index("name_index"), it was removed since there is only one value
