### ISSUE TITLE
result.toObservable doesn't emit

### ISSUE THREAD

**Issue by Glurt** [requery/requery#216]
This might be an issue with Rx more than Requery but I thought I'd check with you first.

I'm loading some results from the datastore which I'd like to be reactive.
````
@Override
    public Observable<Result<Submission>> getSubmissionsForSubreddit(final String subreddit) {
        return dataStore.select(Submission.class)
                .where(Submission.SUBREDDIT.eq(subreddit))
                .get()
                .toSelfObservable();
    }
`````

The calling class then maps it from Result<Submission> to Observable<Submission> so that it can be treat like a normal Observable (the .cast method is just to cast it to its base type). The issue is that any method after .flatMap is never called, I have tried moving the subscriber to directly after this method and it still won't emit. 

````
@Override
    protected Observable<Thing> loadFromDisk(final String after, final String sorting, final String timePeriod) {
        return diskRepo.getSubmissionsForSubreddit(subreddit)
                .flatMap(new Func1<Result<Submission>, Observable<Submission>>() {
                    @Override
                    public Observable<Submission> call(final Result<Submission> submissions) {
                        return submissions.toObservable();
                    }
                })
                .cast(Thing.class);
    }
````

Is there something other than submissions.toObservable() that I should be using?

**Comment by npurushe** [comment]
Without the flatmap is the observable triggered?  By default the selfObservable is triggered at least once just by subscribing to it, do you get that call?

**Comment by Glurt** [comment]
If I remove the flatmap and subscribe directly to diskRepo.getSubmissionsForSubreddit(subreddit) then onNext is called so it seems that flatmap is the issue. I'll see if other methods work.

**Comment by npurushe** [comment]
Unfortunately wasn't able to reproduce this, there is an explicit test case for that behavior https://github.com/requery/requery/blob/master/requery-test/src/test/java/io/requery/test/RxTest.java#L195 and it's working ok. I think most likely the observable you map on to `final Result<Submission> submissions` emits no results because the underlying query has no results. Are you sure that result emits more than 0 items?

**Comment by Glurt** [comment]
My first thought was that the query wasn't returning any results but that wasn't the case, though there is something else I'd like to ask you about this case.

My subscriber was was using the .toList() operator to group the items and then put them in the RecyclerViewAdapter, removing it means they now emit, no idea what the issue could be.

Regarding the empty Result, is it possible for the Observable to not automatically complete? My use case is subscribing to the results of a given subreddit, if it returns empty then trigger a download to populate the datastore, updating any subscribers.

**Comment by npurushe** [comment]
Right the observables will complete if there are no results which is expected for `Result`. If you are using toList then that will complete with an empty list if there are no results which you can use to trigger your action.

**Comment by Glurt** [comment]
I've stopped using .toList for now so that I can focus on getting everything else to work. If I query the database for results that are guaranteed to not exist then the Observable completes but doesn't call my subscribers onComplete.

I now also have a switchIfEmpty statement immediately after _diskRepo.getSubmissionsForSubreddit(subreddit)_ but even that doesn't get called.

What's the best way to handle empty results?

**Comment by npurushe** [comment]
switchIfEmpty should work, onComplete should also be called if it is empty the only thing that could prevent that is an exception (onError) or maybe you unsubscribed your subscriber?

**Comment by Glurt** [comment]
I'll try and add a failing test case to reproduce the issue and start a pull request.

**Comment by npurushe** [comment]
Thanks for providing the test case, the issue here is that toSelfObservable is not a terminating Observable it's published through a Subject so a subscriber's on complete won't get called for it, thats why switchIfEmpty fails there. I would suggest subscribing to the selfObservable, then invoking another function on the `Result` applying operators on to it's toObservable() and basing your actions on that rather than mapping the original self observable.
