### ISSUE TITLE
Conditional eqIgnorecase

### ISSUE THREAD

**Issue by Glurt** [requery/requery#217]
Following the testing of my previous issue, I noticed that there's no eqIgnoreCase for String values.

For example, I would like 

```
.where(Submission.SUBREDDIT.eq(subreddit))
```

to be:

```
.where(Submission.SUBREDDIT.eqIgnorecase(subreddit))
```

**Comment by npurushe** [comment]
You can accomplish this by using the lower() function and then also lower casing the input string and comparing those, but agree this would be a nice enhancement
