### ISSUE TITLE
AbstractUser versus AbstractPerson

### ISSUE THREAD

**Issue by caralin3** [requery/requery#218]
What is the difference between these two? Which one should I implement to create users that need to login for my app?

**Comment by npurushe** [comment]
You can name the entity classes however you want it's up to you :)

**Comment by caralin3** [comment]
But they are implemented slightly differently like AbstractUser is more simple than the AbstractPerson

**Comment by npurushe** [comment]
Those are examples and test code it doesn't reflect any particular use case exactly, define the fields as needed by your application

**Comment by caralin3** [comment]
What does Serializable do?

**Comment by npurushe** [comment]
https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html
