### ISSUE TITLE
Embedded objects support

### ISSUE THREAD

**Issue by deinlandel** [requery/requery#22]
As @Embedded JPA annotation.

I already have table with entity and its "embedded" object fields stored in the same table (I currently use "raw" SQL). Being unable to map requery entities to my table prevents me from migrating to requery. =(

**Comment by npurushe** [comment]
Hi yes do plan to add support for embedded objects. At the moment you can repeat those fields in the entity but if you have a lot of them that's where @Embedded is useful. When using embedded objects do you use  [AttributeOverride](https://docs.oracle.com/javaee/6/api/javax/persistence/AttributeOverride.html) ?

**Comment by deinlandel** [comment]
Hi, thanks for you reply. AttributeOverride  would be useful, but not absolutely necessary.

**Comment by deinlandel** [comment]
Thank you for implementing this. Great work!

**Comment by npurushe** [comment]
Sure the initial support for this is in the beta21 version.
