### ISSUE TITLE
Constructing type-safe `groupBy` date expressions

### ISSUE THREAD

**Issue by neilpa** [requery/requery#220]
I'm struggling to find a type-safe way for constructing a `groupBy` expression that converts timestamp query attributes (Joda DateTime) to just the date for grouping.

```javav
date.select(Entity.AMOUNT.sum().as("daily total"))
  .where(Entity.CREATED.greaterThanOrEqual(start))
  .and(Entity.CREATED.lessThan(end)) 
  .groupBy(Entity.CREATED.???)
```

I poked around some of the `Expression` code but haven't figured out how it all fits together yet. Is this even possible or do I have to drop to raw SQL?

**Comment by npurushe** [comment]
Did `groupBy(Entity.CREATED)` not work for your case? You shouldn't need to do anything else

**Comment by neilpa** [comment]
The problem is that created is the full timestamp, what I want is the daily rollup, e.g. `GROUP BY DATE(created)`

**Comment by npurushe** [comment]
Thanks for the clarification looks like you just want to apply a function to the Entity.CREATED column. This function isn'y built in yet for db compatibility reasons but you can easily add it like this:
```java
public class Date<V> extends Function<V> {
    private final Expression<V> expression;

    private Date(Expression<V> expression) {
        super("date", expression.getClassType());
        this.expression = expression;
    }

    public static <U> Date<U> date(Expression<U> expression) {
        return new Date<>(expression);
    }

    @Override
    public Object[] arguments() {
        return new Object[] {expression};
    }
}
```
Then use `Date.date(Entity.CREATED)`. Will make this a bit easier in a future version

**Comment by neilpa** [comment]
Awesome! Thanks for the pointer.
