### ISSUE TITLE
Kotlin @Superclass inheritance not working as expected

### ISSUE THREAD

**Issue by trevjonez** [requery/requery#221]
The following interfaces:
```kotlin
@Superclass
interface BaseModel {
  @get:Key
  @get:Column(unique = true, nullable = false) //Not sure if this is needed, error is same with/without
  var id: UUID
}
```
and:
```kotlin
@Entity
interface User : BaseModel, Persistable {
  var username: String
  var password: String
}
```

Results in the generated class throwing this error when compiled: 
```UserEntity is not abstract and does not override abstract method setId(UUID) in BaseModel```

**Comment by npurushe** [comment]
Unfortunately Kotlin doesn't indicate any superclass type information to annotation processors, will have to see if it's possible to workaround

**Comment by npurushe** [comment]
Looks like requery wasn't handled this for interfaces will be pushed in the next update soon
