### ISSUE TITLE
Need an example of @JunctionTable where column names are specified

### ISSUE THREAD

**Issue by kenyee** [requery/requery#222]
I'm trying 1.0.0-rc1, but this still doesn't seem to have support for this (at least I couldn't find an example in the repo).

The DB schema looks like this:
```
CREATE TABLE routes (route STRING PRIMARY KEY, color INTEGER, oppositecolor INTEGER, pathblob BLOB, listorder INTEGER, agencyid INTEGER, routetitle STRING);
CREATE TABLE stopmapping (route STRING, tag STRING, PRIMARY KEY (route, tag));
CREATE TABLE stops (tag STRING PRIMARY KEY, lat FLOAT, lon FLOAT, title STRING, parent STRING);
```

The Stops interface includes this:
```
    @JunctionTable(name="stopmapping")
    @ManyToMany
    Set<Routes> getRoutes();
```

The Routes interface includes this:
```
    @ManyToMany
    Set<Stops> getStops();
```

@JunctionTable appears to be able to take a columns parameter but I can't figure out what to put into it.  I tried doing 

`columns = { "route", "tag"}`

but it wanted Column data types, so I also tried this, but it wanted constants:

`columns = { RouteEntity.ROUTE, StopsEntity.TAG }`

Neither seem to work because when I do StopsEntity.getRoutes(), it tries using routesId and stopsId for the column names instead of route and tag :-(

**Comment by npurushe** [comment]
Annotations can only contain compile time constants, check the type to see it takes @Column not strings or attributes the other things won't compile. However this currently only mean't to define the foreign key columns not arbitrary columns. For your case you should define your own type using @JunctionTable.type()

```java
    @JunctionTable(columns = {
            @Column(name = "personId", foreignKey =
                @ForeignKey(references = AbstractPerson.class, referencedColumn = "id")),
            @Column(name = "groupId", foreignKey =
                @ForeignKey(references = AbstractGroup.class, referencedColumn = "id")) } )
```

**Comment by kenyee** [comment]
I think there's a bug...it seems to be mixing the class and column names which your test above wouldn't notice because both referenced columns are "id" :-)

I used this:
```
    @JunctionTable(name="stopmapping", columns = {
            @Column(name = "route", foreignKey =
            @ForeignKey(references = RoutesEntity.class, referencedColumn = "route")),
            @Column(name = "tag", foreignKey =
            @ForeignKey(references = StopsEntity.class, referencedColumn = "tag")) })
    @ManyToMany
    Set<Routes> getRoutes();
```

But the generated code (thanks for the source.setDefaultLogging setting :-) looks like this:
`select a."route", a."agencyid", a."color", a."listorder", a."oppositecolor", a."pathblob", a."routetitle" from routes a inner join stopmapping b on a."route" = b."tag" inner join stops c on b."route" = c."tag" where c."tag" = '36540';`

Note that it's matching a.route w/ b.tag and b.route with c.tag.  I can hack around it for now by flipping the column names but I suspect that wasn't the intention :-)

**Comment by kenyee** [comment]
@npurushe : 'fraid this code change didn't work.  When I do a stop.getRoutes() in my code, I get this error now:
Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
at this line in EntityReader:
                QueryAttribute<E, Object> tId = Attributes.get(tKey.getReferencedAttribute());

instead of no results.  There is no SQL output by the Requery obviously...fails before it gets to that point.
On the bright side, thanks for the @Transient fix...that worked well :-)

**Comment by kenyee** [comment]
not sure if this helps, but during compile time, it sends out a bunch of these errors too:
```
Warning:(38, 23) Couldn't find referenced element com.keysolutions.mbtafail.db.models.RoutesEntity for com.keysolutions.mbtafail.db.models.Stopmapping.route
Warning:(29, 23) Couldn't find referenced element com.keysolutions.mbtafail.db.models.StopsEntity for com.keysolutions.mbtafail.db.models.Stopmapping.tag
Warning:Couldn't find referenced element com.keysolutions.mbtafail.db.models.RoutesEntity for com.keysolutions.mbtafail.db.models.Stopmapping.route
Warning:Couldn't find referenced element com.keysolutions.mbtafail.db.models.StopsEntity for com.keysolutions.mbtafail.db.models.Stopmapping.tag
Warning:Couldn't find referenced element com.keysolutions.mbtafail.db.models.RoutesEntity for com.keysolutions.mbtafail.db.models.Stopmapping.route
Warning:Couldn't find referenced element com.keysolutions.mbtafail.db.models.StopsEntity for com.keysolutions.mbtafail.db.models.Stopmapping.tag
```

**Comment by npurushe** [comment]
Try using the source class (abstract class or interface) in `references` instead of the generated type.

**Comment by kenyee** [comment]
@npurushe Thanks..that did it.  I updated my wiki page on that too in case you haven't used it yet :-)
