### ISSUE TITLE
added doc page for how to handle existing schemas

### ISSUE THREAD

**Issue by kenyee** [requery/requery#223]
Added a doc page for this as well as updated Android page to include how to use the logging setting...apparently, you can't do a pull request on wiki updates :-(

My fork of the wiki is here: https://github.com/kenyee/requery-wiki

Note that the doc page assumes this bug has been fixed: https://github.com/requery/requery/issues/222

**Comment by npurushe** [comment]
Sure will expand the wiki to cover these, thanks
