### ISSUE TITLE
expose SingleEntityStoreFromBlocking constructor with 2 arguments

### ISSUE THREAD

**Issue by yshrsmz** [requery/requery#224]
`SingleEntitiyStoreFromBlocking` has two constructor, but currently the constructor which takes scheduler as second argument is not exposed.

I need this constructor for better unit testing(I'd like to use `Schedulers.immediate()` as default scheduler so that tests can be synchronous.

So could you add `RxSupport#toReactiveStore(BlockingEntityStore<S> store, Scheduler scheduler)` ?

**Comment by npurushe** [comment]
You can use RxJavaSchedulersHook for testing reasons but this change should still be ok as added to RxSupport as an overload

**Comment by yshrsmz** [comment]
thank you!
