### ISSUE TITLE
[QUESTION] Indexes

### ISSUE THREAD

**Issue by uKL** [requery/requery#228]
Is it possible to have an index on multiple fields to enforce them to be unique?

**Comment by npurushe** [comment]
You can define an multi column index like this
```java
@Index(name = "multi_index")
 String key1;
@Index(name = "multi_index")
String key2;
```
then one index will be created on columns key1 and key2 unfortunately its not currently possible to define that index to be unique, however that should be straight forward enhancement if needed.

**Comment by npurushe** [comment]
So this is possible already. You can make the index unique by using `@Column(unique = true)`
