### ISSUE TITLE
where.and query w/ two notLike conditions doesn't work?

### ISSUE THREAD

**Issue by kenyee** [requery/requery#229]
I have a query that looks like this:
```

List<Stops> stops = mDataStore.select(Stops.class)
                            .where(StopsEntity.TAG.notLike("hubway_%")
                            .and(StopsEntity.TAG.notLike("%_ar")))
                            .orderBy(StopsEntity.LAT, StopsEntity.LON)
                            .get().toList();
```

Remove the .and condition and it works fine.  Leave it in and I get this cryptic compile time error: 

```
Error:(55, 29) error: method where in interface Where<E> cannot be applied to given types;
required: Condition<V,?>
found: LogicalCondition<CAP#1,CAP#2>
reason: inferred type does not conform to equality constraint(s)
inferred: CAP#3
equality constraints(s): CAP#3,CAP#4
where V,E are type-variables:
V extends Object declared in method <V>where(Condition<V,?>)
E extends Object declared in interface Where
where CAP#1,CAP#2,CAP#3,CAP#4 are fresh type-variables:
CAP#1 extends Object from capture of ?
CAP#2 extends Object from capture of ?
CAP#3 extends Object from capture of ?
CAP#4 extends Object from capture of ?

```

**Comment by npurushe** [comment]
Which java version are you using? It's similar to #208 and also a java compiler bug https://bugs.openjdk.java.net/browse/JDK-8043926

**Comment by kenyee** [comment]
Java 1.8.0_102 (latest) for the compiler.  I'm using retrolamba on Android like the #208 user as well.

It does look similar, but the workaround doesn't work for me.  It breaks the builder so the orderBy no longer can be followed by the .get().

![capture](https://cloud.githubusercontent.com/assets/586670/17063309/945e792a-5004-11e6-889c-a8be5f0dfbdd.JPG)

**Comment by cbruegg** [comment]
Same issue here with the latest compiler. The casting to `Condition` workaround works when casting the code before `get()` to `Result<T>`, but it looks really bad. I've put together a small sample project that demonstrates the issue @npurushe.

https://github.com/cbruegg/requery-compile-issue-demo

**Comment by npurushe** [comment]
Thanks for the example will see if it's possible to work around it.
