### ISSUE TITLE
Databinding

### ISSUE THREAD

**Issue by caralin3** [requery/requery#230]
I'm getting this error
Error:(11, 59) error: package requery.model.databinding does not exist
Error:(26, 13) error: cannot find symbol class ActivityEditPersonBinding

Here are the dependencies in my gradle file
compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'io.requery:requery:1.0.0-rc2'
    compile 'io.requery:requery-android:1.0.0-rc2'
    apt 'io.requery:requery-processor:1.0.0-rc2'
    provided 'io.requery:requery-processor:1.0-SNAPSHOT'
    apt 'io.requery:requery-processor:1.0.0-beta23'   // use an APT plugin
    compile 'io.requery:requery:1.0-SNAPSHOT'
    compile 'io.requery:requery-android:1.0-SNAPSHOT'
    compile 'net.zetetic:android-database-sqlcipher:3.4.0'
    compile 'io.requery:sqlite-android:3.13.0-2'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'io.reactivex:rxjava:1.1.5'
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'com.android.support:design:24.1.1'
    compile 'io.requery:sqlite-android:3.13.0-1'
    compile 'io.requery:requery:1.0.0-beta23'
    compile 'io.requery:requery-android:1.0.0-beta23' // for android
    apt 'io.requery:requery-processor:1.0.0-beta23'   // use an APT plugin

Is the databinding supposed to be autogenerated?

**Comment by npurushe** [comment]
Yes the databinding classes are auto generated by the android databinding plugin, follow the guide for android [databinding](https://developer.android.com/topic/libraries/data-binding/index.html). Also you have the dependencies for requery listed twice, just use the latest version.

**Comment by caralin3** [comment]
Which one is the latest version?

**Comment by npurushe** [comment]
1.0.0-rc2
