### ISSUE TITLE
@Embedded/@Embeddable uses wrong builder in @AutoValue setup

### ISSUE THREAD

**Issue by objcode** [requery/requery#231]
When using the `@Embedded` and `@Embeddable` annotation with `@AutoValue` immutable types, the generated `Type` file attempts to use the destination builder (generating a compiler error) to construct the `@Embedded` type.

Minimal example:

```
@AutoValue
@Entity
public abstract class Bike {

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder setSeat(Seat seat);
        public abstract Bike build();
    }

    public static Builder builder() {
        return new AutoValue_Bike.Builder();
    }

    @Embedded
    public abstract Seat getSeat();
}
```

```
@AutoValue
@Embeddable
public abstract class Seat {

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder setMake(String name);
        public abstract Builder setYear(int year);
        public abstract Seat build();
    }

    public static Builder builder() {
        return new AutoValue_Seat.Builder();
    }

    public abstract String getMake();
    public abstract int getYear();
}
```

Correctly, construction of a `Seat` should use `new Seat.Builder()` but currently it attempts to use `new Bike.Builder()`.

I took a stab at trying to put together a PR, but got a bit lost in `EntityGenerator.generateAttribute`  so making an issue instead.

**Comment by npurushe** [comment]
Thanks for reporting, this isn't currently supported due to the complexity of mapping the the sub type builders and storing them into the parent type, but should be possible in a future version
