### ISSUE TITLE
Repeated @Embedded fields conflict

### ISSUE THREAD

**Issue by objcode** [requery/requery#232]
When specifying two fields in the same class with the same `@Embeddable` reference, the generated embedded fields conflict (and the code generator errors).

Minimal example:

```
@AutoValue
@Entity
public abstract class Bike {

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder setSeat(Seat seat);
        public abstract Builder setSecondSeat(Seat secondSeat);
        public abstract Bike build();
    }

    public static Builder builder() {
        return new AutoValue_Bike.Builder();
    }

    @Embedded
    public abstract Seat getSeat();
    @Embedded
    public abstract Seat getSecondSeat();
}
```

```
@AutoValue
@Embeddable
public abstract class Seat {

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder setMake(String name);
        public abstract Builder setYear(int year);
        public abstract Seat build();
    }

    public static Builder builder() {
        return new AutoValue_Seat.Builder();
    }

    public abstract String getMake();
    public abstract int getYear();
}
```

When attempting to build this, it attempts to recreate the `BikeType_SeatType` generated class (crashes). Further, the fields `make` and `year` are not namespaced, leading to a conflict.

Expected:
1. `Bike_SeatType` crash doesn't happen
2. Embedded fields are namespaced so they can be repeatedly composed.

I attempted to put together a PR but got over my head in `EntityGenerator.generateAttribute`, so opening an issue instead.

**Comment by npurushe** [comment]
Thanks for reporting, Supporting this would require something JPA @AttributeOverrides where you have to redefine all the column names for target entity so they don't conflict.
