### ISSUE TITLE
Reference Cache

### ISSUE THREAD

**Issue by alistairbrightec** [requery/requery#233]
**Problem**
If I switch the reference cache off, anytime I try to get the reference variables it returns empty. Is this a bug or should I be doing something else extra in order to not have reference cache. i.e. I want everytime I get the references it to get them live from the db again.

**Info:**
Platform: Android

```
builder.setEntityCache(new EntityCacheBuilder(model)
                            .useReferenceCache(false)
                            .build());
```

```
compile 'io.requery:requery:1.0.0-rc2'
compile 'io.requery:requery-android:1.0.0-rc2'
apt 'io.requery:requery-processor:1.0.0-rc2'
```

**By the way, love this library, I think you have done an insanely good job.**

**Comment by npurushe** [comment]
Which API are you using to retrieve your entity? From a query or findByKey?

**Comment by alistairbrightec** [comment]
findByKey

**Comment by npurushe** [comment]
If you set logging enabled with `databaseSource.setLoggingEnabled(true);` what sql gets executed? It should work fine if that entity is actually in the database with that key as your code snippet will cause no caching to be used

**Comment by alistairbrightec** [comment]
```
I/requery: beforeExecuteQuery select parseId, author, dateLastViewed, dateRemoved, displayName from CGroup where parseId = ?  sql: select parseId, author, dateLastViewed, dateRemoved, displayName from CGroup where parseId = ? 
I/requery: afterExecuteQuery
```

The list which is empty is defined as:
```
@OneToMany(mappedBy = "cGroup", cascade = {CascadeAction.SAVE})
List<CGroupUser> cGroupUsers;
```

**Comment by alistairbrightec** [comment]
I believe I have worked out the problem. I was using the variable directly and not calling the getter. I added a convenience method into the Abstract class and just used the variables rather than passing the obj into the method and using the getters. 

Sorry to have wasted your time on this. Love the library, thank you for producing this.

**Comment by npurushe** [comment]
Great glad it's working
