### ISSUE TITLE
Entity not updated

### ISSUE THREAD

**Issue by dadino** [requery/requery#236]
Using the EntityDataStore (with 1.0 rc2), built this way
 
    if (dataStore == null) {
					EntityModel model = Models.DEFAULT;
					DatabaseSource dataSource = new DatabaseSource(context, model, DB_VERSION);
					Configuration configuration = new ConfigurationBuilder(dataSource,
							model).useDefaultLogging()
					              .build();
					dataStore = new EntityDataStore<>(configuration);
				}

When I try to update an entity, it isn't updated and I can't find exceptions or errors in the log. This is how I update a Status entity (with a trick to update or insert):

    @Override
	public Single<Status> upsert(Status status) {
		return Single.create(new Single.OnSubscribe<Status>() {
			@Override
			public void call(SingleSubscriber<? super Status> singleSubscriber) {
				try {
					Status updatedStatus = db().update(status);
					Status persistedStatus = db().findByKey(Status.class, status.getMac());
					Logs.repository("Status updated: " + updatedStatus);
					Logs.repository("Status  actual: " + persistedStatus);
					singleSubscriber.onSuccess(updatedStatus);
				} catch (RowCountException r) {
					Status updatedStatus = db().insert(status);
					Status persistedStatus = db().findByKey(Status.class, status.getMac());
					Logs.repository("Status inserted: " + updatedStatus);
					Logs.repository("Status   actual: " + persistedStatus);
					singleSubscriber.onSuccess(updatedStatus);
				} catch (Exception e) {
					singleSubscriber.onError(e);
				}
			}
		});
	}

As you can see I log both the updated/inserted entity and the one I query immediately after and they are different. The insert method works, the update one doesn't, so I only have the original entity.

I've seen issue #81, but the answer is to subscribe to a Single that I don't have (update return the entity, not a Single), so I can't apply that.

I'm sure I'm doing something wrong, I just can't find it.

**Comment by npurushe** [comment]
How are you creating the Status instance you are passing into update? If it's the same instance you inserted but didn't make any modifications then the update call will not do anything

**Comment by dadino** [comment]
No, it's created by Gson, downloaded from a server. I don't use an autogenerated long key, but a String (also taken from the server).

**Comment by npurushe** [comment]
Thanks for the clarification. Gson modifies the private fields of an object without using it's setters so requery has no knowledge that the object was modified. 

This is tracked in #73, which has some solutions, this will be documented a bit better and some enhancements maybe made to try to work around it. Another solution is to use a json library that can map to setters like Jackson data bind.
