### ISSUE TITLE
Inner classes

### ISSUE THREAD

**Issue by alejandro-pnz** [requery/requery#237]
What about possibility of the inner classes? I have tried to use this one in my code:

```
@Entity
abstract class Content {
	@Key
	String id;
	String type;
	String url;

	@Entity
	public abstract class Source {
		@Key
		String id;
	}

	@Entity
	public abstract class Copyright {
		public String note;
		public String url;
	}
}
```

And I've got an next compile-time error:
```
Error:(76, 27) error: an enclosing instance that contains Content.Source is required
Error:(109, 30) error: an enclosing instance that contains Content.Copyright is required
```

**Comment by npurushe** [comment]
How would expect that to be mapped into a table? I think embedded types and superclasses which are supported cover most object composition requirements.

**Comment by npurushe** [comment]
Closing for now if you have additional info please post back
