### ISSUE TITLE
Build fails when using retrolambda

### ISSUE THREAD

**Issue by KrzysztofWrobel** [requery/requery#24]
I've tried to enable Lambda expressions in Android example project:
```
apply plugin: 'me.tatarka.retrolambda'

...

compileOptions {
     sourceCompatibility JavaVersion.VERSION_1_8
     targetCompatibility JavaVersion.VERSION_1_8
}

...

```

When building @Entity annotated classes are not visible and builds fail.

Is it possible to run Requery alongside with Retrolambda?

I considered porting my current project from Squidb to Requery, but I use there a lot of lambda expressions.

**Comment by gholz** [comment]
I'm using both in my project and everything is running fine. Did you add all the requery dependencies? 
`compile 'io.requery:requery-android:1.0-SNAPSHOT'
 compile 'io.requery:requery:1.0-SNAPSHOT'
 apt 'io.requery:requery-processor:1.0-SNAPSHOT'`

**Comment by KrzysztofWrobel** [comment]
Yes, I did. Though I did not specify that I'm talking about Android project:) 

I had cloned Requery repo and then tried to run example project with Retrolamda plugin applied. 
That's when the issue is happening.

**Comment by npurushe** [comment]
Hi there shouldn't be an issue combining requery with retrolambda. Can you post the output from `gradle build` in that directory? Also what versions of retrolambda are you using? Thanks

**Comment by KrzysztofWrobel** [comment]
Hey,

Sat down to this issue with fresh mind in the morning and it turns out I had experienced different issue.

Issue was completely different and not related to enabling retrolambda, but using generated classes in xml for databinding. I can open new issue for that one.

Thanks for letting me know that there should be no issues with retrolambda. :) That helped me point my problem.
