### ISSUE TITLE
How to use DataStore inside IntentService

### ISSUE THREAD

**Issue by oleonov** [requery/requery#240]
I have two EntityDataStore - one inside `Application` and one inside `IntentService`.
When I change data in serivce via dataStorage1 I can't get this updates inside my dataStorage2 inside Aplication.
How can I do it?

**Comment by npurushe** [comment]
Why are you creating another one in the service? There is no reason to, just use the one you created in your application.

**Comment by oleonov** [comment]
IntentService called from AlarmManager when application shut down. I can't use Application dataStorage

**Comment by npurushe** [comment]
Your Application instance still gets created and initialized when woken from an AlarmManager broadcast. Basically it's created anytime your app is running.
