### ISSUE TITLE
toSelfObservable does emit on relation update, but actual value is not updated.

### ISSUE THREAD

**Issue by yshrsmz** [requery/requery#241]
tested on 1.0.0-rc2.

I have following three entities

```kotlin
@Entity
interface CredentialDB : Persistable {

  @get:Key
  val key: String

  @get:[OneToOne(cascade = arrayOf(CascadeAction.SAVE)) ForeignKey]
  val token: TokenDB

  @get:[OneToOne(cascade = arrayOf(CascadeAction.SAVE)) ForeignKey]
  val user: UserDB
}
```

```kotlin
@Entity
interface TokenDB : Persistable {

  @get:Key
  val key: String

  val secretKey: String
}
```

```kotlin
@Entity
interface UserDB : Persistable {

  @get:[Key]
  val id: UUID

  val name: String

  val following: Int

  val likes: Long

  val defaultPostFormat: String
}
```

and following method

```kotlin
override fun read(spec: Spec): Observable<List<Credential>> {
    checkSpec(spec)

    val query: Result<CredentialDBEntity>
    if (spec.all) {
      query = entityStore.select(CredentialDBEntity::class.java).get()
    } else {
      query = entityStore.select(CredentialDBEntity::class.java)
          .where(CredentialDBEntity.KEY.eq(spec.key)).get()
    }
    return query.toSelfObservable()
        .filter { it.count() > 0 }
        .flatMap {
          Observable.from(it)
              .map { toModel(it) }
              .toList()
        }
  }
```

and here is a test case

```kotlin
@Test
  fun read() {
    val token = Token(key = "this_is_key", secretKey = "this_is_secret_key")
    val user = User(following = 100, defaultPostFormat = PostFormat.MARKDOWN, name = "test_user", likes = 200)
    val credential = Credential(token, user)

    val credential2 = credential.copy(user = user.copy(likes = 300))

    val entity1 = toEntity(credential)

    val ts = TestSubscriber.create<List<Credential>>()

    entityStore.insert(entity1).subscribe()

    repository.read(CredentialLocalRepository.Spec(key = token.key))
        .subscribe(ts)

    ts.assertNotCompleted()
    ts.assertValue(listOf(credential))

    val entity2 = toEntity(credential2)
    entityStore.update(entity2).subscribe()

    ts.assertNotCompleted()
    ts.assertValues(listOf(credential), listOf(credential2)) // test fails here!
    // below passes, btw
    //ts.assertValues(listOf(credential), listOf(credential1))
  }
```

`toModel` is a method to convert entity to kotlin data class, and `toEntity` vice versa.

btw, running method below gets updated value correctly. `entityStore.select(CredentialDBEntity::class.java).where(CredentialDBEntity.KEY.eq(token.key)).get().toList()`

**Comment by npurushe** [comment]
What are the differences between `credential` and `credential2` in the failing test case? If it's the user.likes value that is expected given your example.

**Comment by yshrsmz** [comment]
Only difference is `user.likes`. every other fields are copied from `credential`.
In credential2, it should be 300.

**Comment by npurushe** [comment]
Ok. Looks like you are creating a self observable against `CredentialDB` when you insert the first time you insert a Credential, User and Token. That will trigger your observable with `credential`. Then you change the user like value when you update `credential2 `. For that update only the user table should be changed not any other table, so it won't emit for `CredentialDB`'s observable.

**Comment by yshrsmz** [comment]
hm, but as I said, toSelfObservable emit with outdated item, even if I change update method to `entityStore.update(entity2.user).subscribe()`.

Is this correct behavior?

**Comment by yshrsmz** [comment]
requery-android example seems to be able emit with updated relation, I must have done something wrong...

**Comment by npurushe** [comment]
From the library's perspective the original credential/user was the one that was cached and only the ids in `CredentialDB`will be refreshed not the User inside it when making your select query. 
You should either not copy the object when updating (change the like count on the original object and then update it) or call `refresh()` on the User to get the changes.

**Comment by yshrsmz** [comment]
I see.
I am a big fan of clean architecture, so I tried to separate domain model from data entity.
I'm going to try what you suggest.
Thanks.

**Comment by npurushe** [comment]
You can keep them separate, just instead of copying the object either keep a reference to it or use findByKey to get the cached version or retrieve it.

**Comment by yshrsmz** [comment]
ah, findByKey solved my problem. thank you!
