### ISSUE TITLE
Clarification on Parcelable Entities.

### ISSUE THREAD

**Issue by lyrafelipe** [requery/requery#242]
I encountered a problem when having interfaces that extends Parcelable and wanted to make sure if my implementation is correct.
I have two interfaces that look roughly like this:
```
@Entity public interface A extends Parcelable {
...
@JunctionTable @ManyToMany List<B> getBs();
...
}
```
```
@Entity public interface B extends Parcelable {
...
@ManyToMany List<A> getAs();
...
}
```
Whenever I add an item to A's `List<B>` and put A as an extra to pass it back to an Activity, when I retrieved the Parceled A the items inside `List<B>` are lost. 
Does requery works with Parcelable out-of-the-box or do I have to implement it myself?

Hope my explanation isn't too confusing!

**Comment by npurushe** [comment]
Hi please see this answer https://github.com/requery/requery/issues/123#issuecomment-216443484 basically you should be using unique ids for passing entities between activities in your own process. The parceling functionality is mean't only for serializing a row of data outside of your application.

**Comment by lyrafelipe** [comment]
Thanks for the quick response!

**Comment by lyrafelipe** [comment]
Another question appeared.
So, I did what you suggested, instead of parceling my object I just passed it's ID and loaded it.
But now I need to pass just the ManyToMany List and I am getting the following error:
> java.lang.ClassCastException: io.requery.util.ObservableList cannot be cast to java.util.ArrayList
Any suggestion for this case?

**Comment by npurushe** [comment]
You should pass the id of the entity contain the relation, or if you really need an ArrayList copy the list contents into a new ArrayList
