### ISSUE TITLE
Entity Kotlin-Interface Definition leads to crash on Android

### ISSUE THREAD

**Issue by jonathanbergen** [requery/requery#243]
When using kotlin interfaces as  entity definition for Android, the app would crash on startup due to `ClassNotFoundExceptions` for Application- /Activityclasses. All classes defined in the manifest are packed and shipped with the apk file though.

Steps to reproduce:

1. Download this [requery-android](https://github.com/wearemakery/requery-android-example) sample.
 a) Build
 b) Run (should work)

2. Transform the User.java file into User.kt file and define the entity using a kotlin interface.
 a) Clean
 b) Build
 c) Run (should crash)

**Comment by npurushe** [comment]
Please provide the full stacktrace of the crash thanks. Also make sure that you clean and rebuild and have correctly setup the Kotlin plugin, if you make structural changes and rely on Android instant run it often produces invalid builds.

**Comment by jonathanbergen** [comment]
Thank you for your quick answer! I tried to reproduce the issue again, but now it seems to work, so I'm going to close this first off.
