### ISSUE TITLE
Auto saving @OneToMany

### ISSUE THREAD

**Issue by dusanjencik** [requery/requery#244]
Hello, I have a problem with automatic saving of relation @OneToMany.

	@Entity(name = "BaseDeal")
	public abstract class BaseDealEntity {
		@Key
		protected Long id;

		@OneToMany
		protected List<Tag> tags;
	}

---

	@Entity(name = "Tag")
	public abstract class TagEntity {
		@Key
		protected Long   id;

		@ManyToOne
		protected BaseDeal baseDeal;
	}

I want to save a list of BaseDeals with filled list of Tags. But BaseDeal instance have not any setTags(..) method. If I add manually setter to BaseDealEntity, saved list of Tags is not persisted to DB. So I have to create a list of BaseDeals and list of Tags separately and save it one by one. Is it a feature or bug? Or Am I doing something wrong?

Thank you for your answer.

**Comment by npurushe** [comment]
Use `deal.getTags().add` or `addAll` or any of the standard `List` API. Requery has to keep track of what is changing inside the collection so this collection is already initialized once per entity and shouldn't be overwritten or this information would be lost.

**Comment by dusanjencik** [comment]
Thank you for you fast response but it didn't help me. When I add Tag instance to the deal as you mentioned the effect is always same. No Tag is saved. In debugger I can see an instance of Tag in deal but to the DB is saved the only deal.
Do you have any other idea what can I do?
Thanks.

**Comment by npurushe** [comment]
How are you saving the entity? In general this works for example see the test code (https://github.com/requery/requery/blob/9e17470db7ac88db9267ed18b15ba1a2d65d402e/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L609)  . As you modify the collection those elements will be tracked in ObservableList then you update or save requery will persist those elements as needed

**Comment by dusanjencik** [comment]
Thank you for your response but the mistake was that auto creating of tables don't work without @Generated annotation for id field.
