### ISSUE TITLE
DBFlow's N(3) for Query DSL might be wrong

### ISSUE THREAD

**Issue by agrosner** [requery/requery#245]
Based on the readme you define query DSL as:
```
Result<Person> query = data
    .select(Person.class)
    .where(Person.NAME.lower().like("b%")).and(Person.AGE.gt(20))
    .orderBy(Person.AGE.desc())
    .limit(5)
    .get();
```

You can represent this in DBFlow as:
```
CursorResult<Person> query = SQLite
    .select()
    .from(Person.class)
    .where(Person.name.like("b%")).and(Person.age.greaterThan(20))
    .orderBy(Person.age, false)
    .limit(5)
    .queryResults();
```

So what qualifies as query DSL?

Love the lib, BTW.

**Comment by npurushe** [comment]
The distinction was where it would not be possible to generate incorrect sql statements by limiting the functions that could be called when chaining them. I think at the time of writing that was the case for DBFlow but it looks more advanced now so I have updated to a Y thanks!
