### ISSUE TITLE
@Key @ManyToOne(cascade = CascadeAction.NONE) being ignored?

### ISSUE THREAD

**Issue by dukeyin** [requery/requery#248]
Currently using 1.0.0-rc2.

```
@Entity
public interface Things extends Persistable {

    @Key
    @ManyToOne(cascade = CascadeAction.NONE)
    Bucket getBucket();

    @Key
    @Convert(MyEnumConverter.class)
    MyEnum getNumber();

// non-key fields
```
```

@Entity
public interface Bucket extends Persistable {

    @Key
    String getId();

// non-key fields
```

I have an "INSERT OR REPLACE" statement I run on the above Bucket table during ```onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion)```.  To my surprise, after running that insert/replace statement, all the rows in the Things table were dropped.  When I opened up a backup of the SQLite database file in SQLiteSpy, it said that the create table statement contained this:
```foreign key (bucket) references Bucket(id) on delete cascade on update cascade```

It seems that CascadeAction.NONE is being ignored?

**Comment by npurushe** [comment]
Hi the CascadeAction only controls the way the value is cascaded during entity operations. You should use @ForeignKey(delete = NO_ACTION) to control how the table schema is generated.

**Comment by dukeyin** [comment]
Thanks, by adding `@ForeignKey(delete = ReferentialAction.NO_ACTION)`, I see in the result of a newly created database file `foreign key (bucket) references Bucket (id) on delete no action on update cascade`
