### ISSUE TITLE
Fill QueryRecyclerAdapter with dummy data

### ISSUE THREAD

**Issue by krabatom** [requery/requery#249]
Hi, is it possible to fill QueryRecyclerAdapter with some dummy data without reading from DB? I tried to create Result<Entity> from your class SingleResult<E>, but it is not showing any data.  If I read data from DB, it is working, but if I create data from SingleResult it is not working. Do you have any idea  why?

**Comment by npurushe** [comment]
I would suggest on your RecyclerView just switch adapters between QueryRecyclerAdapter and another one with the dummy data.

**Comment by krabatom** [comment]
Ok, thanks. :+1:
