### ISSUE TITLE
[Databinding] Generated classes cannot be used in xml

### ISSUE THREAD

**Issue by KrzysztofWrobel** [requery/requery#25]
I've modified the example Android code to use generated classes in xml as following:
```
<layout xmlns:android="http://schemas.android.com/apk/res/android">
<data>
     <variable name="person" type="io.requery.android.example.app.model.PersonEntity"/>
</data>
...
```
Then builds fails during ":requery-android:example:compileDebugJavaWithJavac" with 
```

Execution failed for task ':requery-android:example:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Found data binding errors.
  ****/ data binding error ****msg:Cannot resolve type for person~ file:/Users/krzysztofwrobel/MyPrograms/Playground/requery/requery-android/example/src/main/res/layout/activity_edit_person.xml loc:20:30 - 20:35 ****\ data binding error ****

```

I'm planning to move my project to Requery so I've modified bunch of things in exmaple project and published it here:
[https://github.com/KrzysztofWrobel/requery](https://github.com/KrzysztofWrobel/requery)

Anyone know why I can't use generated classes in xml?

**Comment by npurushe** [comment]
Hi this is because the Android databinding compiler runs before any annotation processors run. So it is only aware of the non-generated code. This is why the classes in the example project are bound to interfaces. If you bind to the interfaces it works fine like in the example.

**Comment by npurushe** [comment]
I think it might be worth raising an issue on the Google issue tracker about this, as there some good cases for using generated code in the binding (even besides this project) but unlikely they would address it anytime soon

**Comment by KrzysztofWrobel** [comment]
True. Thanks for response in that matter.

Partially because of that I had to redesign my models and add custom deserializers to GSON in order to get it to work with Retrofit. :)

Would be nice to have more Android libraries integrations as samples:) I had to spend some time experimenting what would be the best pratice to integrate Requery with GSON, @AutoParcelGson and Databinding. :)

**Comment by austynmahoney** [comment]
I would also like to retain the ability to use classes as Entities, so I submitted this [issue](https://code.google.com/p/android/issues/detail?id=205656) on the Android bug tracker.

**Comment by npurushe** [comment]
Closing for now since it depends on support from the android databinding plugin

**Comment by pdjstone** [comment]
I worked around this by binding to the Abstract class, and including abstract getters where needed, e.g.

```java
@Entity
public abstract class AbstractPerson extends BaseObservable {
    @Key @Generated
    int id;

    @Bindable
    String name;

    public abstract String getName(); // required so we can bind to it
}
```
