### ISSUE TITLE
Requery over an existing DB

### ISSUE THREAD

**Issue by anitasantoso** [requery/requery#251]
Hi, I'm using Requiry to manage an existing DB in an Android app. I specified table and column names in the Entity to match existing schema by the following @Table(name = "foo") and @Column(name = "bla"), however I found that onCreate was still being triggered in the DatabaseSource even though mode is set to CREATE_NOT_EXISTS. 

Now I notice that column ordering is different as Requery create columns in the order of name alphabetical, and I can't make it follow existing order. Also String data type is by default assigned varchar(255) whereas existing type is TEXT. I wonder if these discrepancy caused the problems? Does anyone have any solution?

**Comment by npurushe** [comment]
Hi `DatabaseSource.onCreate` will only be called if it's a new database. I would check the name of the database matches the existing one. The TableCreationMode value is only used `onUpgrade`. 

But yes there maybe a problem with column ordering in this case, something to verify.

**Comment by anitasantoso** [comment]
I checked that the existing database's name and location matches exactly one that I passed to Requery. onCreate was called but when Requery tries to create the table I get "table already exists". Subsequent call to getConnection() fails because db.isOpen() returns false and SQLNonTransientConnectionException was thrown. Any ideas?

**Comment by anitasantoso** [comment]
Never mind, there was a problem with unclosed connection from other parts of the app. Thanks for your help.

**Comment by npurushe** [comment]
Sure if you still are encountering an issue mapping or upgrading to your database please post back
