### ISSUE TITLE
Allow adding a UNIQUE constraint across multiple columns

### ISSUE THREAD

**Issue by cbruegg** [requery/requery#252]
SQL allows applying a UNIQUE constraint across multiple columns on tables ([see](http://stackoverflow.com/a/2701903/1502352)). I don't think there's a way to express that in requery yet, but there probably should be.

If you could please confirm whether there's a way to do this currently, I could look into implementing this if it's not already possible.

**Comment by npurushe** [comment]
Yes this can be done by adding a `@Index` annotation with a shared name on the desired columns and setting `@Column(unique = true)` on those columns.

**Comment by cbruegg** [comment]
Are you sure? It generates the following statements:

```
CREATE TABLE saved_responses (id integer primary key, field_id varchar(255) not null unique, question_id varchar(255) not null unique, val varchar(255) not null unique);
CREATE INDEX unique_idx on saved_responses (field_id, question_id, val);
```

Specifically, it does not generate a `CREATE UNIQUE INDEX` statement. Perhaps the `Index` annotation needs a method `unique()` as well?

**Comment by cbruegg** [comment]
I wonder if this is the best solution. Are you sure there's no situation
where one would like to have an index on a combination of columns and a
constraint about uniqueness of individual columns? I think adding a
`unique` method on the index annotation would be a more flexible option.

Additionally, the current solution does not support multiple indexes on the
same table. That's not an issue for me, but I thought I'd just let you
know.

Nikhil Purushe <notifications@github.com> schrieb am Do., 18. Aug. 2016,
17:52:

**Comment by npurushe** [comment]
You can specify multiple indexes on the same columns by specifying the index names it belongs to e.g. `@Index({"index1", "index2"})` this is also why @Index doesn't have a unique attribute since it can apply to multiple indexes. I agree there should be way to do this without making the column also unique but that can be supported another way.

**Comment by cbruegg** [comment]
Perhaps there's an easy solution: Adding a method `String[] uniqueIndexes() default {}` on the `@Table` annotation. An index is then unique iff it is contained by the array returned by the method.

**Comment by noberasco** [comment]
The commit introduced here does fix the inability to create unique constraints spanning multiple columns, but, since unique constraints are also created for the single columns, it does not really fix the issue.

Practical example follows.

I have a table that is manually created as follows:

    CREATE TABLE IF NOT EXISTS ZCACHE (tile_hash INTEGER NOT NULL, cache_key VARCHAR(25) NOT NULL, last_used DOUBLE NOT NULL, data BLOB NOT NULL);
    CREATE UNIQUE INDEX IF NOT EXISTS main_index ON ZCACHE(tile_hash, cache_key);
    CREATE INDEX IF NOT EXISTS last_used_index ON ZCACHE(last_used);

The best model for this table that I could devise, following advice found on this issue, is this:


    @Entity
    abstract class AbstractCachedTile {

        @Index("main_index")
        @Column(unique = true, nullable = false, name = "tile_hash")
        long tileHash;

        @Index("main_index")
        @Column(unique = true, nullable = false, length = 25, name = "cache_key")
        String cacheKey;

        @Index("last_used_index")
        @Column(nullable = false, name = "last_used")
        double lastUsed;

        @Column(nullable = false, name = "data")
        byte[] data;
    }

When I try to insert the following items:

        cachedTile = new CachedTile();
        cachedTile.setTileHash(12345);
        cachedTile.setCacheKey("TEST1");
        cachedTile.setLastUsed(123455);
        cachedTile.setData(bytes);

        dataStore.insert(cachedTile);

        cachedTile = new CachedTile();
        cachedTile.setTileHash(12345);
        cachedTile.setCacheKey("TEST2");
        cachedTile.setLastUsed(123455);
        cachedTile.setData(bytes);

        dataStore.insert(cachedTile);

The second insert throws a SQLiteConstraintException, because in addition to the multi-column constraing, requery also created constraints for the single columns.

This is the actual schema that has been generated:

![shot](https://cloud.githubusercontent.com/assets/475725/19341434/bd12f188-912d-11e6-9dcb-e01f074cbf79.png)

I second @cbruegg proposal of adding a unique param to the Index annotation...

**Comment by npurushe** [comment]
Hi yes this is something that should be supported in the next release.

**Comment by noberasco** [comment]
I would like to give your fix a test run.

Is there a convenient way to pull requery as a dependency for my project from a github commit in Android Studio?

**Comment by cbruegg** [comment]
Check out https://jitpack.io. Use the multi module syntax as described
here: https://www.jitpack.io/docs/BUILDING/#multi-module-projects.

noberasco <notifications@github.com> schrieb am Di., 18. Okt. 2016 um
18:07 Uhr:

**Comment by npurushe** [comment]
Hi yes you can use jitpack, also hoping to have an updated released version shortly on bintray

**Comment by noberasco** [comment]
jitpack sounds very interesting, but I'm having difficulties getting it to work.

My Android studio project has a 'app' module, which I tried to edit as follows:

    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:23.4.0'
        compile 'com.android.support:design:23.4.0'
        compile 'com.google.android.gms:play-services-maps:9.6.1'
        compile 'org.greenrobot:eventbus:3.0.0'

        //ORIGINAL
        //compile 'io.requery:requery:1.0.0'
        //compile 'io.requery:requery-android:1.0.0'
        //apt 'io.requery:requery-processor:1.0.0'

        //FROM GITHUB COMMIT
        compile 'com.github.requery:requery:64c3e74'
        //compile ('com.github.requery:requery:64c3e74') {
        //    exclude module:'requery-kotlin'
        //    exclude module:'requery-test'
        //}
        //compile 'com.github.requery:requery-android:64c3e74'
        //compile 'com.github.requery:requery-processor:64c3e74'

        compile 'io.requery:sqlite-android:3.14.2'
    }

This fails with error

    Error:Module 'com.github.requery:requery:64c3e74' depends on one or more Android Libraries but is a jar

**Comment by consp1racy** [comment]
The format is `com.github.<user>:<repo>:<module>:<commit>`. And there's a difference between `compile` and `apt` methods. Try:

    compile 'com.github.requery:requery:requery:64c3e74'
    compile 'com.github.requery:requery:requery-android:64c3e74'
    apt 'com.github.requery:requery:requery-processor:64c3e74'

**Comment by noberasco** [comment]
does not work, fails on the first of the 3 lines:
    
    Error:Could not find com.github.requery:requery:requery.

There probably is something even more basic that I'm getting wrong here.

**Comment by consp1racy** [comment]
My bad, `com.github.requery.requery` instead of `com.github.requery:requery`. Just read https://www.jitpack.io/docs/BUILDING/#multi-module-projects in case I made another mistake.

**Comment by AndroidDeveloperLB** [comment]
So... how do you add a constraint to a field in the table?

I tried something like that:

@Entity
interface TLPhoneToTheme : Parcelable, Persistable {
    @get:Key
    @get:Generated
    var id: Long
    @Column(unique = true, nullable = false)
    var phoneNumber: String
    @get:OneToOne
    @get:ForeignKey
    var theme: TLTheme
}


But then I got this error:

> This annotation is not applicable to target 'member property without backing field or delegate'


![image](https://user-images.githubusercontent.com/5357526/46078731-abbb3880-c19d-11e8-98f5-fcd64cbc5a09.png)

I tried adding a name to the field, or an index, but both failed with the same error.

How come?
