### ISSUE TITLE
Processor tries to annotate static fields with @NotNull, fails

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#253]
Kotlin static interface fields cause `NotNull not applicable to static or final member` error.

```
@Entity
interface Thing : Persistable, Observable, Parcelable {
    @get:Key @get:Generated
    var id : Int
    
    companion object {
        const val THING_CONSTANT = "something"
    }
}
```

I haven't tried with Java.

**Comment by consp1racy** [comment]
Hello, admire how quickly sou solved this! Do you have an estimate on rc3 or a snapshot? Mainly for https://github.com/requery/requery/issues/227.

**Comment by npurushe** [comment]
Should be soon probably end of today

**Comment by consp1racy** [comment]
Awesome! Will it also be safe to use implemented properties on kotlin
interfaces after this? Example:

interface Person: Persistable {
    @get:Key @get:Generated
    var id: Int

    @get:Transient
    val testing: String
        get() = return "person id $id"
}

Dne 18. 8. 2016 16:39 napsal uživatel "Nikhil Purushe" <
notifications@github.com>:

Should be soon probably end of today

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/requery/requery/issues/253#issuecomment-240743812>, or mute
the thread

**Comment by npurushe** [comment]
Yes that should work fine
