### ISSUE TITLE
Upserts with generated IDs

### ISSUE THREAD

**Issue by cbruegg** [requery/requery#254]
Is there any reason why upserts are not allowed with generated keys at all? I've implemented an auto-save system that periodically persists a draft to the database. The same object is mutated over and over again, but its key doesn't change. 

Now, I want to insert the draft if it's not in the DB yet or update the existing entry if an auto-save operation already happened. I suspect the reason for not allowing this is that with generated IDs, multiple objects that have the same content will always have unique IDs, correct? That'd be a point against it, but maybe it would be better to simply warn users about it instead of not allowing this though there are valid use cases.

**Comment by npurushe** [comment]
An upsert statement requires the key to be provided in the query. If the key is not known then it's not possible to generate that statement. You're looking for something different it sounds like which is a check if an entity has an id then update, if not insert? That is more of a client side logic check and not an sql upsert.

**Comment by cbruegg** [comment]
Checking whether the entity has an ID would only make sense for entities
with generated keys though, right? In this case, it would work as a
workaround though. Perhaps it would make sense to generate a method called
`isGeneratedKeyPresent` or something similar that allows checking whether
the entity was either retrieved from the database or inserted into it
already. I could look into implementing this if you'd like me to.

Nikhil Purushe <notifications@github.com> schrieb am Do., 18. Aug. 2016,
08:54:

**Comment by jedikv** [comment]
Maybe a check to see if the potential function that checks an entry fulfils the unique key constraint which then would turn that insert in to an update?

**Comment by npurushe** [comment]
Will look into what could be done here, thanks for the feedback!
