### ISSUE TITLE
Kotlin generic collections in entities do not compile

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#257]
`var listOfThings: List<IThing>`
currently generates
`public void setListOfThings(List<IThing> listOfThings)`
instead of
`public void setListOfThings(List<? extends IThing> listOfThings)`

![image](https://cloud.githubusercontent.com/assets/4589773/17832868/62032784-670e-11e6-9b40-e4617212fdc1.png)

![image](https://cloud.githubusercontent.com/assets/4589773/17832870/6e23a746-670e-11e6-9c96-6fe81020795e.png)

![image](https://cloud.githubusercontent.com/assets/4589773/17832872/76c20078-670e-11e6-9b81-bf5335cfa6bf.png)

`val listOfThings: List<IThing>` compiles. As I understand this is correct syntax. Would it be possible to issue an error message if one tries to use collections in a variable instead of constant?

**Comment by npurushe** [comment]
Thanks for reporting, yes agree that is something that can be improved
