### ISSUE TITLE
Add documentation about creating unique indexes

### ISSUE THREAD

**Issue by cbruegg** [requery/requery#258]
The wiki needs some information about creating unique indexes, perhaps in the section about [defining entities](https://github.com/requery/requery/wiki/Defining-Entities). I've written something up, but unfortunately GitHub doesn't allow PRs for wiki pages, so here it is:

## Unique indexes across multiple columns
You can enforce uniqueness across multiple columns by creating unique indexes like this:
```
class Person {
  @Index("shared_idx")
  @Column(unique = true)
  String name;
  
  @Index("shared_idx")
  @Column(unique = true)
  String address;
  
  ...
}
```
In this example, the table may not contain more than one person with the same name and address.

**Comment by npurushe** [comment]
Wiki updated
