### ISSUE TITLE
Performance comparison with realm.io

### ISSUE THREAD

**Issue by shubhamchaudhary** [requery/requery#26]
It might be useful to add realm.io comparison in the readme table.

**Comment by npurushe** [comment]
Hi yes sure I will add it to the comparison table. Although realm is an interesting case as it's a proprietary non-sql database but it does have a Android layer that is open source. On the pure database side I think independent comparisons have shown it to be only slightly faster than SQLite. Realm queries are also extremely limited compared to what you can do with the subset of SQL SQLite supports.

**Comment by npurushe** [comment]
Closing since Realm is more of a graph database not a SQL one also its not really an ORM. Might be worth mentioning in the wiki.
