### ISSUE TITLE
A non RX-Java Example? 

### ISSUE THREAD

**Issue by karantrehan** [requery/requery#263]
Hie.. trying to refactor a complete application from ActiveAndroid to Requery because it seems really promising.
We do not have RxJava or RxAndroid in our app. I hope this is not an issue for Requery.
If not, can we get a non-RxJava sample? It is becoming really hard to figure out anything.

Thanks.

**Comment by npurushe** [comment]
You don't have to use RxJava it's not a requirement. You can look at the [query examples](https://github.com/requery/requery/wiki/Query-examples) and [test code](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java) for functional examples, these don't involve RxJava

**Comment by karantrehan** [comment]
Hie, Thanks a lot for your reply. The Query examples were helpful, where we were stuck was => data. What is it? Going through the sample gave us a good idea that it is an instance of SingleEntityStore which depends on Rx.. We read through the documentation and found EntityDataStore.

We used it as following: 
```java
protected EntityDataStore<Persistable> dataStore;

public BaseCrud() {
        if (dataStore == null) {
            DatabaseSource source = new DatabaseSource(YodaApplication.getContext(), Models.DEFAULT, 1);
            Configuration configuration = source.getConfiguration();
            dataStore = new EntityDataStore<>(configuration);
        }
    }
```

Hope it helps someone else :)

**Comment by Borkason** [comment]
Thanks mate. For someone new to Android Development, all the Rx stuff in the example makes for a steep learning curve.
