### ISSUE TITLE
How to insert entities with relations that have a unique column

### ISSUE THREAD

**Issue by aegis123** [requery/requery#266]
How can one easily insert entities that have a relations that have unique columns?

So for instance the entities look like as shown below. How would you insert a thread entity? because the a User entity might already have been inserted in the database with another thread or message? In the ThreadRepository class I can make check to see if there is already a thread with a certain remoteId and either insert or update the entity, that would also insert or update the User entity which will throw an `android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed` exception. Upsert also doesn't work because the Id is generated.

```java
@Entity
public class Thread {
	@Key @Generated
	long id;
	@Column(index = true, unique = true)
	String remoteId;
	@NonNull
	String subject;
	@OneToMany
	@NonNull
	List<User> participants;
	@OneToMany
	@NonNull
	List<Messages> message;
}

@Entity
public class Message {
	@Key @Generated
	long id;
	@Column(index = true, unique = true)
	String remoteId;
	@NonNull
	String message;
	@NonNull
	@OneToOne
	User sender;
}

@Entity
public class User {
	@Key @Generated
	long id;
	@Column(index = true, unique = true)
	String remoteId;
	@NonNull
	String name;
}
```

**Comment by npurushe** [comment]
If remoteId is always unique why not use it as the primary key for the table? Otherwise yes you will have to check if the remoteId exists for all entities you are attempting to insert before inserting them.

**Comment by aegis123** [comment]
Is there a way to do something with `@PrePersist` lifecycle callback? like retrieving the Id or something?

**Comment by npurushe** [comment]
`@PrePersist` will not know the generated id.

**Comment by npurushe** [comment]
Closing for now, I think if you combine making the remoteid the primary and key with the `upsert` you can avoid having many redundant checks for existing unique columns in your case
