### ISSUE TITLE
name change ?

### ISSUE THREAD

**Issue by benoitjadinon** [requery/requery#27]
since the library is pretty new (and pretty awesome!), it would be nice, before it's too late, to consider renaming it to something more abstract. 
cause the problem is, it's a real word, which makes google searches less practical.
the "cupboard" library has the same issue ;-)

**Comment by npurushe** [comment]
Sure I understand that searches might be tricky at first. The top hit for requery right now is Form.Requery on MSDN. There will be a website at requery.io up pretty soon. I think if it gets enough attention it should appear pretty high if not first in the google rankings and be relatively easy to find as the word is not commonly used on it's own, it does take a little time though :)

**Comment by benoitjadinon** [comment]
I hope so too ;-)
thanks for the lib
