### ISSUE TITLE
Custom model is not generated after usage of ManyToMany 

### ISSUE THREAD

**Issue by krabatom** [requery/requery#270]
Hi, I have 3 entities:

FirstDefaultEntity 
```java
@Entity(name = "FirstDefault")
public abstract class FirstDefaultEntity {

	@Key
	Long id;

	@ManyToMany
	@JunctionTable(name = "junction_table")
	Set<SecondDefaultEntity> list;

}
```

SecondDefaultEntity 
```java
@Entity(name = "SecondDefault")
public abstract class SecondDefaultEntity {

	@Key
	Long id;

	@ManyToMany
	Set<FirstDefaultEntity> list;

}
```

ThirdCustomEntity 
```java
@Entity(name = "ThirdCustom", model = "custom")
public abstract class ThirdCustomEntity {

	@Key
	Long id;

	String name;

}
```

Without @ManyToMany in FirstDefaultEntity  and SecondDefaultEntity  everything working, otherwise in your generated file Models.java these lines of code are missing:

```java
 public static final EntityModel CUSTOM = new EntityModelBuilder("custom")
    .addType(ThirdCustom.$TYPE)
    .build();
```

**Comment by npurushe** [comment]
You have 2 different models. What's the content of your Models.java file? They will only be in the same file if all the entities are in the same java package, otherwise you'll have a different Models.java file in the other package.

**Comment by krabatom** [comment]
Every entities are in a same package. I know, that I have 2 different models, that was purpose. Problem is, that ManyToMany somehow affecting  generation of second model "custom". Without usage of ManyToMany I have Models.java:
 
```Java
   public static final EntityModel DEFAULT = new EntityModelBuilder("default")
    .addType(FirstDefault.$TYPE)
    .addType(SecondDefault.$TYPE)
    .build();

    public static final EntityModel CUSTOM = new EntityModelBuilder("custom")
    .addType(ThirdCustom.$TYPE)
    .build();
```
But after I used ManyToMany annotation, Models.java has only:
```Java
   public static final EntityModel DEFAULT = new EntityModelBuilder("default")
    .addType(FirstDefault.$TYPE)
    .addType(SecondDefault.$TYPE)
    .build();
```

**Comment by npurushe** [comment]
Thanks that helps will try to reproduce this. As a temporary workaround placing the models in different packages should work.

**Comment by krabatom** [comment]
Ok, thanks. :+1:
