### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by jiqimaogou** [requery/requery#271]
Error:Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/databinding/library/1.2.1/library-1.2.1.pom'. Received status code 409 from server: Conflict
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

**Comment by npurushe** [comment]
This an issue with your gradle repository setup, not related to requery. Maybe try removing 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' from your list of repositories
