### ISSUE TITLE
Prefix not removed from referenced field when using @ForeignKey

### ISSUE THREAD

**Issue by ecdpalma** [requery/requery#272]
The 'm' prefix is not being removed in the generated code for a foreign entity (setReferencedAttribute method). E.g.:

```
abstract class BaseCategory {
  @Key
  @Generated
  @Column(name = "id")
  Integer mId;
}

abstract class BaseVehicle {
  @Key
  @Generated
  @Column(name = "id")
  Integer mId;

  @ForeignKey
  @Column(name  = "category_id")
  BaseCategory mCategory;
}

```

The code generated for the Category entity:

```
  public static final QueryAttribute<Category, Integer> ID = ...
```

And for the Vehicle entity:

```
...
.setReferencedAttribute(new Supplier<Attribute>() {
  @Override
  public Attribute get() {
    return Category.M_ID;
  }
})
...
```

I suppose the expected would be the `get` above to return `Category.ID`. If `BaseCategory.mId` is changed to `Category.id` (without the prefix), the code is generated correctly.

**Comment by ecdpalma** [comment]
I think I solved it here https://github.com/ecdpalma/requery/commit/9f81d3cc27dc387769b93b4bd2edab9ce913f8a5 (it seems too trivial for a pull request).

**Comment by npurushe** [comment]
Yup that looks like a good fix, any bug fix is good enough for a PR feel free to submit.
