### ISSUE TITLE
Booleans not getting updated in store

### ISSUE THREAD

**Issue by alistairsykes** [requery/requery#274]
I am having an issue where I am using the update() method to change a boolean within an entry and it doesn't appear to be changing in the store. It keeps the value it was assigned when first created. Am I doing something wrong? I have checked the values going in and they are definately changed but the values once I call findByKey are not.
Any help you can offer would be much appreciated.

`Application.getData().update(mFriendship);`

```
public static EntityDataStore<Persistable> getData() {
    if (sDataStore == null) {
        final EntityModel model = Models.DEFAULT;
        DatabaseSource source = new DatabaseSource(instance, model, 1);
        if (BuildConfig.DEBUG) {
            // use this in development mode to drop and recreate the tables on every upgrade
            source.setTableCreationMode(TableCreationMode.DROP_CREATE);
            source.setLoggingEnabled(true);
        }
        Configuration configuration = source.getConfiguration();
        sDataStore = new EntityDataStore<>(configuration);
    }
    return sDataStore;
}
```

```
I/requery: beforeExecuteQuery sql: select mParseId, mConfirm1, mConfirm2, mFriendsSince, mPerson1, mPerson2 from Friendship where mParseId = ?
I/requery: afterExecuteQuery
```

**Comment by npurushe** [comment]
Do you have the log from when you called update? It should show the update sql statement, thanks

**Comment by alistairbrightec** [comment]
No the update message isn't appearing but I break pointed the 
`public <E extends T> E update(E entity)` in `EntityDataStore` and it's definately getting called.

**Comment by alistairsykes** [comment]
I am recreating the objects from scratch. I have checked in the debugger that the object is definately different (i.e. the boolean is different) and that the id is the same.

The situation being I have a parse backend and I am storing some parse objects locally, so I use the parseId as my ids. I do a query for all the objects and save them all locally. Either using insert or update.

**Comment by npurushe** [comment]
I think probably you are not changing the object through the setter, e.g. if you something like gson it modifies the object's private fields directly (see #73) and then requery would be unaware it was changed.

**Comment by alistairsykes** [comment]
Ok, great I understand how it works now. That `(stateless = true)` is what I was looking for. Brilliant thanks you.
