### ISSUE TITLE
upserting entity with ManyToMany

### ISSUE THREAD

**Issue by aegis123** [requery/requery#275]
When upserting an entity with A ManyToMany relationship I get a Foreign Key constraint failed exception on the Junction Table entity because it already exist in the JunctionTable. When I set through it with debugger all the entity have CascadeMode.UPSERT in the EntityWriter but the Junction Table has CascadeMode.INSERT when it tries to insert the same object which has previously been inserted.

Shouldn't it have CascasdeMode.UPSERT since it has a valid primary key?
The entities I use are below.

```java
@Entity
public interface Thread {
    @Key
    String id();

    @Column(nullable = false)
    String subject();

    @JunctionTable
    @ManyToMany
    List<AccountEntity> participants();
}

@Entity
public interface Account {

    @Key
    String id();

    @NonNull
    @Column(nullable = false)
    String email();
}
```

**Comment by npurushe** [comment]
Thanks for reporting will try to reproduce this, but yes sounds like it should be upsert in the chain.
