### ISSUE TITLE
Error inserting 'empty' entity

### ISSUE THREAD

**Issue by jackwakefield** [requery/requery#276]
When inserting a Schedule entity below with a generated key and a one-to-many relationship, an IllegalStateException is being thrown:
`java.lang.IllegalStateException: Cannot generate update statement with an empty set of values`

```java
@Entity public abstract class AbstractSchedule implements Parcelable, Persistable {
  @Key @Generated int id;

  @OneToMany(cascade = { CascadeAction.DELETE, CascadeAction.SAVE })
  MutableResult<ScheduleDate> dates;
}
```

If I add a placeholder field to AbstractSchedule, the exception isn't thrown and the data is inserted correctly

```java
@Entity public abstract class AbstractSchedule implements Parcelable, Persistable {
  @Key @Generated int id;

  @OneToMany(cascade = { CascadeAction.DELETE, CascadeAction.SAVE })
  MutableResult<ScheduleDate> dates;

  int dummyField;
}
```

**Comment by npurushe** [comment]
Yes currently this is not supported, as there must be one column that is not generated. However it looks like this possible to support. Thanks for reporting
