### ISSUE TITLE
[QUESTION] How can i use long text in Android (SQLITE)

### ISSUE THREAD

**Issue by gaemi** [requery/requery#280]
Is it possible to have an column on 'text' type?

**Comment by npurushe** [comment]
Hi any String type will be mapped and created as 'TEXT', the sql emitted may use var char but this just gets mapped to TEXT by SQLite automatically.

**Comment by npurushe** [comment]
https://www.sqlite.org/datatype3.html

**Comment by gaemi** [comment]
Thank you ^^
