### ISSUE TITLE
Feature request: Support DECIMAL type out-of-box

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#282]
BasePreparedStatement#setObject does not handle `BigDecimal`s (resolved as `Types.DECIMAL`). Although `BigDecimal` is recognized as standard type in `GenericMapping`.

Is this by design?

Is there another way besides implementing a custom converter?

**Comment by npurushe** [comment]
Hi yes correct BigDecimal is not supported by default in the android library, but should be easy to add. As a workaround on the current version yes you can support this with a custom Converter.
