### ISSUE TITLE
Preventing update from overwriting certain fields?

### ISSUE THREAD

**Issue by Glurt** [requery/requery#284]
Is there an easy way to prevent a field being overwritten once it has been set? If not, is it possible to prevent initialised fields from being set back to null.

I have an entity with a field that once set, needs to either stay as that value or at the very least, not be set to null. Ideally it would just ignore the new value/null and just keep the existing value. 

I'm thinking this could be an annotation but there may be a better way.

**Comment by npurushe** [comment]
When is the value being set to null and by what code? Setting `@Column(nullable = false)` prevents the value from being null in the database.

**Comment by Glurt** [comment]
I'm populating entities with values from the web, caching them and then displaying them in a list. When the user clicks on an item in the list I open a detail activity for that entity, redownloading it to keep it up to date with the server.

The problem is that not all of the entities fields are populated from the server as some are local to the app, when the new entity is downloaded all of the local fields are null and are set to such when I update the entity in the db.

I could put a lot of checks in myself and set all of the fields back to their original value but I thought I'd check if this was something requery could take care of for me.

**Comment by npurushe** [comment]
Ultimately for json serialization requery will support a jackson module for this (see #73). I think libraries that depend on modifying the private members of entity objects would cause some hidden problems that would be hard to support.
