### ISSUE TITLE
Inheritance in converter

### ISSUE THREAD

**Issue by bangarharshit** [requery/requery#286]
Hey,

I have a use case

```
public class BaseMessage {
}

public class TextMessage extends BaseMessage {
        // To string and from string are based on Gson.
}

public class ImageMessage extends BaseMessage {
        // To string and from string are based on Gson.
}

private enum MessageType {
    IMAGE, TEXT;
}
public class Chat {
   @Converter(?? - which can take message type as an input, I will cast it when I will use it).
    private BaseMessage baseMessage; // Chat supports 100 different type of messages so serialising before saving it to disk.
   private MessageType messageType;
}
```

I am looking at code to see if i can modify it to suit my need. In case you know of an existing pattern.

**Comment by npurushe** [comment]
Does your base message type contain enough information to know which type of message it needs to create? If it's a string and contains this information then it should be fine. However if you need to know what the value of another column/field is e.g. like messageType in your example that info is not available to the converter

**Comment by npurushe** [comment]
Closing for now, please follow up if you have more info. thanks

**Comment by bangarharshit** [comment]
Hey Nikhil,

Sorry for late reply. Are you suggesting something like this? Can you give some example?
```
public class BaseMessageContainer {
    public String type;
    public BaseMessage baseMessage; // it varies based on type.
}
```

**Comment by npurushe** [comment]
Hi currently a converter won't know any information about other fields/columns in the object. But this could be useful in your case and possible others so it will keep it as an enhancement.

**Comment by bangarharshit** [comment]
@npurushe . I looked at the converter code and can take a shot.

**Comment by npurushe** [comment]
I think a better option here is to have a method in your `Chat` class that looks at the message type and creates the right message type on the fly based on the current value of messageType. This doesn't seem like something that needs to be supported while converting to and from the database representation.

**Comment by bangarharshit** [comment]
Unfortunately converting it on fly is not so good. I had this use case for list view and while converting it on fly made it run on ui thread. I agreed though it's a rare use case. Sqldelight has a concept of mapper - https://github.com/square/sqldelight and the only reason its possible to do there is because  you have access to underlying cursor.

**Comment by npurushe** [comment]
If you read a record off the main thread you can use to the callback methods to do this e.g.

```java
Chat {
    ...
    @PostLoad 
    void onLoad() {
        if (messageType == ...) {
           // perform conversion on other fields
        }
    }
}
```
Accessing the cursor doesn't really help you're storing the value as string either way.
