### ISSUE TITLE
Stateless not working

### ISSUE THREAD

**Issue by alistairsykes** [requery/requery#288]
I am using stateless for entity (see previous issue #274) but it doesn't appear to be working. The booleans aren't getting updated when I call update. Any ideas?

```
@Entity(stateless = true)
abstract class AbstractFriendship {

    @Key
    String mParseId;

    @Convert(ConverterUser.class)
    User mPerson1;
    Boolean mConfirm1;
    @Convert(ConverterUser.class)
    User mPerson2;
    Boolean mConfirm2;
    Date mFriendsSince;

}
```

**Comment by npurushe** [comment]
Which update API are you calling? if it's a non-blocking API you may need to evaluate the call further (eg subscribe if its RxJava).

**Comment by alistairsykes** [comment]
The update call
`Application.getData().update(friendship);`

Code from Application.class
```
public static EntityDataStore<Persistable> getData() {
        if (sDataStore == null) {
            final EntityModel model = Models.DEFAULT;
            DatabaseSource source = new DatabaseSource(instance, model, 1);
            if (BuildConfig.DEBUG) {
                // use this in development mode to drop and recreate the tables on every upgrade
                source.setTableCreationMode(TableCreationMode.DROP_CREATE);
            }
            Configuration configuration = source.getConfiguration();
            sDataStore = new EntityDataStore<>(configuration);
        }
        return sDataStore;
    }
```

I am using rc4.

**Comment by npurushe** [comment]
Added a specific test case for this in this [commit](https://github.com/requery/requery/commit/14d5df41b8d1f5a121d197b6500c1f2ee387f632) and it works fine, the update statement is correct.
`INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4PreparedStatement@3bd40a57 sql:
update Entry set id = ? ,created = ? ,flag1 = ? ,flag2 = ? where id = ? `

**Comment by alistairsykes** [comment]
Yep I am seeing a similar statement
```
09-21 09:34:29.390 30333-30431/com.example.dev I/requery: beforeExecuteUpdate sql: update Friendship set mParseId = ? ,mConfirm1 = ? ,mConfirm2 = ? ,mFriendsSince = ? ,mPerson1 = ? ,mPerson2 = ? where mParseId = ? 
09-21 09:34:29.392 30333-30431/com.example.dev I/requery: afterExecuteUpdate
```

However it is still not getting set. I am watching it in debug and I am changing the value from true to false but the database entry is not getting updated. Could it be anything to do with the fact that I have Converters in the friendship object maybe?

**Comment by npurushe** [comment]
I would check you are updating the right row with the key you are expecting (mParseId) and also that something else isn't overwriting or changing the values in your object.

**Comment by alistairsykes** [comment]
As far as I can tell, I am not overwriting my change. I am running through in debug and checking nothing is overriding. I am creating the friendship object with a constructor I have written in the abstract entity class. Could that be having any affect?

**Comment by npurushe** [comment]
No the other objects shouldn't affect those fields

**Comment by alistairsykes** [comment]
Sorry I imagine you're very busy but have you got any other ideas for me. I'm struggling to find the problem.

**Comment by alistairsykes** [comment]
So I have found a work around. If I disable the cache on the object everything works as expected. Does that give you any hint as to what the problem might be?

**Comment by npurushe** [comment]
Disabling the cache mean's objects don't get reused, possibly the original cached object was modified by code elsewhere in your app?

**Comment by npurushe** [comment]
Closing for now, please post back if you get more info thanks
