### ISSUE TITLE
Querying children of object (and children of children)

### ISSUE THREAD

**Issue by dadino** [requery/requery#289]
I have the following structure

    @Entity(stateless = true)
    abstract class AbstractPark {
                @Key
	        long id;

	        String name;

	        @Column(name = "tariffs")
	        @OneToMany(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
	        List<Tariff> tariffs;
    }

    @Entity(stateless = true)
    abstract class AbstractTariff {
	        @Key
	        long id;

	        @ManyToOne
	        @Column(name = "park")
	        Park park;

	        @OneToMany(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
	        @Column(name = "rates")
	        List<Rate> rates;
    }

    @Entity(stateless = true)
    abstract class AbstractRate {

	        @Key
	        long id;

	        @ManyToOne
	        @Column(name = "tariffs")
	        Tariff tariff;

	        @Column(name = "duration_in_minutes")
	        int durationInMinutes;

	        @Column(name = "price")
	        double price;
    }

I want to query the Parks and get a java Park with all the Tariffs and all the Rates inside it.

Right now I only have a Park with null tariffs:
 
     return db().select(Park.class)
		           .get()
		           .toSelfObservable()
		           .map(Result::toList);

- Is this the normal behavior? 
- Can I get all Tariffs and Rates with a query? 
- Can I choose what to get (when querying a list of Parks, I'll just need their name)?

**Comment by npurushe** [comment]
Hi initially your Park will have all it's non-lazy (default fields) loaded in that query. Then when you call getTariffs() it will load all the tariffs associated with that Park and so on for you other types. It wont be null but an empty collection if there are none.

You can query just the names for example by doing `select(Park.NAME).get().toList()` for example to retrieve just the names or `select(Park.class, Park.NAME).get()` to retrieve partial objects.

**Comment by dadino** [comment]
Ok, so something like

     return db().select(Park.class)
               .get()
               .toSelfObservable()
               .map(Result::toList)
               .map(this::getLazy);

    List<Park> getLazy(List<Park> parks){
               for(Park park : parks){
                     for(Tariff tariff : park.getTariffs()){
                          tariff.getRates();
                     }
               }
               return parks;
    }

should do the trick?

Can I propose a getLazy method on the generated Park class that does this work?

**Comment by npurushe** [comment]
Yes sure you can do that. Lazy vs Eager fetching of other items is something that is being added, although how exactly it will be done is not finalized.
