### ISSUE TITLE
Build-failure when specifying requery-processor-RC4 with dagger-2.7 apt processor.

### ISSUE THREAD

**Issue by splendidbits** [requery/requery#290]
* Android SDK 7 (N)
* Android Studio 2.2
* Gradle 1.3

This took me a waaaayy too long to figure out as there did not seem to be any others that have previously experienced this and so was not google-able.

There seems to be an apt pre-processor collision with the following Gradle apt dependencies:

>apt 'com.google.dagger:dagger-compiler:2.7'
>apt 'io.requery:requery-processor:1.0.0-rc4'

Which cause the following nightmare of a low-level build failure:

>Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: Invalid class name identifier: $classname>

I removed the requery pre-processor which seems to have fixed the immediate build error output, but I am unsure what other issues this could invoke.

**Comment by npurushe** [comment]
Where you able to find the cause of your issue? thanks
