### ISSUE TITLE
this and base files have different roots

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#294]
Kotlin 1.0.4 with old kapt, incremental compiler enabled and overridden build directory produces the following error: 
> Error:Execution failed for task ':app:compileDevDebugKotlinAfterJava'.
> this and base files have different roots: R:\gradle\build\quickjobs-android\app\generated\source\kapt\devDebug\cz\quickjobs\android\database\model\PendingCandidateReview.java and C:\Users\Eugen\Documents\Android\Projects\quickjobs-android.

This only happens on incremental builds.

### projectRoot/gradle.properties
```
kotlin.incremental=true
```

### ~/.gradle/init.gradle
```
gradle.projectsLoaded {
    rootProject.allprojects {
        buildDir = "R:/gradle/build/${rootProject.name}/${project.name}"
    }
}
```

`R:` is a RAM disk.

Creating a symbolic link `C:\RAMDisk` to `R:` and updating the path in `init.gradle` works around the issue. In that case `Execution failed for task ':app:compileDevDebugKotlinAfterJava'.` because no classes were generated.

**Comment by consp1racy** [comment]
See also https://github.com/requery/requery/issues/295

**Comment by consp1racy** [comment]
https://github.com/JetBrains/kotlin/blob/b8f4c78d340778f63f98966b265d8b0531bc0225/ChangeLog.md

> KT-14056 Fixed exception "This and base file have different roots"

The issue is not necessarily related to requery then (does Dagger 2 work out of the box because it does not use KAPT?).

**Comment by npurushe** [comment]
Unfortunately this is not something that can be resolved by requery.
