### ISSUE TITLE
"builder" parameter is ignored

### ISSUE THREAD

**Issue by feichngr** [requery/requery#297]
I'm currently integrating my Immutables value classes with requery.
I tried to avoid defining additional abstract `Builder` classes in my models by setting the `builder` parameter of `Entity` to the `Builder` classes generated by Immutables.

What I hoped would work is something like this

```
@Value.Immutable
@Value.Style(builder = "new")
@Entity(builder = ImmutableTestModel.Builder.class)
abstract class TestModel {
    @Key abstract int id();
    abstract String a();
    abstract String b();
    abstract String c();
}
```

Unfortunately the annotation processor for requery generates an `TestModelType` class and the build fails with the error message `error: cannot find symbol method build()`

**Comment by npurushe** [comment]
Thanks for reporting is `ImmutableTestModel.Builder.class` a class that is generated by the Immutables library? It maybe requery is trying to resolve it and it's not generated yet, might be possible to work around that.

**Comment by feichngr** [comment]
Yes, the ```Builder``` is generated by Immutables. ```@Value.Style(builder = "new")``` gives it a non-private constructor as required by the ```builder``` parameter.
Maybe it is possible to defer the requery generator step for ```Entity```s until this class is generated?

**Comment by feichngr** [comment]
Accidentally closed the issue, sorry for that
