### ISSUE TITLE
Entity not updated UI to which binded

### ISSUE THREAD

**Issue by s1155030742** [requery/requery#298]
In my project, I implemented requery with rxjava:
In my fragment, which containing a listview, I subscribed
data from db
 private void getDevices() {
        mSubscriptions.add(mDataManager.getDevices()
            .observeOn(AndroidSchedulers.mainThread())
            .subscribeOn(Schedulers.io())
            .subscribe(new Subscriber<DeviceEntity>() {           
                @Override
                public void onNext(DeviceEntity device) {
                    mDeviceAdapter.addItem(device);
                }
            })); 
This is my xml:
 `
<data>
        <variable
            name="device"
            type="com.abc.model.Device"/>
    </data>`
<TextView
                android:id="@+id/connection_status"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:textColor="@color/description_color"
                android:text="@{device.connected ? device.CONNECTED : device.DISCONNECTED}"
                android:textSize="@dimen/description_size" />

on runtime, after device.connected's value is changed. The textview will not follow the change in the value. Effectively, it only keep showing the text according to the value when the view is created.

As mentioned in document, 

> With binding enabled you can automatically update your UI when the underlying database entity is changed or updated.

So, I have no idea why would this happen. :(

**Comment by npurushe** [comment]
The wiki you're referring to is about Android Databinding which is separate and unrelated to RxJava. Please see the example project for an example that uses Android Databinding.
