### ISSUE TITLE
orderBy not working

### ISSUE THREAD

**Issue by timothycoutlakis** [requery/requery#299]
The documentation says:

    Result<Person> query = data
        .select(Person.class)
        .where(Person.NAME.lower().like("b%")).and(Person.AGE.gt(20))
        .orderBy(Person.AGE.desc())
        .limit(5)
        .get();

However, nothing after the `orderBy` line works.
It says **`"cannot resolve method limit(int)"`**

**Comment by npurushe** [comment]
There are numerous test cases and examples using orderBy and limit, added another one. Are you sure your'e not missing something?

**Comment by timothycoutlakis** [comment]
Thank you for your reply.  I checked your tests and you are correct.
My getData method was returning `EntityDataStore` instead of `EntityDataStore<Persistable>`, which caused the error.

**Comment by npurushe** [comment]
Sure, glad you found the cause
