### ISSUE TITLE
Error when reading Long value from database.

### ISSUE THREAD

**Issue by nathanieloliveira** [requery/requery#3]
Long value gets persisted as INTEGER sql type which is fine, but is mapped as java.lang.Integer when read from database, then an invalid typecast exception is thrown when converting.

Workaround i found is to use a custom converter to a BLOB type:
```
public class LongToByteArrayConverter implements Converter<Long, byte[]> {

    @Override
    public Class<Long> mappedType() {
        return Long.class;
    }

    @Override
    public Class<byte[]> persistedType() {
        return byte[].class;
    }

    @Override
    public Integer persistedSize() {
        return Long.SIZE / Byte.SIZE;
    }

    @Override
    public byte[] convertToPersisted(Long value) {
        return ByteBuffer.allocate(Long.SIZE / Byte.SIZE).putLong(value).array();
    }

    @Override
    public Long convertToMapped(Class<? extends Long> type, byte[] value) {
        return ByteBuffer.wrap(value).getLong();
    }
}
```

Maybe a way to know when to convert back to java's Long is needed.

**Comment by npurushe** [comment]
Thanks good catch. If your entity contains long the conversion should respect that. Will add a fix for this today.

**Comment by npurushe** [comment]
Fixed in latest snapshot version. Thanks for reporting!

**Comment by nathanieloliveira** [comment]
No problem! 

    Em Segunda-feira, 15 de Fevereiro de 2016 22:39, Nikhil Purushe <notifications@github.com> escreveu:
 

 Fixed in latest snapshot version. Thanks for reporting!—
