### ISSUE TITLE
Question. Async load object w/o rx

### ISSUE THREAD

**Issue by BOOMik** [requery/requery#301]
Hello.
How i can load complex object async without using rx?

When i receive as
`EventEntity data = mData.select(EventEntity.class).limit(1).get().first();`
data is contain empty objects with FETCH state? but i need full LOADED object

**Comment by FuriousSeraphim** [comment]
mData.select(EventEntity.class).limit(1).get().toObservable().first();

**Comment by consp1racy** [comment]
@BOOMik Off-topic: Great title...

@FuriousSeraphim Quoting OP "without rx". Observable is rx.

**Comment by npurushe** [comment]
Your object will be loaded using that query, but as you said it is not a async call in your example. If you're not using RxJava you can simply run that code in another thread the api is thread safe. There are a number of ways to do that Java 8 CompletableFuture.supplyAsync for example.
