### ISSUE TITLE
Cannot compare persisted UUID

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#303]
Version used: 1.0.0

UUID (persisted as `ByteArray`) cannot be used with `eq` method. Are byte arrays compared by reference?

**Comment by npurushe** [comment]
The UUID converter should be called to convert the value into a parameter for the prepared statement. Do you se the default UUIDConverter or are you providing your own converter?

**Comment by consp1racy** [comment]
I tried something along the lines of 

    val uuid = ...
    val req = UUIDConverter().convertToPersisted(uuid)
    val q = store.select(IJobOffer::class) where (requestId eq req)

but then requery complained because the statement expected the mapped type (`UUID`) not the persisted type (`byte[]`) as argument. This leads me to believe the converter is called for me.

I tried explicitly setting a custom `UUID` to `String` converter on the entity field with no success because `UUID` is internally always persisted as `byte[]` by requery before converter gets a chance.
