### ISSUE TITLE
[BUG] cannot delete if no primary key is present

### ISSUE THREAD

**Issue by noberasco** [requery/requery#304]
Take the following Entity

    @Entity
    abstract class AbstractMapServer {
        @Column
        int type;

        @Column
        String name;

        @Column
        String jsonParams;
    }

Now insert a couple of records:

    mapServer = new MapServer();
    mapServer.setName("Test 1");
    mapServer.setType(1);
    mapServer.setParams("");
    dataStore.insert(mapServer);
    
    mapServer = new MapServer();
    mapServer.setName("Test 2");
    mapServer.setType(1);
    mapServer.setParams("");
    dataStore.insert(mapServer);

Now attempt to delete one of these records:

    dataStore.delete(mapServer);

This will throw a io.requery.sql.RowCountException: Expected 1 row affected actual 2 exception.

If I alter the Entity adding a primary key:

    @Entity
    abstract class AbstractMapServer {
        @Key
        @Generated
        int id;
        
        [snip]
    }

the aforementioned delete command works.

It seems that, in absence of a primary key, the delete command for a single entity attempts to delete all records, fails an internal check, aborts the transaction and throws an exception ;-)

**Comment by npurushe** [comment]
What's the expected outcome? The only way this can work is if there is a where clause comparison against all the column values. I think that can be supported but without a unique constraint it cannot guarantee more than 1 row would be deleted in which case an exception would still be thrown.

**Comment by noberasco** [comment]
The expected outcome is it being able to delete the instance of the entity I instructed it to delete ;-)

How can that be achieved? Good question.

I come from Core Data on iOS, which is a full fledged ORM. Core Data handles the primary key for a given entity internally, so I guess adding a primary key internally if none has been specified externally is a possibility.

Otherwise, I guess the internal DELETE statement can be implemented, in absence of primary key, with a WHERE clause matching all of the fields and a LIMIT of 1. But I'm aware that this won't work with many sqlite versions shipped with Android (this is an optional feature of SQLite which needs to be enabled at compile time).

Or maybe you can simply throw a better exception. Instead of attempting to delete the record, then throw exception because you deleted more records than expected (which should not happen in the first place as it would go entirely undetected if I happen to have a single record matching the DELETE statement you create) you could throw a NotSupportedException with a message like 'deleting records without a WHERE clause or a PRIMARY KEY is not supported'.
