### ISSUE TITLE
Generated classes clash with existing classes.

### ISSUE THREAD

**Issue by apkelly** [requery/requery#305]
Hi,

I have 2 classes defined in my app, PointOfInterest and PointOfInterestType, however when using requery for my persistence layer the classes it generates clash with my existing PointOfInterestType.

I'm using AutoValue if that makes a difference, but I was wondering if there was a way to have the generated classes added as inner classes of my existing models, or if I could put them in a model/requery sub-package.

Thanks.

**Comment by npurushe** [comment]
Hi you can override this generated class name using `@Entity(name = "PointOfInterestDef")` or similar alternate name. For AutoValue requery defaults to suffixing 'Type' onto the class name which collides with your existing class.

**Comment by apkelly** [comment]
Will that also rename my database table or will that still be based on the class name of my entity?

**Comment by npurushe** [comment]
Nope that doesn't effect the table name, just the generated class name
