### ISSUE TITLE
Annotations wiki page and gradle 2.2's annotationProcessor

### ISSUE THREAD

**Issue by stephenmcd** [requery/requery#307]
The wiki page for Annotations (https://github.com/requery/requery/wiki/Gradle-&-Annotation-processing) suggests various plugins for annotation processing, and then mentions newer gradle versions may negate the need.

It looks like gradle 2.2 provides `annotationProcessor` which does in fact negate the need for a plugin. I've tested this with the following:

```
dependencies {
    ...
    annotationProcessor 'io.requery:requery-processor:1.0.0'
}
```

Suggest updating the wiki page to reflect this - I would contribute the changes but GitHub doesn't provide a way to.

Thanks for the excellent project!

**Comment by npurushe** [comment]
Yeah this is a new feature provided by the android gradle plugin. Will update the wiki thanks!

**Comment by stephenmcd** [comment]
Thanks again

**Comment by steelxtreme** [comment]
Is the new annotation gradle plugin working? I recently started to use requery also I have downloaded android example from repository and Models  and entities  classes are not being generated.
