### ISSUE TITLE
Cannot use where on foreign key

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#308]
Requery 1.0.0

`IJobOffer::author eq sessionManager.userId` constraint causes the query to fail.

`sessionManager.userId` is an `Int`, so is `IJobOffer::author`.

```
class JobOfferManager(val app: QuickJobsApplication, val databaseManager: DatabaseManager, val jobManager: JobManager, val sessionManager: SessionManager) {
    fun loadAuthoredJobOffers(): List<IJobOffer> {
        val store = databaseManager.store
        val q = store.select(IJobOffer::class) where (IJobOffer::author.isNull()) or (IJobOffer::author eq sessionManager.userId)
        return q.get().toList() // L21
    }
}
```

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to cz.quickjobs.android.database.model.Person
   at cz.quickjobs.android.database.model.Person$51.apply(Person.java:632)
   at io.requery.sql.Attributes.replaceKeyReference(Attributes.java:61)
   at io.requery.sql.SelectResult.iterator(SelectResult.java:131)
   at io.requery.query.BaseResult.iterator(BaseResult.java:123)
   at io.requery.query.BaseResult.collect(BaseResult.java:77)
   at io.requery.query.BaseResult.toList(BaseResult.java:71)
   at cz.quickjobs.android.app.JobOfferManager.loadAuthoredJobOffers(JobOfferManager.kt:21)
   ...
```

### Person.java (generated)

    public static final Type<Person> $TYPE = new TypeBuilder<Person>(Person.class, "IPerson")
    .setBaseType(IPerson.class)
    .setCacheable(true)
    .setImmutable(false)
    .setReadOnly(false)
    .setStateless(false)
    .setFactory(new Supplier<Person>() {
        @Override
        public Person get() {
            return new Person();
        }
    })
    .setProxyProvider(new Function<Person, EntityProxy<Person>>() { // L632
        @Override
        public EntityProxy<Person> apply(Person entity) {
            return entity.$proxy;
        }
    })
    .addAttribute(FACE_FILE)
    .addAttribute(SURNAME)
    .addAttribute(SEND_NOTIFICATION)
    .addAttribute(EMAIL)
    .addAttribute(NAME)
    .addAttribute(INTERNAL_TIME_UPDATED)
    .addAttribute(COMPANY_NAME)
    .addAttribute(RATING_COUNT)
    .addAttribute(CREATED)
    .addAttribute(OPTIONAL_FILE)
    .addAttribute(DESCRIPTION)
    .addAttribute(RATING)
    .addAttribute(BIRTH_DATE)
    .addAttribute(GENDER)
    .addAttribute(PHONE_NUMBER)
    .addAttribute(AVATAR_FILE)
    .addAttribute(LOCAL_ID)
    .addAttribute(BODY_FILE)
    .addAttribute(REMOTE_ID)
    .build();

### IJobOffer.kt
```
@Entity
interface IJobOffer : Parcelable, Persistable {
    @get:Key
    @get:Generated
    @get:Column(name = "_id")
    var localId: Int?

    @get:Column(name = "id")
    var remoteId: Int?

    @get:ManyToOne
    @get:ForeignKey(update = ReferentialAction.CASCADE, referencedColumn = "id", references = IPerson::class)
    var author: Int?
}
```

### IPerson.kt
```
@Entity
interface IPerson : Parcelable, Persistable {
    @get:Key
    @get:Generated
    @get:Column(name = "_id")
    var localId: Int?

    @get:Column(name = "id")
    var remoteId: Int?
}
```

**Comment by npurushe** [comment]
In this case you should remove @get:ManyToOne from the author field since it's not holding an entity.

**Comment by consp1racy** [comment]
Fails no more, thank you so much.

**Comment by npurushe** [comment]
Ok great closing for now, will try to make this a warning in the future thanks

**Comment by consp1racy** [comment]
In that case reopen as `enhancement`.
