### ISSUE TITLE
Requery for Android: error when use example standalone

### ISSUE THREAD

**Issue by ValeriusGC** [requery/requery#311]
Hi!
It's about 'requery' in Android context.
When I extracted android-example and tried to launch it standalone, i got error 

```
"Could not find method apt() for arguments [io.requery:requery-processor:1.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
    <a href="openFile:***RequeryExample/app/build.gradle">Open File</a>"

```
So when I tried to add some dependencies 

```
    dependencies {
      compile 'com.jakewharton:butterknife:8.0.1'
      apt 'com.jakewharton:butterknife-compiler:8.0.1'
    }

```
like described in SO it did not help me.

When i added plugin
`apply plugin: 'android-apt'`
and 
`classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'`
i got next errors in layout:
```
Error:(21, 29) No resource type specified (at 'text' with value '@{person.name}').
Error:(30, 29) No resource type specified (at 'text' with value '@{person.phoneNumberList[0].phoneNumber}').
Error:(39, 29) No resource type specified (at 'text' with value '@{person.email}').
Error:(55, 29) No resource type specified (at 'text' with value '@{person.address.line1}').
Error:(63, 29) No resource type specified (at 'text' with value '@{person.address.city}').
Error:(71, 29) No resource type specified (at 'text' with value '@{person.address.state}').
Error:(79, 29) No resource type specified (at 'text' with value '@{person.address.zip}').
Error:(86, 29) No resource type specified (at 'text' with value '@{person.address.country}').

```
help me to resolve this issue, please.

Best regards, Valerius

**Comment by npurushe** [comment]
Hi please see the wiki page [Gradle-&-Annotation-processing](https://github.com/requery/requery/wiki/Gradle-&-Annotation-processing). Just use Android's `annotationProcessor` in the android plugin. The examples were updated using this.

**Comment by ValeriusGC** [comment]
Thanks,  @npurushe.
But i got another issue - when i try to use requery with android annotations i got list of errors
```
Error:(22, 54) error: cannot find symbol class Models
Error:(8, 54) error: cannot find symbol class NoteEntity
Error:(9, 54) error: cannot find symbol class TagEntity
```
My **build.gradle** looks like
```
    compile 'io.requery:requery:1.0.0'
    compile 'io.requery:requery-android:1.0.0' // for android
    annotationProcessor 'io.requery:requery-processor:1.0.0'

    compile "org.androidannotations:androidannotations-api:4.1.0"
    annotationProcessor "org.androidannotations:androidannotations:4.1.0"
```
Is this possible to use these 2 library in common?

Best regards, Valerius

**Comment by npurushe** [comment]
You can combine it with other libraries. Your build is probably failing because of an error in your model(s) so the code is not generated. This indicated in the build output, You can see the whole output from `./gradle build`. Also make sure you are not using incremental complication, also try a clean rebuild
