### ISSUE TITLE
Android - ManyToMany comes to strange error.

### ISSUE THREAD

**Issue by ValeriusGC** [requery/requery#312]
I tried using your Android-sample. It compiled inside packet, well... 
But when i put 2 new sample classes in model
```
@Entity
public interface Address2 extends Observable, Parcelable, Persistable {
    @Key
    @Generated
    int getId();

    @Bindable
    @ManyToMany
    Result<Address3> getAddresses3();
}

```
and 
```
@Entity
public interface Address3 extends Observable, Parcelable, Persistable {
    @Key
    @Generated
    int getId();

    @Bindable
    @ManyToMany
    Result<Address2> getAddresses2();
}
```
i have got errors 
```
Error:(29, 50) error: package io.requery.android.example.app.databinding does not exist
Error:(31, 44) error: cannot find symbol class AddressEntity
Error:(33, 44) error: cannot find symbol class PersonEntity
Error:(35, 44) error: cannot find symbol class PhoneEntity
Error:(48, 13) error: cannot find symbol class PersonEntity
Error:(49, 13) error: cannot find symbol class ActivityEditPersonBinding

```
But if i remove cross reference, for example
```
    @Bindable
    @ManyToMany
    Result<**Person**> getPersons();

```
all errors disappeared.

Eeeehhhh... Well how can I explain this? And how can I realize this ManyToMany correct?

**Comment by npurushe** [comment]
Hi you should remove `@Bindable` for types of `Result`. Use lists or sets instead if you need android databinding for them.

**Comment by ValeriusGC** [comment]
Alas, it did not solve problem.
My code looks now like
```
    @ManyToMany
    Result<Address2> getAddresses2();
```
and
```
    @ManyToMany
    Result<Address3> getAddresses3();
```
but i got these errors as couple of hours before.

Would you be so kind to extend your android sample with ManyToMany fields? 
Thanks beforehand, Valery.

**Comment by npurushe** [comment]
The example has a ManyToMany model, however it is not used by the application yet, that will be enhanced in the future
