### ISSUE TITLE
fail to insert under relationship @ManyToOne 

### ISSUE THREAD

**Issue by s1155030742** [requery/requery#313]
I have 2 table DeviceLostRecord and Device which is in @ManyToOne relationship:

`
@Entity
public interface Device extends Observable, Parcelable, Persistable {

```
@Key
@Generated
int getId();

@Bindable
String getName();
```

}

@Entity
public interface DeviceLostRecord  extends Observable, Parcelable, Persistable {

```
@Key
@Generated
int getId();

@Column(value = "CURRENT_TIMESTAMP")
Date getCreateTime();

@Bindable
Location getLocation();

@ManyToOne(cascade = {CascadeAction.NONE})
Device getDevice();
```

}
`

when I attempt to insert a new record of DeviceLostRecord by:
`
    public Observable<DeviceLostRecordEntity> addDeviceLostRecord(final Device device,final Location location) {

```
    DeviceLostRecordEntity newLost = new DeviceLostRecordEntity();

    newLost.getDevice().add(device);
    newLost.setLocation(location);
    return dataStore.insert(newLost).toObservable();
}
```

`

It throws exception like this:

> java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
> 
> Caused by: rx.exceptions.OnErrorNotImplementedException: table DeviceLostRecord has no column named device (code 1): , while compiling: insert into DeviceLostRecord (createTime, device, location) values (?, ?, ?)

I have no idea about the solution after googled for one and half day...

**Comment by npurushe** [comment]
Sounds like you generated the tables originally without the device column. You should clear the app data and redeploy the application which will cause the tables to be regenerated

**Comment by s1155030742** [comment]
I see. It seems the problem of 
`
    newLost.getDevice().add(device);
`

after changing it to 
`        
newLost.setDevice(device);
`

It works now, though another problem comes out. While I am inserting DeviceLostRecord
`
dataStore.insert(newLost).toObservable();
`
a unwanted insert to Device happened
(or should I ask in a new issue?) 

Anyway, I guess this issue can be closed. Thank you very much.

**Comment by npurushe** [comment]
Hi you should be able to do both, when adding to collection you should update the source object to persist the change. 

When you do `dataStore.insert(newLost).toObservable();` what's the unexpected insert that occurs? This action should insert the newLost object.

**Comment by s1155030742** [comment]
Yes it inserted the newLost object. Also, it did an insert to the device table.... , which is unwanted.

For instance, initial I have 

Device table :
- device 1

NewLost table :

after doing  `dataStore.insert(newLost).toObservable();` :

Device table :
- device 1
- device 1

NewLost table :
- NewLost

**Comment by npurushe** [comment]
If device1 is already existing in the table you should do something like:

```java
device = dataStore.findById(deviceId);
newLost.getDevice().add(device);
dataStore.insert(newLost);
```

in your original snippet looks like you create a new DeviceLostRecordEntity each time.

**Comment by s1155030742** [comment]
super helpful!!!!!!
Thank you very much
