### ISSUE TITLE
RXJava : insert API

### ISSUE THREAD

**Issue by droidekas** [requery/requery#314]
I was trying out this library cannot seem to cross this.
I am running an instrumentation test for this and I have overriden the RxSchedulers too.

my Datasource setup

```
   DatabaseSource source = new DatabaseSource(InstrumentationRegistry.getTargetContext(), Models.DEFAULT, 1);
        source.setTableCreationMode(TableCreationMode.DROP_CREATE);
        EntityModel model = Models.DEFAULT;
        Configuration configuration = new ConfigurationBuilder(source, model)
                .useDefaultLogging()
                .build();
        dataStore = RxSupport.toReactiveStore(
                new EntityDataStore<Persistable>(configuration));
```

My requery access method:

```
 @Test
    public void testBla() throws Exception {
        List<Folder> folders = DBUtils.generateDefaultFolders();
        dataStore.insert(folders).toObservable().subscribe(new Subscriber<Iterable<Folder>>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {
                throw new AssertionError(e);
            }

            @Override
            public void onNext(Iterable<Folder> folders) {

            }
        });
    }
```
My database file is always empty. However a non  Rx-Java insert seems to work fine. This might be a stupid question but i've spent 2 days combing through issues.

Am I doing something wrong?

**Comment by npurushe** [comment]
Hi this is probably not working because your test in this case is observing the result asynchronously, so the test method complete before anything happens. You should block until the subscription completes (as shown in the example test code in the commit) you can also do this using `Rx.TestScheduler`

**Comment by droidekas** [comment]
I am not asserting anything actually .I extract the database from the device and then check for the results.This should not be affected by the threads right? I somehow think I am doing something wrong in my Entity classes. Adding those too for your reference . 


```
@Entity
public interface ISong {

    @Key
    @Generated
    public int getId();

    public String getTitle();

    public String getDisplayName();

    public String getArtist();

    public String getAlbum();

    public String getPath();

    public int getDuration();

    public int getSize();

    public boolean isFavorite();

    @ManyToOne
    public Folder getFolder();
}
```

and 
```
@Entity
public interface IFolder {

    @Key
    @Generated
    public int getId();

    public String getName();

    public String getPath();

    public int getNumOfSongs();

    @OneToMany()
    public List<Song> getSongs();

    public Date getCreatedAt();
}

```

**Comment by npurushe** [comment]
Doesn't matter if you assert anything or not, you have to ensure the data is getting inserted by blocking or waiting for the subscribe call or using a rx scheduler that executes immediately on the current thread.

**Comment by droidekas** [comment]
Thanks. This solved it.
