### ISSUE TITLE
[Android] Generated classes are not found when project is run in emulator

### ISSUE THREAD

**Issue by wolkenschieber** [requery/requery#315]
Hi,

sorry to bother you, my problem is probably more a configuration issue than a library issue.

I've written some really basic app for testing this library. The code compiles fine, but if I try to run the app in the emulator, the generated classes can't be found. It seems that they are cleared before the run.

The log says following:
```
Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:assembleDebug]
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/receiver/SmsReceiver.java
Error:(11, 38) error: cannot find symbol class ReceivedMessagesEntity
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/MainActivity.java
Error:(20, 44) error: package de.comp.pingme.databinding does not exist
Error:(21, 38) error: cannot find symbol class ReceivedMessagesEntity
Error:(133, 72) error: cannot find symbol class ReceivedMessagesEntity
Error:(134, 27) error: cannot find symbol class ReceivedMessageItemBinding
Error:(144, 23) error: cannot find symbol class ReceivedMessagesEntity
Error:(152, 30) error: cannot find symbol class ReceivedMessageItemBinding
Error:(161, 38) error: cannot find symbol class ReceivedMessagesEntity
Error:(161, 81) error: cannot find symbol class ReceivedMessageItemBinding
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/PingMeApplication.java
Error:(7, 38) error: cannot find symbol class Models
Warning:View field message collides with a variable or import
/mnt/Storage/android/projects/PingMe/app/src/main/res/layout/received_message_item.xml
```

Since my google-foo didn't get me anywhere, I'd really appreciate some help.

Cheers

**Comment by npurushe** [comment]
If you're using Android Studio you may want to disable instant run temporarily and forcefully rebuild and relaunch the application.

**Comment by wolkenschieber** [comment]
Thanks for your reply. I disabled instant run through *File* → *Settings* → *Build, Execution, Deployment* → *Instant Run and uncheck Enable Instant Run*. Unfortunatelly this doesn't have any effect.

I'm getting the same error messages from above, if I clean the project and then call make or rebuild.
Strangely there aren't any errors show in the IDE afterwards.

I'm using Android Studio 2.2.2 and SDK 25. I've created a gist of my [build.gradle](https://gist.github.com/wolkenschieber/aa0ed3df5c849203c03d6affeb010e3f). The option `android.compileOptions.incremental` and `dependency.provided` were for testing as some issue here mentioned them.

I'm wondering where my `build.gradle` differs from the one given in the android example?

**Comment by npurushe** [comment]
Yeah looking at your log again it's a compilation error. What's the output of './gradlew build' from the command line? possibly you have an model error not shown in the output of your original message.

**Comment by wolkenschieber** [comment]
The build output showed following message in the terminal:

```
  symbol:   class ReceivedMessageItemBinding
  location: class MainActivity.ReceivedMessagesAdapter
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/MainActivity.java:161: error: cannot find symbol
        public void onBindViewHolder(ReceivedMessagesEntity item, BindingHolder<ReceivedMessageItemBinding> holder,
                                     ^
  symbol:   class ReceivedMessagesEntity
  location: class MainActivity.ReceivedMessagesAdapter
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/MainActivity.java:161: error: cannot find symbol
        public void onBindViewHolder(ReceivedMessagesEntity item, BindingHolder<ReceivedMessageItemBinding> holder,
                                                                                ^
  symbol:   class ReceivedMessageItemBinding
  location: class MainActivity.ReceivedMessagesAdapter
/mnt/Storage/android/projects/PingMe/app/src/main/java/de/comp/pingme/PingMeApplication.java:7: error: cannot find symbol
import de.comp.pingme.model.Models;
                                     ^
  symbol:   class Models
  location: package de.comp.pingme.model
warning: View field message collides with a variable or import
  file:///mnt/Storage/android/projects/PingMe/app/src/main/res/layout/received_message_item.xml Line:18
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Found data binding errors.
  Could not find accessor de.comp.pingme.model.ReceivedMessages.timestamp
  file:///mnt/Storage/android/projects/PingMe/app/src/main/res/layout/received_message_item.xml Line:33
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Turns out I had an error in the layout definition of my binding. I tried to format a `long` variable using `android:text="@{message.timestamp}"`. With the layout corrected the project builds fine.

Thanks for your time and patience!

**Comment by npurushe** [comment]
Great glad you found the case

**Comment by Glurt** [comment]
I'm having similar issues, I understand that this isn't a problem with the library itself but it seems that any compilation issues prevent the code generation from taking place. Meaning the original compilation issue is buried in a sea of Symbol not found errors.

Do you know if there's any way around this?

**Comment by wolkenschieber** [comment]
@Glurt Knowing that the compile errors are not written to the *Messages* view, best thing to come up with is the *Gradle Console*.
Since the build error is usually at the bottom of the output, you only have to scroll up a little to see the cause (or the affected file at least).

**Comment by Glurt** [comment]
The Gradle Console shows the same error messages as the Messages view. I think in my case there's a problem with one of my Dagger Modules or Components as that too relies on annotation processing and code generation. Is there a way to control the order in which these things are run?
