### ISSUE TITLE
Have OffsetDateTimeConverter retain offset

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#316]
- ZonedDateTimeConvrter retain zone info

Currently OffsetDateTime is stored as `Instant` with zero offset.

Besides having another hidden column storing the offset I have no idea how to implement it (maintaining backwards compatibility).

**Comment by npurushe** [comment]
This should map onto `TIMESTAMP WITH TIMEZONE` on databases that support it

**Comment by npurushe** [comment]
Unfortunately this is pretty poorly supported across different drivers. So by default everything is converted to utc, this is clarified in the javadoc for those converters.
