### ISSUE TITLE
Question: how to query for nested objects

### ISSUE THREAD

**Issue by pjakubczyk** [requery/requery#318]
Hi there. First of all thanks for such a good piece of code :)

I'm struggling with queries with one-to-many and many-to-many relations. Let's have two small classes 

``` @Entity
public class Session {
    @Key
    int id;
    String title;
    @OneToMany
    Set<Speaker> speakers;
}
```

``` @Entity
public class Speaker {
    @Key
    int id;
    String firstName;
    String lastName
    @ManyToOne
    Session session;
}
```

It's a book example of many-to-one relationship. A session can have multiple speaker. A speaker can do one session.

While I'm querying for all sessions (using RX)
`database.select(SessionEntitiy.class).get()`
I see that all sessions objects are populated fine. In theory I need to do another query for each session to fetch its speakers. Is there any option to Requery do it for me?

btw: I'd be happy to do a pull request with docs update after our discussion :)

**Comment by npurushe** [comment]
If you have a session you can the speakers belonging to it by just calling`getSpeakers()`

**Comment by pjakubczyk** [comment]
I tried but it returns an empty collection

**Comment by pjakubczyk** [comment]
I've created a test which doesn't use RX implementation and it works:
```
SessionEntity sessionEntity = new SessionEntity();
sessionEntity.setId(1);
sessionEntity.setTitle("Session title #1");

SpeakerEntity speakerEntity = new SpeakerEntity();
speakerEntity.setId(12);
speakerEntity.setFirstName("John");
speakerEntity.setLastName("Doe");

SpeakerEntity speakerEntity1 = new SpeakerEntity();
speakerEntity1.setId(13);
speakerEntity1.setFirstName("Marcy");
speakerEntity1.setLastName("Eod");


sessionEntity.getSpeaker().add(speakerEntity);
sessionEntity.getSpeaker().add(speakerEntity1);

dataStore.insert(speakerEntity);
dataStore.insert(speakerEntity1);

SessionEntity insert = dataStore.insert(sessionEntity);

SessionEntity result = dataStore.select(SessionEntity.class).get().first();

assert result.getSpeaker().size() == 2;
```

In debugger I checked that RX implementation `session.getSpeakers()` return an `ObservableSet` but I can't attach any subscriber. Any clues :)?

**Comment by pjakubczyk** [comment]
Please close the ticket. I found a bug in my data serializer.

I use same Speaker class for DB and retrofit+gson. While parsing the HTTP response went fine but there is one important thing. Gson uses fields not setter thus the `SpeakerEntitiy` proxy setter were not used. I **guess** that it's important for ORM to use setter to create a detailed plan for update/insert. 

I found it first during `upsert` call. Result in database was empty - that lead me to idea to use insert. I **guess** insert is not interested in exact plan so operation was successful. `upsert` checks that no values has been set so there is no job to do.

**Comment by npurushe** [comment]
Hi yes you are correct it's important for the getter/setter to be used when modifying the entity object. Gson modifies the private fields directly causing issues in the change detection (see #73) this is something that will be improved in an updated release. Thanks!
