### ISSUE TITLE
Add a tag on StackOverflow (and a link to my question there)

### ISSUE THREAD

**Issue by dadino** [requery/requery#323]
[I asked this](http://stackoverflow.com/questions/40422193/requery-for-android-stackoverflow-on-select) on StackOverflow, but I couldn't add a tag for Requery. Can you (or someone with enough reputation), create it?

**Comment by npurushe** [comment]
Unfortunately I'm not a big stackoverflow user so I don't have enough points to create it. Hopefully someone can!
