### ISSUE TITLE
Java getters and setters not generated for @Transient Kotlin properties

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#325]
Requery 1.0.1

Expected behavior: Generated class implements getter and setter for @Transient property and serializes the field to parcel if the entity is Parcelable. Requery will not persist this field to database.

Current behavior: Haven't got that far but presumably will throw an exception if one tries to access the nonexistent getter or setter at all.

![image](https://cloud.githubusercontent.com/assets/4589773/20024893/c032e71a-a2e9-11e6-8ec7-40e98be528a7.png)

![image](https://cloud.githubusercontent.com/assets/4589773/20024905/d61758ea-a2e9-11e6-8c44-33ec678b5cb8.png)

**Comment by consp1racy** [comment]
Parceling a transient field seems counter intuitive. Can the desired parceling behavior be controlled?

**Comment by npurushe** [comment]
Could you share your model definition? for interfaces it appears for both val/var properties a getter/setter is generated for kotlin properties

**Comment by consp1racy** [comment]
Apologies. It appears I didn't build the project after adding the property. I just hit the build button and the methods were there.
