### ISSUE TITLE
Nullability of a foreign key depends on primitivity of the relevant primary key.

### ISSUE THREAD

**Issue by mplucinski** [requery/requery#327]
I am working with requery version 1.0.1 on Android. Database is SQLite. I have following entities (details removed):

```
@Entity
abstract class Child {
    @Key @Generated
    long id;

    @ManyToOne
    Parent parent;
}

@Entity
abstract class Parent {
    @Key @Generated
    long id;
}
```

This works correctly, assuming that every child has a parent. However, if I do:
```
Child child = new Child();
dataStore.insert(child); // note that child.parent is null
```
and do a select later:
```
Child selected = dataStore.select(Child.class).get().toList().get(0);
```
I expect, that `selected.getParent()` returns `null`. However, it returns `Parent()` (default-constructed instance). I am not 100% sure if it's a bug, but I could not find any documentation related to this behavior.

After some debugging, I found out that, internally, the type of a foreign key is taken from the type of `Parent.id` field, and since this field is primitive, the code that reads the foreign key, does not check if the result value was null.

As a workaround, chainging type of `Parent.id` to` Long` (boxed), with `@Column(nullable=false)` attribute, solved the problem (the `nullable` parameter seems to be not taken into account, when type of the foreign key is being established). 

Also, just for the record, as far as I see, `EntityReader.fromResult` in line 538 skips complete code block if the value was `null`. This makes me wonder, if there is some scenario where not assigning the `null` to the `Child.parent` may cause troubles (though as for now, my usecases seem to work correctly).

**Comment by npurushe** [comment]
Hi yes correct the type of the field determines the default nullability of the column, but it's overridable through the annotation. The reason a default object is created is because it's used to hold the key value, hope that makes sense.
