### ISSUE TITLE
Tables are not getting dropped

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#330]
Hi there,

with a minimal sample project, the tables are not getting dropped when I modify the schema, even though I set the the table creation mode to `DROP_CREATE`. Please download the full sample project [here](https://github.com/requery/requery/files/579033/RequeryTest.zip).
Steps to recreate:
1. Simply run and install
2. Add any column to `Customer.class`
3. Rerun

I then get the exception `Caused by: android.database.sqlite.SQLiteException: table Customer has no column named ...`
This my sample application class

```Java
public class TestApplication extends Application {
  private SingleEntityStore<Persistable> dataStore;

  @Override
  public void onCreate() {
    super.onCreate();
  }


  SingleEntityStore<Persistable> getData() {
    if (dataStore == null) {
      DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 1);
      source.setTableCreationMode(TableCreationMode.DROP_CREATE);

      Configuration configuration = source.getConfiguration();
      dataStore = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
    }
    return dataStore;
  }
}
```

My sample entity
```Java
@Entity
public abstract class Customer{
  @Key @Generated
  long id;
  String firstName;
  String lastName;
  String alias;
}
```

My sample activity
```Java
public class MainActivity extends AppCompatActivity {

  SingleEntityStore<Persistable> reactiveEntityStore;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    reactiveEntityStore = ((TestApplication)getApplication()).getData();
    final CustomerEntity customer = new CustomerEntity();
    customer.setFirstName("John");
    customer.setLastName("Smith");
    Log.d("MainActivity", reactiveEntityStore.insert(customer).toBlocking().value().toString());
  }
}
```

Am I creating the datastore incorrectly? I was basically copying it from the requery Android example. Any help would be appreciated!

Best regards

**Comment by npurushe** [comment]
Hi you need to increment the schema version of the database after making changes in order for the table generation to occur

**Comment by Agraphie** [comment]
Hi,

thanks for your reply. Then I didn't understand this mode correctly, I thought the schema version needs to be increased for a possible migration to start. Wouldn't it be beneficial to have a switch for automatically dropping the tables without increasing the schema version? For someone who is new to requery and just playing around with it or for someone who is heavily developing the model, it might be a bit cumbersome to always increase the schema version after a small change.

**Comment by npurushe** [comment]
The current table creation ties into Android's `SQLiteOpenHelper` which relies on the schema version to trigger the `onUpgrade` which performs the upgrade. I guess you're asking to drop the tables on every application start, I agree there are cases where that is useful, I think you can accomplish that with something like:

```java
if (BuildConfig.DEBUG) {
   context.deleteDatabase("dbName");
}

// create database source
DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 1);
```

**Comment by Agraphie** [comment]
Hi,

thanks very much for this. Not sure why I was looking for requery to do this for me, it's simple enough as you said.
