### ISSUE TITLE
Transaction savepoint support

### ISSUE THREAD

**Issue by MikeNicholls** [requery/requery#331]
I'm looking for a way to set and rollback to savepoints during a transaction.  I see mention of savepoints in a couple of the connection classes, but it looks like it might currently be there only because it's part of the java.sql.Connection interface.  Is there a way to access the current connection object directly from an entity store?

**Comment by npurushe** [comment]
Hi yes, you can get the current `EntityDataStore.transaction()` instance cast it to `ConnectionProvider` and from that access the underlying JDBC connection instance. The connection is not exposed directly in order to provide future support for non-JDBC databases.
