### ISSUE TITLE
Working with existing database Example

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#333]
Hi i have recently started to use requery, I have a database called wayu.sqlite in asset folder previously populated. But I don't know how to pass name to DatabaseSource.
 I have tried:

 `new DatabaseSource(this, Models.DEFAULT, this.getApplicationInfo().dataDir + "/databases/"+ "wayu.sqlite", 19)`

and

` new DatabaseSource(this, Models.DEFAULT,"wayu.sqlite", 19)`

Can i get an example on how to do this?

also i'm getting : 
**Could not find class 'io.requery.sql.ManagedTransaction', referenced from method io.requery.sql.ThreadLocalTransaction.begin**

**Comment by npurushe** [comment]
Android doesn't support loading a sqlite database from the apk's assets directly. You need to copy the database into the app's data directory on first run and then use it from there. See [this](http://stackoverflow.com/questions/2605555/android-accessing-assets-folder-sqlite-database-file-with-sqlite-extension/5949629#5949629) question.

`Could not find class 'io.requery.sql.ManagedTransaction', referenced from method io.requery.sql.ThreadLocalTransaction.begin`

is just a warning, the library will run fine on android.
