### ISSUE TITLE
Not able to set date to current time

### ISSUE THREAD

**Issue by s1155030742** [requery/requery#334]
I am going to have a create_time every table in my database.

For instance, one of my table is : 
`
@Entity
public interface DeviceLostRecord  extends Observable, Parcelable, Persistable {

    @Key
    @Generated
    int getId();

    @Column(value = "now()")
    Date getCreateTime();

    @Bindable
    Double getLatitude();

    @Bindable
    Double getLongitude();

}
`

value in @Column was "now()" according to instruction in 
[requery](http://requery.github.io/javadoc/io/requery/Column.html)

I follow the above and got 

Syntax error bug: 

11-10 11:55:24.063 17125-17125/com.r_guardian.antiloss E/SQLiteLog: (1) near "(": syntax error

java.sql.SQLException: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: create table DeviceLostRecord (id integer primary key autoincrement not null, createTime date default now(), device integer, latitude real, longitude real, foreign key (device) references Device (id) on delete cascade)

Then, I try @Column(value="CURRENT_TIMESTAMP") and I got null...

**Comment by npurushe** [comment]
Hi this is database specific for sqlite the function to get the current time is `date('now')` https://www.sqlite.org/lang_datefunc.html
