### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by Wanimal** [requery/requery#335]
With Rxjava version 2.0

Log:
The type rx.Single cannot be resolved. It is indirectly referenced from required .class files

**Comment by npurushe** [comment]
rx.Single is from RxJava 1.0, it's referenced in the compiled code but not a required dependency. Can you share what requery version, Java version and IDE you are using?

**Comment by Wanimal** [comment]
requery version:1.0.1
Java version:1.8
 IDE:Android Studio 2.2.2

**Comment by npurushe** [comment]
Do you call `toSingle()` or use any of the classes in `io.requery.rx` ? For RxJava 2.0 you should use only the classes in `io.requery.reactivex` and just `single()` on result objects

**Comment by Wanimal** [comment]
yes, I use the
`import io.requery.rx.SingleEntityStore;`
remove is ok. Thank you for reminding me.

**Comment by npurushe** [comment]
Great!
