### ISSUE TITLE
Chaining conditions with "or" and "and"

### ISSUE THREAD

**Issue by metawave** [requery/requery#338]
I didn't manage to implement following query.

```sql
select * from person p
where p.city = 'New York' and (p.name = 'Miller' or p.birthName = 'Miller')
```

```java
data.select(Person.class)
.where(PersonEntity.CITY.eq("New York").and(PersonEntity.NAME.eq("Miller").or(PersonEntity.BIRTH_NAME.eq("Miller")))).get()
```

since I've put the OR expression inside one .and() call, I'd expected to generate the parentheses around the OR expression chain.

**Comment by npurushe** [comment]
You have chained the and part of the query as part of `where p.city = 'New York'` hence there won't be any parentheses generated, instead you should add it after closing the where part (note the parentheses location)

e.g.
`data.select(Person.class)
                .where(PersonEntity.CITY.eq("New York")).and(Person.NAME.eq("Miller").or(PersonEntity.BIRTH_NAME.eq("Miller"))).get()`

**Comment by metawave** [comment]
Looks a bit odd, to write
```kotlin
data.select(Person.class).where(condition).and(condition2).orderBy....
```

I'd expected to have all where-conditions as one where function's parameter. Like in QueryDSL or JOOQ, where `condition1.and(condition2).or(condition3)` doesn't generate the same sql as `condition1.and(condition2.or(condition3))`, where the first would generate `condition 1 AND condition 2 OR condition3`, and the second would generate `condition1 AND (condition2 OR condition3)`. The result would be totally different.

It get's messy when the where conditions are constructed in code (pseudo code, won't compile).

```kotlin
val whereClause = PersonEntity.CITY.eq("New York");
if (searchForName) {
   whereClause.and(PersonEntity.NAME.eq(searchTerm).or(PersonEntity.MAIDEN_NAME.eq(searchTerm))
}
val searchResult = data.select(Person.class).where(whereClause).get().toList()
```

so my query wouldn't be possible to create, which is quite a bummer.

**Comment by npurushe** [comment]
1.0.2 contains this change
