### ISSUE TITLE
A problem with inserting using upsert operation

### ISSUE THREAD

**Issue by stbychkov** [requery/requery#339]
I've created a simple entity:
```java
@Entity
public abstract class AbstractFirstModel {
    @Key
    Integer mId;

    public void setId(int firstModelId){
        mId = firstModelId;
    }
}
```

Then I created a test for inserting this model using upsert operation:
```java
@Test
    public void tryInsertModel(){
        int firstModelId = 1;

        FirstModel firstModel = mEntityStore.findByKey(FirstModel.class, firstModelId).toBlocking().value();
        assertNull(firstModel);

        firstModel = new FirstModel();
        firstModel.setId(firstModelId);

        FirstModel insertedModel = mEntityStore.upsert(firstModel).toBlocking().value();
        assertNotNull(insertedModel);

        // this test should fail here, but entity store still doesn't contains any models
        assertSame(mEntityStore.select(FirstModel.class).get().toList().size(), 0);

        insertedModel = mEntityStore.insert(firstModel).toBlocking().value();

        assertNotNull(insertedModel);
        // after calling insert function, entity store has 1 model
        assertNotSame(mEntityStore.select(FirstModel.class).get().toList().size(), 0);
    }
```
All assertions of this test **passed**.
When we use upsert on some models like this, entity store **doesn't save it**. I haven't any exceptions or insert records in the log. _Insert operation work succesfully._ 

Requery version: 1.0.1
Java version: 1.8
IDE: Android Studio 2.2

Am I doing something wrong?

**Comment by npurushe** [comment]
Hi you shouldn't implement your own setId method, it's generated for you automatically and is used in the generated code to track changes in the object.

**Comment by stbychkov** [comment]
It works, thank you so much.

**Comment by Agraphie** [comment]
I have the same problem. I cannot solve this by using a generated Id, as I am getting a generated Id from the server. Is there any other way to fix this?
