### ISSUE TITLE
Self-referencing / recursive foreign keys in Entity

### ISSUE THREAD

**Issue by polmabri** [requery/requery#345]
Hey,

is it possible to use recursive foreign keys in an entity?

Kotlin example:

```Kotlin
@Entity
interface Category {

    @get:Key
    @get:Generated
    val id: Int
    var title: String

    @get:ManyToOne
    var parent: Category?

    @get:OneToMany(mappedBy = "parent")
    var children: Set<Category>
}
```

I also tried some other combinations, but i always got this warnings:
```
warning: 2 mappings found for: com.example.model.CategoryEntity.parent -> com.example.model.CategoryEntity
warning: Circular Foreign Key reference found between com.example.model.CategoryEntity and com.example.model.CategoryEntity
```

**Comment by npurushe** [comment]
Hi that is just a warning you can have a self referencing key and it will work.

**Comment by AllenVork** [comment]
@Entity(name = "PersonProxy")
public interface Person extends Persistable {

    @OneToMany(mappedBy = "owner", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Phone> getPhoneNumberList();
}

@Entity
public interface Phone extends Persistable {

    @ManyToOne
    Person getOwner();
}

I got an error: `Error:(21, 12) 警告: 2 mappings found for: com.zhangruofan.requery.model.PhoneEntity.owner -> com.zhangruofan.requery.model.PersonProxy`

**Comment by npurushe** [comment]
The multiple mappings message is a warning not an error. Are you sure it is listed as an error? what's your environment?

**Comment by AllenVork** [comment]
My projects runs successfully. Here is my build.gradle:
```gradle
    compile "io.reactivex.rxjava2:rxjava:$rxjava2_version"
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.requery:requery:1.0.2'
    compile 'io.requery:requery-android:1.0.2'
    annotationProcessor 'io.requery:requery-processor:1.0.2'


    lintOptions {
        abortOnError false
    }
```
I just wanna know why i have this warning and how to avoid it.
