### ISSUE TITLE
Query condition on custom type

### ISSUE THREAD

**Issue by OHoussein** [requery/requery#348]
I have an array column that conveterd into String with a converter, the array is converted like this: item1&item2&item3 .
I want to add a **contain** condition in this array but I didn't find a way to do it.
Can I add a custom condition? or query the original stored column before calling the converter ?

**Comment by npurushe** [comment]
I think you mean you have a string column that you convert to an array in your java model, correct? in that case you pass an array to the condition and the converter you specified in your model will be used.

**Comment by OHoussein** [comment]
Thank you for your answer, but I want to select the rows who have a specific element in their array.

**Comment by npurushe** [comment]
You can use normal sql operators such as `like` to match the string, however if you need to do this you may want to revisit your schema design and use a separate table instead. Some databases like postgres support array types for which you could define custom mappings for but it's database specific.
