### ISSUE TITLE
String key

### ISSUE THREAD

**Issue by Helmt89** [requery/requery#349]
Hello! I have this models:

@Entity
public interface RQCourse extends Persistable {

    @Key // i can't integer id
    String getEntityId();

    String getName();

    boolean getIsFree();

    @OneToMany(mappedBy = "course", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<RQTopic> getTopics();
}

and

@Entity
public interface RQTopic extends Persistable {

    @Key  // i can't integer id
    String getEntityId();
    

    @ManyToOne
    RQCourse getCourse();

    void setCourse(RQCourse person);

    @OneToMany(mappedBy = "topic", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<RQTopic> getSubTopics();

    @ManyToOne
    RQTopic getTopic();

    void setTopic(RQTopic person);
}

 mDataBase.insert(entity).subscribe(courseAction);

Data can be [course][List topic][List subtopic]

When i insert course in base, I can't add topics in course. When i use integer id, this work. but I can't use integer id. How  i can resolve this issue?

**Comment by npurushe** [comment]
How are you setting the id? you need to set the id before you insert the entity.

**Comment by Helmt89** [comment]
Yes. I have id from server, and i need set the id before insert/update the entity.

**Comment by npurushe** [comment]
What's the actual error you receive? please provide a stack trace thanks

**Comment by Helmt89** [comment]
I insert entity in dataBase  
![image](https://cloud.githubusercontent.com/assets/13830733/20724781/3a8df8d2-b678-11e6-981f-c83a55e5d1fd.png)

 I have course and nested topiсs.

mDataBase.insert(entity).subscribe(courseAction);
   Action1 courseAction = new Action1<RQCourse>() {
                @Override
                public void call(RQCourse rqCourses) {

                }
            };

But when i have call in courseAction, a have't nested topics.  And topics is't added in data base.

![image](https://cloud.githubusercontent.com/assets/13830733/20724934/e3e9cf5a-b678-11e6-8388-f1dfce4b0863.png)

When i use  generate int key instead string key, i have nested topics in course. I think this problem with string key

**Comment by Helmt89** [comment]
And log:
beforeExecuteQuery sql: select entityId, isFree, name from RQCourse where entityId = ? 
 I/requery: afterExecuteQuery
 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
 I/requery: beforeExecuteUpdate sql: insert into RQCourse (entityId, isFree, name) values (?, ?, ?)
 I/requery: afterExecuteUpdate
 I/requery: beforeExecuteQuery sql: select entityId, isFree, name from RQCourse where entityId = ? 
 I/requery: afterExecuteQuery
 I/requery: beforeExecuteUpdate sql: insert into RQCourse (entityId, isFree, name) values (?, ?, ?)
 I/requery: afterExecuteUpdate
 I/requery: beforeExecuteQuery sql: select entityId, course, description, isFree, isRead, shortDescription, title, topic from RQTopic where course = ? 
 I/requery: afterExecuteQuery
I/requery: beforeExecuteUpdate sql: update RQTopic set entityId = ? ,course = ? ,description = ? ,isFree = ? ,isRead = ? ,shortDescription = ? ,title = ? where entityId = ? 
 I/requery: afterExecuteUpdate
 I/requery: beforeExecuteUpdate sql: update RQTopic set entityId = ? ,course = ? ,description = ? ,isFree = ? ,isRead = ? ,shortDescription = ? ,title = ? where entityId = ? 
 I/requery: afterExecuteUpdate
 I/requery: beforeExecuteUpdate sql: update RQTopic set entityId = ? ,course = ? ,description = ? ,isFree = ? ,isRead = ? ,shortDescription = ? ,title = ? where entityId = ? 
 I/requery: afterExecuteUpdate
 I/requery: beforeExecuteQuery sql: select entityId, course, description, isFree, isRead, shortDescription, title, topic from RQTopic where course = ?

**Comment by npurushe** [comment]
Thanks for the detailed report. I think your issue should be fixed with #355
