### ISSUE TITLE
Table joins

### ISSUE THREAD

**Issue by echistyakov** [requery/requery#35]
How do joins work in requery? Let's say my schema has 3 entities: Sailor(id), Boat(id, color), Reservation(sid, bid, date). Is there a way to get all Sailors who reserved a red Boat?
I see that requery has a Join interface, but I couldn't find a way to join tables on foreign keys.

**Comment by npurushe** [comment]
Hi yes you can have something like:

```java
@Entity
public class AbstractBoat {
    @Key int id;
    String color;
}
@Entity
public class AbstractSailor {
    @Key int id;
}
@Entity
public class AbstractReservation {
    @ForeignKey(references = AbstractBoat.class)
    int boatId;
    @ForeignKey(references = AbstractSailor.class)
    int sailorId;
    Date date;
}
```
and then the query:
```java
Result<Sailor> sailors = data.select(Sailor.class)
            .join(Reservation.class).on(Sailor.ID.eq(Reservation.SAILOR_ID))
            .join(Boat.class).on(Reservation.BOAT_ID.eq(Boat.ID)).
              where(Boat.COLOR.eq("red")).get();
```
data is `EntityDataStore` created from your entity model, which is generated. See the example project. From the result you can iterate it, or convert it to a list and much more.
Hope that answers your question, thanks!

**Comment by echistyakov** [comment]
Thank you for the quick response! The above query, however, results in a compilation error because `eq()` expects an Integer but gets a QueryAttribute instead. Am I missing something?

**Comment by npurushe** [comment]
Hi this was just fixed in the beta4 version :) if you update it should work.

**Comment by echistyakov** [comment]
The new version fixed the problem. Thank you!

**Comment by npurushe** [comment]
Great thanks for reporting!

**Comment by consp1racy** [comment]
How would one do it if it was `Sailor sailor` instead of `int sailorId`?
