### ISSUE TITLE
Provide a Reactor based API

### ISSUE THREAD

**Issue by sdeleuze** [requery/requery#352]
In addition to RxJava 1 and 2 APIs, it would be nice if Requery could provide an API based on [`Flux`](https://projectreactor.io/core/docs/api/reactor/core/publisher/Flux.html)  and [`Mono`](https://projectreactor.io/core/docs/api/reactor/core/publisher/Flux.html) types from Reactor Core (these types extends Reactive Streams `Publisher`). More information on [Reactor by example InfoQ article](https://www.infoq.com/articles/reactor-by-example).

It could enable seemless integration with the upcoming Spring Framework 5 and Spring Boot 2.0.

**Comment by sdeleuze** [comment]
I have a project where I would like to experiment with Requery + Reactor. Do you think I could start by porting the current RxJava 2 support to Reactor as an external dependency or does it require some modification on Requery itself?

**Comment by npurushe** [comment]
For the EntityStore api, yes you would be able to do that. Requery also provides some convenience functions on the `Result` type to convert the results into observables/streams which would require changes in the library. I looked at Reactor API and it's similar enough to RxJava that it should be easy enough to support.

**Comment by sdeleuze** [comment]
Awesome !!!!

**Comment by mduesterhoeft** [comment]
@sdeleuze I am wondering if the implementation of [`io.requery.reactor.ReactorEntityStore`](https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/reactor/ReactorEntityStore.java) is actually correct.

e.g.
```java
@Override
    public <E extends T> Mono<Iterable<E>> insert(final Iterable<E> entities) {
        return Mono.fromCallable(new Callable<Iterable<E>>() {
            @Override
            public Iterable<E> call() throws Exception {
                return delegate.insert(entities);
            }
        });
    }
```

`delegate.insert(entities);` is the call to the blocking api.

Reading the [reactor documentation on this topic](http://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking) I would assume we need something like - where we push the blocking part to a separate thread:

```java
@Override
    public <E extends T> Mono<Iterable<E>> insert(final Iterable<E> entities) {
        return Mono.fromCallable(new Callable<Iterable<E>>() {
            @Override
            public Iterable<E> call() throws Exception {
                return delegate.insert(entities);
            }
        }).subscribeOn(Schedulers.elastic());;
    }
```
