### ISSUE TITLE
bindBlobLiteral on Android fails if there are more than one variable to substitute

### ISSUE THREAD

**Issue by watercrossing** [requery/requery#353]
When a query contains more than one binary field that is filled by `bindBlobLiteral` method (https://github.com/requery/requery/blob/master/requery-android/src/main/java/io/requery/android/sqlite/BasePreparedStatement.java#L97), the first field is filled correctly, but any subsequent call fails.

The issue is that the method searches for literal question marks in the statement, but then substitutes the `?` in the query for the binary blob.  However it does not keep track of how many question marks have been substituted. If a prepared statement initially had 2 `?`s, if one is substituted, the attempt to substitute the second one fails as there is only one `?` left.

**Comment by watercrossing** [comment]
Also, how does one write decent tests for this?

**Comment by npurushe** [comment]
Thanks for reporting, there is a centralized testing module requery-test FunctionalTest contains most of the base tests that are run on all platforms
