### ISSUE TITLE
Incorrect prepare of statement when using in query SQL of bigger one BLOB (UUID)  arguments

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#358]
Indexes for arguments after record of the first BLOB of an argument, become incorrect. In case of record of an argument check of an index happens by the "actual" quantity "?" in a prepared statement.

SynergetRtspChannel.PARENT_ID - UUID
SynergetRtspChannel.EXT_ID - UUID

`SynergetRtspChannel currentChannel = dataStore.select(SynergetRtspChannel.class).where(SynergetRtspChannel
.DELETED.eq(false)).and(SynergetRtspChannel.PARENT_ID.eq(config.getId()))
.and(SynergetRtspChannel.EXT_ID.eq(channel.getExtId())).get().firstOrNull();`

There is a damage of query SelectResult -> preparedStatement -> sql:
x'37756CBBF13949C295AB3B3A5711EC74'elect id, active, creation_date, deleted, ext_id, host, last_modified_date, name, parent_id, parent_table, password, path, port, state, transport_type, username, video_wall from synerget_rtsp_channel where deleted = ? and parent_id = x'D0541F03BBB411E6ABFB7D4401C2F1C8' and ext_id = 

If to use one UUID parameter that everything is OK

**Comment by npurushe** [comment]
This looks like the same issue as #353 which should be fixed in the next update

**Comment by vmitiaev** [comment]
I also assumed that this issue is already solved, to pety compiled and checked for versions with the last commit [41103fe](https://github.com/requery/requery/tree/41103feaeda163cb6c3c45b86263ae2c6d1ccabb). But the issue repeated. I will try soon after to check once again.

**Comment by vmitiaev** [comment]
Has double-checked on the version with the last commit, the issue exists

**Comment by npurushe** [comment]
The change should resolve the issue, it's not possible with the new change for the uuid argument to be inserted at the beginning of the string as posted originally. Please retry thanks.

**Comment by vmitiaev** [comment]
Sorry. Repeated once again, there is a project continued to use the old requery-android version from gradle cache, but not the version with the last commits.
