### ISSUE TITLE
Initial setup for using RxJava 2 version

### ISSUE THREAD

**Issue by VasileUngureanu** [requery/requery#360]
Hi, i read that library support RxJava 2 but i cannot find documentation how to initialize it!
Thanks!

**Comment by VasileUngureanu** [comment]
Hmm... Strange! For example SingleEntityStore is only in io.requery.rx. I use version 1.0.2

**Comment by npurushe** [comment]
Use the following api to create a ReactiveStore instance: `io.requery.reactivex.ReactiveSupport.toReactiveStore`
the class names are not necessarily 1:1 but all the fundamental operations are the same
