### ISSUE TITLE
SQLConnection Object leak

### ISSUE THREAD

**Issue by nikhil-thakkar** [requery/requery#363]
I'm using requery in one of my projects. I found this issue wherein I opted for the "Don't Keep Activities" in Developer options.
I query the database using requery and attach a subscriber(I'm using rxjava) to it in Activity's onCreate and unsubscribe it in onDestroy. When I move from one Activity to another, the following log is printed in the console though sometimes, "A SQLiteConnection object for database '**path to my database**' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed." 
Also when coming back from another activity and adding a single record in db, triggers onNext twice, as I see it in logs(I'm using Frodo to log rx).
Please let me know if this is a real problem or I'm doing something wrong.
By the way, thanks for such a awesome library.. :).

**Comment by npurushe** [comment]
Is this on a query or save/delete operation?

**Comment by nikhil-thakkar** [comment]
So the query thing is causing the error log.. 'A SQLiteConnection object for database 'path to my database' was leaked!'.
After I write a single record (I'm using SelfObservable) to db, the onNext is fired twice for the same record.
This is only observed, sometimes, when I opted for the "Don't Keep Activities" in Developer options otherwise it works as intended.
Hope that helps.

**Comment by Glurt** [comment]
I've noticed this too but I'm not using "Don't Keep Activities", at first I thought it was because I wasn't properly unsubscribing from the sequence and therefore keeping a reference to the database somehow but that doesn't seem to be it.

**Comment by npurushe** [comment]
How are you using the `Result` type in your observable? You should close the result if you use it's iterator, the built in functions such as `toMap` do this automatically.

**Comment by Glurt** [comment]
In my case I'm simply checking if something exists and creating and inserting it if not, the result of the insert is ignored as I'm just returning a Completable.

````
return datastore.getAnonymousAccount()
                .switchIfEmpty(Maybe.defer(() -> Maybe.fromSingle(createAnonymousAccount())))
                .flatMapCompletable(account -> {
                    if (account == null) {
                        return Completable.error(new NullPointerException());
                    }

                    return Completable.complete();
                });
````

Maybe it's something to do with the way I'm inserting entities:

````
    /**
     * Upserts an entity and returns that entity
     */
    @Override
    public <E extends Thing> E put(final E entity) {
        return putSingle(entity)
                .blockingGet();
    }

    /**
     * Upserts an entity and returns that entity
     */
    @Override
    public <E extends Thing> Single<E> putSingle(final E entity) {
        return dataStore.toBlocking()
                .runInTransaction(() -> dataStore.upsert(entity));
    }
````
