### ISSUE TITLE
SqlCipherDatabaseSource delete doesn't delete @OneToMany table relations

### ISSUE THREAD

**Issue by magillus** [requery/requery#364]
Hello,
I noticed that when using `SqlCipherDatabaseSource` and calling delete on entity that have relation to other entity by `@OneToMany` the related entities are not deleted.
When using `DatabaseSource` it does delete the related entities.

When I get a chance I will prepare sample project.

**Comment by npurushe** [comment]
Thanks for reporting. This is most likely because foreign key support is not turned on in SqlCipher

**Comment by magillus** [comment]
Thank you!

**Comment by magillus** [comment]
While trying to reproduce issue #386 and creation of the sample project I noticed that this issue is still active in 1.1.0 and 1.1.1
here is link to example project
https://github.com/magillus/SqlQuery102_to_110UpdateBug
