### ISSUE TITLE
Constraint exception when inserting

### ISSUE THREAD

**Issue by greenrobot-team** [requery/requery#37]
I am trying to write a performance test for your library, but currently fail to insert elements due to constraint exceptions. I feel like I do not understand correctly how to insert/update existing entity objects.

The code affected is in greenrobot/android-database-performance#7.

The entities are generated like:
```    
protected static SimpleEntityNotNull createEntity(long id) {
        SimpleEntityNotNull entity = new SimpleEntityNotNull();
        entity.setId(id);
        entity.setSimpleBoolean(true);
        entity.setSimpleByte(Byte.MAX_VALUE);
        entity.setSimpleShort(Short.MAX_VALUE);
        entity.setSimpleInt(Integer.MAX_VALUE);
        entity.setSimpleLong(Long.MAX_VALUE);
        entity.setSimpleFloat(Float.MAX_VALUE);
        entity.setSimpleDouble(Double.MAX_VALUE);
        entity.setSimpleString("greenrobot greenDAO");
        byte[] bytes = { 42, -17, 23, 0, 127, -128 };
        entity.setSimpleByteArray(bytes);
        return entity;
    }
```

Then they are inserted like
```
DatabaseSource source = new DatabaseSource(getApplication(), Models.DEFAULT, DATABASE_VERSION);
Configuration configuration = new ConfigurationBuilder(source, Models.DEFAULT).build();
BlockingEntityStore<Object> data = new EntityDataStore<>(configuration).toBlocking();

// TODO: NOT NULL constraint failed: SimpleEntityNotNull.simpleByte
data.insert(entities.get(i)); // entites = List<SimpleEntityNotNull>
```

I saw that in other issues (#32, #33) inserting entities was done pretty much the same. As the documentation is spotty in that regard I hope you can point me into the right direction.

**Comment by greenrobot-team** [comment]
Oops, here is one stacktrace: http://pastebin.com/x9EVxBmn

**Comment by npurushe** [comment]
Hi thanks for reporting. The problem is there is primitive mapping for byte yet, simple to fix will be added tomorrow.

**Comment by npurushe** [comment]
Please retry with 1.0.0-beta5

**Comment by greenrobot-team** [comment]
Great, is working now. Thank you for supporting this!

**Comment by greenrobot-team** [comment]
When trying to `data.update(entity)` the above entity it fails with
`io.requery.PersistenceException:      java.sql.SQLException: unhandled type -6`

Stacktrace: https://gist.github.com/greenrobot-team/346d2aaa3f32dc8c7b8e

It works fine when removing the `byte` field from the model class.

Guess you overlooked something when adding support for `byte´?

**Comment by npurushe** [comment]
Right looks like there is one more issue there, will fix today
