### ISSUE TITLE
Is it possible to get r.x.Observable in version 1.1.0?

### ISSUE THREAD

**Issue by contrudar** [requery/requery#370]
Hello! In the previous versions of your library we could get rx.Observable like that:

`cityEntityDataStore.select(City.class).get().toObservable();`

With version 1.1.0 you updated an Android example and added ReactiveEntityStore + RxJava2.

Is there a way to use rx.Observable from RxJava1 and requery 1.1.0?

Thanks in advance.

**Comment by npurushe** [comment]
Yes RxJava 1.0 is still supported you need to make sure `cityEntityDataStore` is typed as 'io.requery.rx.SingleEntityStore' when referencing it. The previous version of the examples actually still work with the current version.
