### ISSUE TITLE
toObservable not working after 1.1.0

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#376]
Hi,
I updated to 1.1.0, but after updating wherever I had defined toObservable and toSelfObservable, it showed these methods could not be referenced. I have defined my data variable as KotlinEntityDataStore. What changes are required to make them working again?

**Comment by contrudar** [comment]
I've already asked similar question, check out the answer here https://github.com/requery/requery/issues/370

**Comment by npurushe** [comment]
Thanks for reporting this is a bit of gap with the Kotlin library after changes to 1.1.0. Will provide an update soon so that both RxJava 1.0 and RxJava 2.0 methods are visible in Kotlin as well
