### ISSUE TITLE
Use this project with Maven Pom.xml

### ISSUE THREAD

**Issue by JarekToro** [requery/requery#378]
I can't find away to add the Annotation Processor to my POM.xml.

**Comment by JarekToro** [comment]
To Clarify, I added this to my POM.xml. But its not generating anything.

```XML
 <dependency>
            <groupId>io.requery</groupId>
            <artifactId>requery-processor</artifactId>
            <version>1.0.0</version>
</dependency>
```

**Comment by npurushe** [comment]
How are you building it? from an IDE, if so it may require additional steps see https://immutables.github.io/apt.html

**Comment by npurushe** [comment]
Closing for now, hope that resolved your issue
