### ISSUE TITLE
Passing entities via Bundle in Android

### ISSUE THREAD

**Issue by nekdenis** [requery/requery#381]
If we pass any entity object as Serializable to Bundle than we are unable to use getters after restoring because Proxy is null (because it is "transient"). 
So maybe is better to disallow to call serialization mechanism?

**Comment by npurushe** [comment]
You should avoid default java serialization in Android. The recommended way is to pass only the object's key in the bundle (usually an int or String) and then retrieve the object later using the key with `data.findByKey`
