### ISSUE TITLE
No class generation

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#383]
Hi there,

would it be possible to instead of generating classes from (abstract/interface/normal) classes to just put the generated code in the original class?
Say I have a domain class `User`. Instead of generating a class `UserEntity`, could requery just modify the original class `User`? Similar in a way how Lombok does it.
I'm not quite familiar with code generation, so sorry if this is a stupid quesiton.

Best regards

**Comment by npurushe** [comment]
It's not possible to change the original source code, Lombok works through bytecode manipulation. This project is preferring source code generation since it's easier to debug and more flexible, however bytecode manipulation maybe a possibility in a future version.
