### ISSUE TITLE
Rxjava2

### ISSUE THREAD

**Issue by AllenVork** [requery/requery#384]
It's strange that you use both rxjava2 and rxjava1.In my Android project,i just compile the rxjava2 then I get an error when i use `            dataStore = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration), Schedulers.newThread());
` .It tells me to use rx.Scheduler instead of io.reactivex.Scheduler.

**Comment by AllenVork** [comment]
![image](https://cloud.githubusercontent.com/assets/5970517/21479206/4ac5fde2-cb8d-11e6-9896-0093f8970c27.png)

**Comment by Wanimal** [comment]
ReactiveSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));

**Comment by AllenVork** [comment]
@Wanimal I know this method.I just use SingleEntityStore as the readme.md tells me.You mean SingleEntityStore is used for Rxjava1 and ReactiveEntityStore is used for Rxjava2 ?

**Comment by Wanimal** [comment]
yes

**Comment by AllenVork** [comment]
ok,thx.

**Comment by AllenVork** [comment]
I got another question.I'm using SingleEntityStore.
```java
   //non-blocking method
    @Override
    public <E extends T> Single<Void> delete(final E entity) {
        return Single.fromCallable(new Callable<Void>() {
            @Override
            public Void call() {
                delegate.delete(entity);
                return null;
            }
        }).subscribeOn(subscribeOn);
    }

  //blocking method
     @Override
    public <E extends T> Deletion<Scalar<Integer>> delete(Class<E> type) {
        return delegate.delete(type);
    }
```
we can see it the delete method has blocking and non-blocking method.But we can see the query method:
```java
    @Override
    public Selection<Result<Tuple>> select(Set<? extends Expression<?>> expressions) {
        return delegate.select(expressions);
    }
```
it has only blocking method.Why?

**Comment by npurushe** [comment]
To clarify:
RxJava 1.0 support is in `io.requery.rx`
RxJava 2.0 support is in the package `io.requery.reactivex`

For the later those are 2 different delete overloads, it's not about blocking vs non-blocking,
1) The first is you have an entity and want to delete it `delete(x).subscribe(...)`
2) The second is you want to make a delete query e.g. `delete(X.class).where(<some condition>).get().subscribe(...)`

The query methods return `Result` (multiple values) or `Scalar` (single value), these are lazily evaluated, they can be blocking or non-blocking. Both have Rx extension methods such as observable(), single() etc. E.g. [ReactiveResult](http://requery.github.io/javadoc/io/requery/reactivex/ReactiveResult.html)

**Comment by AllenVork** [comment]
@npurushe you are right.But I'm using Rxjava1's SingleEntityStore,the select method has no method such as single() and observable().

**Comment by npurushe** [comment]
For RxJava 1.0 the names are slightly different [http://requery.github.io/javadoc/io/requery/rx/RxResult.html](RxResult) the name is toObservable().
