### ISSUE TITLE
Models class not generated with KAPT2

### ISSUE THREAD

**Issue by NeverwinterMoon** [requery/requery#385]
I've been using `Kotlin 1.0.5` but also tried with `1.0.4` just to be sure - in both cases Requery does not generate any classes.

Parts of my Gradle build file:

```
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

kapt {
  generateStubs = true
}

// ...

dependencies {
  // ...
  compile 'com.google.dagger:dagger:2.8'
  kapt 'com.google.dagger:dagger-compiler:2.8'

  compile "io.requery:requery:$requery"
  compile "io.requery:requery-android:$requery"
  compile "io.requery:requery-kotlin:$requery"
  kapt "io.requery:requery-processor:$requery"
}
```

I see stuff generated for Dagger 2 in  `build/generated/source/kapt2` but nothing for Requery.

**Update**

Aha, because I had `apply plugin: 'kotlin-kapt'`, I had been using kapt2 instead of kapt. So, it means Requery is not working with kapt2. 

Any change kapt 2 will be supported? It's a real shame to move to older stuff. I know there is kapt 3 already on the way...

**Comment by consp1racy** [comment]
Kapt2 is currently not supported. Beware, it generates something in Kotlin 1.0.6 EAP but it's bogus (no compile time errors but it fails at runtime when working with EntityStore). Stick with kapt for now.

**Comment by npurushe** [comment]
See #296. I looked at kapt2 and that appears to simply not process anything. I'm not sure if people are using it successfully with other annotation processing libraries but there are no apparent issues with the requery processor. kapt2 never even invokes the requery processor so it actually never runs.

**Comment by NeverwinterMoon** [comment]
I've been using kapt2 successfully with Dagger 2. Had absolutely zero problems.
