### ISSUE TITLE
StackOverflowError After update to 1.1.0 (from 1.0.2)

### ISSUE THREAD

**Issue by magillus** [requery/requery#386]
Hello,
Everything was working fine in 1.0.2 version on my project, however after update to 1.1.0 I got StackOverflowError with stacktrace (truncated):
```

java.lang.StackOverflowError
	at io.requery.proxy.EntityProxy.stateListener(EntityProxy.java:323)
	at io.requery.proxy.EntityProxy.preUpdate(EntityProxy.java:328)
	at io.requery.sql.CompositeEntityListener.preUpdate(CompositeEntityListener.java:44)
	at io.requery.sql.EntityWriter.update(EntityWriter.java:523)
	at io.requery.sql.EntityWriter.upsert(EntityWriter.java:489)
	at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:902)
	at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:792)
	at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:660)
	at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:621)
...
	at io.requery.sql.EntityWriter.update(EntityWriter.java:523)
	at io.requery.sql.EntityWriter.upsert(EntityWriter.java:489)
	at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:902)
	at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:792)
	at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:660)
	at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:621)
...
```

I do have Entities with @OneToMany and @ManyToOne relation. (no example to share yet).
If you know what might be issue let me know of something changed that I wasn't aware of - maybe some configuration entry?

I may create a test project in free time to reproduce it.

**Comment by npurushe** [comment]
What entity store method did you call when you got this exception? `upsert(<Entity>)`?. Do you encounter the same problem if you use just `update`? thanks

**Comment by magillus** [comment]
Main method is `insert`, before the insert I do full delete on the same Entity class - basically wipe/replace content of an entity

**Comment by npurushe** [comment]
If you have a sample project demonstrating the issue that would be great. thanks!

**Comment by magillus** [comment]
In my example project that is close to my main application I can't reproduce the issue.
I will try to debug the issue more closely to find out why this loop of calls queues up to make the example project reproducible 

Project github:https://github.com/magillus/SqlQuery102_to_110UpdateBug

**Comment by magillus** [comment]
As I debug the bindable attributes update method I see that @ManyToOne property passes the check:
```if (!filterBindable.test(attribute)) {
                continue;
            }
            // persist the foreign key object if needed
            S referenced = foreignKeyReference(proxy, attribute);
            if (referenced != null && !stateless) {```
and another cascadeWrite starts on https://github.com/requery/requery/blob/1.1.0/requery/src/main/java/io/requery/sql/EntityWriter.java#L573
after that it loops

**Comment by magillus** [comment]
I was able to reproduce the issue, main reason based on the example project at:
https://github.com/magillus/SqlQuery102_to_110UpdateBug
is that [`User`](https://github.com/magillus/SqlQuery102_to_110UpdateBug/commit/1f35049b4eb27b95ed1fcc1b77009c112f8ef60b#diff-e6526f526bd064007d7a27a331096768L16) entity does not have `@Key` that is `@Generated` but assigned.
While it was working on 1.0.2 it is not in 1.1.0+ - is that bad usage example, should I add not used ID that is generated?

**Comment by npurushe** [comment]
Thanks for the example will take a look, it should work either way with or without a generated key.

**Comment by npurushe** [comment]
Can you retry with 1.1.2 ? I don't think this should occur anymore thanks.

**Comment by magillus** [comment]
Unfortunetly it is still happening, maybe it is by design?
the version 1.1.2 have same issue like 1.1.0.

The work around this is in this commit: https://github.com/magillus/SqlQuery102_to_110UpdateBug/commit/73ff52b95c559051c1e3d32c9dc137f0a9d34e51

you can still re-produce running that app (and then press  'Store Group') before the changes in above commit.

I do not have myself capacity to fix this bug, if this is still a bug, maybe miss usage of `@Key` annotation.

**Comment by magillus** [comment]
@npurushe you do not need to fix this, but can you confirm that this is a bug with my previous comment and commit that fixes the issue from model code perspective?

**Comment by npurushe** [comment]
Hey sorry didn't see the notification for your comment. It shouldn't matter wether you use a generated key or not, neither should cause a stackoverflow in any case. 

I didn't see any possible cases in your model where it would cause a stackoverflow but will look at your project again.

**Comment by magillus** [comment]
Thank you, I updated the project. Please let me know if need help or update/test

**Comment by contrudar** [comment]
Just in case if somebody caught this kind of issue. I got the same `java.lang.StackOverflowError` and the reason in my case was `@ManyToOne` mode.  `@ManyToOne` has by default `Cascade.Save` mode and at the same time my `@OneToMany` part got `Cascade.Save` and `Cascade.Delete` modes. In this case they fire each other infinite times until the error. So I just put `Cascade.None` for my `@ManyToOne` part.
