### ISSUE TITLE
Clarify Usage of QueryRecyclerAdapter

### ISSUE THREAD

**Issue by elswenson** [requery/requery#39]
Hi, I am having trouble getting my extended QueryRecyclerAdapter to populate a recyclerview. There are no errors thrown, but it's simply not happening. 

I have overridden performQuery, onCreateViewHolder, and onBindViewHolder. I am also calling queryAsync after setting up an executor and adding the adapter to the recyclerView. Any help you can provide on this matter would be appreciated.

**Comment by elswenson** [comment]
I'm not sure what the issue was, but it's no longer an issue. It seems to be working as intended.

**Comment by npurushe** [comment]
Glad it's working! If you find the cause of the issue please post here as it may help others or improve the api. Thanks!
