### ISSUE TITLE
how to add custom methods or constructor in a model ?

### ISSUE THREAD

**Issue by mayuroks** [requery/requery#390]
How to add custom methods ? Below is the example of what I am trying to achieve
```java
@Entity
abstract class AbstractPerson {
    @Key @Generated
    int id;

    @Index("name_index")                     // table specification
    String name;

    Email email;

   public String sayHello();  // ===> where does this method go ?
}
```

Also, if I want to create a custom constructor like
```java
public Person(String email) {
     mEmail = email;
}

public Person(String name, String name) {
    mName = name;
    mEmail = email;
}
```

Can you help me out here ?

**Comment by npurushe** [comment]
You should define those constructors in the abstract class and the generated version will create matching constructors that forward to them. For you method `sayHello` just define it in the abstract class.
