### ISSUE TITLE
onUpgrade

### ISSUE THREAD

**Issue by AllenVork** [requery/requery#391]
Requery has a default SchemaUpdater to update the table when new tables are created or new columns are added to the table。But what if i wanna rename a column,  remove a column, drop a table or rename a table ? I have to override the onUpgrade() method and write sth like what the SchemaUpdater does?

**Comment by npurushe** [comment]
Hi yes the built in updater only supports additive changes. If something more complex is needed that should be handled by the using application since it could result in loss of data.

**Comment by AllenVork** [comment]
You mean I have to rewrite the onUpgrade() if I wanna do some complex manipulation and it will result in loss of data? What if i just wanna drop a column of a table? Will the other column's data of the table be removed?

**Comment by npurushe** [comment]
It's database specific. If you take sqlite as an example you can't drop a column from a table. You have to create a new table copy the data into it, then delete the old table. If something goes wrong during this there is the possibility of data loss, hence it's best left up to the application for these types of migrations.

**Comment by AllenVork** [comment]
sqlite can rename a table, drop a table or create a new table and remove the old data to it. If I want to do sth like that, what should I do? Just override the onUpdate and do sth like the SchemaUpdater does? or there is some other way?
