### ISSUE TITLE
Custom converters broken in 1.1.1 update

### ISSUE THREAD

**Issue by colintheshots** [requery/requery#396]
We were using custom converters to handle simple objects that don't fit well into the SQL relational tables model. For example, our API sends objects with a UNIX time and Set&lt;String&gt; which we need to persist to compare the times for caching purposes. So I created custom converters that stored the data as a JSON string. Using a separate table and relation for each string set seemed seriously overkill.

Now in 1.1.1, we're seeing a hard compile-time error like the following because Requery sees the custom Objects when generating entities and assumes they need a missing relation to work correctly. I do not know any way to tell the library otherwise. That's what I thought the custom converter accomplished.

> Error:(26, 17) error: Entity reference missing relationship annotation

Any advice to resolve this situation with Requery or to handle this model better?

**Comment by npurushe** [comment]
That's an interesting case, this was added to catch some common errors. Will suppress this error if the attribute has a converter assigned to it.
