### ISSUE TITLE
Is latest build broken?

### ISSUE THREAD

**Issue by matoushybl** [requery/requery#4]
Hi, I am trying this library and when I add all the dependencies and refresh gradle project only requery android is available, is the build broken or is the problem somewhere in my app?

Thanks

**Comment by npurushe** [comment]
Should be working fine. What environment are you using? try `gradle assemble` on the terminal and see if that works. If so the problem is likely an IDE setup issue, If you are using Intellij make sure you have JDK 8 and are using Intellij IDEA 15.

**Comment by npurushe** [comment]
Also if you are just adding it as a gradle dependency can you paste the error that you get from gradle? Thanks.

**Comment by matoushybl** [comment]
I am using Android with Kotlin and Android Studio, the problem is that I am not able to import anything from the base requery artifact, it doesn't appear in the External libraries tab in the Studio, while the artifact does.

I have this in my dependencies, is it correct?
```
    compile 'io.requery:requery:1.0-SNAPSHOT'
    compile 'io.requery:requery-android:1.0-SNAPSHOT'
    apt 'io.requery:requery-processor:1.0-SNAPSHOT'
```

Gradle build normally works. Is there a problem with required Java version as I am still using the default 6 for Android development?

**Comment by npurushe** [comment]
Those are the correct dependencies. Have you added http://oss.jfrog.org/artifactory/oss-snapshot-local to your repositories? Currently only snapshots are available, there will be also a release to bintray soon.

```gradle
repositories {
    jcenter()
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
}
```
If that doesn't work, can you copy paste the error from gradle output? Thanks

**Comment by matoushybl** [comment]
I have added the repository, it builds fine, but classes from the main artifact are not available. Gradle output si here, although there are no errors.

```
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2310Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72310Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbinding030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingAppcompatV7030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingAppcompatV7Kotlin030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingDesign030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingDesignKotlin030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingKotlin030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingSupportV4030Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbindingSupportV4Kotlin030Library UP-TO-DATE
:app:prepareIoReactivexRxandroid110Library UP-TO-DATE
:app:prepareIoRequeryRequeryAndroid10SNAPSHOTLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl UP-TO-DATE
:app:processDebugAndroidTestManifest UP-TO-DATE
:app:compileDebugAndroidTestRenderscript UP-TO-DATE
:app:generateDebugAndroidTestBuildConfig UP-TO-DATE
:app:generateDebugAndroidTestAssets UP-TO-DATE
:app:mergeDebugAndroidTestAssets UP-TO-DATE
:app:generateDebugAndroidTestResValues UP-TO-DATE
:app:generateDebugAndroidTestResources UP-TO-DATE
:app:mergeDebugAndroidTestResources UP-TO-DATE
:app:processDebugAndroidTestResources UP-TO-DATE
:app:generateDebugAndroidTestSources UP-TO-DATE

BUILD SUCCESSFUL

Total time: 5.905 secs
```

**Comment by matoushybl** [comment]
I am sorry for this inconvience, it seem like it was just a bug in Android Studio, after restarting it, it works fine.

**Comment by npurushe** [comment]
Sure no problem glad it's working!
