### ISSUE TITLE
Support for other aggregate functions (sum(), avg(), min(), max())

### ISSUE THREAD

**Issue by KrzysztofWrobel** [requery/requery#40]
Count() is already supported. How about other aggreagte functions?

It would be cool to use this on numeric QueryAttributes of my entites:)

**Comment by KrzysztofWrobel** [comment]
Ohh if somehow this could also react to changes on database. Similar to toSelfObservable() that would have been amazing:) Once I have more time I will try to dig in into your code and help with some PR's, because I'm starting to feel guilty for reporting so many issues/enhancements:)

**Comment by npurushe** [comment]
Hi those should already be supported. For example in the test code:

```java
try (Result<Tuple> query = data.select(Person.BIRTHDAY.min().as("firstBday")).get()) {
            Date date = query.first().get("firstBday");
}
```
do you have an example of the query you're trying to execute?
Also feel free to create issues, any feedback is welcome.

**Comment by KrzysztofWrobel** [comment]
Works like charm:) Will test it more in real life scenarios and I hope will not have to report any issues:)

Ohh one more thing. Maybe it could be added to docs for the others?

**Comment by npurushe** [comment]
Sure yup the documentation will be updated for that, glad its working!
