### ISSUE TITLE
How to filter a QueryRecyclerAdapter with a SearchView?

### ISSUE THREAD

**Issue by andre-artus** [requery/requery#402]
I want to replace my current RecyclerView.Adapter with requery's QueryRecyclerAdapter, but I cannot figure out how to do the filtering.

With my existing adapter I just filter the master list (from RxSearchView.queryTextChangeEvents) into a new list and assign that to the adapter. 

I'm populating the RecyclerView with these
```
// adapter
  override fun performQuery(): Result<MyClass> {
            return mPresenter.getMyClassResults()
  }

//presenter
override fun getMyClassResults(): Result<MyClass> = datasource.getMyClassResults()

// repository
override fun getMyClassResults(): Result<MyClass> {
        return (data select (MyClass::class) orderBy MyClass::column_name.lower()).get()
    }
```

Do I need to implement `Filterable`, if so how do I link it to the Search View. Or is there something else I need to do?

**Comment by npurushe** [comment]
You can transform your query to a list and keep using your current adapter or you can extend the requery adapter and implement the filtering interface and then call QueryRecyclerAdapter.setResults in the publishResults call. It seems like there are multiple ways to do this on Android RecyclerView doesn't seem to prescribe doing it a certain way.

**Comment by andre-artus** [comment]
Thanks, I'll play around with it. I was already doing the first option, but I thought that QueryRecyclerAdapter would add something. I think I'll stick to my existing adapter as it works, but loading thousands of items is something I wish to avoid.
