### ISSUE TITLE
Stale data in SelfObservable result

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#403]
Hi,
I have two entities A and B. There is a ManyToOne relationship from A to B. I have added a selfObservable on a query which returns all the rows in table A.
Now, whenever I update any row of table B, the selfObservable fires the query, but the result it gives doesn't have the latest values, it still gives me the value before updating, though the value was successfully updated in the DB.
And if I try to query the value of that row in table B just after updating it, then the query fired from selfObservable shows me the correct latest value.
I am using the 1.1.1 version on Android.

**Comment by npurushe** [comment]
Is it possible your making multiple modifications the first that would not affect the results of your query? That's usually common, the result will trigger even in any possible change to the table, not necessarily the query. If you're using Rxjava you could also use something debounce if there are too frequent notifications.

**Comment by guptakeshav** [comment]
Hey,

1. I have ensured that my selfObservable method is not getting called due to any other update in the db.
2. Also, in the entire process, the selfObservable should get fired sometime at least with the updated values right?
3. If I ensure that I am making a query to get the same row of B, that was updated(before the selfObservable is called, by running it on the same thread or delaying the selfObservable thread), it reflects the new value in the selfObservable method, which suggests there might be some issue in the library?
P.S.: If I delay the query to get the row, to run after the selfObservable thread, or to get a different row, then the same stale data is received in the selfObservable method.

Thanks.

**Comment by npurushe** [comment]
For 2. yes it is fired after a transaction is committed to the database. For 3. Are you saying you're not getting the data you want no matter how you use the observable? (e.g. different scheduler)

**Comment by npurushe** [comment]
Closing for now, please post back if you have more info
