### ISSUE TITLE
Class Cast Exception: String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by chippiimen** [requery/requery#404]
Hi,

I have one entity that contains a list of custom class object as follows:
```

@Entity
public abstract class A implements Parcelable, Persistable {
public List<BEntity>list;
}

@Entity
public abstract class B implements Parcelable, Persistable {
public String name;
public String url;
}
```

However, when I try to fetch the data from DB, i am getting the cast exception. Any idea?

Thanks

**Comment by npurushe** [comment]
Hi you need to indicate the type of relationship of `List<BEntity>list;` has, e.g. OneToMany and then  also indicate any inverse relationship in B. (e.g. ManyToOne)
