### ISSUE TITLE
[Question] Is there a way to insert object with nested objects without inserting them first?

### ISSUE THREAD

**Issue by Atraac** [requery/requery#407]
I'm currently trying to make an Android MVP sample using Dagger2, RxJava2 and Requery, but I'm having few problems. First of all, sample consists of a simple, two-fragment app that downloads Pokemon from https://pokeapi.co/
and stores them for later use.
Repository: https://github.com/Atraac/mvp-pokemon

Most problems revolve around relations between objects as I don't think I fully understand the usage of those. I'll link to github to spare code fragments here. I'm using ReactiveEntityStore<Persistable> to work on Observables.

[PokemonModel](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/models/AbstractPokemonModel.java)
[LocalDataSource](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/repositories/pokemon/PokemonLocalDataSource.java) used inside [PokemonRepository](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/repositories/pokemon/PokemonRepository.java)

Pokemon has one Sprites object, I've annotated it with ForeignKey, OneToOne, but the problem is, when I try to insert PokemonModel into database I'll get contraint exception. I found out, that I have to insert Sprites first, then insert Pokemon itself. It creates a lot of problems when nested objects have nested objects itself. Is there a way to insert it all at once?
This creates especially a problem when I've added @ManyToMany relation with Stats models. Pokemon, has a List of Stats objects, the Stats object itself, has a nested Stat object. If I wanted to add a pokemon now, I would have to loop through each Stats object inside the list, adding nested objects first, then itself, and only then, Pokemon model. What's the way to go in this case?

Also a side question, is there a way to make upsert work on Android SQLite? Right now it doesn't really Insert the object.

**Comment by Agraphie** [comment]
Hi,

for your first question (OneToOne) do you get a foreign key (constraint) missing exception? Or do you get an exception that the entity already exists?

For the second (ManyToMany), maybe #388 is the same problem?

Upsert works for my projects on Android with SQLite, when doesn't it work? Only for the problems you described above or in general?

Regards

**Comment by Atraac** [comment]
I changed the Debug drop/create on purpose to check something, I'll get it back but that wasn't the issue. 

Now, after reading your thread(which for some reason I didnt see before, sorry for that) I realized that upsert and insert werent working as intended because I was getting my objects from Retrofit through Gson. From what I now understand, I need to manually add/set any related objects(whether it's One to One, or x To Many) to the parent object and then insert/upsert like that:
```java
pokemonModel.setSprites(pokemonModel.getSprites());
```
For some reason, when I upserted a model without manually setting OneToOne object, it just didn't get upserted at all without any errors. Insert on the other hand just threw SQLIntegrityConstraintViolationException as Foreign Key was failing(it didn't exist). That's why the solution I used when you were checking the project was to insert Sprites first, and only then, insert the parent Pokemon object. Either way, I undesrtand my mistake now. Thank you.

Is there a way around that though? It makes insane around of problems with complicated objects to manually add everything.

**Comment by Agraphie** [comment]
Hi,

Hm in general you should only have to do the "adding" for OneToMany or ManyToMany, but not for OneToOne. I'm still not entirely sure what the problem is. Did you push all your code? I can checkout your repository again and have a look, but as I said, it worked for me. In case you didn't know, you can access your sqlite DB via ADB.

For the insertion problem with OneToMany or ManyToMany, there is no solution yet. I suppose if there will be, it will be posted in #388 .

**Comment by Atraac** [comment]
I know about the ADB, I pull the database to check the results every time. I've just pushed the changes I made.
In [this datasource](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/repositories/pokemon/PokemonLocalDataSource.java) in savePokemon method if I remove this line:
```java
pokemonModel.setSprites(pokemonModel.getSprites());
```
The model will not be inserted with upsert. That may be due to the Gson not using setters/getters when parsing response from Retrofit but I'm not entirely sure. Also in this case changing upsert to insert results in the mentioned exception.

On the other hand, right now the @OneToMany does not get inserted, even with the foreach loop I did:
```java
List<StatsModel> tempList = new ArrayList<>(pokemonModel.getStats());
pokemonModel.getStats().clear();

for (StatsModel statsModel : tempList) {
    statsModel.setBaseStat(statsModel.getBaseStat());
    pokemonModel.getStats().add(statsModel);
}
```
[PokemonModel](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/models/AbstractPokemonModel.java) has a list of [StatsModel](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/models/AbstractStatsModel.java) which has one object of [StatModel](https://github.com/Atraac/mvp-pokemon/blob/master/app/src/main/java/com/example/mvp_pokemon/data/models/AbstractStatModel.java)

**Comment by Agraphie** [comment]
Hi,

for the first question: Requery relies (afaik?) on setters to instantiate the entities correctly. GSON however (which you are using) is NOT using setters/getters but reflection. Jackson is using getters/setters. Using Jackson I could resolve your first issue (or you manually set the entity). Please refer to #73 and #236.

For your second question, you would need to save the model, then on the returned model add the collection and save again or copy it to a freshly instantiated entity (applying either works for me). #73 has also some other workarounds.

**Comment by Atraac** [comment]
Thank you, I guess that's all I needed to know.
