### ISSUE TITLE
onNext() is not invoked on toSelfObservable() when deleting entitiy

### ISSUE THREAD

**Issue by KrzysztofWrobel** [requery/requery#41]
I don't know if it's still present, but I had to make a design workaround because I didn't get onNext() callback on toSelfObservable() when I was deleting objects from my database... Haven't seen this covered in Android example or tests.

**Comment by npurushe** [comment]
Can you retry with the latest version? added test case for that https://github.com/requery/requery/commit/13045e567331c8f74d5d1c03f2896314a07a529f

**Comment by KrzysztofWrobel** [comment]
Tried in my code, but still experiencing issue...
Here is how I'm doing this... I'm not sure how your library works, but maybe issue is somehow related to difference between query params of selection and deletion 

```
//Observing entities:
database.select(TrainingEntity.class)
                .where(TrainingEntity.USER_ID.eq(serverSessionManager.getUserServerId()))
                .orderBy(TrainingEntity.TRAINING_END_MILLIS.desc())
                .limit(2).get()
                .toSelfObservable()
                .subscribe(trainingResult -> {

//Deleting entity(DB_ID is primary key)
database.delete(TrainingEntity.class)
                    .where(TrainingEntity.DB_ID.eq(trainingDbId)).get()
                    .toSingle()
                    .subscribe(success -> {
```

**Comment by KrzysztofWrobel** [comment]
I have once again check insert and it works just fine:
```
TrainingEntity training = (TrainingEntity) currentTrainingViewModel.getTraining();
   ...
return database.insert(training).doOnError(throwable -> {
      Timber.e(throwable, "Error saving training!");
   ...
}).doOnSuccess(trainingEntity -> {
      Timber.d("Save training success");
   ...
}).toObservable();
```

**Comment by npurushe** [comment]
Thanks for the example that helped to narrow down the problem
