### ISSUE TITLE
Cannot set generated key field

### ISSUE THREAD

**Issue by low205** [requery/requery#410]
When you annotate field as @Generated, you cannot set this field value explicitly.

**Comment by AlexeyKorshun** [comment]
when db generated this value for id

**Comment by low205** [comment]
Case is simple.
1. Get new entity from client.
2. Load old entity from db
3. Need to update old entity with new entity's fields, but you simply cannot set new entity id and use update. I have to use something like BeanUtils.copyProperties and so on.

**Comment by AlexeyKorshun** [comment]
Do you have unique value in your entity?

**Comment by npurushe** [comment]
For a case like this you can use findByKey to get the entity, and then update the fields as needed.
