### ISSUE TITLE
Upsert without key

### ISSUE THREAD

**Issue by low205** [requery/requery#411]
You cannot use upsert if entity has no @Key annotated field. Sql generated by upsert raises ORA-00936: missing expression.

**Comment by npurushe** [comment]
The syntax issue has been resolved by the above commit. However on Oracle there doesn't seem to be a good way to do this.

The upserted objects cannot use their values in a merge on clause, this gives the error `ORA-38104: Columns referenced in the ON Clause cannot be updated: `

Similarly for Postgres `there is no unique or exclusion constraint matching the ON CONFLICT specification`. 

So this can only be supported on some database systems.
