### ISSUE TITLE
How do I ignore a object field to be a column in table?

### ISSUE THREAD

**Issue by jiqimaogou** [requery/requery#42]

**Comment by npurushe** [comment]
Hi you can add the `@Transient` annotation to ignore the field/method.

**Comment by a-merkle** [comment]
Hi, I had a similar problem and `@Transient` is working for fields within the current class. But when the class has a super class which has non private fields, requery is generating columns for these fields. In this case `@Transient` isn't working and it seems that every other annotation is ignored either. Am I doing something wrong?

**Comment by npurushe** [comment]
Ah ok so you have a super class not marked as an entity, but the fields in your super class are generated as columns? If so that is a bug and will provide a fix

**Comment by a-merkle** [comment]
Yes, exactly. But it would be nice to be able to define columns in a super class. I have tables which have some columns in common and for them I'm currently forced to define each column in each class instead of putting them into a super class.

**Comment by nathanieloliveira** [comment]
Maybe the support for the "@Embedded" annotation could satisfy these needs.

**Comment by npurushe** [comment]
Yup embedded is one way but that will be a while as there are some complexities to solve there. Both inheriting and not inheriting the members from the superclass is useful so will make this configurable. thanks for the feedback

**Comment by npurushe** [comment]
In the updated version you'll have to make inheriting from a base class explicit by using @Superclass, (this is similar to JPA which has @MappedSuperclass which is also now supported). This also resolves the issue @a-merkle reported where the annotations from the base class weren't being processed.

**Comment by a-merkle** [comment]
Thank you very much for the quick fix and feature. It works like a charm! :+1:

**Comment by npurushe** [comment]
Great!

**Comment by shubhammukati** [comment]
Thanks!!
