### ISSUE TITLE
Requery files fail to generate every other compile

### ISSUE THREAD

**Issue by davidwhitman** [requery/requery#420]
Project: https://github.com/davidwhitman/deep-link-launcher

Android Data Binding + Kotlin

Compiling the project will work one time, and then the next time, the Requery files won't be generated. Compile again and they will be generated again. Same happens with unit tests. Data Binding files *are* generated every time. 

I've tried with different versions of kapt, the gradle plugin, kotlin. I've tried toggling `kotlin.incremental`. I've tried both windows and linux mint. Unfortunately, I don't know much about annotation processing so my debugging has been rudimentary at best. 

Sometimes, everything will work fine for a while, but if there's an unrelated compiler error, the issue might come back. It's quite frustrating.

Any ideas?

**Comment by consp1racy** [comment]
I've had success with the following setup:

1) Kotlin 1.0.6 and Requery 1.1.2
2) `apply plugin: 'kotlin-kapt'`
3) Remove `kapt.generateStubs = true`
4) Disable Kotlin incremental compiler.

**Comment by davidwhitman** [comment]
Thank you! I thought I had tried that earlier, but probably I tried it on the Kotlin 1.1 beta and it didn't work there.

**Comment by davidwhitman** [comment]
I left the incremental compilation enabled and haven't had issues.
