### ISSUE TITLE
Unable to use Immutables @Value.Default

### ISSUE THREAD

**Issue by rowysock** [requery/requery#421]
In the immutables library there is a concept of default values. In abstract class you can annotate a non-abstract method with @Value.Default and it will be recognized as an attribute (https://immutables.github.io/immutable.html#default-attributes). Requery on the other hand doesn't seem to recognize non-abstract method in abstract class as an attribute, which for most cases makes sense. If I understand the code correctly, a simple fix would be to add a check for "org.immutables.value.Value.Default" in EntityType.isMethodProcessable.

**Comment by npurushe** [comment]
This fix is in version 1.2.0 thanks

**Comment by rowysock** [comment]
I've tried to use this new feature, but without a success. I copied a code from https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/immutables/Person.java 
Both ImmutablePerson and PersonType classes were generated but the latter one didn't have UUID attribute inside. What am I missing?

**Comment by npurushe** [comment]
Hey sorry about that the name of the immutable default annotation was incorrect, will be fixed in a patch release soon

**Comment by npurushe** [comment]
This fix is in 1.2.1
