### ISSUE TITLE
Transaction auto-commit's when using Transaction.Mode.NONE 

### ISSUE THREAD

**Issue by josecoll** [requery/requery#423]
The ConnectionTransaction commit() code automatically sets the connection AutoCommit to true (in the finally block), instead of checking whether 'supportsTransaction' is true (which it does correctly in the begin() function). 

The effect of this bug is that transactions will be committed immediately upon the first operation.
For example,
        databaseTransaction(database) {
            transactionStorage.addTransaction(txn)
            requerySession.withTransaction {
                insert(createVaultStateEntity(txn))   // AUTO-COMMIT FORCE COMMIT HERE!!!
            }
            rollback()  // ROLLBACK IGNORED (as transactions already committed)
        }

**Comment by josecoll** [comment]
Same problem occurs in the rollback() function of ConnectionTransaction.
finally() block always sets AutoCommit to true (without checking supportTransaction flag)

**Comment by josecoll** [comment]
finally() block in commit() also always attempt to close the connection causing similar behaviour to reported in https://github.com/requery/requery/issues/424

**Comment by npurushe** [comment]
Hi thanks for reporting. Yes the connection auto commit value shouldn't be changed when using TransactionMode.NONE that has been updated in the closing commit. Can you tell me more about your use case with TransactionMode.NONE and why you want the connection to remain open? thanks

**Comment by josecoll** [comment]
Thanks for addressing this issue so expediently.
Our project is currently using Exposed, and coordinates transactions across many different schemas. My prototyping work with Requery required combining Exposed and Requery CRUD operations under the same transaction boundaries.
We are considering using Requery to replace Exposed completely so ultimately our usage of TransactionMode.NONE would be replaced with AUTO.

**Comment by npurushe** [comment]
Ah ok so this relates to #424 as well. In your prototype code do you manage the connection lifetime entirely? Are you using a custom ConnectionProvider with a single connection or just a standard jdbc DataSource?
