### ISSUE TITLE
Connection auto-closing upon table creation

### ISSUE THREAD

**Issue by josecoll** [requery/requery#424]
SchemaModifier uses try-with-resources (in createQueryBuilder) to automatically close a connection in table creation, forcing subsequent operations to fail with an:
io.requery.sql.TableModificationException: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-193]

Sample output:
`[INFO ] 15:23:17.664 [main] HikariDataSource.<init> - HikariPool-2 - Started.
Feb 08, 2017 3:24:29 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate HikariProxyStatement@1659435106 wrapping stat0 sql:
create table if not exists vault_states (transaction_id varchar(64), output_index integer, consumed_timestamp timestamp, contract_state varbinary(10000), contract_state_class_name varchar(255), lock_id varchar(255), lock_timestamp timestamp, notary_key varchar(255), notary_name varchar(255), recorded_timestamp timestamp, state_status integer, primary key (transaction_id, output_index))
[INFO ] 15:24:29.864 [main] HikariPool.shutdown - HikariPool-1 - Close initiated...
[INFO ] 15:24:29.865 [main] HikariPool.shutdown - HikariPool-1 - Closed.
Disconnected from the target VM, address: '127.0.0.1:52193', transport: 'socket'

io.requery.sql.TableModificationException: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-193]`

**Comment by npurushe** [comment]
This connection is created initially to probe the metadata about the database/platform. Closing should be ok, even if using a pooling connection provider it would just be returned to the pool. If you have more details please follow up thanks, might be related to something specific to H2.
