### ISSUE TITLE
ArrayList<Integer> updating values

### ISSUE THREAD

**Issue by kenzo23312** [requery/requery#427]
Hey,

I have question if I'm doing something wrong..

I have class like this:

```
 @Entity
  public abstract class AbstractMyObject implements Persistable {
     @Key
     int id;

     @Nullable
     String title;

     @Nullable
     String description;

     @Convert(IntegerListConverter.class)
     ArrayList<Integer> someIDs= new ArrayList<>();
}
```

and now I'm trying to insert value to ArrayList and with simple `update` it's not working, method `convertToPersisted` is not called, and as I debugged there is no modifier for ArrayList like MODIFIED state. 

When I do `update(MyObject.class, Myobject.SOME_IDS)` it's working.

What's problem with simple `update` on whole MyObject.class that this ArrayList is not updated?

**Comment by npurushe** [comment]
Hi update only updates the modified fields in an entity for efficiency. When you have a collection that is converted the framework will not know it is modified from what it is stored currently hence why no change was made. `update(MyObject.class, Myobject.SOME_IDS)` is a good way to handle that like you mentioned.

**Comment by kenzo23312** [comment]
Thank for fast reply! I understand, than it should described somewhere in docs as I couldn't find solution for this easily.

**Comment by npurushe** [comment]
This is mentioned in the update javadoc, but will look into making this more clear (possibly returning the row count so you know how the rows affected)
