### ISSUE TITLE
Random function

### ISSUE THREAD

**Issue by DevHugo** [requery/requery#428]
Hello, 

I didn't find any [Random ](https://github.com/requery/requery/tree/master/requery/src/main/java/io/requery/query/function) function. My use case is dead simple, just want to select n row randomly. In sqlite, i will go for `SELECT * FROM table ORDER BY RANDOM() LIMIT 10;` but i can't do that with the requery api.

Regards

**Comment by npurushe** [comment]
Before this get's added you can do this by defining your own function

```java
public class Random<T> extends Function<T> {
    public Random(Class<T> type) {
        super("random", type);
    }
    @Override
    public Object[] arguments() {
        return new Object[0];
    }
}
```
Then use new Random(Float.class) in your query.

**Comment by DevHugo** [comment]
Thank a lot for your answer.

**Comment by npurushe** [comment]
This is in version 1.2.0 thanks

**Comment by DevHugo** [comment]
/o/
