### ISSUE TITLE
Adding a foreign key column on non-SQLite platform may fail

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#429]
Requery 1.1.2

io.requery.sql.SchemaModifier:205

    public <T> void addColumn(Attribute<T, ?> attribute) {
        Type<T> type = attribute.getDeclaringType();
        QueryBuilder qb = createQueryBuilder();
        qb.keyword(ALTER, TABLE).tableName(type.getName());
        if (attribute.isForeignKey()) {
            if (platform.supportsAddingConstraint()) {
                // create the column first then the constraint
                qb.keyword(ADD, COLUMN);
                createColumn(qb, attribute); // <============== We prepare a column creating statement.
                executeSql(qb); // <=========================== We create a column.
                qb = createQueryBuilder();
                qb.keyword(ALTER, TABLE)
                    .tableName(type.getName()).keyword(ADD);
                createForeignKeyColumn(qb, attribute, true); // We prepare a statement that
                                                                creates a column with a foreign key contraint.
            } else {
                qb = createQueryBuilder();
                qb.keyword(ALTER, TABLE)
                    .tableName(type.getName()).keyword(ADD);
                createForeignKeyColumn(qb, attribute, false);
            }
        } else {
            qb.keyword(ADD, COLUMN);
            createColumn(qb, attribute);
        }
        executeSql(qb); // We create a column with a for-
                        // Nope, column with such name already exists, cannot create, crash!
    }

I'd expect something like `createForeignKeyReferenceOnColumn` instead of `createForeignKeyColumn`.

I haven't tested what actually happens if you try executing this code so please correct me if creating a column that already exists is OK.

**Comment by npurushe** [comment]
It wouldn't fail for the reason you're saying. However this is not really meant to be public function since we don't support migrations fully. It is used internally by the Android code to perform basic additions of columns, but not elsewhere. And was working on H2, HSQL, Derby before this change under the SchemaModifierTest. It's now expanded to fix an issue on Postgres

Postgres, H2, HSQL, Apache Derby: 
```sql
alter table Person add column address integer 
alter table Person add foreign key (address) references Address (id) on delete cascade 
```
SQLite:
```
alter table Person add address integer references Address (id) on delete cascade 
```

-Not working Oracle
-Not tested MySQL
