### ISSUE TITLE
Transaction Example

### ISSUE THREAD

**Issue by gmribas** [requery/requery#430]
Can you provide some transaction example using kotlin?
Thanks.

https://github.com/requery/requery/issues/106#issuecomment-212747185 (there isn't `runInTransaction()` version `1.1.2`)

**Comment by gmribas** [comment]
I've found.
`data.toBlocking().invoke {
     insert(TestTransaction(1))
     insert(PhoneEntity())
}`

**Comment by npurushe** [comment]
Hi for Kotlin you should use `withTransaction` example:

```kotlin
        data.withTransaction {
            insert(randomPerson())
            insert(randomPerson())
            val result = select(Person::class) limit 10
            assertSame(result().toList().size, 3)
        }
```
