### ISSUE TITLE
How to use functions?

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#433]
val q = select(IJobOffer::class) where
                (IJobOffer::createdAt gt Now.now(OffsetDateTime::class.java))
    return q.get()

java.lang.ClassCastException: io.requery.query.function.Now cannot be cast to org.threeten.bp.OffsetDateTime

It's not a working piece of code, point is the Function is not executed. No Function is executed. How do I make it work?

**Comment by npurushe** [comment]
Do you have the full stack trace? The function will just be converted to the equivalent sql, it' won't really be 'executed' in that sense

**Comment by npurushe** [comment]
I was able to replicate the problem, thanks for reporting
