### ISSUE TITLE
SELECT WHERE <composite key> IN 

### ISSUE THREAD

**Issue by josecoll** [requery/requery#434]
I would like to perform a query using a table's composite key.
SQL-92 select by composite key:
            // SELECT ... FROM foo WHERE (a,b) IN ((a1,b1) ...)
Is it currently possible to execute a query of this type? 
(Please provide example if so)

The Query DSL syntax does not support:

`val query = select (StatesEntity.TX_ID, StatesEntity.INDEX) .where((States::txId, States::index) in (setOf(ids), setOf(idxs))`

I also tried unsuccessfully to use the raw native query syntax:

`val queryString = "SELECT * FROM STATES WHERE (tx_id, index) IN ?"`
`val resultRawQuery = raw(StatesEntity::class, queryString, *objArgsTxId.toTypedArray(), *objArgsIndex.toTypedArray())`

(I tried many variations of the above to no avail)

**Comment by josecoll** [comment]
// Requery does not support SQL-92 select by composite key:
            // SELECT ... FROM foo WHERE (a,b) IN (SELECT f,d FROM ...)
            // see  http://stackoverflow.com/questions/29479891/where-in-query-with-a-composite-key
            //      http://stackoverflow.com/questions/7865414/how-to-execute-a-select-on-a-table-with-a-list-of-composite-keys?rq=1

**Comment by npurushe** [comment]
Thanks for reporting the thing missing here is supporting nested collection parameters. For the raw query you would need to expand the list and substitute each value e.g. `SELECT * FROM STATES WHERE (tx_id, index) IN ((?,?), (?,?))` as thats what needed by jdbc. Possibly setArray could work on some drivers or maybe in the future requery could regenerate the expanded query for you.

**Comment by josecoll** [comment]
Thanks for rapid response. 
Yes, I tried using `setArray` but just couldn't get the syntax to work with (?,?).
Also seems to be very driver dependent (whether it is supported or not).

```
PreparedStatement pstmt = 
                conn.prepareStatement("select * from employee where id in (?)");
Array array = conn.createArrayOf("VARCHAR", new Object[]{"1", "2","3"});
pstmt.setArray(1, array);
ResultSet rs = pstmt.executeQuery();
```

**Comment by npurushe** [comment]
Added an initial version of this, will look something like 
```java
Tuple t = data.select(Person.ID, Group.ID)
.where(RowExpression.of(Arrays.asList(Person.ID, Group.ID)).in(Arrays.asList(1, 1), Arrays.asList(1, 2)))
.get().first();
```
Pretty close to your kotlin example
```kotlin
val t = data.select(Person::id, Group::id)
.where(RowExpression.of(setOf(Person.ID, Group.ID)).in(setOf(1, 1), setOf(1, 2))).first();
```

While it is defined in sql 92 it's still not possible to support it on databases not supporting row value expressions, so support will be limited to just those that do. Also some kotlin specific extensions to capture properties as an expression instead of requery attributes can also be added.

**Comment by josecoll** [comment]
Excellent - have been testing it today and does the job.
Thanks very much for addressing this.
