### ISSUE TITLE
SQLite - composite unique key support.

### ISSUE THREAD

**Issue by autovalue** [requery/requery#437]
I am trying to create the schema below using requery but unless I am missing something in the documentation, it isn't possible:
```sql
CREATE TABLE my_entity (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    unique_pair_id_col INT not null,
    unique_pair_str_col TEXT not null,
    extra TEXT,
  UNIQUE (unique_pair_id_col, unique_pair_str_col)
  ON CONFLICT REPLACE
);
```

My model class is available below,

```java

import android.os.Parcelable;

import com.google.auto.value.AutoValue;

import io.requery.Column;
import io.requery.Entity;
import io.requery.Generated;
import io.requery.Key;
import io.requery.Persistable;
import io.requery.Table;

@Entity()
@Table(name = "my_entity", uniqueIndexes = {"unique_pair_id_col","unique_pair_str_col"})
@AutoValue
public abstract class MyEntity implements Parcelable, Persistable {

  @Key @Generated
  public abstract int _id();

  @Column(name = "unique_pair_id_col", nullable = false, unique = true)
  public abstract int uniquePairIdCol();

  @Column(name = "unique_pair_str_col", nullable = false, unique = true)
  public abstract String uniquePairStrCol();

  public static Builder builder() {
    return new AutoValue_MyEntity.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    abstract Builder _id(int _id);

    public abstract Builder uniquePairIdCol(int uniquePairIdCol);

    public abstract Builder uniquePairStrCol(String uniquePairIdCol);

    public abstract MyEntity build();
  }
```

and here is what Requery generates:
```sql
CREATE TABLE my_entity (
     _id integer primary key autoincrement not null,
     unique_pair_id_col integer not null unique, 
     unique_pair_str_col varchar(255) not null unique
)
```

**Comment by autovalue** [comment]
As a sidenote, do you mind clarifying the difference between `@Table's uniqueIndexes` vs `@Column unique`?

Thanks

**Comment by autovalue** [comment]
The [railroad diagram](https://www.sqlite.org/lang_createtable.html) for the CREATE TABLE statement shows that it's valid (specifically the _table-constraint:_ and _conflict-clause:_ portions)

**Comment by npurushe** [comment]
@Table.uniqueIndexes are the index names that are unique. So you would want something like this:

```java
@Entity(model = "autovalue")
@Table(name = "my_entity", uniqueIndexes = "unique_pair")
@AutoValue
public abstract class MyEntity implements Persistable {
    @Key
    @Generated
    public abstract int _id();

    @Index(value = "unique_pair")
    @Column(name = "unique_pair_id_col", nullable = false)
    public abstract int uniquePairIdCol();

    @Index(value = "unique_pair")
    @Column(name = "unique_pair_str_col", nullable = false)
    public abstract String uniquePairStrCol();

    public static Builder builder() {
        return new AutoValue_MyEntity.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        abstract Builder _id(int _id);
        public abstract Builder uniquePairIdCol(int uniquePairIdCol);
        public abstract Builder uniquePairStrCol(String uniquePairIdCol);
        public abstract MyEntity build();
    }
}
```

which will yield
```sql
create table if not exists my_entity (_id integer primary key autoincrement not null, unique_pair_id_col integer not null, unique_pair_str_col varchar(255) not null)
create unique index if not exists unique_pair on my_entity (unique_pair_id_col, unique_pair_str_col)
```

during table generation. Which is equivalent to what you're looking for minus the `on conflict replace` which for sqlite can only be placed on a constraint. Sql on conflict clauses are not currently something that is auto generated but could be added potentially.

**Comment by autovalue** [comment]
Thank you SO MUCH for the extremely quick reply!
I've been pulling my hair out trying to figure out how to get it to work.
You should probably include this sample in the Wiki/README for better visibility.

> Sql on conflict clauses are not currently something that is auto generated but could be added potentially.

Argh, that's a real bummer, I'd really rather not have to do an explicit check before trying to insert data into my database. How difficult do you think it'd be to implement?

And is there currently a way for me to manipulate the generated database scripts to include the needed command?

**Comment by npurushe** [comment]
You can run your own table script, you don't have to use the one provided by requery, the entity just has to match your table definition. Also `on conflict replace` is rarely what people want because it leads to rows being deleted (including any references that may have foreign keys to them) it's not really a substitute for correct updates. However agree it should be supported in some way.

**Comment by codebymikey** [comment]
> You can run your own table script

How would one go about doing this? And I'm guessing once I go this route, automatic migrations will be off the table?

>  leads to rows being deleted (including any references that may have foreign keys to them)

Wow, didn't know about this. Just did some more research on this and you're right! It probably makes more sense to handle the updates myself.

Not sure if this should be under a different issue, but is there support for creating views/triggers?

**Comment by autovalue** [comment]
> You can run your own table script

How would one go about doing this? And I'm guessing once I go this route, automatic migrations will be off the table?

>  leads to rows being deleted (including any references that may have foreign keys to them)

Wow, didn't know about this. Just did some more research on this and you're right! It probably makes more sense to handle the updates myself.

Not sure if this should be under a different issue, but is there support for creating views/triggers?

**Comment by autovalue** [comment]
Found the `@Table.uniqueIndexes` wasn't working with the code snippet you sent through.
And on further debugging, encountered the #425 bug and how it's already been fixed in master.

Is there a release schedule you stick to and how close is the next release?

**Comment by npurushe** [comment]
Hi sorry about that, yes there will be an update today or tomorrow at the latest

**Comment by npurushe** [comment]
1.2.0 has that fixed

**Comment by npurushe** [comment]
For running your own script you can extend `DatabaseSource` and override `onCreate` / `onUpgrade` as needed. Requery can map to views but doesn't generate them currently that is something that will be added, triggers most likely as well.

**Comment by autovalue** [comment]
Thanks for all the help dude!

I'll close this ticket now and then check in on the version update tomorrow.
