### ISSUE TITLE
Can i receive a list using observabeResult?

### ISSUE THREAD

**Issue by vaccum121** [requery/requery#439]
I am trying to transform emitted items to list, but onNext in subscriber is never called. I think it could happen when onComplete is never called. How can I fix it?
```
dataStore
        .select(Organization::class)
        .get()
        .observableResult()
        .flatMap { it.observable() }
        .toList()
```

**Comment by npurushe** [comment]
With that operation the list will be collected once, in which case you don't need an observable result, just an observable of the elements. 

If you want to observer changes in the query then you should subscribe to observableResult and on each invocation convert it to a list and do something with the list.

```kotlin
data.select(Organization::class).get()
                .observableResult()
                .subscribe { r -> r.toList() } // do something with list 
```

Hope that makes sense
