### ISSUE TITLE
Nullpointer with new requery-jackson module

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#445]
Hi,

when using the new requery EntityMapper I get the following exception with retrofit (and okhttp3)

```Java
java.lang.Exception: com.fasterxml.jackson.databind.JsonMappingException: Multiple back-reference properties with name 'null'
                                                                                                         at [Source: okhttp3.ResponseBody$BomAwareReader@565255c; line: 1, column: 1]
```

Unfortunately there is not more error output and just using the normal ObjectMapper makes everything work again. I also couldn't find a way to reproduce this with a simpler class and setup. I will continue looking for it, but maybe someone has an idea. Is it possible this this error I thrown if a received answer contains a null value for a ManyToMany or OneToMany annotation?

Sorry for the sparse infos.

**Comment by npurushe** [comment]
Do you have multiple relationships to one entity type in another entity? requery doesn't set any json managed reference names at the moment, if they are named probably that would resolve this issue

**Comment by Agraphie** [comment]
I have one self-refering ManyToOne and one ManyToMany, but did not add any JsonBackReferences or JsonManagedReferences.
I added a named `@JsonBackReference` (e.g. `@JsonBackReference(value="nice-list")` to all list and the error disappeared.
But I don't understand why Jackson is perfectly fine with deserialising a JSON string and as soon as I use requeries `EntityMapper` I get this error.

**Comment by Agraphie** [comment]
It seems like I didn't understand the JsonBackReference correctly as you said in #451. Because even though I don't get an error, the lists are not saved to the DB. If I need to add `@JsonManagedReference` to make it work with requery (as otherwise I'll get the error above), then I also need to add `@JsonBackReferenc` to the corresponding field. But this way I cannot have a unidirectional `@ManyToMany` mapping which is what I have in my project.
Am I correct?

**Comment by npurushe** [comment]
You have to use the requery EntityMapper to ensure collections are saved correctly, you can try `enable(MapperFeature.USE_GETTERS_AS_SETTERS);` but there still could be issues. I'm looking into adding names for the Jackson references which should resolve this issue.

**Comment by Agraphie** [comment]
Sorry for the late reply. I am using the EntityMapper and I get the error as mentioned in my comment before. Even with the Jackson property enabled (which you mentioned) the collections are not inserted.

**Comment by npurushe** [comment]
This fix is in 1.2.1

**Comment by Agraphie** [comment]
I will try asap and let you know, thanks already!

**Comment by Agraphie** [comment]
Without adding any references or anything, just using the entity mapper I don't get any errors. However, for my unidirectional `@ManyToMany` the state is still `null` and thus they don't get inserted...
