### ISSUE TITLE
Question: Make generated relationship fields public?

### ISSUE THREAD

**Issue by savatia** [requery/requery#446]
Hello. I have a table Sales, which has a foreign key for Products table like so: 
```java
@Entity
@Table(name = "sales")
public abstract class AbstractSale {
    @Key
    public String sale_id;
    @ManyToOne
    public Product product;
    public int quantity;
    public float price;
}
```
Is there any way to generate a field `int product_id` in the corresponding class `Sale` which contains the key for the class `Product`, and if so how do I ensure that the generated field is public. We want to be able to serialize the model into json easily. Thanks in advance.

**Comment by autovalue** [comment]
Any reason you can't declare the field yourself through something like this?

```java
@ManyToOne
@ForeignKey(referencedColumn = "_id", references = Product.class)
@Column(name = "product_id", nullable = false)
public int productId;
```

**Comment by savatia** [comment]
Is there a way to have both the field `public int product_id` and `public Product product`? I've tried declaring both of them in my class but its throwing this error:
`Error:(130, 55) error: variable PRODUCT_ID is already defined in class Test`

**Comment by npurushe** [comment]
Hi you should define either ProductId as an int key or a Produce reference as a @ManyToOne, you can't have both since it would lead to inconsistent state.

When you use 
```java
@ManyToOne
    public Product product;
```
the id is in the `Product` object itself so there is no need for a field and requery doesn't generate one in that case.
