### ISSUE TITLE
requery-jackson usage

### ISSUE THREAD

**Issue by azabost** [requery/requery#447]
Could you please provide some _requery-jackson_ configuration and data model example?

Additionally, I would like to know if I could use my own Jackson module with it. The module affects serialization of enums which implement some custom interface and I use it for network communication.

**Comment by npurushe** [comment]
```java
EntityMapper mapper = new EntityMapper(Models.<yourmodel>, dataStore);
// use mapper just like ObjectMapper
```

Jackson supports combining modules, so you can create your own `ObjectMapper` and add the `RequeryModule` and your other modules to it. So as long as they aren't overlapping in functionality it would work fine.
