### ISSUE TITLE
Using EnumStringConverter with Kotlin

### ISSUE THREAD

**Issue by azabost** [requery/requery#448]
I have a problem trying to use the `EnumStringConverter`.

```
@Entity
interface Frequency : Persistable {

    @get:Key
    @get:Generated
    var id: Int
    var quantity: Int

    @get:Convert(EnumStringConverter::class)
    var interval: Interval
```

I get following error:

> Error:(95, 19) error: constructor EnumStringConverter in class EnumStringConverter<E> cannot be applied to given types;
> required: Class
> found: no arguments
> reason: actual and formal argument lists differ in length
> where E is a type-variable:
> E extends Enum declared in class EnumStringConverter

I have also tried this:
`@get:Convert(EnumStringConverter::class.java)`

Then, the error says:
> Error:annotation @Convert is missing a default value for the element 'value'

Could you please tell me what I do wrong?

**Comment by npurushe** [comment]
Hi enum's are stored as strings by default so you don't actually need to apply the converter. The converter is mean't to be extended and requires a type argument e.g.

```kotlin
class IntervalEnumConverter<Interval> : EnumStringConverter<Interval>(Interval::class.java)
```
then use IntervalEnumConverter
