### ISSUE TITLE
AutoValue setters not generated properly.

### ISSUE THREAD

**Issue by Squeazer** [requery/requery#449]
I have my AutoValue class setup with method names without "get", e.g.:

    public abstract String name();

When I annotate it with `@Entity` it will try to generate setters like this:

    @Override
    public void set(ShoeType entity, String value) {
        entity.builder.name(value);
    }

However, my builder class does include "set", e.g.:

    public abstract Builder setName(String name);

If I change my methods to include "get" (e.g. `public abstract string getName()` it works ok. It also works ok if i change my builder methods to not include "set" (e.g. `public abstract Builder name(String name);`

IMO different combinations of set / get should be supported.

**Comment by npurushe** [comment]
Thanks for reporting. Updated to look at the builder type if available and match the setter to one that exists there

**Comment by npurushe** [comment]
Will be available in an update soon

**Comment by npurushe** [comment]
This fix is in 1.2.1
