### ISSUE TITLE
upsert method javadoc is not really clear on return type

### ISSUE THREAD

**Issue by DevHugo** [requery/requery#450]
Hello, 

I was checking the upsert javadoc method : 

> public abstract <E extends T> io.reactivex.Single<Iterable<E>> upsert(Iterable<E> entities)
> … 
> Returns:
> the operation result.

The expression "the operation result" made me think that only row that have been changed will be return and that not the case. 

For exemple, 
```Java
  @Test
    public void testAlreadyInsert() {
        Tag t1 = new Tag();
            t1.setId(UUID.randomUUID());

        data.insert(t1);

        Tag t2 = new Tag();
            t2.setId(UUID.randomUUID());

        Iterable<Tag> expectedResult = data.upsert(Arrays.asList(t2, t1));

        // Should have one result t2 and not t1. Got two result t1 and t2.
    }

    @Test
    public void testNoUpdate () {
        Tag t1 = new Tag();
        t1.setId(UUID.randomUUID());

        data.insert(t1);

        Iterable<Tag> expectedResult = data.upsert(Arrays.asList(t1));
       
       // Expected: empty iterable got one result t1.
    }
```

Tested on H2, SQLite, MySQL.

Two solutions now : 
  - easy : just changed the documentation
  - difficult : the function need to return only row that have been changed. I don't think it possible, but, yeah, I am dreamer !

Thank in advance.

**Comment by npurushe** [comment]
Hi thanks, it was a bit vague since there are multiple implementations of the interface for sync/async. In general all rows will be changed in such an operation possibly more if considering cascading operations. Without forcing versioning it would be problematic to return just 'changed' entities.
