### ISSUE TITLE
Field not recognised with EntityMapper

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#451]
Hi,

I tried the following example, but the associated addresses are not being deserialised. It will give the exception `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "addresses"`. But when I use the normal `ObjectMapper` and don't change anything else, the field gets deserialised correctly.

```Java
@Entity
public abstract class AbstractAddressModel {
  @Key
  int id;
  String street;
  @ManyToMany
  @JunctionTable
  List<PersonModel> persons;
}
```

```Java
@Entity
public abstract class AbstractPersonModel {
  @Key
  int id;
  String username;

  @ManyToMany
  List<AddressModel> addresses;
}
```

Insertion code

```Java
  EntityMapper entityMapper = new EntityMapper(Models.DEFAULT, database);
  entityMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
  String user = "{\n" +
      "  \"id\": 1,\n" +
      "  \"username\": \"testuser\",\n" +
      "  \"number\": 123,\n" +
      "  \"addresses\": [\n" +
      "    {\n" +
      "      \"id\": 1,\n" +
      "      \"street\": \"street1\"\n" +
      "    },\n" +
      "    {\n" +
      "      \"id\": 2,\n" +
      "      \"street\": \"street2\"\n" +
      "    }\n" +
      "  ]\n" +
      "}";
      try {
    PersonModel personModel = entityMapper.readValue(user, PersonModel.class);
    database.insert(personModel).blockingGet();
  } catch (IOException e) {
    e.printStackTrace();
  }
```

**Comment by npurushe** [comment]
The @JunctionTable denotes the owning or managed side of the relationship (`JsonManagedReference`) while the other side is considered the back reference (`JsonBackReference`). You've placed it on AbstractAddressModel but when you're serializing AbstractPersonModel contains the references, hence the exception. 

You should adjust the managed/back reference accordingly to match what you expect to be the managed side.
