### ISSUE TITLE
KotlinEntityDataStore java.lang.IllegalStateException: data.delete(entities) must not be null

### ISSUE THREAD

**Issue by zdevwu** [requery/requery#453]
KotlinEntityDataStore's delete function has a return type of Void:
`override fun <E : T> delete(entity: E): Void = data.delete(entity)`
Kotlin expects a none-null Void! type using this signature while the implementation in EntityDataStore in java the data.delete always return null, this causes Kotlin to throw:
`java.lang.IllegalStateException: data.delete(entities) must not be null`

Unless something obvious that I haven't notice, does anyone have this issue in your Kotlin code?

**Comment by consp1racy** [comment]
What version of Koltin and Requery do you use?

**Comment by zdevwu** [comment]
@consp1racy kotlin: 1.0.6 and 1.1.0, requery: 1.2

**Comment by zdevwu** [comment]
I've done a fix, I will create a pull request if it is OK?

**Comment by tonyjs** [comment]
Similar, I'm too.
I've modified the sample. on click action the row of `Person`

![2017-03-02 9 42 32](https://cloud.githubusercontent.com/assets/8830704/23507636/59075c92-ff91-11e6-8ed5-ab2d63635948.png)
I try to remove `Address` but the Exception has occurred. How can I solve this.

and One more question. I want to remove only `Address` wihout `Person`. What can I set the cascade action OneToOne relationships?

**Comment by zdevwu** [comment]
@tonyjs CascadeAction.NONE I guess?

**Comment by tonyjs** [comment]
@zdevwu ah, thanks! and Speaking of the exception, the solution is just what you said `Void` I think too.

**Comment by npurushe** [comment]
Hi this issue was fixed by this PR #418 , the return type was changed to `Void?` looks like you're not using the latest version? Closing for now, please post back if there is a problem with the latest released version.
