### ISSUE TITLE
Jackson serializer inlines the first reference

### ISSUE THREAD

**Issue by kakai248** [requery/requery#456]
Hello,

I'm trying to use the new Jackson module to serialize my DB. I'm manually building a JSON that will hold all the different tables. I noticed that in objects that reference some object in other table, the first reference will get inlined:

```
[ {
    "id" : 1,
    "account" : {
      "id" : 1,
      "accessToken" : "...",
      "expirationDate" : "...",
      "identifier" : "...",
      "refreshToken" : null,
      "type" : 0
    },
    "displayName" : "...",
    "lastAccess" : "...",
    "name" : null
   }, {
    "id" : 2,
    "account" : 1,
    "displayName" : "...",
    "lastAccess" : "...",
    "name" : "..."
   } ]
```

Is it possible to avoid this behavior and never expand the related object? I looked into the source code but Jackson gets a bit over my head and I'm not sure if this is a setting for Jackson or a decision that you made in the serializer.

Thanks for your time.

**Comment by npurushe** [comment]
Hi you should use the standard jackson annotations for ignoring fields, e.g. `@JsonIgnore`

**Comment by kakai248** [comment]
I didn't want to ignore the field, just to not inline the first reference of a related model.

But your answer pointed me in the right direction, that can be done with an annotation. In case anyone needs it, you have to annotate the field that has the relation with:

```
@JsonIdentityReference(alwaysAsId = true)
```

Thank you!
