### ISSUE TITLE
Q: How can I drop and recreate manually?

### ISSUE THREAD

**Issue by tonyjs** [requery/requery#457]
I want to clear all data in my application.

So I want to drop all tables and recreate all.(like applicationsetting > clear data)

How can I this?

**Comment by npurushe** [comment]
For Android you can use `DatabaseSource.setTableCreationMode(TableCreationMode.DROP_CREATE);` when using the DatabaseSource.

**Comment by tonyjs** [comment]
I mean that clear all data at runtime. ex) `button.onClick { database.dropTable }` 

`DatabaseSource.setTableCreationMode(TableCreationMode.DROP_CREATE)` drop an recreate immediately?

**Comment by npurushe** [comment]
For that you can use `SchemaModifier`
e.g.
`new SchemaModifier(configuration).createTables(TableCreationMode. DROP_CREATE);`
where configuration is from `DatabaseSource.getConfiguration()`

**Comment by junseon** [comment]
👍 Thanks for your reply.
