### ISSUE TITLE
Calling delete(iterable) on ManyToOne does not delete as expected

### ISSUE THREAD

**Issue by Tomo-SmudgeApps** [requery/requery#458]
Here is a test that I've appended onto the functional tests that you have set up.

The first test is test for deleting multiple entities from ManyToOne.
The second test is test for deleting a single entry from ManyToOne.

Am I doing something unexpected that causes the first test to fail? Thanks for your time.

```
    @Test
    public void testAllDeleteFromManyToOne() {
        Person person = randomPerson();
        data.insert(person);
        Phone phone1 = randomPhone();
        Phone phone2 = randomPhone();
        phone1.setOwner(person);
        phone2.setOwner(person);
        data.insert(phone1);
        data.insert(phone2);
        data.refresh(person);
        data.delete(person.getPhoneNumbers());

        Phone cached = data.findByKey(Phone.class, phone1.getId());
        assertNull(cached);
    }

    @Test
    public void testSingleDeleteFromManyToOne() {
        Person person = randomPerson();
        data.insert(person);
        Phone phone1 = randomPhone();
        Phone phone2 = randomPhone();
        phone1.setOwner(person);
        phone2.setOwner(person);
        data.insert(phone1);
        data.insert(phone2);
        data.refresh(person);
        data.delete(phone1);

        Phone cached = data.findByKey(Phone.class, phone1.getId());
        assertNull(cached);
    }
```

**Comment by consp1racy** [comment]
`delete` is a query operation. You need to actually

    data.delete(...).call();

to trigger and consume the operation.

**Comment by npurushe** [comment]
That could be the case if you are using a non-blocking `EntityStore`, if you are using the blocking version for your test what output do you see in the log if you enable logging?

**Comment by Tomo-SmudgeApps** [comment]
Hi guys, thanks for the reply. Unfortunately I've left the project on a different computer so I will try to provide this tomorrow. (from NZ GMT+13)

I'm using a blocking store. I've added these tests onto the FunctionalTests.java and ran the tests through Android studio. 

Either way, I will provide the logs later. Thank you.

**Comment by Tomo-SmudgeApps** [comment]
Sorry, I can't quite figure out how to set the logging enabled. Pretty new to Java/Android and to using this particular library.

If you could tell me how I could turn on the logging that'll be very helpful as I couldn't find the variable that I need to be calling setLoggingEnabled from ParameterizedFunctionalTest.java I can provide the logs quickly.

Alternatively, just adding the tests provided into FunctionalTests.java under io.requery.test package  in requery-test is enough to reproduce this issue. 

Sorry I can't provide the necessary information at this stage.

**Comment by npurushe** [comment]
Thanks for the test case, there was a problem with this particular use case which is fixed by the above commit. Will be available in the next update soon.
