### ISSUE TITLE
EntityStore thread safety question

### ISSUE THREAD

**Issue by jknack** [requery/requery#465]
Hi,

 First of all, congrats for such a great project. I'm working in a requery module for http://jooby.org and need to know if EntityStore is a thread safe class or not?

 That's is it safe to have one and only one instance per application/db? Or should I create (and close) each time need to I need one (one per request)?

 Thanks.

**Comment by npurushe** [comment]
Hi thanks, that's great to hear. Yes the implementations of EntityStore are thread safe and can be stored for the lifetime of an application

**Comment by npurushe** [comment]
Will clarify this in the documentation thanks!
