### ISSUE TITLE
No-args constructor of @Embeddable object is not generated

### ISSUE THREAD

**Issue by mirkoluchi** [requery/requery#469]
I have this data model:
* An **IPerson** entity
* An **IAddress embeddable** object
* The **IPerson** has an **embedded property** address of type IAddress

```Java
@Entity
public interface IPerson {
  
    @Id
    @GeneratedValue
    public Long getId();

    @Embedded()
    public IAddress getAddress();

}

@Embeddable
public interface IAddress {
    
    @Column
    public String getAddress();

}

```

The generated class to represent the embedded relationship is **Person_Address**. The class **does not have a no-args constructor**, but just this:

```Java
public Person_Address(EntityProxy<Person> proxy, Attribute<Person, String> address) {
        this.$proxy = proxy;
        this.$address = address;
}
```

This is a **problem when I try to parse the JSON representation of a Person** using for instance Jackson, because it **cannot find a no-args constructor** on the Person_Address class: `com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.lokrim.vehicle.Person_Address: no suitable constructor found`

**Would it be a problem to modify the Person_Adress generated class to have also the no-args constructor**, and then make the Person.setAddress setter to properly set the two attributes that now are in the Person_Address constructor?
Something like this:

```Java

class Person{
 ....
   public void setAddress(Person_Address address) {
        if(address != null && address.$proxy == null){
             address.$proxy = $proxy;
             address.$address = ADDRESS_ADDRESS;
        }
        this.address = address;
    }
}

```
NOTE that in the above code I neglected fact that Person_Address.$proxy and Person_Address.$address properties are both final and private.

**Comment by npurushe** [comment]
The embedded type needs those arguments in order to be a valid object, e,g it must be owned by `Person` in your case. It would be invalid to construct it by itself.

For Jackson you should use `USE_GETTERS_AS_SETTERS` on the mapper to ensure the Person object is used to fill in the embedded type or use the requery-jackson module. Hope that makes sense, thanks!

**Comment by mirkoluchi** [comment]
Hi.

* **USE_GETTERS_AS_SETTERS**, from **Jackson Javadoc**, **affects only** properties that are **collections**, not objects (so it's not suitable for my example). (`Feature that determines whether otherwise regular "getter" methods (but only ones that handle Collections and Maps, not getters of other type)...`
* the **requery-jackson module doesn't work either**, throwing the same exception I get using 'standard' Jackson

This is my code to test it:

```Java
 Person p = new Person();
 p.setId("id");
 p.getAddress().setAddress("Some Address");
 
EntityMapper m = new EntityMapper(Models.PERSON, getDataStore());
String json = m.writerFor(Person.class).writeValueAsString(p);

Person pParsed = m.readValue(json, Person.class); // <--- this throws an exception
Assert.assertEquals(p, pParsed);

```

The parsing fails with the exception:
`com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.lokrim.person.Person_Address: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)`

I know that embedded objects are owned by parent object, but even in JPA you can freeely create them with the default constructor and set them on the parent object.
I think that there is just **some effort of attaching the embedded object to the parent one** once we set it (properly setting proxy and PropertyState), but it should definitely be possible.

BTW, for the moment, I used a custom JsonDeserializer as workaround:

```Java
Entity
public interface IPerson {
    ...
    @Embedded()
    @JsonDeserialize(using = Person_AddressJsonDeserializer.class)
    public IAddress getAddress();
}

public class Person_AddressJsonDeserializer extends JsonDeserializer<Person_Address>{

    private ObjectMapper mapper = new ObjectMapper();

    @Override
    public Person_Address deserialize(JsonParser p, DeserializationContext ctxt) throws IOException, JsonProcessingException {
        JsonStreamContext parsingContext = p.getParsingContext();
        JsonStreamContext parent = parsingContext.getParent();
        Person parentPerson = (Person) parent.getCurrentValue();
        Person_Address address = parentPerson.getAddress();
        mapper.readerForUpdating(address).readValue(p, Person_Address.class);
        return address;
    }

}

```

**Please consider reopening this issue and maybe mark it as future improvement.**

**Comment by npurushe** [comment]
Sorry that didn't work, will look into some way to support this thanks for the detailed information!
