### ISSUE TITLE
How do I use insert or replace? (conflict on replace)

### ISSUE THREAD

**Issue by jiqimaogou** [requery/requery#47]

**Comment by npurushe** [comment]
Sounds similar to #38 insert or update if exists (upsert) ? Or do you just want to set the conflict algorithm during table generation?

**Comment by jiqimaogou** [comment]
both two.

**Comment by KrzysztofWrobel** [comment]
That would be great to have the resolve conflict alogrithm!

**Comment by npurushe** [comment]
Closing since the upsert method is ultimately the better way to handle this.
