### ISSUE TITLE
Error:2 mappings found for...I can't find it

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [requery/requery#475]
i try to use the requery-android-example
[image](https://ww4.sinaimg.cn/large/006tNbRwly1fdtrtvcm02j30ta0gh0x5.jpg)
`Error:(40, 12) 警告: 2 mappings found for: com.example.zyf.requerydemo.model.PhoneEntity.owner -> com.example.zyf.requerydemo.model.PersonEntity`
`Error:(493, 64) 错误: 找不到符号
符号:   类 BR
位置: 程序包 com.example.zyf.requerydemo.model`

**Comment by npurushe** [comment]
Did you just rename the package? if so you may need to do a clean/rebuild

**Comment by zhuangYuFeiHelloGit** [comment]
thank u
