### ISSUE TITLE
Question: How can I select entity except specific field(column)?

### ISSUE THREAD

**Issue by tonyjs** [requery/requery#476]
Example Entities
```
@Entity
interface User {
    ...
    val id : Long

    val name : String

    @OneToMany
    var phones : MutableList<Phone>
}

@Entity
interface Phone {
    ...
```

I want to find one user except phones.
(or wan to select only `id` and `name` column)

Can you tell me how to build up the select method, please?

**Comment by npurushe** [comment]
This is the default behavior, associations are lazily loaded on demand. You can also specify partial selection in a select query using the kotlin property references 

```kotlin
val result = data.select(User::id, User::name) 
```
