### ISSUE TITLE
Documentation for Caching, Partial objects/refresh

### ISSUE THREAD

**Issue by AlexFrost** [requery/requery#479]
Hi, 
Main page has feature list. Where can I find documentation with details of this feature:

- Partial objects/refresh
- Upsert support
- Caching

Thanks.

**Comment by npurushe** [comment]
Some basic information below. If you have a specific question please ask, thanks:

(Partial objects:)[http://requery.github.io/javadoc/io/requery/Queryable.html#select-java.lang.Class-io.requery.meta.QueryAttribute...-]
this means you can select only some fields into an object e.g. `data.select(Person.class, Persion.ID, Person.NAME)` the same is true for [refresh](http://requery.github.io/javadoc/io/requery/EntityStore.html#refresh-E-io.requery.meta.Attribute...-)

(Upsert)[http://requery.github.io/javadoc/io/requery/EntityStore.html#upsert-E-]

(Caching)[https://github.com/requery/requery/wiki/Caching]

**Comment by AlexFrost** [comment]
Thanks a lot.

**Comment by AndroidDeveloperLB** [comment]
It is said that :

> Caching can also be disabled through the Configuration object.

But I don't see any function or field to do it. How come?
