### ISSUE TITLE
How do I delete a table ?

### ISSUE THREAD

**Issue by jiqimaogou** [requery/requery#48]

**Comment by miomao656** [comment]
`reQuery.delete(TableEntity.class).get().value(); `works for me

**Comment by npurushe** [comment]
Yup that is the correct way to delete all the rows in a table. If you want to delete the whole database on Android you should just delete the sqlite file via context.deleteDatabase

**Comment by miomao656** [comment]
So if i want to delete all data from tables in one command without deleting the whole .db file that is not possible?

**Comment by npurushe** [comment]
You can use `SchemaModifier` [dropTables](http://requery.github.io/javadoc/io/requery/sql/SchemaModifier.html#dropTables--) to drop all the tables but then they need to be recreated again to use the db. It really depends on your use case. If you just want to delete some tables then what you posted is the way to delete all rows of a table.

**Comment by vanniktech** [comment]
Neither `entityStore.delete(MyClass.class)` nor `entityStore.delete(MyClass.class).get()` works for me. How come?

**Comment by npurushe** [comment]
See https://github.com/requery/requery/issues/156 you need to use the result returned by get and evaluate it

**Comment by vanniktech** [comment]
Which type will I get back when using `entityStore.delete(MyClass.class).get()`?

**Comment by vanniktech** [comment]
Okay for future reference `((SuppliedScalar) data.delete(MyClass.class).get()).value();` did the job

**Comment by SantiagoONE** [comment]
Hi there, 
To use context.deleteDatabase I need the db's name, which is it and how to specific it?
`DatabaseSource source = new DatabaseSource(context, Models.DEFAULT, 1)`
