### ISSUE TITLE
Wrong generation of entity which is part of a hierarchy deeper than 2 levels

### ISSUE THREAD

**Issue by mirkoluchi** [requery/requery#480]
My data model has an **entity** (_IEntity_) which has a **mapped superclass** (_ISuperEntity_) which itself has a **mapped superclass** (_ISuperSuperEntity_).

```Java

@Entity
public interface IEntity extends ISuperEntity {
    @Column
    public String getAttributeOnEntity();
}

@MappedSuperclass
public interface ISuperEntity extends ISuperSuperEntity {
    @Column
    public String getAttributeOnSuperEntity();
}

@MappedSuperclass
public interface ISuperSuperEntity {
    @Column
    public String getAttributeOnSuperSuperEntity();
}

```

The annotation processor seems to behave **wrongly** processing **only one level** of the **hierarchy**, therefore **Entity class** ends up **missing** the attribute **attributeOnSuperSuperEntity** which was declared on its ancestor, causing this compilation error:

`Error:(18, 8) error: Entity is not abstract and does not override abstract method getAttributeOnSuperSuperEntity() in ISuperSuperEntity`

**I think the annotation processor should be fixed to handle hierarchies of depth greater than 2.**

**Comment by npurushe** [comment]
version 1.3.0 contains this fix
