### ISSUE TITLE
Primary key not generated

### ISSUE THREAD

**Issue by victordigio** [requery/requery#483]
Hi, I have this entity data class written in Kotlin:

```@Entity
data class  Event(
        @Key @Generated var pk: Long?,
        var name: String?       
) : Persistable, Serializable
````

I want to have an auto generated primary key in the field pk. Events are built with Retrofit and gson automatically. Then, I persist an array of Events like db.insert(events). In that moment, pk fields are null, because the server doesn't send that field. I expect to have that fields initialized after the insertion in database, but they remain null. After that, when I do a query like db.select(Event::class).get().toList(), I can see that the pk fields are null.

**Comment by npurushe** [comment]
Hi please the answer in #466 about using generated keys in kotlin data classes
