### ISSUE TITLE
Requery 1.2.1 does not handle views properly.

### ISSUE THREAD

**Issue by andre-artus** [requery/requery#485]
In 1.2.0 a feature was added expose views with the `@View` annotation. I have a problem in 1.2.1 that occurs when the view does not yet exist in the DB it is created as a table by requery, which causes an error when one wants to create the view.

e.g.

java.lang.RuntimeException: Unable to start activity ComponentInfo{ActivityName}: android.database.sqlite.SQLiteException: use DROP TABLE to delete table MyView (code 1): , while compiling: DROP VIEW IF EXISTS MyView

It seems to work fine when the view is created first. I create the DB from code, so it causes issues for me.

I'm using requery 1.2.1 and Kotlin 1.1.1 on Android

**Comment by npurushe** [comment]
Views are specifically excluded from any generated create or drop statements (https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/sql/SchemaModifier.java#L279) Your view entity will have `setView(true)` in the generated code, are you sure that's the case?

**Comment by andre-artus** [comment]
It's set.  I'm currently using 1.2.0 as 1.2.1 was causing problems with my join queries (logged as different issue).

``` Java
 public static final Type<ViewNameEntity> $TYPE = new TypeBuilder<ViewNameEntity>(ViewNameEntity.class, "view_name")
    .setBaseType(ViewName.class)
    .setCacheable(true)
    .setImmutable(false)
    .setReadOnly(false)
    .setStateless(false)
    .setView(true) // <--- Entity set as a view
    .setFactory(new Supplier<ViewNameEntity>() {
        @Override
        public ViewNameEntity get() {
            return new ViewNameEntity();
        }
    })
    .setProxyProvider(new Function<ViewNameEntity, EntityProxy<ViewNameEntity>>() {
        @Override
        public EntityProxy<ViewNameEntity> apply(ViewNameEntity entity) {
            return entity.$proxy;
        }
    })
// addAttributes ... 
    .build();
```

**Comment by npurushe** [comment]
Found the problem with this property not being carried over from the builder, will be fixed in the next release

**Comment by npurushe** [comment]
version 1.3.0 contains this fix
