### ISSUE TITLE
INSERT INTO from SELECT using Kotlin

### ISSUE THREAD

**Issue by andre-artus** [requery/requery#486]
Are there examples of the correct way to use this feature with Kotlin?

This is my current attempt.

``` Kotlin
_data.insert(Table1Entity::class,
   Table1Entity.COLUMN1,
   Table1Entity.COLUMN2,
   Table1Entity.COLUMN3,
   Table1Entity.COLUMN4)(
   _data.select(Table2Entity.COLUMN1,
           Table2Entity.COLUMN2,
           Table2Entity.COLUMN3,
           Table2Entity.COLUMN4
   )).get()
```

**Comment by npurushe** [comment]
Unfortunately there was a bug in the kotlin implementation of this, fixed and now more closely matches the core version, the syntax is:

```kotlin
val count = data.insert(Person::class, Person::name, Person::description)
                .query(data.select(Group::name, Group::description)).get().first().count()
```

**Comment by andre-artus** [comment]
Will. 1.2.1 be reissued, or will it be in 1.2.2?

**Comment by consp1racy** [comment]
@andre-artus Maven artifacts are never reissued because clients keep original release in local cache.

Wait for next release or consume current code through jitpack.io.

**Comment by andre-artus** [comment]
@consp1racy, I'll wait for the next release as I currently just drop the table before creating the view and that duct tape can last for a little bit.
