### ISSUE TITLE
@PostLoad functions not called in some cases

### ISSUE THREAD

**Issue by tasn** [requery/requery#487]
Hey,

In some (many) cases, @PostLoad functions aren't called. I have to manually call them to make things work.

Here are my models:
https://github.com/etesync/android/blob/master/app/src/main/java/com/etesync/syncadapter/model/JournalModel.java

See how I have to call afterLoad manually in "getCollections" to make it work.

Any idea what's wrong? Would you like me to post my generated entity class?

Thanks,
Tom.

**Comment by npurushe** [comment]
Hi this method won't be called if a cached entity is loaded (caching is enabled by default). However this behavior is something that could be changed as it does looks like it happens in other persistence frameworks.

**Comment by tasn** [comment]
Thanks for the quick reply. I'm essentially using it to populate transient variables in the structure after load, so I need it to always be called.

Thanks.

**Comment by tasn** [comment]
Thanks!

**Comment by tasn** [comment]
Hey @npurushe,

Please reopen, I tested it after the release, and it didn't work. I thought I may have had an issue somewhere else, but I now had time to investigate, and I can confirm the issue is still there.

I updated to 1.3.0, and removed my explicit calls to "afterLoad" and without them, afterLoad is still not called. Added them back, and everything works again.

Please take another look.

Thanks.
