### ISSUE TITLE
observableResult() Scheduler

### ISSUE THREAD

**Issue by bajicdusko** [requery/requery#488]
I have noticed interesting behavior and I'm not sure is it implemented on purpose or it is a bug.

ReactiveEntityStore has been created as on example:
```
    @Provides
    @Singleton
    public ReactiveEntityStore<Persistable> provideReactiveEntityStore(EurekaApplication eurekaApplication) {
        DatabaseSource source = new DatabaseSource(eurekaApplication, Models.DEFAULT, 1);
        if (BuildConfig.DEBUG) {
            // use this in development mode to drop and recreate the tables on every upgrade
            source.setTableCreationMode(TableCreationMode.DROP_CREATE);
            //source.setLoggingEnabled(true);
        }
        Configuration configuration = source.getConfiguration();
        return ReactiveSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration) {
        });
    }
```

In background service, changes on SyncDB entity are observed like this:
```
dataStore.select(SyncDb.class).where(SyncDb.SYNCED.eq(false))
                .get()
                .observableResult()
                .flatMap(syncDbs -> syncDbs.observable())
                .toFlowable(BackpressureStrategy.BUFFER)
                .subscribeOn(Schedulers.newThread())
                .map(syncDb -> apiSyncRepository.upload(syncDb)
                        .onErrorReturn(throwable -> {
                            Timber.e(throwable);
                            Timber.e(Util.getErrorMessage(throwable));
                            return new SyncDb();
                        }).blockingSingle()
                )
                .filter(syncDb -> syncDb.getId() != RequeryConstants.NO_ID)
                .flatMap(syncDb -> dbSyncRepository.markAsSynced(syncDb))
                .subscribe(syncDb -> Timber.i("Sync %d %s finished", syncDb.getTableId(), syncDb.getTableName()),
                        throwable -> {
                            Timber.e(throwable);
                            Timber.e(Util.getErrorMessage(throwable));
                        },
                        () -> Timber.i("SyncDb listener completed."));
```

You will notice that I'm am setting subscriber to work on Schedulers.newThread(). Also in order to queue long running uploads, I have added blockingSingle() on upload method inside map operator.

Now lets say that somewhere in app I have something like this:

```
public void onSomeClick(){
    Flowable.fromCallable(() -> getSomeNewSyncObject())
        .flatMap(dbSyncRepository::create)
        .subscribe(a -> {}, throwable -> {}, () -> closeSomething());
}
```

After executing this (simplified) click above `apiSyncRepository.upload` call (in first snippet) will throw `NetworkOnMainThreadException`. Obviously, streams are connected starting with `Flowable.fromCallable()` in `onSomeClick` because `.subscribeOn(Schedulers.newThread())` in first snippet is ignored. Of course, because of `blockingSingle()`, `onSomeClick()` won't finish as long as upload is executing.

I was expecting for entity observable to be independent of the source of change, therefore to be allowed to write to some table on various threads and yet to receive changes somewhere in the background.

Any comment on this ?

I appreciate hard work you put into requery. Thank you.

**Comment by npurushe** [comment]
Hi it's not clear how your `onSomeClick` handler is related to your first snippet. But if `getSomeNewSyncObject` or `dbSyncRepository::create` have blocking operations then you need to schedule that work on a background thread. 

`ReactiveEntityStore` doesn't assign any Scheduler for subscribeOn or observeOn it's up to the caller to decide what schedulers to use. (For database background work in Android a single background thread is sufficient)

**Comment by bajicdusko** [comment]
I'm sorry for confusing you. Let me explain it more clearly, hopefully :)

First snippet is placed in background service and it is started when connection is established or manually from within the app.

`getSomeNewSyncObject()` is simple method that returns new object.
`dbSyncRepository::create` writes that object into `SyncDb` table and there are no any blockings here.

I have left click method to run on android main thread on purpose so that I could reproduce `NetworkOnMainThreadException`. I know that I can change it (and I did), however I'd like to know why `NetworkOnMainThreadException` in background service can happen at all.
So as I see it this is what happens:

1. In third snippet `dbSyncRepository::create` is called on main thread and it writes new object into `SyncDb`
2. In second snippet `observableResults()` picks up the change in this table and emits changed item
3.  `subscribeOn(Schedulers.newThread())` is ignored somehow and thread remains to be android main thread.
4. `apiSyncRepository.upload(syncDb)` tries to `POST` change to API and throws `NetworkOnMainThreadException`

I was thinking that stream in `onSomeClick` method and stream in background service are mutually independent, meaning that Scheduler from `onSomeClick` (in this case android main thread) should not be applied to `observableResults()` and somehow it is. And since I've put `blockingSingle()` in background service, `onSomeClick()` method is blocked until upload completes..

I might be wrong, but I think that `observableResults()` on some table should not pick up the Scheduler from which `table.insert` is called.

If necessary I can write down some tests to reproduce this issue.

**Comment by npurushe** [comment]
The observable result is triggered from a RxJava `Subject`. So if you don't assign any scheduler via `observeOn` then it will be observed on the thread where the transaction originated. You cannot change the scheduler used for subscription using `subscribeOn`, because of the way subjects work. 

On Android you should ensure you use `subscribeOn` to do all database writes on a background thread then there is no case where the observableResult would be triggered on the main thread. You can also use `observeOn` to switch to a background thread scheduler do network I/O and then switch back to the main thread with another `observeOn` after you have a result. See http://reactivex.io/documentation/operators/subscribeon.html for more info.

Hope that makes sense.

**Comment by bajicdusko** [comment]
It makes sense of course. 

> The observable result is triggered from a RxJava Subject. So if you don't assign any scheduler via observeOn then it will be observed on the thread where the transaction originated.

This statement clears it up and confirms my doubts on how it works since the transaction is originated at `insert` call.
I just thought that once the database writes are finished, observable result will be started as new stream where we can call `subscribeOn`

Thank you for your time.
