### ISSUE TITLE
How can I see whats wrong when the gradle build fails and the Model class is not generated?

### ISSUE THREAD

**Issue by martijndebruijn** [requery/requery#49]
I've added the proper annotations to my model classes. First I had some error pointing to wrong annotations. I fixed these errors but not the gradle build still fails. The Models.class and the *Entity classes are not generated. 
How can I see what is going wrong?

(I'm using annotates classes instead op interfaces as in the example)

**Comment by npurushe** [comment]
Hava a look at [APT setup](https://github.com/requery/requery/wiki/Gradle-&-Annotation-processing) did you add the processor with an APT plugin? If so any errors from the gradle output during the build?

**Comment by martijndebruijn** [comment]
Yes, I used the APT setup as described. How can I trigger the APT generation explicitly?

**Comment by npurushe** [comment]
What's the output of `gradle build` from the terminal in your project?

**Comment by martijndebruijn** [comment]
Nikhil,
This is the output of the gradle build.

13:45:43: Executing external task 'build'...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDemoDebugBuild UP-TO-DATE
:app:checkDemoDebugManifest
:app:preDemoReleaseBuild UP-TO-DATE
:app:preHotnetworkzDebugBuild UP-TO-DATE
:app:preHotnetworkzReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2320Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72320Library UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2320Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2320Library UP-TO-DATE
:app:prepareComGithubCastorflexSmoothprogressbarLibrary110Library UP-TO-DATE
:app:prepareComGithubDmytrodanylykAndroidProcessButtonLibrary104Library
UP-TO-DATE
:app:prepareComGithubFlavienlaurentDatetimepickerLibrary002Library
UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareComJakewhartonHugoHugoRuntime121Library UP-TO-DATE
:app:prepareComProlificinteractiveMaterialCalendarview120Library UP-TO-DATE
:app:prepareDeHdodenhofCircleimageview200Library UP-TO-DATE
:app:prepareIoReactivexRxandroid110Library UP-TO-DATE
:app:prepareIoRequeryRequeryAndroid100Beta3Library UP-TO-DATE
:app:preparePlCharmasAndroidAndroidReactiveLocation08Library UP-TO-DATE
:app:prepareDemoDebugDependencies
:app:compileDemoDebugAidl
:app:compileDemoDebugRenderscript
:app:generateDemoDebugBuildConfig
:app:generateDemoDebugAssets UP-TO-DATE
:app:mergeDemoDebugAssets
:app:generateDemoDebugResValues UP-TO-DATE
:app:generateDemoDebugResources
:app:mergeDemoDebugResources
:app:processDemoDebugManifest
:app:processDemoDebugResources
:app:generateDemoDebugSources
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\MainApplication.java:15:
error: cannot find symbol
import com.staffplanners.android.model.Models;
                                      ^
  symbol:   class Models
  location: package com.staffplanners.android.model
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\services\LocationMonitoringService.java:8:
error: cannot find symbol
import com.staffplanners.android.model.AgendaGpsMonitoringEntity;
                                      ^
  symbol:   class AgendaGpsMonitoringEntity
  location: package com.staffplanners.android.model
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\services\GpsMonitoringIntentService.java:12:
error: cannot find symbol
import com.staffplanners.android.model.AgendaGpsMonitoringEntity;
                                      ^
  symbol:   class AgendaGpsMonitoringEntity
  location: package com.staffplanners.android.model
:app:compileDemoDebugJavaWithJavac FAILED
:app:compileRetrolambdaDemoDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDemoDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: invalid class name identifier

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

Total time: 8.741 secs
invalid class name identifier
13:45:51: External task execution finished 'build'.


2016-03-18 16:24 GMT+01:00 Nikhil Purushe <notifications@github.com>:

> What's the output of gradle build from the terminal in your project?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/requery/requery/issues/49#issuecomment-198408081>
>



-- 


E. mdebruijn@novumsoftware.nl
M. 06 - 55 713 186

  <http://www.plamo.nl>

**Comment by npurushe** [comment]
Thanks that helps. The problem is indicated here:

* What went wrong:
Execution failed for task ':app:compileDemoDebugJavaWithJavac'.
 java.lang.IllegalArgumentException: invalid class name identifier

So a couple of possible causes are. Using the Entity(name = "something") where something is not valid class name, are you specifying that anywhere?

If you run it with `gradle build --stacktrace` that will help pinpoint the exact problem, thanks

**Comment by martijndebruijn** [comment]
The output with stacktrace:


gradlew build --stacktrace
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDemoDebugBuild UP-TO-DATE
:app:checkDemoDebugManifest
:app:preDemoReleaseBuild UP-TO-DATE
:app:preHotnetworkzDebugBuild UP-TO-DATE
:app:preHotnetworkzReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2320Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72320Library UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2320Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2320Library UP-TO-DATE
:app:prepareComGithubCastorflexSmoothprogressbarLibrary110Library UP-TO-DATE
:app:prepareComGithubDmytrodanylykAndroidProcessButtonLibrary104Library
UP-TO-DATE
:app:prepareComGithubFlavienlaurentDatetimepickerLibrary002Library
UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareComJakewhartonHugoHugoRuntime121Library UP-TO-DATE
:app:prepareComProlificinteractiveMaterialCalendarview120Library UP-TO-DATE
:app:prepareDeHdodenhofCircleimageview200Library UP-TO-DATE
:app:prepareIoReactivexRxandroid110Library UP-TO-DATE
:app:prepareIoRequeryRequeryAndroid100Beta3Library
:app:preparePlCharmasAndroidAndroidReactiveLocation08Library UP-TO-DATE
:app:prepareDemoDebugDependencies
:app:compileDemoDebugAidl UP-TO-DATE
:app:compileDemoDebugRenderscript UP-TO-DATE
:app:generateDemoDebugBuildConfig UP-TO-DATE
:app:generateDemoDebugAssets UP-TO-DATE
:app:mergeDemoDebugAssets UP-TO-DATE
:app:generateDemoDebugResValues UP-TO-DATE
:app:generateDemoDebugResources UP-TO-DATE
:app:mergeDemoDebugResources
:app:processDemoDebugManifest
:app:processDemoDebugResources UP-TO-DATE
:app:generateDemoDebugSources UP-TO-DATE
:app:compileDemoDebugJavaWithJavac
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\MainApplication.java:15:
error: cannot find symbol
import com.staffplanners.android.model.Models;
                                      ^
  symbol:   class Models
  location: package com.staffplanners.android.model
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\services\LocationMonitoringService.java:8:
error: cannot find symbol
import com.staffplanners.android.model.AgendaGpsMonitoringEntity;
                                      ^
  symbol:   class AgendaGpsMonitoringEntity
  location: package com.staffplanners.android.model
C:\Users\mdebruijn\Dropbox\plamogit\plamo-paas\android\AndroidApp\app\src\main\java\com\staffplanners\android\services\GpsMonitoringIntentService.java:12:
error: cannot find symbol
import com.staffplanners.android.model.AgendaGpsMonitoringEntity;
                                      ^
  symbol:   class AgendaGpsMonitoringEntity
  location: package com.staffplanners.android.model
:app:compileDemoDebugJavaWithJavac FAILED
:app:compileRetrolambdaDemoDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDemoDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: invalid class name identifier

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task
':app:compileDemoDebugJavaWithJavac'.
        at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at
org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at
org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at
org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at
org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at
org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at
org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at
org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at
org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at
org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at
org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at
org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at
org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at
org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at
org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at
org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at
org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at
org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at
org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at
org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at
org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at
org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at
org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at
org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at
org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at
org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at
org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at
org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at
org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at
org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at
org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at
org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at
org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at
org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at
org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at
org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at
org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at
org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at
org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
        at
org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at
org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at
org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at
org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at
org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at
org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at
org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at
org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at
org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at
org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at
org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at
org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at
org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at
org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at
org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at
org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at
org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException:
invalid class name identifier
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at
com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at
com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at
org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
        at
org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at
org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
        at
org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
        at
org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
        at
org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
        at
org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at
org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
        at
org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
        at
org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at
com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at
org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
        at
org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at
org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
        at
org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: java.lang.IllegalArgumentException: invalid class name identifier
        at io.requery.processor.QualifiedName.<init>(QualifiedName.java:68)
        at
io.requery.processor.EntityGraph.referencingEntity(EntityGraph.java:99)
        at
io.requery.processor.EntityGraphValidator.validateEntity(EntityGraphValidator.java:67)
        at
io.requery.processor.EntityGraphValidator.validate(EntityGraphValidator.java:50)
        at
io.requery.processor.EntityProcessor.process(EntityProcessor.java:102)
        at
com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at
com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at
com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at
com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at
com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at
com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1173)
        at
com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:859)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 80 more


BUILD FAILED

Total time: 18.118 secs


2016-03-19 14:28 GMT+01:00 Nikhil Purushe <notifications@github.com>:

> Thanks that helps. The problem is indicated here:
>
>    - What went wrong: Execution failed for task
>    ':app:compileDemoDebugJavaWithJavac'. java.lang.IllegalArgumentException:
>    invalid class name identifier
>
> So a couple of possible causes are. Using the Entity(name = "something")
> where something is not valid class name, are you specifying that anywhere?
>
> If you run it with gradle build --stacktrace that will help pinpoint the
> exact problem, thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/requery/requery/issues/49#issuecomment-198703532>
>



-- 


E. mdebruijn@novumsoftware.nl
M. 06 - 55 713 186

  <http://www.plamo.nl>

**Comment by npurushe** [comment]
Thanks that narrows down, and I will change to be a warning/error in the processor so there is no exception. From the stack track it looks like there is an invalid name in your @ForeignKey annotation, are you specifying that somewhere e.g. @ForeignKey(references = "")?

**Comment by martijndebruijn** [comment]
Thanks for your reply. I only have @ForeignKey annotations without
parameters.

2016-03-19 15:31 GMT+01:00 Nikhil Purushe <notifications@github.com>:

> Thanks that narrows down, and I will change to be a warning/error in the
> processor so there is no exception. From the stack track it looks like
> there is an invalid name in your @ForeignKey
> <https://github.com/ForeignKey> annotation, are you specifying that
> somewhere e.g. @ForeignKey <https://github.com/ForeignKey>(references =
> "")?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/requery/requery/issues/49#issuecomment-198713130>
>



-- 


E. mdebruijn@novumsoftware.nl
M. 06 - 55 713 186

  <http://www.plamo.nl>

**Comment by npurushe** [comment]
Do you have any @ManyToOne annotations (without the @ForeignKey)?

**Comment by martijndebruijn** [comment]
Nikhil,
That solved my problem. I had one @ManyToOne annotation without the
@ForeignKey.
Thanks.

2016-03-19 15:43 GMT+01:00 Nikhil Purushe <notifications@github.com>:

> Do you have any @ManyToOne annotations (without the @ForeignKey
> <https://github.com/ForeignKey>)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/requery/requery/issues/49#issuecomment-198714908>
>



-- 


E. mdebruijn@novumsoftware.nl
M. 06 - 55 713 186

  <http://www.plamo.nl>

**Comment by npurushe** [comment]
Great!
