### ISSUE TITLE
ManyToMany and list of ids

### ISSUE THREAD

**Issue by maxxx** [requery/requery#490]
Hello, i have next structure (parsed from backend api and therefore depends on it)
```
@Entity
public interface ClassOne
{
    List<Integer> getClassTwoIds();

    @JunctionTable()
    @ManyToMany()
    Set<ClassTwo> getClassTwoEntities();
}
```

---
```
@Entity
public interface ClassTwo
{
	@JunctionTable()
	@ManyToMany()
	Set<ClassOne> getClassOneEntities();
}
```

So JunctionTable should have several (getClassTwoIds().size()) entries with pairs ClassOne.id - ClassTwo.id. I know that it's may be a non normalized scheme, but still there is some way to [auto-]populate junction table from ClassOne.getClassTwoIds() (or make it less painful)? Also keys in JunctionTable are foreign so i can insert only after both class entities written to db (i.e. can't insert just after ClassOne and before ClassTwo).

**Comment by npurushe** [comment]
Hi only one side of the ManyToMany should have the JunctionTable annotation. You can define the JunctionTable entity class yourself and have the keys be not foreign constrained. However then your db could be in state where ids are referring to table entries that do not exist.

Once you deserialize the ClassTwoIds you should create and insert/update corresponding ClassTwo entities ensuring they exist, that may be easier.
