### ISSUE TITLE
insert log statements are defect

### ISSUE THREAD

**Issue by DaRolla** [requery/requery#493]
hi there,

today I started with this wonderful tool. 

after some tiny issues I managed to create and insert some data.

now, taking a more precise look at my log I found out that the insert statements logs are defect.

Here comes my log (creating some tables, then adding some data)

	I/requery: beforeExecuteUpdate sql: create table Product (id integer primary key autoincrement not null, itemNumber varchar(255), name varchar(255), subCategory integer, foreign key (subCategory) references SubCategory (id) on delete cascade)
	I/requery: afterExecuteUpdate 0
	I/requery: preInsert {0}
	I/requery: beforeExecuteUpdate {0} sql:
			{1}
	I/requery: afterExecuteUpdate {0}
	I/requery: postInsert {0}
	I/requery: preInsert {0}
	I/requery: beforeExecuteUpdate {0} sql:
			{1}
	I/requery: afterExecuteUpdate {0}
	I/requery: postInsert {0}
	I/requery: preInsert {0}
	I/requery: beforeExecuteUpdate {0} sql:
			{1}
	I/requery: afterExecuteUpdate {0}
	I/requery: postInsert {0}
	I/requery: preInsert {0}
	I/requery: beforeExecuteUpdate {0} sql:
			{1}
	I/requery: afterExecuteUpdate {0}
	I/requery: postInsert {0}

best regards,
DaRolla

**Comment by npurushe** [comment]
How did you enable logging? If you're using android you should use `databaseSource.setLoggingEnabled(true)` which uses an Android specific [LoggingListener](https://github.com/requery/requery/blob/master/requery-android/src/main/java/io/requery/android/LoggingListener.java). 

(The core logging listener uses `java.util.Logger`, unfortunately Android doesn't implement this API properly until the most recent versions, hence why there is also an Android specific one implemented using `android.util.Log`.)

**Comment by DaRolla** [comment]
yes, thats the documented way we use it.
in more detail we use this:
	final SqlCipherDatabaseSource source = new SqlCipherDatabaseSource(context, Models.DEFAULT, "test.db", databasePassword, 1);
	source.setLoggingEnabled(databaseLoggingEnabled);

**Comment by npurushe** [comment]
Right so with that you shouldn't have any issue. Or are you saying you still see these log statements? if so make sure you haven't enabled the other logging which is set from `useDefaultLogging` in the `ConfigurationBuilder` object,  e.g. it's not needed to call that on Android.

**Comment by DaRolla** [comment]
Well, I use the source.setLoggingEnabled(true) and my log looks like I posted above. That's the reason I opened this issue :-)

**Comment by npurushe** [comment]
Sorry wasn't able to reproduce on several versions of android, also using SqlCipher. Looking at the code in android it's using a logger that will not result in that output. If you have more info please post back thanks
