### ISSUE TITLE
@Collumn(nullable = false) with @ForeighKey() leads to missing NOT NULL

### ISSUE THREAD

**Issue by devoto13** [requery/requery#496]
I'm using `SchemaModifier.createTables()` to generate create table statements for the following structure:

```
@Entity
public abstract class AbstractAccount implements Persistable {
    @Key
    @Generated
    Long id;
}

@Entity
public abstract class AbstractApplication implements Persistable {
    @Key
    @Generated
    Long id;

    @Column(nullable = false)
    @ForeignKey(references = AbstractAccount.class)
    Long ownerId;
}
```

The problem is that, `NOT NULL` part is not being added to the `ownerId` column definition. If I remove `@ForeignKey()` annotation it adds `NOT NULL` correctly.

It seems to be related to the fact that `createForeignKeyColumn()` method doesn't check for nullability of the attribute as `createColumn()` [does](https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/sql/SchemaModifier.java#L532). Same issue applies to similar properties, like `DEFAULT`, `UNIQUE`, `PRIMARY KEY`, etc.

I'm using Requery 1.2.1 with PostgreSQL.

cc @alex-shpak

**Comment by npurushe** [comment]
Thanks for reporting this fix should be in the next upcoming update

**Comment by devoto13** [comment]
Great! Thank you for a quick fix :)

**Comment by npurushe** [comment]
version 1.3.0 contains this fix
