### ISSUE TITLE
OneToMany and ManyToOne

### ISSUE THREAD

**Issue by Gi-lo** [requery/requery#5]
Hey there,
Thirst of all thank you for this very nice library :+1: 

 Yet I am currently having an issues with implementing a ```OneToMany```and ```ManyToOne```relationship as follows:

```java
@Entity()
public interface Category {

    // Getters

    @Key
    @Generated
    int getId();

    @OneToMany(mappedBy = "category")
    Set<Record> getRecords();
}

@Entity
public interface Record {

    // Getters

    @Key
    @Generated
    int getId();

    @ManyToOne()
    Category getCategory();
}
```

At first it seems to work, but when I restart the application via Android Studio (and only then) the app crashes with the following stacktrace:

```java
FATAL EXCEPTION: java.lang.IllegalStateException                                                                                                                                                 
at io.requery.sql.EntityReader.associativeQuery(EntityReader.java:304)
at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:227)
at io.requery.sql.EntityReader.refresh(EntityReader.java:219)
at io.requery.sql.EntityReader.refresh(EntityReader.java:153)
at io.requery.sql.EntityReader.load(EntityReader.java:123)
at io.requery.proxy.EntityProxy.get(EntityProxy.java:96)
at  o.requery.proxy.EntityProxy.get(EntityProxy.java:80)
at xxx.models.RecordEntity.getCategory(RecordEntity.java:184)
```

Following the stacktrace leads to https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/sql/EntityReader.java#L304. Where I obtain the following code snippet:

```java
 case MANY_TO_ONE:
 default:
     throw new IllegalStateException();
```

**My question now is:**
Am **I** doing something completely wrong or have a basic misunderstanding here?
Or is this **feature yet to be implemented**?
Or is it even a **bug**?

Thanks in advance.

**Comment by npurushe** [comment]
Doesn't look like you're doing anything wrong. There does seem to be a bug here refreshing ManyToOne attributes will provide a fix today. Thanks for reporting!

**Comment by Gi-lo** [comment]
Awesomesouce :+1:

**Comment by npurushe** [comment]
Should be fixed in latest snapshot version thanks for reporting!
