### ISSUE TITLE
[Question] Passing null to OneToOne field

### ISSUE THREAD

**Issue by JuzTosS** [requery/requery#501]
Hi, I found some kind of non consistent behaviour.

The code:
```
@Entity
public interface Bar {

}

@Entity
public interface Foo {
    @ForeignKey
    @OneToOne
    Bar bar;
}
```

I have Foo object with `bar = null`.
I save it  `entityStore.upsert(foo);`
And then I get it back `entityStore.select(Foo.class).get()`
But the bar field is not null anymore it's a Bar object with null fields.

So the object I've saved to DB is not equal to object that I get from DB.

Is there a way to prevent this behaviour?

**Comment by npurushe** [comment]
Hi you should make your ForeignKey, nullable, e.g.

```java
@Entity
public interface Foo {
    @Column(nullable=true)
    @ForeignKey
    @OneToOne
    Bar bar;
}
```

That should make your OneToOne null on retrieval.

**Comment by JuzTosS** [comment]
Thanks!
