### ISSUE TITLE
No way to use Kotlin with Jackson

### ISSUE THREAD

**Issue by I60R** [requery/requery#502]
`EntityMapper` constructor requires `EntityStore` from package `io.requery`, but using Kotlin I have `EntityStore` from package `io.requery.kotlin`. They have same name and no inheritance relation.    
Please, fix that issue

**Comment by npurushe** [comment]
Hi thanks for reporting. The underlying java `EntityDataStore` will be made available in `KotlinEntityDataStore` so you can use it with the jackson mapper.
