### ISSUE TITLE
[Question] Passing null to OneToOne field

### ISSUE THREAD

**Issue by JuzTosS** [requery/requery#503]
Original question:
https://github.com/requery/requery/issues/501

Sorry, but setting `@Column(nullable=true)` didn't help me.
It still returns an object instead of null.

Interesting that `nullable=true` is set by default, so it shouldn't help.

The code:
```
    @Column(nullable = true)
    @ForeignKey
    @OneToOne
    @Nullable
    Foo getFoo();
    void setFoo(Foo foo);

```

**Comment by npurushe** [comment]
Hi yeah there may be a problem here if the key is a primitive type, (instead of a boxed type)

**Comment by JuzTosS** [comment]
Yep!
I changed all the id's to the boxed Long. And everything works fine now.

Before:
```
@Key
long getId();
```
After:
```
@Key
Long getId();
```

**Comment by JuzTosS** [comment]
Nice to see that bugs are getting fixed!
Thank you!
