### ISSUE TITLE
Supporting a logical NOT operator

### ISSUE THREAD

**Issue by spouzols** [requery/requery#507]
There does not seem to be support for a NOT operator at the moment at the same logical level as AND and OR (only negative operators essentially like NOT IN, NOT NULL etc.). Do you think it would be possible to add support for it, or to point to a preferred way to add it in the existing code base?

I open this as an issue as this may be probably introduced in different ways in the project.

This may not look as a big deal not to have this NOT operator but it makes it difficult to map an existing tree to an sql request using this library. And this would mean going back to JPA or another library to build the actual SQL query.

I have been tinkering a bit with the existing version, and after seeing the comment about the unary operators being handled for now as binary ones with a null right hand condition, here is current approach to have something handling it quickly in the where section:

- build upon `AndOr`, adding a `Not` interface and make `AndOr` extend it (for simplicity's sake but could be reused in parallel, even though all three usually go together)
```
public interface Not<Q> {
    Q not();
}
```
- handling the null righthand operand in `DefaultOutput` for unary operators, like in `appendOperation()`
```
            ...
        } else if(leftOperand instanceof Condition) {
            if (condition.getRightOperand() == null) {
                appendOperator(condition.getOperator());
                if (depth > 0) {
                    qb.openParenthesis();
                }
                appendOperation((Condition) leftOperand, depth + 1);
                if (depth > 0) {
                    qb.closeParenthesis();
                }
            } else {
                ...
```
- provide an `Unary` class with static `not` shorthand to be able to write `not(subject)` instead of `subject.not()`

Here is the test case I'm currently working with:

```
    @Test
    public void testSingleQueryWhereNot() {
        final String name = "firstName";
        final String email = "not@test.io";
        for (int i = 0; i < 10; i++) {
            Person person = randomPerson();
            switch (i) {
                case 0:
                    person.setName(name);
                    break;
                case 1:
                    person.setEmail(email);
                    break;
            }
            data.insert(person);
        }
        try (Result<Person> query = data.select(Person.class)
                .where(not(
                        Person.NAME.equal(name)
                            .or(Person.EMAIL.equal(email)))
                ).get()) {
            assertEquals(8, query.toList().size());
        }
    }
```

**Comment by npurushe** [comment]
Hi thanks for the detailed proposal. Yes this is something definitely that should be supported but is not currently. The advantage of having the not() on the expression is that in Kotlin for example that can be an overloaded operator so you could write !<expression>. That doesn't look nice in Java where your static function is better, however its possible to support both.

**Comment by npurushe** [comment]
Closing for now, thanks for the PR!
