### ISSUE TITLE
Subqueries

### ISSUE THREAD

**Issue by a-merkle** [requery/requery#51]
Hi, I am currently trying to build a select-statement with a subquery but I cannot find any methods for that. Is that not possible?  If not, is there an option for using raw queries? This wouldn't be a perfect solution but it could bypass my problem right now.

**Comment by npurushe** [comment]
Subqueries are supported both in the in clause and exists clause, for example:
```java
data.select(Person.class).where(Person.NAME.in( data.select(Group.NAME) )).get()
```
and also in the from clause
```java
data.select(NamedExpression.ofInteger("age").avg())
            .from( data.select(Person.AGE.sum().as("age") )
            .groupBy(Person.AGE).).get()
```
do you have an example of the query you are trying to make? Do you mean a query as one select argument?

**Comment by a-merkle** [comment]
Ah ok. I'm trying to make a select query inside a join clause, e.g.
`SELECT * FROM Person p LEFT JOIN (SELECT ... ) pt ON p.id = pt.person_id`

**Comment by npurushe** [comment]
Ok thanks for the example! will add support for that
