### ISSUE TITLE
android.database.sqlite.SQLiteException: too many SQL variables (code 1) when there are a lot of items in "IN" statement

### ISSUE THREAD

**Issue by simophin** [requery/requery#515]
We have a large set of IDs (talking about ~5000) to query from, so we use `Entity.ID.in(ids)` statement. It ends up with `android.database.sqlite.SQLiteException: too many SQL variables (code 1)`.

I understand it's probably an Android API problem, but is there a nice way to mitigate this without going into manual SQL constructing?

**Comment by KungfuPancake** [comment]
There is a hardcoded 999 variable limit for SQLite in Android. In case you're using RxJava: my suggestion would be to use a buffer to make individual querys and limit the set of IDs to ~999, then merge the results.

**Comment by simophin** [comment]
@KungfuPancake that's not a bad idea. I'm thinking if it's possible for requery to consider: 

1. Substitute the SQL itself to get around this limit, or
2. Provide a mean to turn off variable substitution, as in some cases we can be sure the data is safe to use (i.e. not from user input)

In case of rxjava, imagine I could do a combineLatest and spread the query out to several queries (taking 5 as example), but then it also double the memory usage: there will be 5 ~1000 size list floating around, and then every time data changes, they have to be copied into a 5000 size list. If requery is able to handle this, there will only be one 5000 size list.

**Comment by KungfuPancake** [comment]
@simophin The copy operations are certainly not ideal, but I fear it's the only way to handle it without resorting to manual SQL string building.

Making requery aware of this depends on how platform agnostic we want to be though. One could argue that requery should not know about any SQLite kinks and workarounds.

**Comment by npurushe** [comment]
The limit comes from sqlite itself (https://sqlite.org/limits.html) .That seems like a very large number of values. You may want to consider storing these ids into a temporary table and then querying the temp table. Maybe more efficient depending on how you are determining the ids list.

**Comment by simophin** [comment]
@npurushe Good read! I'm embarrassed not having read this beforehand...
