### ISSUE TITLE
Dagger 2 annotation processing problem

### ISSUE THREAD

**Issue by LeEnot** [requery/requery#516]
Using Requery v.1.3.0 and Dagger v.2.9
When Dagger can't produce some graph dependencies, it is printing its errors to console.
When I'm using Requery with Dagger, and such error occures, I can only see tons of Requery errors in console, like 'cannot find symbol class (here is requery generated entity name)' though all classes generated successfully. 
So, tldr: dagger can't generate graph -> no dagger errors in console (except the ones about missing dagger classes) -> lots of fake requery errors instead
May be this is due to wrong annotation processing order or smth? Really have no clue, if dagger won't report its errors it will be hard as hell to debug.

**Comment by npurushe** [comment]
If you are using gradle you may want to look at the output of `gradle build` directly instead of in an IDE. It maybe easier to find the source of the error that way. It is true if the annotation processor doesn't run then all code referencing the generated code will also show as an error, which can be confusing.

**Comment by LeEnot** [comment]
@npurushe there is also no useful info there. It was, but now only messages about not found entities (which are correctly generated)

**Comment by npurushe** [comment]
Unfortunately there is not really anything that can be done about this. From my experience the dagger errors (or any processor errors) are usually are visible from gradle build on the command line and once fixed allow other annotation processors to work as normal. If your not able to see them I would suggest cleaning your build (`gradle clean`), and maybe also disabling things like incremental compilation.
