### ISSUE TITLE
Project not compileable with versions 1.2, 1.3 entityes not created

### ISSUE THREAD

**Issue by Rufim** [requery/requery#518]
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\fragments\ObservableFragment.java:27: error: cannot find symbol
import ru.samlib.client.domain.entity.AuthorEntity;
                                     ^
  symbol:   class AuthorEntity
  location: package ru.samlib.client.domain.entity
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\job\ObservableUpdateJob.java:17: error: cannot find symbol
import ru.samlib.client.domain.entity.AuthorEntity;
                                     ^
  symbol:   class AuthorEntity
  location: package ru.samlib.client.domain.entity
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:30: error: cannot find symbol
    private JoinAndOr<Result<AuthorEntity>> getAuthorQuery() {
                             ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:37: error: cannot find symbol
    public AuthorEntity insertAuthor(AuthorEntity entity) {
                                     ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:37: error: cannot find symbol
    public AuthorEntity insertAuthor(AuthorEntity entity) {
           ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:41: error: cannot find symbol
    public AuthorEntity updateAuthor(AuthorEntity entity) {
                                     ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:41: error: cannot find symbol
    public AuthorEntity updateAuthor(AuthorEntity entity) {
           ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:45: error: cannot find symbol
    public AuthorEntity doActionAuthor(Action action, AuthorEntity Author) {
                                                      ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:45: error: cannot find symbol
    public AuthorEntity doActionAuthor(Action action, AuthorEntity Author) {
           ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:77: error: cannot find symbol
    public void deleteAuthor(AuthorEntity entity) {
                             ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:85: error: cannot find symbol
    public AuthorEntity getAuthorById(Integer id) {
           ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:89: error: cannot find symbol
    public AuthorEntity getAuthorByLink(String link) {
           ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\service\ObservableService.java:93: error: cannot find symbol
    public List<AuthorEntity> getObservableAuthors() {
                ^
  symbol:   class AuthorEntity
  location: class ObservableService
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:36: warning: This field does not exist, or would have been excluded anyway.
@EqualsAndHashCode(callSuper = false, exclude = {"rawContent", "rootElements", "chapters", "annotationBlocks", "indents"})
                                                               ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:36: warning: This field does not exist, or would have been excluded anyway.
@EqualsAndHashCode(callSuper = false, exclude = {"rawContent", "rootElements", "chapters", "annotationBlocks", "indents"})
                                                                               ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:37: warning: This field does not exist, or would have been excluded anyway.
@ToString(exclude = {"rawContent", "rootElements", "chapters", "annotationBlocks", "indents"})
                                   ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:37: warning: This field does not exist, or would have been excluded anyway.
@ToString(exclude = {"rawContent", "rootElements", "chapters", "annotationBlocks", "indents"})
                                                   ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:54: warning: 2 mappings found for: ru.samlib.client.domain.entity.WorkEntity.author -> ru.samlib.client.domain.entity.AuthorEntity
    Author author;
           ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Work.java:56: warning: 2 mappings found for: ru.samlib.client.domain.entity.WorkEntity.rootAuthor -> ru.samlib.client.domain.entity.AuthorEntity
    Author rootAuthor;
           ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Link.java:57: error: Entity reference missing relationship annotation
    public Author getAuthor() {
                  ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Link.java:29: warning: 2 mappings found for: ru.samlib.client.domain.entity.LinkEntity.rootAuthor -> ru.samlib.client.domain.entity.AuthorEntity
    Author rootAuthor;
           ^
E:\samlib\Samlib\Client\src\main\java\ru\samlib\client\domain\entity\Link.java:27: error: Entity reference missing relationship annotation
    Author author;
           ^
```
@NoArgsConstructor
@Data
@Entity
class Link {
    @Key @Generated
    Integer id;

    @ForeignKey
    @OneToOne(mappedBy = "site")
    Author authorSite;

    @Transient
    Author author;
    @ManyToOne(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    Author rootAuthor;
    @ManyToOne(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    Category category;

    String title;
    String link;
    String annotation;
}
```
As you see requery for some reason asked for  for relationship annotation in field that already have have transient annotation. Also I dont know if it is reason or not that all Entities not created.   

link to all entities: https://github.com/Rufim/Samlib/tree/master/Client/src/main/java/ru/samlib/client/domain/entity

**Comment by npurushe** [comment]
Hi thanks for reporting, this error will no longer be triggered if the attribute is transient. Fix will be in the next update

**Comment by npurushe** [comment]
1.3.1 has this change
