### ISSUE TITLE
substr function

### ISSUE THREAD

**Issue by a-merkle** [requery/requery#52]
Is the SQL substr function implemented somehow? I can't find it.

**Comment by npurushe** [comment]
Hi yes that is currently not in the function package, the reason being that different databases have different names for it `substr` vs `substring` and they sometimes have different arguments.
However you can easily create your own function that does that for now. Planning to add specific functions for each database in a future update.

```java
public class Substr<V> extends Function<V> {
    private final Expression<V> expression;
    private final int offset;
    private final int length;

    private Substr(Expression<V> expression, int offset, int length) {
        super("substr", expression.classType());
        this.expression = expression;
        this.offset = offset;
        this.length = length;
    }
    public static <U> Substr<U> substr(Expression<U> expression, int offset, int length) {
        return new Substri<>(expression, offset, length);
    }
    @Override
    public Object[] arguments() {
        return new Object[]{expression, offset, length};
    }
}
```
Then you can do : `substring(SomeTable.PROPERTY, 0, 5)` in queries.

**Comment by npurushe** [comment]
Looks like there was one small problem with the function args, so it won't work until the next update but it is fixed

**Comment by a-merkle** [comment]
Oh I see, thank you. I will give it a try with the next version.
