### ISSUE TITLE
efficiently load entire parent/child model to memory

### ISSUE THREAD

**Issue by 2x2xplz** [requery/requery#521]
What would be the most efficient way of populating a model with a parent/child relationship from database to memory? For example, my League model contains a set of Teams, each of which contain a set of Players. When my app starts, it should load all the Teams and Players from the database. Requery is trying to help by SELECTing the Players every time I SELECT a team -- but this actually results in  hundreds of SELECTs, due to [issue #446](https://github.com/requery/requery/issues/446), and slows down the app startup time significantly.

(using Kotlin)

    @Entity
    abstract class AbstractTeam : Parcelable, Persistable {
    
      @get:Key
      abstract val TeamID: Int

      abstract val TeamName: String
      abstract val TeamCity: String

      @get:OneToMany(mappedBy = "team")
      abstract val Players: MutableSet<AbstractPlayer>
    }

    @Entity
    abstract class AbstractPlayer : Parcelable, Persistable {

      @get:Key
      abstract val PlayerID: Int

      abstract val PlayerName: String
      abstract val PlayerPosition: String

      //    @get:ForeignKey  // tried with and without
      @get:ManyToOne
      abstract val Team: AbstractTeam
    }

On startup, the app SELECTs the entire Team table, then the entire Player table and iterates through it:

    // pseudo-code
    val players = data.select(Player::class).toList()
    for (team in data.select(Team::class).toList()) {
      // it.player.Team is not accessible as Int, even though that's what it is in database (issue #466)
      // it.player.Team.TeamID requires 2 SELECTs
      for (player in players.filter { it.player.Team.TeamID == team.TeamID }) {
        team.add(player)
      }
      League.teams.add(team)
    }

With the hundreds of SELECTs, the app startup time is north of 10 seconds on older devices. How can I do this more efficiently with requery? Thanks.

**Comment by npurushe** [comment]
When you load a Team instance the Team's players will not be loaded unless you call the Team.Players accessor. So selecting just the Teams won't actually load any players. How is that related to #446 ?

Why do you need to load everything into memory? In general you should load things only as they are needed and used on demand.

**Comment by 2x2xplz** [comment]
Agreed, selecting Teams won't load the Players. But when I do load the players and attempt to assign them to the teams, the line `players.filter { it.player.Team.TeamID == team.TeamID }` results in SELECTs. It is similar to #446 because requery saves the foreign key in the database, as an Int, in the "team" column of the "players" table. But requery won't allow me to access that field as an integer, (and do an easy equality comparison) only as a full Team object (as far as I can tell) which it must SELECT.

The decision to load the entire model into memory is a design decision that has worked for earlier versions of our app (with no ORM/DAO) and kept it speedy. On app startup, the entire model is loaded from the database. Part of that is due to making large amounts of the model available to users via List/Recycler and other views -- instead of selectively loading 60%, one SQL command per object, we just load the entire model (select * from teams, select * from players, iterate, done). After that, the only interaction with the database is persisting new/changed objects and properties. I understand this may not be the most traditional or common pattern but it works for this particular app.

**Comment by npurushe** [comment]
Hi I think the best solution for your case is to remove `@ManyToOne` and instead do something like

```kotlin
@get:ForeignKey  
val TeamId: Int
```

That is you don't need to use the requery's relationship management if it doesn't fit your use case. You can map onto the table columns directly as they are.
