### ISSUE TITLE
Can't add an index on a newly added column

### ISSUE THREAD

**Issue by tasn** [requery/requery#524]
Hi,

I've tried adding this to my *existing* model:

        @Index("some_index")
        @ForeignKey(update = ReferentialAction.CASCADE)
        @ManyToOne
        Service serviceModel;

I use it to create a "unique together" index on a few columns. However, it doesn't work. I keep on getting:

    java.lang.RuntimeException: Unable to start receiver com.etesync.syncadapter.App$AppUpdatedReceiver: io.requery.PersistenceException: java.sql.SQLException: android.database.sqlite.SQLiteException: table Journal has no column named serviceModel (code 1): , while compiling: create index if not exists journal_unique_together on Journal (serviceModel, uid)

I have another model to which I only added the index (the field existed already) and it works there. Also, if I remove the @Index directive, it correctly adds the column, so it's definitely not a problem there.

In addition, adding a new model with a unique together index works, which leads to the conclusion, the problem only occurs when adding a column and an index to an already existing model.

Please let me know if I'm doing anything wrong or if you need more information.

Thanks.

**Comment by npurushe** [comment]
Looks like the `serviceModel` column doesn't exist which would happen if your database wasn't updated to match the current model.

For Android you need to increment the schema version to make a change. For regular java projects run the `SchemaModifier` with `TableCreationMode.CREATE_NOT_EXISTS`

**Comment by tasn** [comment]
Hey,

Please reopen, as I said, if I remove the index directive, it correctly creates the column. Please re-read the text, I tested a few paths that lead me to this conclusion, I know I need to update the schema version (and I did).

**Comment by npurushe** [comment]
1.3.1 has this change

**Comment by tasn** [comment]
Thanks.
