### ISSUE TITLE
Unique constraint on a column doesn't get removed

### ISSUE THREAD

**Issue by tasn** [requery/requery#525]
Hi,

I had a column like such:

        @Column(length = 64, nullable = false, unique = true)
        String uid;

I changed it to:

        @Column(length = 64, nullable = false)
        String uid;

hoping the unique constraint would be dropped. Unfortunately it wasn't the column is still unique. This should probably happen automatically. Any suggested workarounds in the meanwhile?

Thanks,
Tom.

**Comment by Pedramrn** [comment]
In database world, any change to models should happens and instructed with a _migration_.

**Comment by tasn** [comment]
@Pedramrn, some changes (like column additions) are automatic in requery, and changes as described above are automatic in Django, so I find it difficult to agree with your statement.

Regardless, I googled for "requery migrations" before posting it, because that's an obvious workaround, but I found nothing.

Got any info?

Thanks.

**Comment by tasn** [comment]
OK, I figured out I need to write my own SQL. PITA, but did it.

Thanks.

**Comment by npurushe** [comment]
requery supports additive changes to a database model. That is you can add columns/indexes and it will generate the sql to create them when you update your model schema version. 

Dropping columns/indexes are a more complex case because existing data will be lost. Additionally the only way to figure that a column/index has been removed is to diff all the columns/indexes against the existing structure of the database which can be an expensive operation.

**Comment by tasn** [comment]
@npurushe, thanks for your comment. That's why a workflow like in "django" is nice. You decide when you want to make a migration, and then it creates the source code that is needed to make that migration. This is clean, efficient and works very well.

**Comment by Pedramrn** [comment]
I personally like workflows for database migration in django and laravel, But I haven't seen something close to them in java world.
Take look at dbflow, it has some migration support built in.

**Comment by tasn** [comment]
Thanks for the recommendation, but I'm already too invested in requery, migration seems unlikely.

The migration workflows for django are do-able for java too, I don't see any reason why it wouldn't be possible to run an external script that generates the migration code for you.
