### ISSUE TITLE
[Question] Why doesn't work disable cascade with CascadeAction.NONE?

### ISSUE THREAD

**Issue by TomazMartins** [requery/requery#526]
Hi,
I have 3 entities in my project and they looks like with this:

```java
@Table( name = "Task" )
@Entity( name = "TaskEntity" )
public interface ITaskEntity extends Persistable {
    @Key @Generated
    int getId();

    String getTitle();

    @ForeignKey
    @OneToOne
    ICycleEntity getCycle();
}
```
```java
@Table( name = "Cycle" )
@Entity( name = "CycleEntity" )
public interface ICycleEntity extends Persistable {
    @Key @Generated
    int getId();

    String getName();

    @Convert( ListOfLongConverter.class )
    List<Long> getIncrements();

    @ForeignKey
    @OneToOne
    IAlarmEntity getAlarm();

    @OneToOne( mappedBy = "cycle" )
    ITaskEntity getTask();
}
```
```java
@Table( name = "Alarm" )
@Entity( name = "AlarmEntity" )
public interface IAlarmEntity extends Persistable {
    @Key @Generated
    int getId();

    @Convert( CalendarConverter.class )
    Calendar getCalendar();

    @OneToOne( mappedBy = "alarm" )
    ICycleEntity getCycle();
}
```

In my code, to create a Task with `dataStore.insert( task )`, first I create a Cycle with `dataStore.insert( cycle )` and an Alarm, with the method `insert()` too. But, when I checked the log what I saw it was:

```
I/requery: beforeExecuteUpdate sql: create table Alarm (id integer primary key autoincrement not null, calendar varchar(255))
I/requery: afterExecuteUpdate 0
I/requery: beforeExecuteUpdate sql: create table Cycle (id integer primary key autoincrement not null, alarm integer, increments varchar(255), name varchar(255), foreign key (alarm) references Alarm (id) on delete cascade)
I/requery: afterExecuteUpdate 0
I/requery: beforeExecuteUpdate sql: create table Task (id integer primary key autoincrement not null, cycle integer, title varchar(255), foreign key (cycle) references Cycle (id) on delete cascade)
I/requery: afterExecuteUpdate 0
I/ALERT: On Insert Alarm
I/requery: beforeExecuteUpdate sql: insert into Alarm (calendar) values (?)
I/requery: afterExecuteUpdate 1
I/ALERT: On Insert Cycle
I/requery: beforeExecuteUpdate sql: insert into Alarm (calendar) values (?)
I/requery: afterExecuteUpdate 1
I/requery: beforeExecuteUpdate sql: insert into Cycle (alarm, increments, name) values (?, ?, ?)
I/requery: afterExecuteUpdate 1
I/ALERT: On Insert Task
I/requery: beforeExecuteUpdate sql: insert into Alarm (calendar) values (?)
I/requery: afterExecuteUpdate 1
I/requery: beforeExecuteUpdate sql: insert into Cycle (alarm, increments, name) values (?, ?, ?)
I/requery: afterExecuteUpdate 1
I/requery: beforeExecuteUpdate sql: insert into Task (cycle, title) values (?, ?)
I/requery: afterExecuteUpdate 1
```
So, I researched and I found that we can use the annotation option `@OneToOne( cascade = CascadeAction.NONE )`, because I thought that it was the problem. The code changed like this:

```java
// In Task class
   [...]
    @ForeignKey
    @OneToOne( cascade = CascadeAction.NONE )
    ICycleEntity getCycle();
   [...]

// In Cycle class
   [...]
    @ForeignKey
    @OneToOne( cascade = CascadeAction.NONE )
    IAlarmEntity getAlarm();

    @OneToOne( mappedBy = "cycle" )
    ITaskEntity getTask();
   [...]

// In Alarm class
   [...]
    @OneToOne( mappedBy = "alarm" )
    ICycleEntity getCycle();
   [...]
```

But, after run, the result was the same.

What did I do wrong? I forgot something?

Best regards

**Comment by npurushe** [comment]
What's your expected outcome for this change? If it's about the order of insertion, that order has to be maintained because of the foreign key relation ships between your entities.

**Comment by TomazMartins** [comment]
I expected that, in the end of the operation, had only one entity of each type. But, the log shown that there are 3 Alarms, 2 Cycles and 1 Task. 

For default, Requery use `CascadeAction.SAVE`. What I understood is that when I insert an entity with another entity associated, the Requery will persist the two entities, in `CascadeAction.SAVE`. With the `CascadeAction.NONE` I expected that only the entity I insert would be persisted.

When I insert a Task the effect is a insertion of the 2 others types, but I want insert only a Task.
The same to the Cycle. When I insert a Cycle I want persist only the Cycle, but an Alarm is persisted too.

I expected that the log would show me something like that:

```
I/requery: beforeExecuteUpdate sql: create table Alarm (id integer primary key autoincrement not null, calendar varchar(255))
I/requery: afterExecuteUpdate 0
I/requery: beforeExecuteUpdate sql: create table Cycle (id integer primary key autoincrement not null, alarm integer, increments varchar(255), name varchar(255), foreign key (alarm) references Alarm (id) on delete cascade)
I/requery: afterExecuteUpdate 0
I/requery: beforeExecuteUpdate sql: create table Task (id integer primary key autoincrement not null, cycle integer, title varchar(255), foreign key (cycle) references Cycle (id) on delete cascade)
I/requery: afterExecuteUpdate 0
I/ALERT: On Insert Alarm
I/requery: beforeExecuteUpdate sql: insert into Alarm (calendar) values (?)
I/requery: afterExecuteUpdate 1
I/ALERT: On Insert Cycle
I/requery: beforeExecuteUpdate sql: insert into Cycle (alarm, increments, name) values (?, ?, ?)
I/requery: afterExecuteUpdate 1
I/ALERT: On Insert Task
I/requery: beforeExecuteUpdate sql: insert into Task (cycle, title) values (?, ?)
I/requery: afterExecuteUpdate 1
```

I understood the effects of Cascade wrong? If yes, what I must do to have the results that I expect?

Thanks for the fast reply!

**Comment by npurushe** [comment]
Have you associated these objects to each other? sounds like they were not. If the objects are associated you only need to insert the main entity once (with the default cascade mode)

**Comment by TomazMartins** [comment]
The problem is exactly  this. I want create a Task. This object is associated with a Cycle which, in turn, is associated with an Alarm. I need configure it before to associated it this with the Cycle. The same thing to the Cycle and Task.

The process is:
(1)create Alarm -> (2)configure Alarm -> (3)insert Alarm -> 
(4)create Cycle -> (5)configure Cycle -> (6)associate Cycle with Alarm -> (7)insert Cycle ->
(8)create Task -> (9)configure Task -> (10)associate Task with Cycle -> (11)insert Task.

The problem:
In step (7) a Cycle and another Alarm were persisted, not only the Cycle. In step (11) a Task was insert, but another Cycle and Alarm too. In the end of the process I have: 1 Task, 2 Cycles and 3 Alarms, because cascade effect. But I want only one of the entities. In step (7) and (11), because of cascade, I end up persisting a Alarm and a Cycle again.

I thought that I can insert a Task and, with default cascade mode, a Cycle and Alarm are persisted too, like you said. And, after that, I would update this entities with the configurations, but, if I did this I must change the code.

So, I saw that Requery has how to disable the cascade mode, and it would enable me to insert and associate the entities manualy, that would cost me less work.

The change what I did in code was what I said: I added the option `cascade = CascadeAction.NONE` in annotation `@OneToOne`. But it didn't work. I did something wrong or I forgot something?

**Comment by TomazMartins** [comment]
@npurushe, it will be great! Thank you for the attention.

**Comment by npurushe** [comment]
1.3.2 has this change thanks

**Comment by TomazMartins** [comment]
Wow!

Very fast! Thank you for the support!
