### ISSUE TITLE
Cant get it to work with Kotlin

### ISSUE THREAD

**Issue by artkoenig** [requery/requery#528]
Created a new Kotlin project (runtime 1.1.0), added this lines to the build.gradle

```
dependencies {
    compile "io.reactivex.rxjava2:rxjava:2.0.1"
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.requery:requery:1.3.0'
    compile 'io.requery:requery-android:1.3.0'
    compile 'io.requery:requery-kotlin:1.3.0'
    kapt 'io.requery:requery-processor:1.3.0'
}
```

added this lines to my Activity's `onCreate` method (just for testing):

```
val source = DatabaseSource(this, Models.DEFAULT, 1)
source.setTableCreationMode(TableCreationMode.DROP_CREATE)
val data = KotlinReactiveEntityStore<Persistable>(KotlinEntityDataStore(source.configuration))
data.count(Test::class)
```
my entity:

```
@Entity
interface Test : Parcelable, Persistable {
	@get:Key
	@get:Generated
	val id: Int
}
```

the database is not going to be created, no errors in LogCat, no exceptions...

**Comment by npurushe** [comment]
Why do you think the database is not created? most likely it was as this example looks ok

**Comment by artkoenig** [comment]
I checked the data folder of my application, there is no "databases" directory and no database here.

**Comment by artkoenig** [comment]
It is just an example to reproduce the problem. In my real world application I encounter the problem, too. I spent hours trying to find the problem. I also tried to set breakpoints in your code: e.g. `onCreate` method of the `DatabaseSource` is never called in my case, still looking for the cause...

**Comment by artkoenig** [comment]
Here some new results:

Reading data do not creates database.
Writing data with

```
val test = Test()
data.insert(test).doOnSuccess {...}
```

does nothing. Writing data with

```
data.insert(Test::class).doOnSuccess {...}
```

produces an SQLiteException because the generated SQL statement is "insert into Test" and not "insert into Test default values"

```
val test = Test()
test = data.insert(test).blockingGet()
```

works, but it's blocking.

**Comment by npurushe** [comment]
Right if you are using KotlinReactiveEntityStore then the observables are cold and you must subscribe to them for anything to happen. The insert fails because you have entity with only a generated key and no other columns. There is a fully working Kotlin example here https://github.com/requery/requery/tree/master/requery-android/example-kotlin
Hope that helps!
