### ISSUE TITLE
Missing space in query

### ISSUE THREAD

**Issue by a-merkle** [requery/requery#53]
When using aliases in some cases the generated sql query is not valid because of a missing space.
Example:
`data.select(Person.LAST_NAME).from(data.select(Person.LAST_NAME).as("l_name"))
.groupBy(Person.LAST_NAME)`
Well, this is a somewhat hypothetical example but it will result in this sql query:
`select lastname from (select lastname from Person) l_namegroup by lastname`
You can avoid that by adding a trailing white space to the alias but it's still a bug I think. ;-)

**Comment by npurushe** [comment]
Thanks for reporting! yup definitely a bug
