### ISSUE TITLE
How to add Map<String,Data> to Entity

### ISSUE THREAD

**Issue by 3DRaven** [requery/requery#531]
I need to do this:

@Entity
abstract public class AbstractMessage implements Persistable {
    @Key
    @Generated
    int id;

    @OneToMany
    //Not use Set<MessageData>!
    Map<String,MessageData> data;
}

@Entity
public interface MessageData {

    @Key
    @Generated
    int getId();

    String getValue();
    @ManyToOne
    Message getMessage();
}

How to do it right? How to insert this Message? How to select this Message?

**Comment by npurushe** [comment]
Hi currently Map collections are not supported, but that is on the roadmap for a future release
