### ISSUE TITLE
How to observe table changes wothout select or count?

### ISSUE THREAD

**Issue by 3DRaven** [requery/requery#535]
Is there any way to know that the table has changed without requesting its contents?

**Comment by Rainer-Lang** [comment]
Maybe implement a mechanism to observe insert/update/delete statements on tables.
Like in https://github.com/pushtorefresh/storio

**Comment by 3DRaven** [comment]
thanks I got it :)

**Comment by npurushe** [comment]
You can do this already with `TransactionListener` you will get a list of any types changed during a transaction. Which can easily be turned into an Observable. You can supply the creator of the listener with `Configuration.addTransactionListenerFactory()`

**Comment by 3DRaven** [comment]
Thanks!
