### ISSUE TITLE
Abstract entity with Databinding

### ISSUE THREAD

**Issue by LipeDuoli** [requery/requery#536]
When I create a entity abstract class like this
```
import android.databinding.Bindable;
import android.databinding.Observable;
import android.os.Parcelable;

import io.requery.Entity;
import io.requery.Generated;
import io.requery.Key;
import io.requery.Persistable;

@Entity
abstract class AbstractList implements Observable, Parcelable, Persistable {

    @Key @Generated
    Integer id;

    @Bindable
    String name;

}
```
the generated class have a error:
`Error:(24, 8) error: List is not abstract and does not override abstract method removeOnPropertyChangedCallback(OnPropertyChangedCallback) in Observable`

If I create the same entity as a interface, the generated code works without any error.

**Comment by npurushe** [comment]
In your case since your entity is abstract you want to extend `android.databinding.BaseObservable` instead of just implementing `Observable`. BaseObservable provides the implementation of those methods.

**Comment by LipeDuoli** [comment]
Hi,
Yep... Make the change and now it works without error.

Thanks for the fast reply.
