### ISSUE TITLE
RecyclerView shows only data first start after uninstalling.

### ISSUE THREAD

**Issue by Borkason** [requery/requery#537]
I took your example and modified it a little. The issue is that the RecyclerView (RV) only shows data on the very first run. When I close the app and restart it, the RV is empty. Only after clearing the storage data, or uninstalling and reinstalling the app, the RV shows data again.

I have no idea where to start troubleshooting because I don't see any error message. And because I am new to android development, too.

Could you give me a hint? Project is here: https://github.com/Borkason/Gladstone

**Comment by npurushe** [comment]
Does the query that is run return empty results? Or is it maybe a UI display problem?

**Comment by npurushe** [comment]
looks like you're not calling `adapter.queryAsync();` when the activity is shown
