### ISSUE TITLE
How to check entity state (new, modified, loaded etc) ?

### ISSUE THREAD

**Issue by codingworkshopru** [requery/requery#538]
How can I check whether entity has been modified with its one-to-many children? I know that those states exist but I don't know how to get them with public methods/fields. Thank you.

**Comment by npurushe** [comment]
You can use <Entity>$TYPE to do things like get the `EntityProxy` and query specific states, such as loaded, modified etc. Whats the reason you need that information? Typically the api users already knows this since they are modifying the entities directly.

**Comment by codingworkshopru** [comment]
Thank you for your answer. My entity modifies behind the scene with data binding and it wouild be convinient to ask entity if it has been modified.

**Comment by npurushe** [comment]
Ok that makes sense thanks!
