### ISSUE TITLE
Delete codition

### ISSUE THREAD

**Issue by sshutl** [requery/requery#539]
Does requery has any possibility to execute deletion query with condition like DELETE FROM table_name
WHERE condition; using built-in dsl query builder?

**Comment by consp1racy** [comment]
It's the same as querying but instead of `select` write `delete`. Don't forget to `call()` to actually perform the deletion.

    data.delete(Person.class).where(Person.AGE.between(20, 40)).get().call();

https://github.com/requery/requery/wiki/Query-examples
