### ISSUE TITLE
VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY VERY BAD DOCUMENTATION!

### ISSUE THREAD

**Issue by elvisfromsouth** [requery/requery#541]
PLEASE WRITE **GOOD** DOCUMENTATION FOR REQUERY!!!!!!!!!!!!!!!!!!!!!!

**Comment by elvisfromsouth** [comment]
PLEEEEEEEEEEEEEEEEEEEEEEEEASE

**Comment by npurushe** [comment]
Hi please only open issues on specific bugs or improvements, just saying something is bad is not really constructive, thanks.

**Comment by consp1racy** [comment]
@elvisfromsouth Next time be specific. If you're already using Requery feel free to contribute and make documentation better.

**Comment by linheimx** [comment]
run the demo,and u will find your question!
