### ISSUE TITLE
QueryLoader closing previous result even if it's the same result

### ISSUE THREAD

**Issue by Gericop** [requery/requery#545]
Here are two methods of `QueryLoader`:

```java
@Override
protected void onStartLoading() {
    if (result != null) {
        deliverResult(result);
    } else {
        forceLoad();
    }
}

@Override
public void deliverResult(Result<E> data) {
    if (isReset()) {
        if (result != null) {
            result.close();
        }
        return;
    }
    Result<E> previous = result;
    result = data;
    if (isStarted()) {
        super.deliverResult(result);
    }
    if (previous != null) {
        previous.close();
    }
}
```

As it is a `Loader`, it tries to use the previous results if available (`onStartLoading()`'s `deliverResult(result);`). This is cool, but the problem is that `deliverResult(...)` does not check whether the previous result is the same as the new one, and closes it anyway. This results in `IllegalStateException` when trying to use the same result again as it has been closed.

There's a quick fix for the problem in `deliverResult(...)`, instead of
```java
if (previous != null) {
    previous.close();
}
```
it should check whether the previous and current results are different objects:
```java
if (previous != null && previous != data) {
    previous.close();
}
```

**Comment by npurushe** [comment]
Thanks for the detailed bug report, yes that looks like the correct fix will update thanks
