### ISSUE TITLE
[Question] Use requery with ContentProvider

### ISSUE THREAD

**Issue by I60R** [requery/requery#547]
I want to share my db with other applications (and be notified when it changes using ContentObserver).
Is it possible && planned to be implemented?

**Comment by npurushe** [comment]
Hi yes it's definitely possible, you just have to implement ContentProvider interface through you can do this using requery's API. Normally you want to filter and only allow certain operations in a content provider (e.g. read only certain tables) generally it's more app specific.

You can get the Android cursor from a `Result` by doing 

```
final ResultSetIterator<E> iterator = (ResultSetIterator<E>) result.iterator()
Cursor c = iterator.unwrap(Cursor.class);
```
