### ISSUE TITLE
Having non persistant methods in the model

### ISSUE THREAD

**Issue by Pr0bability** [requery/requery#55]
Hello,

I am having troubles with grasping how to correctly implement methods for model entities that should not be persited (ie. helper functions to calculate something). I rewrote the code from interface to abstract class, added @Transient method, but it's crashing on NullPointerExceptions, even though if I call the get method for corresponding data it works.

Any idea what the problem could be here or how to do this correctly?

Thank you.

**Comment by npurushe** [comment]
Hi yes abstract classes will be easier in your case. What is null that causes the NullPointerException? If you have a stack trace that would help. Is it relations or objects that are not loaded yet? for that case you would need to add a null check and only invoke the method after those have been loaded

**Comment by Pr0bability** [comment]
Stack trace doesn't say much. The situation is this, I have an Entity, implemented as an abstract class, having several OneToMany relationships, implemented as Lists in the abstract class. Now, I want to have a method that calculates something from those lists.

The NullPointerException happens since the list is supposedly null, even though calling .getList returns the correct list.

**Comment by npurushe** [comment]
Ok that helps. Those list fields will be null initially. Relations are lazily loaded, calling the getter does load them which is why it works after that. You can do a few things, make sure you only call your method after they are refreshed/loaded. You can also load them also by calling`data.refresh(Entity.RELATION)`, if you don't want to got the db to often you can combine that with a null or empty check.

**Comment by Pr0bability** [comment]
Well the thing is, at the place I need to use the function I do not even have access to the data source. With null checks, the function doesn't work as I want it to.

**Comment by npurushe** [comment]
So when you call getList() the proxy class will then set the variable in your entity class to an instance of io.requery.util.ObservableList. Is that member of your class still null after calling getList()? if so what type of list is getList() returning? is it possible that the method is called on an instance where getList() wasn't called yet?

**Comment by Pr0bability** [comment]
The list is declared as 
` @OneToMany(mappedBy = "medication", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<MedicationTimes> medicationTimes;`

And yes, after calling getMedicationTimes() and then calling the function that should work with the data it's still null.

**Comment by npurushe** [comment]
This seems a bit hard to reproduce can you put a breakpoint in the MEDICATION_TIMES attribute setProperty().set method where the field is actually set? You should be able to see from where your field is being overwritten back to null, the call stack information there will be helpful in finding the cause. thanks.

**Comment by Pr0bability** [comment]
I am having trouble understanding the debugging output in IDEA. For some reason the breakpoint only works once, trying to return to the app causes it to get stuck, so I can't even get to the point where it crashes.
