### ISSUE TITLE
How to write entity to parcel with all its children (one-to-many list) ?

### ISSUE THREAD

**Issue by codingworkshopru** [requery/requery#552]
I'm looking for ability to keep in parcel entity with its children. I have a case when I don't need to insert record in the database, but I have to keep it in RAM until user decides to save all in persistent storage.

**Comment by consp1racy** [comment]
~You don't need a Parcelable for *in-memory* storage. Just put it in any variable in any class you have access to and pick it up later.~

Put it in the database along with the rest and flag it as draft with a custom column. Something like Gmail drafts. The message is stored in DB but can be dismissed or sent later.

Saved state is limited by 1MB for an Activity. That saved state includes fragments. Don't abuse it to store big data.

**Comment by codingworkshopru** [comment]
Thank you for your answer. I'd like to transmit entities between activities inside of Bundle objects for better performance. Also I don't want to mix buiseness logic with service in the same entity. And finally I have a simple data that don't need to be drafted or something, it simply have to be saved or not.

**Comment by npurushe** [comment]
Hi you can do this by saving the entity and the list of one-to-many children separately, and rebuilding the hierarchy on deserializing. Parcelable is not designed to store objects that contains cycles or complex hierarchies, hence why the built in support is just the flat columns of the entity.
