### ISSUE TITLE
How do I model this many-to-many relationship?

### ISSUE THREAD

**Issue by dadino** [requery/requery#553]
I have 2 entities, `Ability` e `Character`. Each ability has 3 levels, each character have 0-n abilities at a specific level.
Do I need to build a 3rd entity `CharacterAbilityLevel` that holds `Character.id`, `Ability.id` and an int `level`? Is there a better way to do it with Requery?

**Comment by npurushe** [comment]
If all the `levels` are unique sounds like they should be their own table, the fact that an ability has 3 levels is something you could just enforce in your app code vs in the database.
