### ISSUE TITLE
Defining callback method in Kotlin interface

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#554]
Hey,
I was trying to define a callback function (`@PostLoad`) in an interface written in Kotlin. Kotlin supports giving the implementation of a function in an interface, but still when I was trying to compile the project, I received an error that `callback method cannot be abstract`.

**Comment by npurushe** [comment]
Unfortunately this isn't currently possible with interfaces, because they would need to be implemented as Java 8 default methods to be callable. See issue https://youtrack.jetbrains.com/issue/KT-4779
