### ISSUE TITLE
Dumb question about Observable for table changes

### ISSUE THREAD

**Issue by xorander00** [requery/requery#555]
What's the mechanism that requery uses to monitor table changes for a given entity?  I haven't yet looked at the code, but figured I'd ask here first.

I ask because I was testing it out for a project, but the Observable didn't call onNext when I changed some rows in the table.  I did so however using Facebook/Stetho and directly ran a SQL query against the database.  It made me wonder if requery keeps an internal hook of some sort to track queries made through it, in which case it would make sense that for the Observable to be triggered the changes would need to be done through requery.

Alternatively I guess requery could poll for changes or something as well.

**Comment by npurushe** [comment]
It's based on the types of entities involved a transaction and what tables those entities map to. There was a bug where this update wasn't triggered in all cases prior to 1.3.2, please try the latest version (1.3.2) thanks!

**Comment by xorander00** [comment]
Thanks!  I'll give it a shot today and will post here if I run into any issues.

Just to clarify: So if my app is running & I have a requery observable setup to watch an entity/table, it should be triggered even if I update the underlying SQLite database externally (ex: using adb), correct?

**Comment by npurushe** [comment]
No that's not correct, it has to be from a change made from the requery api

**Comment by xorander00** [comment]
Ah ok, that makes sense.  Thanks!
