### ISSUE TITLE
QueryRecyclerAdapter missing support for different view types

### ISSUE THREAD

**Issue by Gericop** [requery/requery#557]
As `QueryRecyclerAdapter` is a `RecyclerView` adapter, I'd like to use different view types for different kinds of data read from the database. Currently this is not possible because the result set iterator is private in the base class. I tried overriding `setResult(...)` and saving the iterator instance so I could access it at the given position from `getItemViewType(...)`, which worked fine until the iterator was closed. The iterator is missing a crucial operator for checking whether it's still valid or not. There's an internal `closed` field in the iterator class but, yet again, it's private and there's no way of getting its value (aside from reflection of course). Please, add a simple method for getting this value (or any other method to check the validity of the iterator), so the adapter wouldn't try to access a closed iterator, resulting in `StaleDataException`.

**Comment by npurushe** [comment]
Add methods to support returning a different view type based on the queried element. In either case the result shouldn't be closed until the recycler view is detached or a new result is set, so having a StaleDataException shouldn't happen.
