### ISSUE TITLE
OnErrorNotImplementedException/IllegalStateException when running transaction

### ISSUE THREAD

**Issue by wolkenschieber** [requery/requery#558]
Hi,

when I'm trying to run queries in a transaction I end up in an `OnErrorNotImplementedException` respective `IllegalStateException`:

```
io.reactivex.exceptions.OnErrorNotImplementedException
   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
   at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
   at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
(...)
Caused by: java.lang.IllegalStateException
   at io.requery.sql.ThreadLocalTransaction.commit(ThreadLocalTransaction.java:74)
   at io.requery.reactivex.WrappedEntityStore$18.call(WrappedEntityStore.java:327)
   at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:35)
   at io.reactivex.Completable.subscribe(Completable.java:1635)
```

The affected code tries to execute two queries within a transaction. Upon execution above exceptions are thrown and the app terminates.
```
        List<Single<?>> entries = new LinkedList<Single<?>>();
        entries.add(data.insert(history));
        entries.add(data.insert(numbers));
        Single<?>[] elements = entries.toArray(new Single<?>[entries.size()]);
        Observable<Object> = data.runInTransaction(elements);
        Scheduler scheduler = Schedulers.from(Executors.newSingleThreadExecutor());
        transaction.observeOn(scheduler).subscribeOn(AndroidSchedulers.mainThread()).subscribe();
```

I'm using current versions of requery and rxjava2:
```
    annotationProcessor 'io.requery:requery-processor:1.3.2'
    compile 'io.requery:requery:1.3.2'
    compile 'io.requery:requery-android:1.3.2'

    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
```

I'm not sure whether this my fault or an error in the library. 
Any help would be appreciated!

**Comment by npurushe** [comment]
Hi in this case since you are running the operations on different threads (schedulers) the transaction will not be valid. I understand this is somewhat confusing and this api is being revised to be more clear in the future.

instead you should prefer:

```java
final BlockingEntityStore store = data.toBlocking();
Completeable observable = Completeable.fromCallable(() -> { store.runInTransaction(() -> {
   store.insert(history);
   store.insert(numbers);
})
});

```
to create an async transaction block that is an rxjava Completeable instance

**Comment by wolkenschieber** [comment]
Thanks for your quick reply, but using the `BlockingEntityStore` and doing the operations inside the callables give me the same exception:

```
        final BlockingEntityStore store = data.toBlocking();
        Completable completable = Completable.fromCallable(new Callable<Void>()
        {
            @Override
            public Void call() throws Exception
            {
                store.runInTransaction(new Callable<Void>()
                {
                    @Override
                    public Void call() throws Exception
                    {
                        store.insert(history);
                        store.insert(numbers);
                        return null;
                    }
                });
                return null;
            }
        });
        completable.subscribe();
```

When debugging from a breakpoint on `store.insert`, I can see that on `transaction.commit()` from the `EntityDataStore`, the transaction can't be retrieved in the `ThreadLocalTransaction`.

Same thing happens if I observe and subscribe the completable in the Android main thread. I can't pin down, where the different threads might be.

Btw, I came across this issue when updating the used requery library from 1.0.1 to 1.3.2. Haven't done that in a while.

**Comment by npurushe** [comment]
That shouldn't be the case as the in the blocking runInTransaction method the callable is run in the  same thread so the ThreadLocal cannot be null on commit(), I've added a test case demonstrating that here : https://github.com/requery/requery/commit/6c1da2a5b7af7238b43275b3a133b4c34157c6f8

**Comment by wolkenschieber** [comment]
I've found strange behaviour regarding the configured `TransactionMode`. With this mode set to `NONE` above exceptions occur. However different values create other exceptions.

I've created a minimal app: [wolkenschieber/requery-issue558](https://github.com/wolkenschieber/requery-issue558). By pressing button *Run with TransactionMode.NONE* the scenario and its exception is reproduced.

Some comment in the original project pointed me to issue #319, which was also dealing with transactions, but has been resolved for a long time.

**Comment by wolkenschieber** [comment]
While playing around with the various transaction modes, I've found out that auto mode does the job.
Further results on different transaction modes are outlined in the demo android application mentioned above.

Thanks a lot for your help!
