### ISSUE TITLE
Table index?

### ISSUE THREAD

**Issue by kenyee** [requery/requery#56]
Can't find anything in the code or docs on how to do this.

How do you add table indexes to speed up performance of queries?

**Comment by npurushe** [comment]
Hi yes you can add [@Index](http://requery.github.io/javadoc/io/requery/Index.html) to the field/method to indicate the field is indexed and an index will be created for it during table generation.

```java
...
    @Index(name = "email_index")
    String email;
...
```

**Comment by kenyee** [comment]
Thanks...took a second pass through the docs and found that too..how would I do a multi-column index?
E.g., I want to do a query of
select * from mytable where column3 = 2 and column1=1 and column4='hello';

For the index to work properly, I'd have to be able to specify the order of the columns added to the index...

**Comment by kenyee** [comment]
Also need an example of how to do a transaction.  There seem to be classes for it, but I haven't been able to find an unit test or docs/wiki on how to do this.

Library looks really good so far :-)

**Comment by npurushe** [comment]
Hi yes you can use runInTransaction to execute some blocking operations in a single transaction. E.g:

```java
        data.runInTransaction(new Callable<List<Person>>() {
            @Override
            public List<Person> call() throws Exception {
                List<Person> list = new ArrayList<>();
                for (int i = 0; i < 10; i++) {
                    Person person = randomPerson();
                    data.insert(person);
                    list.add(person);
                }
                return list;
            }
        });
```
Some examples are [here] (https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L216)
Also any batch operation like insert(Iterable<T> items) are automatically done in a transaction

**Comment by npurushe** [comment]
For multi column indexes, that is currently not supported in the DDL output but it's a good enhancement that can be added. Will create an issue to track it

**Comment by kenyee** [comment]
Thanks...wiki page could probably use a page on transactions :-)
It'll do what I need...nicer than I expected actually..thought I had to deal w/ calling beginTransaction, etc. myself but doing it in a callable makes it cleaner.

**Comment by npurushe** [comment]
The latest beta version has the changes for multi column indexes. Will add a page to the wiki about transactions. Thanks
