### ISSUE TITLE
Wrong getter name for Boolean @Column on Class generation

### ISSUE THREAD

**Issue by lubbo** [requery/requery#561]
Hi,

I've found a problem on the generated method name for the getter on Boolean attribute (boxed type). 

The getter is generated with "is" naming instead of "get":

```Java
@Entity
@Table(name = "test_entity")
public abstract class AbstractEntity {
    @Column
    public Boolean booleanAttribute;
}
```

**Generated Entity**

```Java
public class Entity extends AbstractEntity implements Persistable {

    [...]

    public Boolean isAttributeBooleanObj() {
        return $proxy.get(ATTRIBUTE_BOOLEAN_OBJ);
    }

    public void setAttributeBooleanObj(Boolean attributeBooleanObj) {
        $proxy.set(ATTRIBUTE_BOOLEAN_OBJ, attributeBooleanObj);
    }

    [...]
}
```

This is fine for primitive boolean type but is not for boxed Boolean type.

**Comment by npurushe** [comment]
This is intentional, `is` used for boolean types by default. There is no reason to differentiate `boolean` vs `Boolean`, both can be used in expressions. You can always override the generated naming by using the `@Naming` annotation to customize the getter/setter names. Hope that makes sense, thanks.

**Comment by lubbo** [comment]
It's fine to have @Naming annotation to customising it, but keep in mind that the default generation behaviour doesn't comply with JavaBeans specification.

Quite all IDE generate getters with this logic.
In my opinion it could be more useful to have a generated class that is JavaBeans compliant.
Otherwise it could be also useful to generate both 'is' and 'get ' getters.

Whatever you decide, for the time being, I can use `@Naming`.

Thanks.

- From JavaBeans specs:
> 8.3.2 Boolean properties
In addition, for boolean properties, we allow a getter method to match the pattern:
            public boolean is<PropertyName>();
This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” meth- od, or it may be provided in addition to a “get<PropertyName>” method.
In either case, if the “is<PropertyName>” method is present for a boolean property then we will use the “is<PropertyName>” method to read the property value.
An example boolean property might be:
                   public boolean isMarsupial();
                   public void setMarsupial(boolean m);

- An interesting NetBeans bug/discussion for reference:
https://netbeans.org/bugzilla/show_bug.cgi?id=160531

**Comment by consp1racy** [comment]
> **This “is” method may be provided instead of a “get” method**, or it may be provided in addition to a “get” method.

**Comment by lubbo** [comment]
Yes, for boolean, not for Boolean

**Comment by npurushe** [comment]
The original spec was created before Boxed types existed, and many frameworks before then were written around a field with an Object must having a `get` prefix, hence that bug report. But I haven't seen any up to date libraries or tools having a problem with `is`.
