### ISSUE TITLE
Several ManyToMany state null

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#563]
Hi,

similarly to #388 I have the problem that when a class has several ManyToMany to the same entity, the requery Jackson parses resoles them but the entity state is null. Thus they don't get inserted. Am I doing something wrong? Please find below a very simple example. Lookin at `Person` after it was deserialised, the states of `timelinePictures` and `profilePictures` are null. I used requery version 1.3.2.

```Java
String testJson = "{\n" +
    "  \"name\": \"Great name\",\n" +
    "  \"timelinePictures\": [\n" +
    "    {\n" +
    "      \"src\": \"https://static.pexels.com/photos/86462/red-kite-bird-of-prey-milan-raptor-86462.jpeg\"\n" +
    "    }\n" +
    "  ],\n" +
    "  \"profilePictures\": [\n" +
    "    {\n" +
    "      \"src\": \"https://static.pexels.com/photos/145939/pexels-photo-145939.jpeg\"\n" +
    "    }\n" +
    "  ]\n" +
    "}";
DatabaseSource databaseSource = new DatabaseSource(this, Models.DEFAULT, 1);
Configuration configuration = databaseSource.getConfiguration();
EntityDataStore<Persistable> store = new EntityDataStore<>(configuration);

ObjectMapper objectMapper = new EntityMapper(Models.DEFAULT, store);
  try {
      Person person = objectMapper.readValue(testJson, Person.class);
  } catch (IOException e) {
  e.printStackTrace();
  }
```

Entities

```Java
@Entity
@JsonDeserialize(as = PersonEntity.class)
public abstract class Person {
  @Key
  @Generated
  int id;

  String name;

  @ManyToMany
  @JunctionTable(name = "person_picture_timeline")
  List<Picture> timelinePictures;
  @ManyToMany
  @JunctionTable(name = "person_picture_profile")
  List<Picture> profilePictures;
}
```

```Java
@Entity
@JsonDeserialize(as = PictureEntity.class)
public abstract class Picture {
  @Key
  @Generated
  int id;

  String src;
}
```

**Comment by npurushe** [comment]
Thanks for the test code, will try to reproduce

**Comment by Agraphie** [comment]
Thanks for the quick fix, it works well. However, it does not work when using custom setters for the collections above (state will be `null` again). Adding `@JsonIgnore` to the setters solves this problem. 

Wouldn't it also be a solution to generate setters for generated entities? Internally they could just call the generated getter. Not sure if I should open an issue or if this works intendend @npurushe?
