### ISSUE TITLE
Using transaction with Rx in Kotlin

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#564]
Hi,
I saw there is a function called `withTransaction` in `KotlinEntityDataStore`, but couldn't find it in `KotlinRxEntityStore` to run it async using Rx, though there is an implementation in `SingleEntityStore`. Can you please provide an implementation for Kotlin as well?

**Comment by npurushe** [comment]
Thanks for the reporting the syntax for this will look like this

```kotlin
data.withTransaction {
           for (i in 1..10) {
            val entity = createSomeEntity()
               insert(entity) // note this is on the BlockingEntityStore
           }
      } .subscribe()

```
