### ISSUE TITLE
requery + retrofit JSON contains $*_state variables

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [requery/requery#565]
The JSON i receive on server side contains $*_state variables. How to remove them
*Sample Entity*

```Java
@Entity
public abstract class AbstractMaster {
    @Key
    @SerializedName("id")
    public String id;
    public String status;
}
```
*The JSON received on server*
```JSON
  {
    "$id_state": "LOADED",
    "$status": "LOADED",
    "id":1234,
    "status":"OK"
  }
```

**Comment by npurushe** [comment]
What json converter are you using? You should configure to ignore types of `io.requery.proxy.PropertyState`

requery provides a module for jackson serialization, which skips these [types](https://github.com/requery/requery/blob/master/requery-jackson/src/main/java/io/requery/jackson/EntityAnnotationIntrospector.java#L149)

Gson for example you can use `shouldSkipClass` with a custom `ExclusionStrategy`. Most json libraries provide a method to this. Hope that helps.

**Comment by deviant-studio** [comment]
i tried this with no success
```
 GsonBuilder()
            .addSerializationExclusionStrategy(object : ExclusionStrategy {
                override fun shouldSkipClass(clazz: Class<*>): Boolean = clazz is PropertyState

                override fun shouldSkipField(f: FieldAttributes): Boolean = f.declaredClass is PropertyState

            })
            .create()
```

am i missing something?

**Comment by consp1racy** [comment]
>     override fun shouldSkipField(f: FieldAttributes): Boolean = false

So it shouldn't skip any fields?

Everything you need is here https://google.github.io/gson/apidocs/com/google/gson/ExclusionStrategy.html

Make it so it skips fields of type PropertyState.

**Comment by deviant-studio** [comment]
my code is perfectly fine too
