### ISSUE TITLE
FR: JPA annotation support for Composite Key

### ISSUE THREAD

**Issue by josecoll** [requery/requery#570]
Hi 
Do you have any plans soon to implement either of the JPA annotations (@EmbeddedId, @IdClass) required to be able to define a Composite Key on an entity?

https://stackoverflow.com/questions/13032948/how-to-create-and-handle-composite-primary-key-in-jpa

Many thanks.

**Comment by npurushe** [comment]
You can create Composite key by marking multiple fields with the `@Key` annotation.

Entities can be looked up composite keys like so:
```java
        Map<Attribute<Group_Person, Integer>, Integer> map = new LinkedHashMap<>();
        map.put(Group_Person.GROUPS_ID, group.getId());
        map.put(Group_Person.PERSON_ID, person.getId());

        io.requery.proxy.CompositeKey<Group_Person> compositeKey = new CompositeKey<>(map);
        Group_Person joined = data.findByKey(Group_Person.class, compositeKey);
```

**Comment by josecoll** [comment]
Thanks for your comment.

Unfortunately, our platform ([Corda](https://www.corda.net/)) is being developed in such a way that end users (CorDapp Developers) only use **standard JPA annotations** to define and annotate their entity models. I have been using Requery internally within the platform (via interfaces and @Key for composite PK's) ... but am now faced with an incompatibility dilemma.

**Comment by npurushe** [comment]
You can use multiple `@javax.persistence.Id` JPA annotations for the same effect, and this is still JPA compatible. That's the simplest way to define a composite key. JPA though may require you to define `@IdClass` on the entity, I believe this only needed for entity lookup. Is there a particular reason `EmbeddedId` has to be used?
