### ISSUE TITLE
How to use KotlinReactiveEntityStore?

### ISSUE THREAD

**Issue by andre-artus** [requery/requery#574]
The  documentation shows how to use `ReactiveEntityStore` in Java
```Java
ReactiveEntityStore<Persistable> dataStore = ReactiveSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
```
How do I go about creating an instance of `KotlinReactiveEntityStore`? 
What I've tried is:
``` Kotlin
val store = KotlinEntityDataStore<Persistable>(source.configuration)
KotlinReactiveEntityStore(store.toBlocking())
```

Which compiles, but does not seem right (blocking?).

**Comment by andre-artus** [comment]
Nevermind, I revisited the Kotlin example app and found the answer.

**Comment by andre-artus** [comment]
The example uses,
``` Kotlin
Observable.fromCallable { data.insert(person) }.subscribe({ finish() })
```
Could it not be simplified to,
``` Kotlin
data.insert(person).subscribe({ finish() },{ doSomethingWithError(it)})
```
or simply
``` Kotlin
data.insert(person).subscribe({ finish() },{ })
```
?

**Comment by npurushe** [comment]
Yes it definitely could be :) the example has evolved a bit with the api and early versions of kotlin so can be improved in certain places

**Comment by npurushe** [comment]
Thanks updated the example

**Comment by andre-artus** [comment]
Cool. 

I see the example has `.subscribeOn(AndroidSchedulers.mainThread())`, would it not be better to subscribe to `Schedulers.io` and observe on mainThread?

In my own code I use the equivalent of:

``` Kotlin
 data.findByKey(PersonEntity::class, personId)
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe { setPerson(it) }
```

**Comment by npurushe** [comment]
See https://github.com/ReactiveX/RxJava/wiki/The-RxJava-Android-Module for an explanation of this

**Comment by andre-artus** [comment]
@npurushe , perhaps I'm missing something, I checked out your provided link and it seems to recommend my approach. The example application is subscribed to the main thread as opposed to merely observing on it, which I would take to mean that any computation is thus done on the UI (main) thread and the asynchrony benefits are largely lost.

**Comment by npurushe** [comment]
Which part of the example? could be a mistake in the example

**Comment by andre-artus** [comment]
@npurushe,

https://github.com/requery/requery/blob/master/requery-android/example-kotlin/src/main/kotlin/io/requery/android/example/app/PersonEditActivity.kt#L37-L39

As it stands it should do nothing more than if the subscribeOn line was removed.

**Comment by andre-artus** [comment]
And unless something else is going on under the hood these lines are also executed on the UI thread.

https://github.com/requery/requery/blob/master/requery-android/example-kotlin/src/main/kotlin/io/requery/android/example/app/PersonEditActivity.kt#L105-L107

**Comment by npurushe** [comment]
Thanks the examples have been updated
