### ISSUE TITLE
How to get the sql of create table

### ISSUE THREAD

**Issue by vibexie** [requery/requery#576]
Hi, I want to get the right sql of create table when use requery library, is there any way to do it?
And String int java represents varchar(?),  so i want to know the varchar length of String. Thank you

**Comment by vibexie** [comment]
I found the table-create sql via Android-Debug-Database

**Comment by npurushe** [comment]
You can also use [SchemaModifier.createTablesString](http://requery.github.io/javadoc/io/requery/sql/SchemaModifier.html#createTablesString-io.requery.sql.TableCreationMode-) for this
