### ISSUE TITLE
Modifying the table create statement?

### ISSUE THREAD

**Issue by exitface** [requery/requery#578]
I'd like create a FTS table, e.g. `CREATE VIRTUAL TABLE data USING fts3();`, but haven't been able to find a way of modifying the table creation statement. I've looked into using the `createAttributes` of the [@Table annotation](https://github.com/requery/requery/wiki/Defining-Entities) as well as [SchemaModifer class](https://github.com/requery/requery/wiki/Table-Generation), but haven't found any clear way of doing so? Any ideas? 

Thank you!

**Comment by npurushe** [comment]
Hi you should be able to do this by overriding the `SchemaModifier.tableCreateStatement` and appending the using clause. There was a bug where the table createAttributes were not applied, which is fixed. I will also look into a more convenient way to provide a using clause in the statement as well.
