### ISSUE TITLE
generate too many anonymous class。

### ISSUE THREAD

**Issue by jiqimaogou** [requery/requery#58]
requery generate the sub class of a model，but it has so many anonymous class。

**Comment by npurushe** [comment]
Do you have any example? In general this is how it works requery needs to be able to access individual properties of you class. However all this data is static and only initialized once so there is really no penalty or issue in doing it. It could be replaced with lamdas in a future version possibly but to maintain compatibility with Android has to be done with the proxy `Property` classes for now.

**Comment by npurushe** [comment]
Closing this for now, once Android N sdk is final will consider changing property accessors to lamdas
