### ISSUE TITLE
Jackson serialisation custom setters cause state to be FETCH

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#581]
Hi,

as written in #563 (same classes), when using custom setters (setters are in the abstract class) for the collections the state will be null again .Adding @JsonIgnore will only set the state to `FETCH`. In both cases the collections are not persisted.

Wouldn't it also be a solution to generate setters for generated entities? Internally they could just call the generated getter.

**Comment by npurushe** [comment]
Hi, What does your custom setter do? If it overwrites the collection field than that erases the state of the collection and the property possibly causing other unwanted side effects.

**Comment by Agraphie** [comment]
Thanks for your reply. Once I removed the setters (left the getters though) it seems to be all good.
