### ISSUE TITLE
@Superclass inheritance

### ISSUE THREAD

**Issue by a-merkle** [requery/requery#59]
It seems that requery is only recognizing the direct super class with the `@Superclass` annotation. Let's say you have these three classes
`public abstract class A extends B {
    @Column
    int a;
}`
`@Superclass
public abstract class B extends C {
    @Column
    int b;
}`
`@Superclass
public abstract class C {
    @Column
    int c;
}`
The entity generated from `A` will only have the columns `a` and `b` but there will be no `c`.

**Comment by npurushe** [comment]
Hi thanks for reporting. Looks like a bug only the parent class is considered. Should be fixed in the next update
