### ISSUE TITLE
Update set method not working as expected in Kotlin

### ISSUE THREAD

**Issue by exitface** [requery/requery#592]
From the docs

```
int rows = data.update(Person.class)
    .set(Person.ABOUT, "student")
    .where(Person.AGE.lt(21)).get().value();
```

I would expect the Kotlin equivalent to work similarly

```
val rows = data.update(Person::class)
    .set(Page::about, "student")
    .where(Page::age lt 21).get().value()
```

But I get `Type mismatch: inferred type is KMutableProperty1<Person, String> but Expression<String> was expected`. I realize that it must be an Expression, but I'm unsure of the proper way of converting the property to an Expression. 

This is with a `KotlinReactiveEntityStore<Persistable>` data store

**Comment by npurushe** [comment]
Thanks for reporting there was a bug in the set extension method it didn't have the right return type

**Comment by exitface** [comment]
Thanks for the quick fix!

**Comment by exitface** [comment]
Actually a question for you. I pulled the latest fixes and was still experiencing the problem. Looking at the test suite I saw that the Person class is a data class, but I'm using an interface. I figured out that I could get it to work if I just used the generated PersonEntity rather than the Person interface.

```
data.update(PersonEntity::class).set(PersonEntity.ABOUT, "student")
```

Is that intentional or should you be able to use the interface in the same fashion? It through me off because I'm using the interface in every other query.

**Comment by consp1racy** [comment]
data.update(PersonEntity::class).set(findAttribute(Person::about), "student")

Is this what you're looking for?

**Comment by exitface** [comment]
@consp1racy That's helpful, thank you!  I'm just curious if the API is working as intended. If I should expect the update function to behave the same when used with either an interface or data class, or if the workaround you've described is the intended way.

**Comment by npurushe** [comment]
With the change you should be able to do:

```kotlin
data.update(Person::class).set(Person::about, "student")
```

**Comment by exitface** [comment]
I think the issue may be with my datastore which is a `KotlinReactiveEntityStore<Persistable>(KotlinEntityDataStore(source.configuration))`. Given the following model definition:

```kotlin
@Entity
data class Person constructor (
  @get:Key
  var id: Int,
  var name: String,
  var email: String,
  var birthday: Date,
  var age: Int,

  var about: String,

  @get:Column(unique = true)
  val uuid: UUID,
  val homepage: URL,
  val picture: String
) : io.requery.Persistable
```
I get the following errors:

```kotlin
    val rowCount = data.update(Person::class)
      .set(Person::about, "nothing") // Type mismatch: inferred type is KMutableProperty1<Person, String> but Expression<String> was expected
      .set(Person::age, 50) // Type mismatch: inferred type is KMutableProperty1<Person, String> but Expression<String> was expected
      .where(Person::age.eq(100)).get().value()
```

If I don't make `Person` persistable, the compiler obviously complains, but the errors on those lines go away.

**Comment by ninjudd** [comment]
I am having the same issue using `KotlinReactiveEntityStore`

**Comment by xxxifan** [comment]
```
Cannot choose among the following candidates without completing type inference:
public open fun <E : Any> update(entity: KClass<TreeInfoEntity>): KClass<TreeInfoEntity> defined in io.requery.sql.KotlinEntityDataStore
public open fun <E : Any> update(type: KClass<TreeInfoEntity>): Update<Scalar<Int>> defined in io.requery.sql.KotlinEntityDataStore
```
when I use update class. I'm using KotlinEntityDataStore

**Comment by jeffzoch** [comment]
I am having the same issue.
