### ISSUE TITLE
Cannot specify order in orderBy with aliased column

### ISSUE THREAD

**Issue by unveloper** [requery/requery#596]
Hi,
i cannot find a way of specify an order on an aliased column.
For example this code:

```
Result<Tuple> result = dataStore
.select(Case.type(DashboardItemType.class)
				.when(ExpenseSettleEntity.TRANSACTION.isNull(), DashboardItemType.EXPENSE_REPETITION)
				.elseThen(DashboardItemType.EXPENSE_TRANSACTION),
		ExpenseEntity.TITLE, ExpenseEntity.AMOUNT,
		ExpenseSettleEntity.DATE_TIME.as(Constants.DATETIME_COLUMN))
.join(ExpenseSettleEntity.class)
.on(ExpenseEntity.ID.eq(ExpenseSettleEntity.EXPENSE_ID))
.where(ExpenseSettleEntity.DISMISSED.equal(false))

.union()

.select(Case.type(DashboardItemType.class)
				.when(IncomeSettleEntity.TRANSACTION.isNull(), DashboardItemType.INCOME_REPETITION)
				.elseThen(DashboardItemType.INCOME_TRANSACTION),
		IncomeEntity.TITLE, IncomeEntity.AMOUNT,
		IncomeSettleEntity.DATE_TIME.as(Constants.DATETIME_COLUMN))
.join(IncomeSettleEntity.class)
.on(IncomeEntity.ID.eq(IncomeSettleEntity.INCOME_ID))
.where(IncomeSettleEntity.DISMISSED.equal(false))

.orderBy(ExpenseSettleEntity.DATE_TIME.as(Constants.DATETIME_COLUMN).desc())
.get();
```

Where Constants.DATETIME_COLUMN = "datetime".

The orderBy statement with "desc() "gives me compilation error, without it works, so how can  I speficy the order in this case?

Also, how can i specify an alias for the "case" statement?

Thanks

**Comment by npurushe** [comment]
Hi what's the exact error that you get?

**Comment by unveloper** [comment]
Hi,

If I try

.orderBy(ExpenseSettleEntity.DATE_TIME.as(Constants.DATETIME_COLUMN).desc())

I get "error: cannot find symbol method desc()"

If instead I try 

.orderBy(ExpenseSettleEntity.DATE_TIME.desc().as(Constants.DATETIME_COLUMN))

I get "cannot find symbol method as(String)"

**Comment by unveloper** [comment]
I would like to understand if what I want to achive (ordering with direction by an alias and set an alias on a case) is simply not supported / implemented yet or if I'm doing it wrong.

**Comment by npurushe** [comment]
Sorry yeah currently this type of aliasing isn't supported but should be easy to add

**Comment by unveloper** [comment]
Thanks for your answer.
I hope that it will be implemented soon.

You're doing a very good job with this library :)
