### ISSUE TITLE
Cannot find symbol method value()

### ISSUE THREAD

**Issue by riccardoratta** [requery/requery#597]
Hi, I can't figure it out why I can't use `value()` or `call()` methods after `get()`; for example the code `int count = data.count(Session.class).get().value();` generate `Error:(108, 67) error: cannot find symbol method value()` error. Sorry if I'm making a trivial mistake, I'm relatively new to the world of Android/Requery.

**Comment by anatoly-kryzhanovsky** [comment]
what type of _data_ variable is? 
check if you does not miss generic specification for DataStore

**Comment by riccardoratta** [comment]
My configuration for the variable `data` is
```
// Create configuration with configuration builder & database source
Configuration configuration = new ConfigurationBuilder(
        new DatabaseSource(getApplicationContext(), Models.DEFAULT, "database.db", 1)
        , Models.DEFAULT)
    .useDefaultLogging()
    .build();

EntityDataStore data = new EntityDataStore<>(configuration);
```
Am I doing something wrong?

**Comment by anatoly-kryzhanovsky** [comment]
try change type to EntityDataStore<Persistable>

**Comment by riccardoratta** [comment]
Thanks, `EntityDataStore<Persistable> data = new EntityDataStore<>(configuration);` worked.
