### ISSUE TITLE
Base entity class and filtering

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [requery/requery#598]
Hi there
i have base class for all entities:
```
@Superclass
public interface Entity {
    @Key
    @Generated
    int getId();

    @Column
    EEntityState getState();
    void setState(EEntityState value);
}
```

where EEntityState is enum:
```
public enum EEntityState {
    Normal,
    Deleted
}
```
and i have several child entities. For example:
```
@io.requery.Entity
public interface Content extends Entity {
    @Column
    String getName();
    void setName(String value);    
}
```
now, i want co create generic Repository class which allow CRUD operations:
```
public interface IRepository<T extends Entity> {
    T get(int id);

    T[] list();

    boolean save(T entity);
    boolean save(Iterable<T> entities);

    boolean delete(T entity);
    boolean delete(Iterable<T> entitites);
}
```
method list should return all item with State = EEntityState.Normal:
 ```
@Override
    public T[] list() {
        EntityDataStore<Entity> store = _database.getStore();
        Result<T> resultSet = store
                .select(_class)
                .where(**<SOMETHING>.STATE.eq(EEntityState.Normal)**)
                .get();

        List<T> list = resultSet.toList();
        T[] result = (T[]) Array.newInstance(_class, list.size());
        list.toArray(result);

        return result;
    }
```

but i have class for base entity and can create condition for such filter. 
How i can do this?

**Comment by npurushe** [comment]
Hi currently @Superclass merges its attributes into the parent entity type, so all those tables are separate. You would need to join the tables to query all of them. It looks like your looking for a [single table inheritance model](https://en.wikipedia.org/wiki/Single_Table_Inheritance), that enhancement is defined in #419. Going to close this issue please follow the other issue for updates thanks!
