### ISSUE TITLE
Question regarding EnumStringConverter with Kotlin

### ISSUE THREAD

**Issue by channguyen** [requery/requery#601]
Hi there, 
I'm having a model as following:
```
class BirdStatusConverter : EnumStringConverter<BirdStatus>(BirdStatus::class.java)
class RentalStatusConverter : EnumStringConverter<RentalStatus>(RentalStatus::class.java)

@Table(name = "birds")
@Entity
data class Bird(

  @get:Key
  @get:Column(nullable = false, unique = true)
  val id: UUID = UUID.randomUUID(),

  @get:Column(name = "speed")
  var speed: Double = 0.0,

  @get:Column(name = "heading")
  var heading: Double = 0.0,

  @get:Column(nullable = false, name = "bird_status")
  @get:Convert(BirdStatusConverter::class)
  var birdStatus: BirdStatus = BirdStatus.HEALTHY,

  @get:Column(nullable = false, name = "rental_status")
  @get:Convert(RentalStatusConverter::class)
  var rentalStatus: RentalStatus = RentalStatus.AVAILABLE,

  @get:Column(name = "battery_level")
  var batteryLevel: Int = 0,

  @get:Column(name = "created_at")
  val createdAt: Long = System.currentTimeMillis(),

  @get:Column(name = "updated_at")
  val updatedAt: Long = System.currentTimeMillis()
)
```     

Requery generated code successfully, however whenever I tried to do an insert, it complains about:  
```Caused by: org.postgresql.util.PSQLException: ERROR: column "bird_status" is of type bird_status but expression is of type character varying``` 

I was looking for example on the net, can't seem to find a working example with enum string using Kotlin. Any feedback would be greatly appreciated!

**Comment by npurushe** [comment]
What happens if you remove the `@get:Convert` annotations? Enums are converted to strings by default, but both should work.

**Comment by channguyen** [comment]
@npurushe I got exactly the same exact error:
`Caused by: org.postgresql.util.PSQLException: ERROR: column "bird_status" is of type bird_status but expression is of type character varying`
Btw, thanks for quick response 👍

**Comment by channguyen** [comment]
@npurushe Any update? I couldn't find a way to get enum to work with Requery.

**Comment by npurushe** [comment]
It looks like your particular issue is because of a possible bug with generating attributes from kotlin data classes. If you use an interface or abstract class it should work. Once I confirm I'll add the bug label to the issue, thanks

**Comment by channguyen** [comment]
@npurushe Thanks!

**Comment by channguyen** [comment]
In fact, I tested with `interface` as well and it still give the same error.

**Comment by channguyen** [comment]
So I finally found a workaround. I had to create both custom type and custom converter for `postgres enum` as `PGobject`. The default `EnumStringConverter` works if and only if I use `text` in DB

**Comment by npurushe** [comment]
Ok interesting thanks for the update, closing for now.
