### ISSUE TITLE
Is there a way to avoid getter and setter generation?

### ISSUE THREAD

**Issue by lubbo** [requery/requery#602]
I need to generate an entity with some private fields.
Is it possible to avoid generating getter and setters?

**Comment by npurushe** [comment]
What's your use case for this? Getters/setters are needed to support lazy loading as well state tracking. If you use an abstract class you always have access to the private fields anyway.

**Comment by lubbo** [comment]
I want to have a transient attribute, with additional logic on top of the private field.
Transient attribute uses the private field as a storage but I don't want to expose that storage.
