### ISSUE TITLE
Wrong date storing

### ISSUE THREAD

**Issue by oleonov** [requery/requery#603]
Requery not storing milliseconds.
I save date with milliseconds, but get only zeros in milliseconds instead of proper value.

**Comment by consp1racy** [comment]
Hi, use a custom adapter. Requery uses java.sql.Date, Time and Timestamp internally to work with dates and those are terribly unpredictable.

**Comment by oleonov** [comment]
I use it already. I thought exists more suitable path.

**Comment by oleonov** [comment]
I use it already. I thought exists more suitable path.

**Comment by npurushe** [comment]
Requery stores Dates using java.util.Date and the java.sql time values. If you want to use milliseconds you should use a int column, there is not really anything that can go wrong with that. Hope that helps.
