### ISSUE TITLE
Question regarding custom or freeform query

### ISSUE THREAD

**Issue by channguyen** [requery/requery#605]
Hi @npurushe,

I'm not sure if there is an easy way to use free-from select query like
```
SELECT *
FROM your_table
WHERE ST_Distance_Sphere(the_geom, ST_MakePoint(your_lon,your_lat)) <= radius_mi * 1609.34 
```
I'm using `postgres postgis`, and what I'm trying to do is select all points given (lat, lng) and radius. 
An alternative approach that I've tried is to extends from `io.query.kotlin.*; however I still haven't figured out how to do so. I'm wondering if you could provide some pointers how to write custom query expression?

**Comment by npurushe** [comment]
You may want to use the [raw query](http://requery.github.io/javadoc/io/requery/Queryable.html#raw-java.lang.String-java.lang.Object...-) option for this.

**Comment by channguyen** [comment]
@npurushe Awesome, thanks!

**Comment by channguyen** [comment]
Do you mind writing me a quick example? I tried just basic query and get `IndexOutOfBoundException`. Not exactly sure why I need `arguments` here. 
```return dataStore.raw("DELETE FROM users", arrayOf<String>()).toMaybe().map { true }```

**Comment by npurushe** [comment]
You can remove the arguments for that statement, its a vararg function.

**Comment by channguyen** [comment]
Thanks! How could I not see it :(

**Comment by npurushe** [comment]
Cool sure np

**Comment by channguyen** [comment]
@npurushe Unfortunately, it gave the same error even without `args`.
