### ISSUE TITLE
Working with existing sqlite

### ISSUE THREAD

**Issue by bitfield66** [requery/requery#607]
Hello,

I placed my sqlite(which contains data and table pre-populated) in asset folder and copied it from assets to data directory.

I created interface using requery and I tried to access data I am getting below exception

io.requery.sql.TableModificationException: java.sql.SQLException

I used below code for initializing data source:

DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, DB_PATH + DB_NAME, 2);

**Comment by npurushe** [comment]
Are you sure the version matches the user_version (schema version)? If they do then the database won't be created/upgraded which is what looks like is happening.

**Comment by bitfield66** [comment]
yes there is a mismatch thanks it's working now.
