### ISSUE TITLE
In-memory cache? Persisted after db removed?

### ISSUE THREAD

**Issue by skyler-b** [requery/requery#615]
I can't seem to find any documentation about an in-memory cache, but it really seems like requery has one. I'm having a problem where after deleting the .db file, I am still seeing successful loads from the cache.

Supporting evidence for the in memory cache theory is that the first load from cache takes about 200ms, but subsequent loads are almost instantaneous (0-20ms). 

Can you confirm the in memory cache? Is it a bug that deleting the .db file directly does not invalidate the cache? Is there an API for me to wipe all in memory caches. or does it happen only through entity store operations (e.g. .delete())?

**Comment by npurushe** [comment]
Yes this is part of the default [configuration](http://requery.github.io/javadoc/io/requery/sql/ConfigurationBuilder.html#setEntityCache-io.requery.EntityCache-) you can disable it by using an [EmptyEntityCache](http://requery.github.io/javadoc/io/requery/cache/EmptyEntityCache.html#EmptyEntityCache--) or simply clear the cache when you delete the database. There is not really any way to know the database was deleted so it can't be automatic. Hope that answers your question.

**Comment by skyler-b** [comment]
Perfect - that's all the information I was looking for - thanks for the reply!
