### ISSUE TITLE
How to parcel an entity without setId() ?

### ISSUE THREAD

**Issue by DaRolla** [requery/requery#616]
Hi there,

I've got a specific Android topic.

Lets assume I requested a list of MyDataEntity:
	
	@Entity
	public interface MyData extends Persistable {
	
	    @Key
	    @Generated
	    int getId();
	
	    String getName(); // shown in SingleChoiceDialogFragment 
	
	    String getSomething();
	}

I want to show a SingleChoiceDialogFragment in order to choose one.

I need to pass in the MyDataEntity as Parcel.

Implementing the Parcel interface (or using some library like Parceler) is quite easy, I need to put in every member and fetch them in the same order. 

    public class MyDataParcelConverter implements ParcelConverter<MyData> {
        
        @Override
        public void toParcel(final MyData entity, final Parcel parcel) {
            parcel.writeInt(entity.getId());     // <-- this getter is available
            parcel.writeString(entity.getName());
            parcel.writeString(entity.getSomething());
        }
    
        @Override
        public MyData fromParcel(final Parcel parcel) {
            final MyDataEntity entity = new MyDataEntity();
            
            entity.setId(parcel.readInt());     // <-- this setter isn't available
            entity.setName(parcel.readString());
            entity.setSomething(parcel.readString());
            
            return new MyDataEntity();
        }
    }

But right now I am missing the primary key setter method setId(). There is a getter but no setter.

I understand the reason for making the primary key a secret, but how can I solve my problem?

I want to avoid doing database queries in my DialogFragment...

Cheers,
DaRolla

**Comment by Agraphie** [comment]
Hi,

why do you want to avoid database queries? I'm using them in all sort of activities and fragments without any problem. Just pass over the id and then query db, it's very fast. If you still want to do it, you can either let your entitiy implement `Parcelable` (then you can access the fields without `set`), let it implement `Serializable` (not necessarily slower than `Parcelable`) or make the id field public or package private.

**Comment by npurushe** [comment]
In general you should avoid parceling whole objects. You should just parcel instead just the id of the object and then use `entitystore.findByKey` to look up the object in your Fragment. If the entity is cached in memory then there is no overhead in doing this, if the db has to be queried then the penalty is generally small but you could always use RxJava (recommended) or another loading method to do it asynchronously.
