### ISSUE TITLE
Why is field object saved as a string?

### ISSUE THREAD

**Issue by cooperkong** [requery/requery#617]
I have below in a model called Consignment
`@Column(name = "articles")
    @OneToMany(mappedBy = "id")
    List<Article> articles;`
However, it is saved as a String in Consignment table instead of saving to Article entity table, what am I missing here?

**Comment by Agraphie** [comment]
Hi,

first you need to have a corresponding `@ManyToOne` annotation in the `Article` class (see below). Then `mappedBy` should be the name of the variable annotated with `@ManyToOne`. You could have a look here for a deeper explanation https://en.wikibooks.org/wiki/Java_Persistence/OneToMany.

The classes below work for me.

```Java
@Entity
public abstract class Consignment {
  @Key
  @Generated
  int id;
  String name;
  @OneToMany(mappedBy = "consignment")
  List<Article> articles;
}
```

```Java
@Entity
public abstract class Article {
  @Key @Generated
  int id;
  String name;
  @ManyToOne
  Consignment consignment;
}
```
And how I insert them:
```Java
Article article = new ArticleEntity();
ConsignmentEntity consignment = new ConsignmentEntity();
consignment.setName("hi");
consignment.getArticles().add(article);
store.insert(consignment);
```

P.S.: `@Column(name = "articles")` does not have any effect here, as the corresponding foreign key is saved in the `Articles` table.

**Comment by cooperkong** [comment]
@Agraphie Thanks, it works now as expected. Also the article is great!

**Comment by cooperkong** [comment]
Hi @Agraphie 
Now I can successfully read Consignment object, however all Article fields are null. Do you happen to know anything regard this issue? thanks.

**Comment by cooperkong** [comment]
Just did a clean and build. Seems working now.
