### ISSUE TITLE
@OneToOne not cascade delete

### ISSUE THREAD

**Issue by cooperkong** [requery/requery#618]
model Consignment:
```@ForeignKey
    @OneToOne(cascade = {CascadeAction.SAVE})
    public RedirectIneligibility redirectIneligibility;
```

model RedirectIneligibility

```
@OneToOne(mappedBy = "redirectIneligibility", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    public Consignment consignment;
```

insertion works fine. However when I call
```
dataStore.delete(Consignment.class)
```

only consignment table gets cleared, not RedirectIneligibility.

**Comment by npurushe** [comment]
`dataStore.delete(Consignment.class)` only deletes all of Consignment types. The other types would only get deleted if they had a cascading foreign key, or you deleted an entity individually e.g. `dataStore.delete(consignment)`. You can mark one side with `@ForeignKey` to define the side with the foreign key. Hope that helps.

**Comment by cooperkong** [comment]
@npurushe Thanks. It works now.
