### ISSUE TITLE
Convert List of tuple to List of field type when selecting specific column.

### ISSUE THREAD

**Issue by christianCallelero** [requery/requery#619]
Is there a way where we can retrieve list of data as the field type? For example 

From my entity class
`String Name;`

from my query class
```
.select(City.NAME)
.get().toList();
```

this will return  `List<Tuple>`. So is there a way this could return `List<String>`?

**Comment by npurushe** [comment]
If you are using RxJava or Java 8 streams you can just map it using the map operator. The reason being the api is generic (for supporting more than just 1 column)

java 8 example:
```java
data.select(City.NAME).get().stream().map(t -> t.get(0)).collect(Collectors.toList())
```

**Comment by christianCallelero** [comment]
Thanks, ill try this out.
