### ISSUE TITLE
Allow safe raw queries 

### ISSUE THREAD

**Issue by cbruegg** [requery/requery#62]
As mentioned in a reddit thread a few hours ago, it would be great if requery would support safe raw queries. For example:

`List<Book> books = [...].queryRaw("SELECT * FROM books WHERE title = ?", "Harry Potter");`

Arguments should be escaped properly. Requery should not make assumptions about the structure of the query, so that any SQL statement that returns rows compatible with the type argument (`Book` in this case). 

Another nice feature would be to have a similar method returning the result of an aggregate function, for example `Count(*)`/`Sum(price)`. 

I haven't taken a look at the structure of this project yet, but if you could give me a brief description of steps to be taken to implement this, I could try to work on this and submit a PR. 

**Edit:** 
In order to support `IN`-statements, the methods should apply the following transformations:

`List<Book> books = [...].queryRaw("SELECT * FROM books WHERE title IN ?", Arrays.asList("Harry Potter", "Another Book"));`
becomes the following SQL statement behind the scenes: `SELECT * FROM books WHERE title IN (?, ?)` and the iterable or array is 'inlined' into the other arguments.

To make dealing with `null`-values easier, `List<Book> books = [...].queryRaw("SELECT * FROM books WHERE title = ?", null);`
could become `SELECT * FROM books WHERE title IS NULL` behind the scenes for conveniece. I couldn't come up with a case where this wouldn't be desirable behavior.

**Comment by npurushe** [comment]
Hi thanks for the well written description. That is effectively what it would look like. There will be two additional query API's one returning `Tuple` and another that can map on to an entity class using the generated meta information. There is some work on the first part already coming in the next update.

**Comment by cbruegg** [comment]
I've just created opened a PR for supporting IN clauses. Additionally, I've noticed that it could be useful to automatically map parameters that are database entities to their IDs, for example:

```
List<Person> persons = Arrays.asList(...);
Result<Relationship> pRelationships = data.raw(Relationship.class, "select * from Relationship where first IN ?", persons); 
```

I'll look into how this could be implemented.

**Comment by npurushe** [comment]
Closing this one for now.

**Comment by cbruegg** [comment]
Are you interested in support for `raw("X = ?", null)` becoming `X IS NULL` (at least optionally) though or is there some argument against it? I could work on that feature..

**Comment by npurushe** [comment]
`IS NULL` is an operator while the former is a type of expression so it can't really be replaced so easily. e.g. if you take the simplest counter example `update Table set Column = NULL` you don't want to be changing that, there are other more complex cases. In order to be done correctly it requires a full parsing & understanding of the query.

**Comment by cbruegg** [comment]
I see, thanks for explaining. Too bad "WHERE Col = null" doesn't behave like a Java programmer would expect in SQL.
