### ISSUE TITLE
Generics as type KClass

### ISSUE THREAD

**Issue by SkubievA** [requery/requery#620]
I have several function addResult, deleteResult ... they are at Data Layer. And i have many models for save into DB. I wanna write such class which will be work for all type models. Thats why i try use generics in Kotlin. But i have a problem. 

```
@Singleton
class PersistentDatabase <T: Any> @Inject constructor(val type: KClass<T>) : Database <T> {
    @Inject
    lateinit var store: KotlinReactiveEntityStore<Persistable>

    override fun addResult(item: T): Completable = store.insert(item).toCompletable()

    override fun addListResult(item: List<T>): Completable = store.insert(item).toCompletable()

    override fun deleteResult(item: T): Completable = store.delete(item)

    override fun getAllResults(): Single<List<T>> = (store select type).get().observable().toList()

    override fun removeAllResults(): Completable = store.delete(type).get().single().toCompletable()
}

inline fun <reified T:Any> createPersistentDatabase(): PersistentDatabase<T> = PersistentDatabase(T::class)

interface Database <T> {
    fun addResult(item: T): Completable

    fun addListResult(item: List<T>): Completable

    fun deleteResult(item: T): Completable

    fun getAllResults(): Single<List<T>>

    fun removeAllResults(): Completable
}
```

The problem is:

> None of the following functions can be called with the arguments supplied.
> insert(E)   where E cannot be inferred for    fun <E : Persistable> insert(entity: E): Single<E> defined in io.requery.reactivex.KotlinReactiveEntityStore
> insert(Iterable<E>)   where E cannot be inferred for    fun <E : Persistable> insert(entities: Iterable<E>): Single<Iterable<E>> defined in io.requery.reactivex.KotlinReactiveEntityStore
> insert(KClass<E>)   where E cannot be inferred for    fun <E : Persistable> insert(type: KClass<E>): Insertion<ReactiveResult<Tuple>> defined in io.requery.reactivex.KotlinReactiveEntityStore
> insert(KClass<E>, vararg QueryableAttribute<E, *>)   where E cannot be inferred for    fun <E : Persistable> insert(type: KClass<E>, vararg attributes: QueryableAttribute<E, *>): InsertInto<out Result<Tuple>> defined in io.requery.reactivex.KotlinReactiveEntityStore

I really can do this? Or it is impossible? Maybe are there any examples?  Sry for my English. :)

**Comment by npurushe** [comment]
Your generic types don't match your store is `KotlinReactiveEntityStore<Persistable>` while your generic type is `T: Any` should change `T: Any` to `T: Persistable` or change `KotlinReactiveEntityStore<Persistable>` to `KotlinReactiveEntityStore<T>`

**Comment by xxxifan** [comment]
this is not satisfied when using `withTransaction` method, is there any way to fix?
