### ISSUE TITLE
Converting performQuery results into ViewModels?

### ISSUE THREAD

**Issue by jjbrunton** [requery/requery#622]
I'm trying to figure out how I would go about converting the results of performQuery in QueryRecyclerAdapter to representations of the data models instead of returning the actual entities to the views.

I expected that I would be able to do a map on the result and convert the entities but that doesn't  seem to be possible with the Result<T>.

Any help is appreciated.

**Comment by npurushe** [comment]
You would need to create your own extended class from ` RecyclerView.Adapter<VH>` as the provided adapter expects the generic type of the `Result` to match what goes into the RecyclerView, it would be fairly easy to start with QueryRecyclerAdapter and modify it to convert the result `E` into a different object.

**Comment by jjbrunton** [comment]
Perfect, that's a great starting point. I'll have a look into that - thank you @npurushe

**Comment by npurushe** [comment]
sure closing for now, thanks!
