### ISSUE TITLE
Create Entity With Predefined Rows

### ISSUE THREAD

**Issue by DiegoLoTre** [requery/requery#625]
Hi,
I'm using Requery with Kotlin in an Android App, so i wonder if its any way to create an Entity with a predefined values

Thanks

**Comment by Agraphie** [comment]
Hi there,

are you speaking about default values? Then maybe this will help [@Column(value = "...")](https://requery.github.io/javadoc/io/requery/Column.html#value--)

**Comment by npurushe** [comment]
Yup, or you can also just define a factory method to create an object with the values you want.

**Comment by DiegoLoTre** [comment]
I'm talking creating records before all, I have a Users table and i want to create 3 users when the table are created, i already tried coping the kotlin-android-example but it doesnt work
