### ISSUE TITLE
OnUpgrade after adding columns to kotlin immutable entity drops old data

### ISSUE THREAD

**Issue by YuriDenison** [requery/requery#629]
Hello,
I have immutable kotlin data class representing my entity.
After adding a few columns to the entity and incrementing db version, I expect that my old data will be migrated to new version with new fields set to default values.

Let's say I've added 2 String colums:
`var city: String,`
`var country: String`

1. What is correct way for me to override DataSource's onUpgrade() and migrate old data to new version with `city = "", country = ""`? 

2. Should the default onUpgrade implementation work if I use nullable String? types for new columns?

**Comment by npurushe** [comment]
You should mark the fields with [`@Column(value ="..."`](http://requery.github.io/javadoc/io/requery/Column.html#value--) to define a default value that will be used during table generation.

**Comment by npurushe** [comment]
You can also override onUpgrade and execute your migration sql if needed, hope that helps
