### ISSUE TITLE
Db Creation Android

### ISSUE THREAD

**Issue by feliperaymundo** [requery/requery#63]
I have a simple model User

```java
@Entity
public abstract class User implements Persistable {
    @Key @Generated
    public int id;
    public String name;
    public String email;
}
```

and my Application class looks like this

```java
public SingleEntityStore<Persistable> getData() {
        if(dataStore == null) {
            DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, Util.APP_DB_NAME, 1);
            Configuration configuration = source.getConfiguration();
            dataStore = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
        }
        return dataStore;
    }
```

I created a Repository class that calls this getData from application, and try to found a list of Users. But I saw this message in adb: E/SQLiteLog: (1) no such table: User

I changed the code above removing the database name and no luck again =(

What am I doing wrong? And when I change my model, how can I upgrade my model?

EDIT: Ok, so trying a lot this evening, i figured out this situation, using the code below on my Application class:

```java
dataStore = new EntityDataStore<Persistable>(configuration);
```

The database was created, and the user class load correctly. I think there is some weird problem using the SingleEntityStore on Android. 

There is a way to provide you some log file or other log type for helping you?

**Comment by npurushe** [comment]
Hi when you see something like `E/SQLiteLog: (1) no such table: User` the table didn't exist. I would guess this happened because you added the User after running the app once and db was already existing. 

If you make changes to the @Entity classes you should increment the schema version, in which case it will create missing fields. If you're in the development phase of your app you can also just clear data which will recreate the db with the current schema.

**Comment by feliperaymundo** [comment]
When I first run the app including requery, I added the User entity too
following the android sample (but I used an abstract class not an
interface). Even increasing the database version by 1, using
SingleEntityStore didn't create the table.

**Comment by npurushe** [comment]
Hi thanks for the additional info. What's the first query you make that causes the error, when do you make it? Can you copy paste the stack trace from the adb log?

**Comment by feliperaymundo** [comment]
Sorry for my late reply.

I'm counting how many Users I have stored using dataStore.count(Users.class).get().value(), and the ADB shows:
```E/SQLiteLog: (1) no such table: User```
```I/art: Rejecting re-init on previously-failed class java.lang.Class```

**Comment by npurushe** [comment]
Can you set `setLoggingEnabled` on your `DatabaseSource` and log the sql statements in adb? That would indicate if the create table statement is not executed in your case. There is a lock in getWritableDatabase() that ensures the onCreate method of SQLiteOpenHelper runs to ensure the db schema is created before you use it so strange any table would be missing.

**Comment by feliperaymundo** [comment]
I Will post it to you tomorrow.

**Comment by feliperaymundo** [comment]
Sorry for my late response. I published an example in my github, the link is: 
https://github.com/feliperaymundo/RequeryIssue

The messages on my emulator (in device are the same) is:

```
04-15 13:38:20.409 9436-9436/? E/SQLiteLog: (1) no such table: User
04-15 13:39:22.669 10416-10416/com.example.felipe.requeryissue I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-15 13:39:22.669 10416-10416/com.example.felipe.requeryissue I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-15 13:39:22.696 10416-10416/com.example.felipe.requeryissue I/requery: beforeExecuteQuery io.requery.android.sqlite.SqliteStatement@dfdab2e sql: select count(*) from User 
04-15 13:41:12.455 12030-12030/com.example.felipe.requeryissue I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-15 13:41:12.455 12030-12030/com.example.felipe.requeryissue I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-15 13:41:12.508 12030-12030/com.example.felipe.requeryissue I/requery: beforeExecuteQuery io.requery.android.sqlite.SqliteStatement@dfdab2e sql: select count(*) from User```

**Comment by npurushe** [comment]
Hey thanks for the example project that helped a lot. Basically the problem is the same as described here  http://stackoverflow.com/questions/28385069/sqliteopenhelper-setwriteaheadloggingenabled-causes-an-error-log-line so moved enabling of write ahead logging to after the db is created

**Comment by npurushe** [comment]
The beta15 version contains this fix
