### ISSUE TITLE
Generated Kotlin entity allows nulls

### ISSUE THREAD

**Issue by absimas** [requery/requery#630]
I have this entity in Kotlin:

```
@Entity
interface Child {
  var string: String
}
```

And would expect the generated `ChildEntity` not to allow nulls or at least annotate the setter. Instead, I can freely set it to null:

```
val child = ChildEntity()
child.string = null
```

I also tried the following annotations to no avail:
```
@set:NonNull
@get:NonNull
@get:android.support.annotation.NonNull
@set:android.support.annotation.NonNull
```

Is there any other way or could something be done about this before compilation or at least during runtime?

**Comment by npurushe** [comment]
This is because ChildEntity is a java object. If you do the following then it won't allow nulls:

```kotlin
val child = ChildEntity() as Child
child.string = null // fails
```

In a future version Kotlin code itself will be generated if the target project is kotlin, this will simplify this use case. Hope that helps

**Comment by absimas** [comment]
I see. Thank you for clarifying.
