### ISSUE TITLE
Question: Using entity relationships

### ISSUE THREAD

**Issue by christianCallelero** [requery/requery#631]
Hi I'am new to Requery ORM. Im finding it quite hard to understand which way is the best to do relationships with. For example I have a User table and a Car table. Lets make the relationship just one to one. My entity class would be like this

public class AbstractUser{
    @key
    @generated
    int id;

    String name;
    @OneToOne
    Car car;
}
For my Car entity class

public class AbstractCar{
    @key
    @generated
    int id;

    String carName;
}
So my question is:

-What is the best way to Update Car table?

-How do I select Car data from User?

What I have tried:

-Updating the Car table using itself. By doing this when I'm selecting the details of Car by using User it returns null. I think it means that the Car data of the User table is not updating when the Car Table gets updated.

Ex. User.getCar().getCarName();

**Comment by Agraphie** [comment]
Hi there,

just as quick reminder, you can format a whole block of code with 
````Text
```Java
public class AbstractUser{
@key
@generated
int id;

String name;
@OneToOne
Car car;
}
```
````
To answer your questions, here is a short example. Everything else however is well documented and you can really just expand it as you wish https://github.com/requery/requery/blob/master/README.md

```Java
//Create a new car and insert it
CarEntity carEntity = new CarEntity();
carEntity.setCarName("Porsche");
store.insert(carEntity);

//create a new CarUser and insert it
CarUserEntity carUserEntity = new CarUserEntity();
carUserEntity.setName("Mr. Fancy Pants");
store.insert(carUserEntity);

//now let us link them together and update the previous entity
carUserEntity.setCar(carEntity);
store.update(carUserEntity);

//Let's find the first (or null) CarUser who has a ferrari. This is SQL syntax and can really be expanded as you wish.
CarUserEntity carUserEntity1 = store.select(CarUserEntity.class).where(CarUserEntity.CAR_ID.eq(carEntity.getId())).get().firstOrNull();
```

**Comment by npurushe** [comment]
@Agraphie Thanks for the answer. You can also check out the query examples [wiki](https://github.com/requery/requery/wiki/Query-examples)
