### ISSUE TITLE
Subscribe to specific entity changes

### ISSUE THREAD

**Issue by absimas** [requery/requery#633]
I'm using a select + observableResult to listen changes on all entities of some specific entity:
```
store.select(DataEntity::class)
    .get()
    .observableResult()
    .subscribe {
      val items = it.toList()
      ...
    }
```

Is there any way to listen only to the entities that changed or were added? The above method returns all the entities including those that haven't changed.

**Comment by Agraphie** [comment]
HI there,

is #535 what you are after? What you are doing is basically just a select query. Then you subscribe to the result. This will not produce an infinite stream of items, but rather turn the result of a SQL query into an observable.

**Comment by absimas** [comment]
Hi @Agraphie.
I saw that post but couldn't understand how such listener would help me.
It says which types entity types were modified but what I want is to get the actual entities that were modified.

**Comment by Agraphie** [comment]
Ah right, got it, sorry. I'm only aware of one way to hook into the process; with the `@PostUpdate` or `@PreUpdate`. You can add these methods to your entity class and then call your required method from there. I think it's not an optimal solution though. I guess @npurushe will shed some light on this.

**Comment by npurushe** [comment]
The change notification isn't granular to just a single object, it's at the type level so it will fire when a change that could affect entities of the given type happens. You should instead narrow your query down to something specific if possible rather than selecting the whole table. Hope that helps
