### ISSUE TITLE
Transient abstract class methods

### ISSUE THREAD

**Issue by absimas** [requery/requery#634]
Annotating a method with `@Transient` doesn't prevent custom method generation in the entity.

```
@Entity
public abstract class Data {
  @Key
  @Generated
  abstract long getId();

  @Transient
  public Data copy() {
    return null;
  }
}
```
Generates this entity:
```
public class DataEntity extends Data implements Persistable {
    ...
    
    private Data copy;

    @Override
    public Data copy() {
        return this.copy;
    }

    public void copy(Data copy) {
        this.copy = copy;
    }
    
    ...
}
```

I hoped the method would stay unmodified and no new fields created or does `@Transient` not work for methods?

**Edit:**
This kotlin class generates a correct entity:
```
@Entity
abstract class Data {
  @get:Key
  @get:Generated
  abstract val id: Long

  @Transient
  fun copy(): Data? {
    return null
  }
}
```
However, when it overrides an interface's method it fails just like with a java class:
```
interface Copyable {
  fun copy(): Data?
}

@Entity
abstract class Data : Copyable {
  @get:Key
  @get:Generated
  abstract val id: Long

  @Transient
  override fun copy(): Data? {
    return null
  }
}
```

**Comment by rwhite226** [comment]
I am also having the same issue. My temporary workaround it to make the transient methods final.

**Comment by absimas** [comment]
@rwhite226 too bad this doesn't work for kotlin's abstract classes where all functions can only be open (not final).

**Comment by rwhite226** [comment]
Actually kotlin's abstract classes' methods are final by default unless they are declared open,  abstract, or are overriding a method from another abstract class or interface. So in your example if you mark copy() as final in your second kotlin Data class then requery will not generate a method for it.

**Comment by absimas** [comment]
@rwhite226 ahh my bad. I thought you couldn't explicitly mark methods as final in kotlin. Thanks :)

**Comment by zharf** [comment]
well, I tried marking my methods final but requery still generated overriding methods for them which doesn't actually compile because... well, the method is final. This is currently a blocker for me

**Comment by consp1racy** [comment]
`Entity(copyable = true)` will generate implementation for `copy()`. Don't define it on the actual entity or requery will think it's a property.

**Comment by zharf** [comment]
`copy()` isn't what I'm trying to do, I just want to write some helper functions, but they're being overridden by the annotation processor

**Comment by absimas** [comment]
@zharf seems to work fine for me when functions are final. Care to add an example?

**Comment by consp1racy** [comment]
@zharf Oh, I see. @absimas Hmm, that never worked for me (at least in kotlin and requery 1.3.0). 

Either declare the helper functions as Kotlin extension functions, or if you use pure Java do static helper methods.

**Comment by absimas** [comment]
@consp1racy could it be because your requery is outdated? I'm using 1.4.0.

**Comment by zharf** [comment]
@consp1racy I want to write a polymorphic helper function with different implementations in various entities which makes this a problem for me... currently I'm working around it with `@PostLoad` function

my code: http://2ced516863a5c407.paste.se/

**Comment by absimas** [comment]
@zharf you can't mark methods as final when your models are interfaces. What about converting them to abstract classes? I think you'd need to move the helper method to another interface.

**Comment by zharf** [comment]
@absimas obviously. I tried turning them into abstract classes, that just generated uncompilable code

**Comment by zharf** [comment]
ok, apparently if the helpers are defined by an interface that's not an `@Entity` or `@Superclass` it works, so I can implement another interface in `WaniItem`... it's a little cumbersome and would be nice to have some way of telling requery annotation processor to ignore some functions, but this'll work for now

**Comment by npurushe** [comment]
This will be fixed in the next version thanks for reporting

**Comment by VincentMolinie** [comment]
When is the version coming out ? I really need that fix !
Thanks :)

**Comment by npurushe** [comment]
Hope to release an update soon, but you can always use jitpack to get the latest master version
