### ISSUE TITLE
Add Unique Constraints

### ISSUE THREAD

**Issue by UnflavoredMeson** [requery/requery#639]
Would be nice to have the ability to add Unique Constraints in the Table annotation so we can generate a two field unique.  JPA does it as follows.

```
@Table(
   uniqueConstraints = {@UniqueConstraint(columnNames = {"column1", "column2"})}
)
```

**Comment by npurushe** [comment]
You can do this with [`@Column(unique=true)`](http://requery.github.io/javadoc/io/requery/Column.html#unique--). If you need just one unique constrain over multiple columns then you should use `@Index` combined with [`@Table(uniqueIndexes=)`](http://requery.github.io/javadoc/io/requery/Table.html#uniqueIndexes--). Hope that helps!
