### ISSUE TITLE
Can i use requery in Java project?

### ISSUE THREAD

**Issue by ValeriusGC** [requery/requery#641]
Hi.
Can i use this library in Java?
Can you give me some info to start with?
I try to start in IntelliJ Idea with this code
```
public class Requery {

    public static void main(String[] args) {
        System.out.println("Here we are!");

        Platform platform = new SQLite();
        CommonDataSource dataSource = DatabaseType.getDataSource(platform);

    }

}
```
but Datatype was not recognized. 
Could you be so kind to give me some advice?
Best wishes.

**Comment by npurushe** [comment]
Yes this library is written mostly in java for java and android :) There are examples and test code in the repository.

**Comment by deviant-studio** [comment]
i have this issue too. DatabaseType is not recognized. i use gradle+kotlin+kapt
