### ISSUE TITLE
get empty tableName

### ISSUE THREAD

**Issue by xxxifan** [requery/requery#642]
using this configuration to create tables
```
         val configuration = ConfigurationBuilder(dataSource, Models.DEFAULT)
                .useDefaultLogging()
                .build()
        val tables = SchemaModifier(configuration)
        tables.createTables(TableCreationMode.CREATE)
        KotlinEntityDataStore<Any>(configuration)
```
when it goes to ```tables.createTables(TableCreationMode.CREATE)```, throws an exception:
```java.sql.SQLSyntaxErrorException: ORA-00903: invalid table name```
and I found that generated sql is this:

> INFO: beforeExecuteUpdate HikariProxyStatement@1543312745 wrapping 
> oracle.jdbc.driver.OracleStatementWrapper@35c1a6b5 sql:
> create table (id integer generated always as identity (start with 1 increment by 1) primary key not null, name varchar(255))

there's indeed no table name. then I trace into createTables() method and found that
```
public <T> String tableCreateStatement(Type<T> type, TableCreationMode mode) {
        String tableName = type.getName(); // tableName=""

        QueryBuilder qb = createQueryBuilder();
        ...
```
var tableName is an empty string.

and my model is :
```
@Entity @Table interface User {
    @get:Key @get:Generated var id: Int
    @get:Column var name: String
}
```

**Comment by Agraphie** [comment]
Hi there,

this is maybe because `User` is a reserved table name/keyword. Try giving a custom name to the table in the `@Table` annotation.

**Comment by xxxifan** [comment]
thanks, it is the problem! :+1: 
and I have another question, I'm using Oracle as the database, SchemaModifier is no need to do at every bootup. so at first I use CREATE_NOT_EXISTS as create mode, but it will throw an exception saying that is an invalid option, turns out Oracle does not support create table if not exist, so is there any workaround to do with it?

**Comment by npurushe** [comment]
Hi unfortunately Oracle doesn't support this functionality, you have to choose to drop and recreate the tables for development.

**Comment by xxxifan** [comment]
`offset` is not compatible with oracle either
