### ISSUE TITLE
Dynamic/optional where clause

### ISSUE THREAD

**Issue by pdjstone** [requery/requery#645]
I'm writing some code to dynamically create a query - either with a where clause or without. The problem is that .select returns a Selection<> and .where returns a WhereAndOr<>. I can't find a compatible super type or interface that matches both of those that allows me to continue with orderBy, groupBy, limit etc... The other option is to do something like WHERE 1=1, but again I'm not sure how to do that.

```java
Selection<ReactiveResult<Person>> sel = store.select(Person.class);
??? foo;
if (nameFilter != null) {
    foo = sel.where(Person.NAME.like(nameFilter));
} else {
    foo = sel; // cast or sel.XXX or...?
}
Result<Person> result = foo.orderBy(Person.NAME).get();
```

**Comment by npurushe** [comment]
In this case you should be able to use `SetGroupByOrderByLimit< ReactiveResult <Person>>` as the base type. Hope that helps.

**Comment by pdjstone** [comment]
Thanks, that's what I was looking for.

**Comment by bspradling** [comment]
Sorry for redigging this up, but how would this extend to an optional `limit` parameter?
