### ISSUE TITLE
I have a table defined as:

### ISSUE THREAD

**Issue by embydextrous** [requery/requery#648]
I have a table defined as:

```
@Table(name = "Rooms")
@Entity
interface IRooms : Persistable {
    @get:Column(nullable = false)
    @get:Key
    var roomJid: String

    @get:Column(name = "gameId", nullable = false)
    @get:ManyToOne
    var game: IGames

    @get:Column(name = "creatorJid", nullable = false)
    @get:ManyToOne
    var creator: IProfiles

    @get:Column(nullable = false)
    @get:OneToMany(cascade = arrayOf(CascadeAction.DELETE, CascadeAction.SAVE))
    val players: MutableList<IPlayers>

    @get:JunctionTable
    @get:ManyToMany(cascade = arrayOf(CascadeAction.DELETE, CascadeAction.SAVE))
    val invitedContacts: MutableList<IInvitedContacts>

    @get:Column(nullable = false)
    var lastModified: Long

    @get:Column(nullable = false)
    var isLocked: Boolean

    var nextPlayerJid: String?

    @get:Column(nullable = false)
    var hasGameEnded: Boolean

    @get:Column(nullable = false)
    var isSoloRoom: Boolean
}
```

What I want to do is to delete `isSoloRoom` column and add another column `matchType` defined as:

```
@get:Convert(MatchType.RequeryConverter::class)
var matchType: MatchType?
```

Now, I want to write migration script to remove `isSoloRoom` column and if `isSoloRoom` value is `True` set `matchType` to 'SOLO' else `null`.

What I tried:

I removed `isSoloRoom` column from the Schema above and in `onUpgrade` method I wrote:

`db?.execSQL("UPDATE Rooms SET ('matchType') = ('SOLO') WHERE soloRoom = 1")`

The `matchType` column is successfully added with desired effect but `isSoloRoom` is not removed.

What should I do in order to remove the `isSoloRoom` column and add `matchType` column. Should I remove it from Schema too and from `onUpgrade` script too via sqlite (which would be very hectic to write entire create table) or does requery provides some alternative to it?

**Comment by Agraphie** [comment]
Hi,

requery adds columens automatically, but tables or columns are not dropped. So if you want to remove an attribute and drop the column, you first need to remove the field from the entity and then drop the column. Unfortunately, sqlite does not simply allow you to drop columns. So you need to first move the data you want to a new temporary table, create a new table with the desired columns and then copy the data back and drop the temporary table (you can google these steps).

**Comment by embydextrous** [comment]
Okay. But can I create a single table using requery.

**Comment by Agraphie** [comment]
I'm not sure if I understand your question correctly. Requery creates the schema for you based on your entities. If there is already a schema in place then it will add new columns to the existing schema.

**Comment by embydextrous** [comment]
I have to drop one table only. Is this possible via requery?
