### ISSUE TITLE
 is not it requery bug？Unmodified code launch android app ，apper below error

### ISSUE THREAD

**Issue by ywqyunshan** [requery/requery#649]
1	io.reactivex.exceptions.OnErrorNotImplementedException:Expected 1 row affected actual 0
2	io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
3	......
4	Caused by:
5	io.requery.sql.RowCountException:Expected 1 row affected actual 0
6	io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:176)
7	io.requery.sql.EntityWriter.update(EntityWriter.java:514)
8	io.requery.sql.EntityDataStore.update(EntityDataStore.java:243)
9	io.requery.sql.EntityDataStore.update(EntityDataStore.java:268)
10	io.requery.reactivex.WrappedEntityStore$7.call(WrappedEntityStore.java:129)
11	io.requery.reactivex.WrappedEntityStore$7.call(WrappedEntityStore.java:126)
12	io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
13	io.reactivex.Single.subscribe(Single.java:2703)
14	io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
15	io.reactivex.Observable.subscribe(Observable.java:10842)
16	io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
17	io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
18	io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
19	io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
20	java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by npurushe** [comment]
Hi this would happen if you try to `update` an entity before you `insert`ed it, so most likely it didn't exist in the database. Hope that helps
