### ISSUE TITLE
Integration with lombok

### ISSUE THREAD

**Issue by weisebrazil** [requery/requery#655]
Today I use lombok to generate getters, setters, builders, constructors. Have you ever thing about this integration??

I tried to fixed it, but my fork is blocked by this:
https://github.com/rzwitserloot/lombok/issues/1068

**Comment by Agraphie** [comment]
I just use the annotations on my abstract classes. I don't think it's very clean but it works well.

**Comment by weisebrazil** [comment]
What isn't clean, lombok or yours annotation processor?

**Comment by npurushe** [comment]
Unfortunately it is unlikely this can be combined well with lombok. Requery generates special attribute fields which can be used in queries and other methods, which are beyond the scope of lombok. Also lombok is implemented using byte code modification, requery uses java source file generation. requery entities have generated getters/setters/equals/hashcode as needed so there shouldn't be a need to use both in the same type. Hope that makes sense thanks!
