### ISSUE TITLE
data class instead Interface with OneToOne relations

### ISSUE THREAD

**Issue by SkubievA** [requery/requery#656]
Hi i had data class but then i need to have  @OneToOne relations in my database. 

It used to be:
```
@Entity
data class Image(
        val idImage: Int,
        val url: String,
        val urlAnswer: String,
        val race: String
) : Persistable 
```

Now i have:
```
@Entity
interface Image: Persistable {
    @get:Key
    @get:Generated
    val id: Int

    val idImage: Int
    val url: String
    val urlAnswer: String
    val race: String

    @get:OneToOne(mappedBy = "image")
    val watchedImage: WatchedImage
}
```

But with interface i have class **ImageEntity** it is not conveniently. Because i have dagger2 in my project and inject autoGeneraction variable this dagger2 - bad idea.  (:  Can i use data class with field OneToOne relations? I try to do like this, but i get error.

```
@Entity
class Image constructor(
        val idImage: Int,
        val url: String,
        val urlAnswer: String,
        val race: String
) : Persistable {
    @Key
    @Generated
    var id: Int = 0

    @OneToOne(mappedBy = "image")
    val watchedImage: WatchedImage? = null
}
```
The documentation is really bad about data class Entity. Sorry for my English. :)
Warning:warning: Model has error(s) code generation may fail: image : Immutable value type cannot contain relational references

I really can not do it without interface?

And i get this error:error: 
io.requery.OneToOne not applicable to static or final member
private final error.NonExistentClass watchedImage = null;

**Comment by npurushe** [comment]
Kotlin data classes are immutable and so they cannot have relational links in them, the reasons why are outlined in the wiki article https://github.com/requery/requery/wiki/Immutable-types

You can either
1) use an interface type instead
2) use @ForeignKey and query the One-to-One relation instead.

Hope that makes sense thanks!

**Comment by SkubievA** [comment]
Thanks for answer, but i also can't use requery with dagger2 because codegeneration of requery is after codegeneration dagger2, and dagger2 can't incject dependencies.
