### ISSUE TITLE
Integration of requery and dagger2

### ISSUE THREAD

**Issue by SkubievA** [requery/requery#657]
I understand that i did some kind of duplicate issue. But i really like requery and it can't work with dagger2 for me. I provide dependencis like that:

```
    @Provides
    @Singleton
    @NotNull
    fun provideWatchedImages(databaseSource: DatabaseSource): PersistentDatabase<WatchedImageEntity> =
            PersistentDatabase(WatchedImageEntity::class, KotlinReactiveEntityStore(KotlinEntityDataStore(databaseSource.configuration)))
```

But WatchedImageEntity doesn't generated at the moment when dagger2 generated RequeryModule_ProvideWatchedImagesFactory. And in the end i get error 

> PersistentDatabase<NonExistentClass>
> @org.jetbrains.annotations.NotNull @Singleton @Provides com.skubyev.guesstherace.model.storage.PersistentDatabase<error.NonExistentClass> com.skubyev.guesstherace.di.module.RequeryModule.provideWatchedImages(io.requery.android.sqlite.DatabaseSource)
> 

Are there some kind of fixies this problem? I have to use interface of requery model because i have a lot of relations in database. Thanks! Maybe there are some changes in build.gradle or project settings for fix it?

**Comment by npurushe** [comment]
Yes you need to use interfaces here instead of the generated types.
