### ISSUE TITLE
Requery and JDK 7

### ISSUE THREAD

**Issue by rafoufoun** [requery/requery#66]
Hi,
We have experienced a issue with requery on 2 different computers : 

Machine A : Android Studio with JDK 1.8
Machine B : Android Studio with JDK 1.7

The Machine A can import requery and run the project perfectly.
The Machine B can import requery (gradle sync and build OK) but the app crash at launch with a stacktrace like `java.lang.RuntimeException: Unable to instantiate application fr.lesechos.fusion.DevApplication`
We have tried to import Dagger 2 (which also use the apt plugin) because we though that the issue was here. The app launch was successful.
Switching to JDK 1.8, the app can launch without issues.

Maybe there is a issue with requery compile and JDK 1.7, just for your information :)

**Comment by npurushe** [comment]
Thanks for reporting! The annotation processor is written in Java 8 and needs the Java 8 JRE or JDK to run. I will update the docs to make that clear. Interesting that it even compiled and ran the app though it gradle should fail with a compilation error. If you have the full stack trace that would pinpoint the cause.

**Comment by npurushe** [comment]
Added JDK 8 to the setup guide https://github.com/requery/requery/wiki/Android
