### ISSUE TITLE
"Unresolved reference: Models" Models file still not building.

### ISSUE THREAD

**Issue by Ironthighs** [requery/requery#663]
I am getting the error "Unresolved reference: Models". Others appear to periodically get this and the issues get closed, but I've tried what people have suggested and now I have the gradle build files as shown below, still not working. As suggested by other "solutions", I added the source sets block, I copied the buildscript block to both gradle files, I've tried other things. None of these work. I appreciate any help you can give me. Otherwise I'd like to file this as a bug. Also, I am using Kotlin.

Project build.gradle
    
    buildscript {
        ext.kotlin_version = '1.1.4'
        ext.play_services_version = '26.0.1'
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.0-beta2'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
            mavenCentral()
            maven { url "https://jitpack.io" }
        }
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

Module build.gradle

  
   
     buildscript {
        ext.kotlin_version = '1.1.4'
        ext.play_services_version = '26.0.1'
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.0-beta2'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
        }
    }
    
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply plugin: 'kotlin-android-extensions'
    apply plugin: 'kotlin-kapt'
    apply plugin: 'idea'
    
    sourceSets {
        generated {
            "${buildDir}/generated/source/kapt/main/"
        }
    }
    
    android {
        signingConfigs {
            config {
                storeFile file('C:/Users/dcohen/.android/debug.keystore')
            }
        }
        compileSdkVersion 26
        buildToolsVersion "26.0.0"
        defaultConfig {
            applicationId "net.nelnet.dashboard"
            minSdkVersion 15
            targetSdkVersion 26
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
            vectorDrawables.useSupportLibrary = true
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        dataBinding {
            enabled = true
        }
    
    
    
    }
    
    dependencies {
        implementation fileTree(include: ['*.jar'], dir: 'libs')
        androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
        implementation "com.android.support:appcompat-v7:$play_services_version"
        testImplementation 'junit:junit:4.12'
        implementation "com.android.support:design:$play_services_version"
        implementation 'com.android.support.constraint:constraint-layout:1.0.2'
        implementation "com.android.support:support-vector-drawable:$play_services_version"
        //    implementation "co.uk.rushorm:rushandroid:1.3.0"
        implementation 'com.google.code.gson:gson:2.8.1'
        implementation 'com.squareup.picasso:picasso:2.5.2'
        implementation 'com.github.crosswall:Android-Coverflow:release-v1.0.4'
        implementation "com.android.support:cardview-v7:$play_services_version"
        implementation "com.android.support:recyclerview-v7:$play_services_version"
    
        implementation 'io.requery:requery:1.4.0'
        implementation 'io.requery:requery-kotlin:1.4.0'
        implementation 'io.requery:requery-android:1.4.0' // for android
        annotationProcessor 'io.requery:requery-processor:1.4.0'
    
        version
        kapt "com.android.databinding:compiler:2.3.1"
    }
    
    idea {
        module {
            // https://youtrack.jetbrains.com/issue/IDEA-117540
            excludeDirs -= file("$buildDir")
            excludeDirs += file("$buildDir/dependency-cache")
            excludeDirs += file("$buildDir/libs")
            excludeDirs += file("$buildDir/tmp")
            excludeDirs += file("$buildDir/reports")
            excludeDirs += file("$buildDir/classes")
            excludeDirs += file("$buildDir/kotlin-classes")
            excludeDirs += file("$buildDir/libs")
            excludeDirs += file("$buildDir/test-results")
            sourceDirs += file("${buildDir}/generated/source/kapt/main/")
            generatedSourceDirs += "${buildDir}/generated/source/kapt/main/"
        }
    }

**Comment by npurushe** [comment]
Can you confirm the file is generated in `/generated/source/kapt/main/` ? Also is it a compiler error or just an IDE one? Typically for an Android project you shouldn't need to modify `generatedSourceDirs ` even when using Kotlin

**Comment by Ironthighs** [comment]
This is a compiler error. The folder "main" doesn't exist in `generated/source/kapt/` .

**Comment by Ironthighs** [comment]
Somehow I got Models generating and now my model classes are being made, but the generated Model Entity classes are saying they can't resolve reference to Models now...

**Comment by Ironthighs** [comment]
I'm getting rid of errors and coming up with new ones. This time I'm getting 

![capture](https://user-images.githubusercontent.com/5307306/29480601-153e1072-843f-11e7-9f3a-9a9d03fc45b7.PNG)

I am just following the examples from requery. All of this seems easy enough to use when reading the requery github, but there are just so many problems I'm finding. Please, any help would be greatly appreciated.

    @Entity
    interface StudentModel : Parcelable, Persistable {
            @get:Key
            @get:Generated
            var id: Int
            var studentId : String
            var schoolName : String
            var studentName : String
            var grade : String
            @get:OneToMany(mappedBy = "student")
            var classes : MutableSet<ClassModel>
    }

**Comment by dillius** [comment]
I just began trying to make use of this library in a Kotlin project and am immediately running into the same issue.

Models does not seem to exist, can not be imported, etc...

```
buildscript {
    ext.kotlin_version = '1.1.4'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "java"
apply plugin: "kotlin"
apply plugin: "war"

kapt {
    generateStubs = true
}

sourceSets {
    main.kotlin.srcDirs += "src"
    test.kotlin.srcDirs += "test"
    main.java.srcDirs += "src"
}

repositories {
    flatDir { dirs "lib" }
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile group: 'javax', name: 'javaee-api', version: '7.0'
    compile "com.rometools:rome:1.5.1" //RSS Subscription Tool
    compile "com.fasterxml.jackson.module:jackson-module-kotlin:2.7.1-2" //Serialization
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.7.1" //Serialization
    //compile "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.7.1" //Serialization
    compile "org.xerial:sqlite-jdbc:3.8.11.2"
    compile "com.google.oauth-client:google-oauth-client:1.21.0"
    compile "org.jsoup:jsoup:1.8.3"
    testCompile 'junit:junit:4.11'
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    compile 'io.requery:requery:1.3.2'
    compile 'io.requery:requery-kotlin:1.3.2'
    kapt 'io.requery:requery-processor:1.3.2'
}
```

```
        val dataSource = SQLiteDataSource()
        dataSource.databaseName = link.toString()

        val configuration = KotlinConfiguration(dataSource = dataSource, model = Models.DEFAULT)
        data = KotlinEntityDataStore(configuration)
```

**Comment by dillius** [comment]
I have also found previous notes regarding updating to using the newer kapt implementation and turning off the gradle incremental updater, neither of which has changed my results.

**Comment by kirillkh** [comment]
@dillius you are missing this line:
`apply plugin: 'kotlin-kapt'`

**Comment by kirillkh** [comment]
I have the same problem as @Ironthighs. If I declare the OneToMany property like this:
```
    @get:OneToMany(mappedBy = "restaurant")
    var visits: ArrayList<Visit>
```
then it says "(32, 8) error: RestaurantEntity is not abstract and does not override abstract method setVisits(ArrayList<Visit>) in Restaurant"

And if I declare it like this (which supposedly should produce the equivalent of ArrayList<? extends Visit>):
```
    @get:OneToMany(mappedBy = "restaurant")
    var visits: ArrayList<out Visit>
```
then it says: "warning: Couldn't find referenced element for RestaurantEntity.visits"

**Comment by kirillkh** [comment]
Actually, I ported the model into Java and while it compiles, it errors at runtime, saying that ArrayList is not supported. Apparently, only "List" is supported? I then tried to change the type to "List" in my Kotlin code, and now the Kotlin code compiles and works, too, so it's a workaround.

**Comment by dillius** [comment]
I had added
```
apply plugin: 'kotlin-kapt'
```

I also had to add an explicit inclusion for the directory where the java files were being generated:

```
sourceSets {
    main.kotlin.srcDirs += "src"
    test.kotlin.srcDirs += "test"
    main.java.srcDirs += "src"
    main.java.srcDirs += "build/generated/source/kapt/main"
}
```

**Comment by Ironthighs** [comment]
I am always inching closer and closer, but there are so many issues. I am trying to copy exactly what the requery kotlin example is doing by using a MutableSet but I get the above error that my class is not abstract and does not override abstract method setClasses(Set<ClassModel>) etc. When I change MutableSet to List<ClassModel> it compiles. Below are my two models:

Student

    @Entity
    interface Student : Parcelable, Persistable {
        @get:Key
        @get:Generated
        var id: Int
    
        var studentId : String
        var schoolName : String
        var studentName : String
        var grade : String
    
        @get:OneToMany(mappedBy = "student")
        var classes : MutableSet<Course>
    }

Course

    @Entity
    interface Course : Parcelable, Persistable {
        @get:Key
        @get:Generated
        var id: Int
        var className : String
        //var studentGrade : List<String>
        var unitsForSemester : String
        var letterGrade : String
    
        @get:ForeignKey
        @get:ManyToOne
        var student : Student
    }

**Comment by npurushe** [comment]
Hi you should use `val` instead of `var` for relational collections. See #438 for why this is. Thanks!

**Comment by kirillkh** [comment]
Thanks @npurushe, that works for me. Still, it would be better if requery showed a clearer error message about this, because a lot of people seem to fall into this trap.
