### ISSUE TITLE
How do I suppress reserved word warnings?

### ISSUE THREAD

**Issue by ninjudd** [requery/requery#664]
I'm getting warnings from requery about reserved words for a transient property in Kotlin.

Here is the relevant code:

```
data class Transaction(

  ...

  @get:JsonProperty("user")
  @get:Transient // Requery warns even though this is transient :(
  val user: User? = null
)
```

And this is the warning I get:

```
w: /Users/.../model/Transaction.java:66: warning: Column or index name user may need to be escaped
w: 
w:     public final co.bird.model.User getUser() {
```

Is there a way to suppress (or fix) this warning? Thanks!

**Comment by ninjudd** [comment]
This is related to #102

**Comment by npurushe** [comment]
Good catch thanks, this will be fixed in the next release

**Comment by npurushe** [comment]
1.4.1 has this fix thanks
