### ISSUE TITLE
KotlinCompletableEntityStore questing about async query execution

### ISSUE THREAD

**Issue by daMupfel** [requery/requery#665]
Hi there,

I was just going through the KotlinCompletableEntityStore and was wondering what this method in CompletableResult is for?

```
fun toCompletableFuture(): CompletableFuture<out Result<E>> = CompletableFuture.supplyAsync(Supplier { this }, executor)
```

I do understand the other signature, since you can execute the query inside another thread. But this just returns this, and if i use this value to get a query result, only than it will evaluate the query (I thought that is what the Result type is for)?

Have i some kind of missunderstanding?

Thank you so much for this project!

Best Regards

**Comment by npurushe** [comment]
Hi thanks good catch that function doesn't make sense on it's own and probably should be removed.
