### ISSUE TITLE
No such table SQLite on Android

### ISSUE THREAD

**Issue by channguyen** [requery/requery#666]
I just tried to get a simple example to work on Android. Unfortunately, I keep getting this error when perform an insert operation. 
This is how I initialize Kotlin data source.
 ```
val source = DatabaseSource(context, Models.DEFAULT, 1)
 source.setTableCreationMode(TableCreationMode.DROP_CREATE)
 source.setLoggingEnabled(true)
 source.setWriteAheadLoggingEnabled(true)
 return KotlinReactiveEntityStore(KotlinEntityDataStore(source.configuration))
```
Any idea?

**Comment by npurushe** [comment]
Please post the full exception with a stack trace, thanks.

**Comment by huzzoid** [comment]
Same problem with same initial config (this code in application onCreate method, that extends MultiDexApp). 

On of my model:
```
@Entity
interface RqAccountType : Persistable {
    @get:Key
    var id: Long
    var typeName: String?
    var platform: String?
}
```
What i'm doing on first activity start:
```
...
db.toBlocking()
                            .delete(RqAccountType ::class)
                            .get()
                            .value()
...
```

```
09-22 10:24:24.706 5770-5871/huzzoid.me.bcs_connect I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
09-22 10:24:24.706 5770-5871/huzzoid.me.bcs_connect I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.BaseScalar$1>
09-22 10:24:24.755 5770-5871/huzzoid.me.bcs_connect E/SQLiteLog: (1) no such table: RqAccountType
```

I have no idea why, but it happens only on my real android devices with API 21+ (no tested on older versions yet).

**Comment by huzzoid** [comment]
Update:
I tried to log all database table names and found that i have old db schema despite of complete deleting the app from device. 
I have no root access tom make sure that application files is not there after deleting.

**Comment by huzzoid** [comment]
Ok. Init with non-default filename solved the problem
`DatabaseSource(context, Models.DEFAULT, "my_database", 1)`
