### ISSUE TITLE
raw queries close connections?

### ISSUE THREAD

**Issue by daMupfel** [requery/requery#669]
I was trying to use raw queries inside a transaction.

I was wondering for a long time why the connection always closed after a raw query.

It seems to be because of this:
The `SelectResult` type has a check like this:
```java
closeConnection = !(connection instanceof UncloseableConnection);
```
But the `TupleResult` always closes the underlying connection.

Is this intended or am i missing something?

Best regards

**Comment by npurushe** [comment]
That particular change was to work around an issue in the test cases for transactions. If the connection type is `UncloseableConnection` close() won't have any affect on it. Are you getting any exception? is your TupleResult connection a `UncloseableConnection`?
