### ISSUE TITLE
ArrayLists created from GSON not being persisted

### ISSUE THREAD

**Issue by dabx** [requery/requery#67]
I am having an issue where other models used in the main model are not being persisted to the SQLite database.

I have my models set up like so:

```java
@Entity
public abstract class AbstractStudent {
    @Key
    @SerializedName("_id")
    String username;
    @OneToMany(mappedBy = "studentOwner", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Event> events;
}
```

```java
@Entity
public abstract class AbstractEvent {
    @Key
    @Generated
    int eventId;
    String startTime;
    String endTime;
    @OneToOne(mappedBy = "eventOwner", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    Staff staff;

    @ManyToOne
    Student studentOwner;
}
```

```java
@Entity
public abstract class AbstractStaff {
    @Key
    @Generated
    int staffId;
    String firstName;
    String surname;

    @OneToOne
    Event eventOwner;
}
```

The `Student` class is populated by Retrofit/GSON, and on receiving the Student response, I am inserting to the database using `mDataStore.insert(student).toObservable()`.

When subscribing to that observable and looking at the Student object in the debugger, the states of all the fields apart from the events `List` are `LOADED`, but the state of the events `List` is `null`. 

Looking at the SQLite database using a viewer shows that the `Student` was inserted, but all other tables are empty.

The following also appears in the logcat when trying to save it.

```
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
```

Just wondering if this is a setup error/misunderstanding on my part? Thanks!

**Comment by npurushe** [comment]
Hi thanks for reporting and the detailed description. Before you insert the entity, are the Event's in the list? If you set a break point there you should see the list be a `io.requery.util.ObservableList` that has a member `observer` of type `CollectionChanges` with all your events to be persisted, is that the case? Thanks

**Comment by dabx** [comment]
Ah, it appears GSON is creating an `ArrayList` for `events` instead of the `io.requery.util.ObservableList` you mentioned.

Is there a way to convert an `ArrayList` to `ObservableList` so that it can be stored?

**Comment by npurushe** [comment]
Oh ok that's interesting, let me look at the gson source code and see how it works. I think there might be a couple of solutions:
1) Allow the ArrayList to be used. This will work ok for inserts, but for updates it will cause all elements in the list to be updated (instead of just the added/removed ones) basically the change tracking feature will be lost in that case.
2) I think GSON has some adapters that allow the creation of the list/set to be delegated to custom code, an adapter like that could be provided to use the `ObservableList` instead

**Comment by dabx** [comment]
GSON has custom type adapters ([example with Realm](https://gist.github.com/cmelchior/1a97377df0c49cd4fca9#file-customtypeadapter-java)). However, I was struggling to see how this could be adapted to create an `ObservableList`, as the constructor requires a `CollectionObserver` as well as the `List`.

**Comment by dabx** [comment]
@npurushe If you allowed ArrayLists to be used for inserts, would doing something like this allow you to obtain an `ObservableList` after it was inserted?

```java
mRetrofitService.doSomeCall()
                .concatMap(response -> mDataStore.insert(response).toObservable());
```

**Comment by npurushe** [comment]
Hi @dabx `ObservableList` is not related to rx Observables, it's just a list wrapper that tracks changes to the list. Still looking into a way to solve this. Just allowing the ArrayList is not enough. The problem with gson is that it sets the private fields through reflection so from the perspective of the library we don't know it was changed and will skip persisting it even. 

There is an issue open to not use fields https://github.com/google/gson/issues/232 but probably won't be fixed. One solution will be to allow the ArrayList and also set @Entity(stateless = true) which will disable change tracking but persist all fields every update

**Comment by KrzysztofWrobel** [comment]
I had some problems with storing GSON deserialised objects. I didn't find perfect solution, but take a look at my response to #73.

**Comment by npurushe** [comment]
Closing `@Entity(stateless = true)` should cover this case. Let me know if there are still problems.
