### ISSUE TITLE
Request with notIn condition

### ISSUE THREAD

**Issue by SkubievA** [requery/requery#670]
I have this function. It should return to me one random element who doesn't exist in List. 

```
`   fun getRandResult(watchedImages: List<Int>): Single<T> = (store select type)
          .where(Image::idImage.notIn(watchedImages))
          .orderBy(Random())
          .limit(1).get().observable().elementAtOrError(0L)`
```

idImage - has **Int** type.

It works and i get one element(`Single<Image>`) but condition notIn(watchedImages) doesn't work.

Do i do this in right way? Maybe is there way easier?

**Comment by npurushe** [comment]
What's the type of `watchedImages`? Also posting the generated sql output would help, thanks!
