### ISSUE TITLE
Request: A way to access transactions with KotlinReactiveEntityStore

### ISSUE THREAD

**Issue by davidsantiago** [requery/requery#671]
We're trying to implement a slightly different handling of transactions using `KotlinReactiveEntityStore`. What we'd like to be able to do is get access to the `transaction()` function of the `KotlinEntityDataStore`. I haven't worked with the Java version of these classes, but it looks like on the Java side, because `io.requery.BlockingEntityStore` implements `Transactionable`, you can get access to the transaction via the `transaction()` method. But I don't see any equivalent way to get this access on the Kotlin side. Working with a `KotlinReactiveEntityStore`, we can get a `io.requery.kotlin.BlockingEntityStore` via `toBlocking()`, but then the Kotlin `BlockingEntityStore` does not implement or extend anything like `Transactionable`. 

We can currently hack this for ourselves by downcasting the `io.requery.kotlin.BlockingEntityStore` interface pointer to the `KotlinEntityDataStore` type. Obviously, this is not a super great solution, and we're not going to use this, but it does show us that we are able to implement the transaction handling that we'd desire this way. 

Would it be possible to get something like `Transactionable` implemented for the Kotlin version of `BlockingEntityStore`, or any other way to get a function like `Transactionable.transaction()`?

**Comment by davidsantiago** [comment]
Also, I meant to say, we'd be happy to submit a PR, if you give us direction on whether and how you would like this to be done.

**Comment by npurushe** [comment]
Yeah makes sense, added via a property. Will be in the next update thanks!

**Comment by davidsantiago** [comment]
Looks great, thank you so much! About when do you expect the next release.
