### ISSUE TITLE
How to return empty result?

### ISSUE THREAD

**Issue by Syjgin** [requery/requery#673]
Can not find method to explicitly return empty result. For example, in QueryRecyclerAdapter I want to return data via 2 requests, but, if first request returns zero count result, second is already meaningless. For now I have to return query with incorrect id (something like `return MainApp.instance?.dataStore?.select(Feat::class)?.where(Feat::id.eq(-1))
                ?.get() as Result<Feat>` to return empty list. Is it possible to return it explicitly?

**Comment by npurushe** [comment]
1.4.1 has a CollectionResult type that can be used as an empty result
