### ISSUE TITLE
Question about QueryLoader

### ISSUE THREAD

**Issue by LipeDuoli** [requery/requery#678]
I'm testing the QueryLoader and I think I'm having the wrong results. I don't now if I make or understand something wrong.

I set it up like this:

```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ...
        getSupportLoaderManager().initLoader(SHOPPING_LIST_LOADER_ID, null, this);
    }
```
On my activity I implement the loader callback
`implements LoaderManager.LoaderCallbacks<Result<Tuple>>`

```java
@Override
    public Loader<Result<Tuple>> onCreateLoader(int id, Bundle args) {
        return new QueryLoader<Tuple>(mData, this) {
            @Override
            public Result<Tuple> performQuery(EntityStore data) {
                ReactiveEntityStore<Persistable> data2 = (ReactiveEntityStore<Persistable>) data;
                
                return data2.select(ShoppingList.ID.as(ShoppingListTuple.SHOPPING_LIST_ID),
                        ShoppingList.NAME.as(ShoppingListTuple.SHOPPING_LIST_NAME),
                        Count.count(Product.SHOPPING_LIST).as(ShoppingListTuple.SHOPPING_LIST_COUNT))
                        .from(ShoppingList.class)
                        .leftJoin(Product.class).on(Product.SHOPPING_LIST_ID.eq(ShoppingList.ID))
                        .groupBy(ShoppingList.ID)
                        .orderBy(ShoppingList.NAME)
                        .get();
            }
        };
    }
```
````java
@Override
public void onLoadFinished(Loader<Result<Tuple>> loader, Result<Tuple> data) {
         mShoppingListAdapter.swapShoppingList(data.toList());
}
````
The problem is, I receive the sql select log (`I/requery: beforeExecuteQuery sql: select a._id as shoppingListId ...`) in `onLoadFinished` when i execute the `data.toList()`, not in `onCreateLoader`. So I think the query is running outside the `QueryLoader loadInBackground`. 
And because this, when I make something like rotate the screen, loader execute only the `onLoadFinished` again, but I think the query is executed again too because I receive the sql log again when I call `data.toList()`.
This is the expected behavior or I make/understand something wrong? Because I think the query was not supposed to be executed again using the loader.

And other thing. If I try to use the `EntityStore` I receive on `performQuery`, I can't make the select because the select return a Object, not a `Result<Tuple>`. And I can't use the `groupBy` and `orderBy` together, because both return a object too. It's correct cast the EntityScore to the implementation that I use on my application? `ReactiveEntityStore<Persistable>` in that case, but I also tried with `EntityDataStore<Persistable>` and get the same results.

thanks.

**Comment by npurushe** [comment]
Hi yes calling toList can cause the query to be executed. If you are using a list it's probably better to have a loader that returns a list as a result instead of the result type itself. Will clarify this in the android module thanks!
