### ISSUE TITLE
Push library to JCenter

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#68]
The library releases only show up on Maven Central/Bintray and not JCenter search.

I know JCenter syncs from Maven Central, but do you have to do anything else to show up in their search? Android has switched to using JCenter rather than Maven Central, so showing up in their search will help with getting more devs using the library.

**Comment by npurushe** [comment]
The library is published to JCenter first and then synced to Maven Central. Which search were you not able to find it in? From this page https://bintray.com/bintray/jcenter ?

**Comment by austynmahoney** [comment]
Sorry about that, apparently their search is terrible and doesn't update quickly when you type or submit. I waited 10 more seconds and the result finally showed up.
