### ISSUE TITLE
Wrong setter name if final property name equals column name

### ISSUE THREAD

**Issue by lehmanju** [requery/requery#681]
I have experienced a weird behavior when defining my properties in Kotlin:
```kotlin
@get:Column(name = "value")
abstract var value0 : String
var value : String
	get() = value0
	set(value)
	{
		value0 = value //do some verification stuff
	}
```
This is an abstract class with a final property "value". The generated entity class, however, is missing a correct set-method if the column name is the same as the name of the final property "value".

This generates:
```java
@Override
public String getValue0() {
    return $proxy.get(VALUE0);
}

public void setValue(String value0) {
    $proxy.set(VALUE0, value0);
}
```
I think the annotation processor should generally ignore final properties as they can not be overridden anyway.

**Comment by consp1racy** [comment]
In the meantime if you need to customize setters use extension methods.

I.e. do not put anything that's not related to persistence in your entity class/interface.

**Comment by lehmanju** [comment]
This is actually my fault. I just have to add ``Transient`` to ``var value`` to stop requery from generating a database entry.
