### ISSUE TITLE
Sources are missing for requery-android on Maven Central

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#69]
[Maven Central](http://search.maven.org/#artifactdetails%7Cio.requery%7Crequery-android%7C1.0.0-beta10%7Caar)
[JCenter](https://jcenter.bintray.com/io/requery/requery-android/1.0.0-beta10/)

For the `requery-android` library `-javadoc.jar` is present, but not `-sources.jar`

Not sure if this is related to this problem, but Android Studio is not importing the source OR javadoc when I include the library in my app. It only shows me the decompiled class when I open the Requery classes.

**Comment by npurushe** [comment]
Thanks for finding that, sources will be in the updated version
