### ISSUE TITLE
Getting SQLiteDiskIOException out in the real world

### ISSUE THREAD

**Issue by noberasco** [requery/requery#694]
Hello everyone,

I'm using requery in one of my projects (https://play.google.com/store/apps/details?id=com.zirak.easytrails).

Everything seems to be working as intended, but I get crash reports with SQLiteDiskIOException from a non-insignificant number of users. Not knowing where else to look for help, here I am ;-)

No matter what I tried, I have not been able to reproduce it on any of my test devices.

Fatal Exception: android.database.sqlite.SQLiteDiskIOException
disk I/O error (code 1034)
[disk_io_error_1034.txt](https://github.com/requery/requery/files/1352382/disk_io_error_1034.txt)
It happens here:
```java
@Entity
public abstract class AbstractLiveRecordingData {
    private static final String TAG = LiveRecordingData.class.getSimpleName();

    private LiveRecordingData THIS = (LiveRecordingData)this;

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    List<LiveRecordingTrackPoint> liveTrackPoints;

    //...fast forward to crash site...

    private void saveLiveTrackPoint(Location location) {
        LiveRecordingTrackPoint trackPoint = new LiveRecordingTrackPoint();

        //...some sets into trackPoint...

        THIS.getLiveTrackPoints().add(trackPoint);
        DataManager.dataStore.insert(trackPoint);
        DataManager.dataStore.update(THIS); // <== HERE
```
Thus after I insert a new child item, when I attempt to update the parent.
Any ideas?

Error 1034 means SQLITE_IOERR_FSYNC, but I don't undestand why it should happen, especially considering previous statements executed just fine, and (according to the crash report) there is plenty of storage space available.

Only particularity, these insert/updates happen in background thread.

These are my requery dependencies in build.gradle:
```
compile 'io.requery:requery:1.3.1'
compile 'io.requery:requery-android:1.3.1'
compile 'io.requery:sqlite-android:3.18.0'
apt 'io.requery:requery-processor:1.3.1'
```
This is not the latest version, but it should not matter, I have been experiencing this with several previous requery versions as well.

This is my DataManager class, which is used to obtain EntityDataStore:
```java
package com.zirak.easytrails.core.appsubsystems;

import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.util.Log;

import com.zirak.easytrails.BuildConfig;
import com.zirak.easytrails.core.datamodel.*;
import io.requery.Persistable;
import io.requery.android.database.sqlite.SQLiteDatabase;
import io.requery.android.sqlitex.SqlitexDatabaseSource;
import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;
import io.requery.meta.QueryAttribute;
import io.requery.sql.Configuration;
import io.requery.sql.EntityDataStore;

import java.io.File;

import static com.zirak.easytrails.core.utils.Assert.Assert;

/**
 * Created by thorin on 12/10/16.
 */

public class DataManager {
    private static final String TAG = DataManager.class.getSimpleName();

    private static final int CURRENT_DB_VERSION = 4;

    private static final EntityModel EASYTRAILS_MODEL = new EntityModelBuilder("EasyTrails")
            .addType(MapServer.$TYPE)
            .addType(Track.$TYPE)
            .addType(TrackSegment.$TYPE)
            .addType(TrackPoints.$TYPE)
            .addType(LiveRecordingData.$TYPE)
            .addType(LiveRecordingTrackPoint.$TYPE)
            .addType(Waypoint.$TYPE)
            .addType(WaypointType.$TYPE)
            .addType(Track_Waypoint.$TYPE)
            .addType(Image.$TYPE)
            .build();

    private static File easyTrailsDBPath = null;
    private static EasyTrailsDatabaseSource source = null;

    public static EntityDataStore<Persistable> dataStore = null;

    public static File dataDir(Context context) {
        File files[] = ContextCompat.getExternalFilesDirs(context, null);
        File docDir = files[0];

        if (docDir == null) {
            docDir = context.getFilesDir();
        }

        if (docDir == null) {
            throw new RuntimeException("Could not locate app data directory");
        }

        docDir.mkdirs();

        return docDir;
    }

    public DataManager(Context context) {
        easyTrailsDBPath = new File(dataDir(context), "EasyTrailsData.sqlite");

        Log.i(TAG, "DataManager: DB PATH: " + easyTrailsDBPath.getAbsolutePath());

        source = new EasyTrailsDatabaseSource(context, EASYTRAILS_MODEL, easyTrailsDBPath.getAbsolutePath(), CURRENT_DB_VERSION);

        Configuration configuration = source.getConfiguration();

        dataStore = new EntityDataStore<>(configuration);

        Assert(dataStore != null, "Should have a working dataStore at this point!");
    }

    private class EasyTrailsDatabaseSource extends SqlitexDatabaseSource {
        public EasyTrailsDatabaseSource(Context context,
                                        EntityModel model,
                                        String name,
                                        int version) {
            super(context, model, name, version);

            setWriteAheadLoggingEnabled(true);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i(TAG, "CREATING DB with model version" + CURRENT_DB_VERSION);

            super.onCreate(db);

            WaypointType.setDefaultWaypointTypes();
            Waypoint.setDefaultWaypoints();
            Track.setDefaultTracks();
        }

        @Override
        public void onUpgrade(final SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i(TAG, "UPGRADING DB FROM VERSION " + oldVersion + " TO VERSION " + newVersion);

            super.onUpgrade(db, oldVersion, newVersion);

            //data model update code goes here
        }
    }
}
```

Thanks in advance for any insight on this issue...

**Comment by npurushe** [comment]
Hi thanks for the detailed report. I haven't seen that error occur myself unfortunately. But based on the info you provided would try the following:
1) Try the latest requery sqlite version which may have important bug fixes
2) Do you have the same issue when setWriteAheadLoggingEnabled is disabled? there are some potential issues with WAL mode which is why it is normally not enabled by default.
2) Do you have any paths in your code that delete or remove the database file? If so it is necessary to make sure there are no other threads or code attempting to perform db operations when that occurs.

**Comment by noberasco** [comment]
Hi @npurushe,

thank you for your answer.


> 1. Try the latest requery sqlite version which may have important bug fixes

Will do, but honestly I do not expect changes on this particular issue.

> 3. Do you have any paths in your code that delete or remove the database file? If so it is necessary to make sure there are no other threads or code attempting to perform db operations when that occurs.

No, this is the main application data base. It gets created / updated (when application starts), but never deleted.

> 2. Do you have the same issue when setWriteAheadLoggingEnabled is disabled? there are some potential issues with WAL mode which is why it is normally not enabled by default.

Care to elaborate on these potential issues? My application actually relies on WAL being enabled; I can turn it off, but it would require some refactoring, so I would rather not do that unless I have compelling reason to.

**Comment by npurushe** [comment]
There are no concrete issues defined, but it does turn up in a number of searches on the error code. It's hard to say, it may have to do with disk corruption or issues with the underlying file system. Unfortunately not much can be done by this library about that so closing for now.

**Comment by noberasco** [comment]
OK, I'm testing a version with WAL disabled.
I'll try and publish an update with the aforementioned changes to check whether it helps.
In the mean time, thank you for your answer.

**Comment by noberasco** [comment]
I updated my app to requery 1.4.0 and disabled WAL, but I'm still observing the same issue.
Same exact error as reported above, experienced by a small but not insignificant number of users.
It does not seem tied to specific devices, I see it on devices from different vendors (Asus, Google, HTC, ...) running different Android versions (from 4.4.4 to 7.1.2).
