### ISSUE TITLE
Delete on upgrade

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#70]
Is there an easy way to clear out the entire database and start fresh?

Some other libraries have a Delete On Upgrade setting in the configuration that is very useful when developing. Most of the time during pre-release development I don't care about upgrading a schema, I just want it deleted.

**Comment by npurushe** [comment]
Currently onUpgrade will attempt to add missing tables/columns but this could be made configurable. You can do this currently extending `DatabaseSource` and overriding onUpgrade with something like:

```java
@Override
public void onUpgrade(final SQLiteDatabase db, int oldVersion, int newVersion) {
    SchemaModifier schema = new SchemaModifier(getConfiguration());
    schema.createTables(TableCreationMode.DROP_CREATE);
}
```
