### ISSUE TITLE
Make query expressions visible in Type object

### ISSUE THREAD

**Issue by mirkoluchi** [requery/requery#702]
**io.requery.meta.Type** internally contains a **Set<QueryExpression<?>> expressions**, which is however not exposed publicly.

Could you please make it visible through a getter on the type interface?

**Comment by npurushe** [comment]
Hi what's the motivation for supporting this?

**Comment by mirkoluchi** [comment]
Hi. 
I am writing some code that generically builds queries on the data model.
That code basically takes as input:
- the class of the entity to query
- the names of the attributes to select. 
If an attribute name is dotted, It implies a 'navigation' into a related entity, which implies a SQL join. 
To be able to specify the join condition, I must use the QueryExpression corresponding to the foreign key. That's why I need them exposed.
Do you have otherwise an alternative approach to specifying the join condition?
