### ISSUE TITLE
Eager fetch relations

### ISSUE THREAD

**Issue by Spierki** [requery/requery#703]
Hey, 

I have seen in other issue that you've the idea of a solution to eager fetch relations. I would like to know if there is any progress on that ?

Currently the fact that relations are lazily fetch with getter is a problem for me because it's done on UIThread. 
I can make the thing work by loading them in the background but is there is @JPA annotation or something like this ?

Thanks in advance,
Florian

**Comment by npurushe** [comment]
Hi yes this still in progress, probably won't be available until version 2.0. However you can always use `Result` as the return type of lazily fetched items, which can be loaded on background threads easily with RxJava. Hope that helps!
