### ISSUE TITLE
Updating column to be primary key

### ISSUE THREAD

**Issue by christianCallelero** [requery/requery#706]
Hi, I have a column i wanted to be a primary key. The problem is the app is in prod. I tried updating the db version and adding @Key. However I notice after updating the app it didnt make the column as primary key. Do I really need to drop the table and just create it again for this to be implemented?

**Comment by npurushe** [comment]
Hi is this for SQLite? Unfortunately SQLite doesn't let you add a primary key constraint after the table has been created. The only way to do this is to create a new table with a constraint and copy old data into the new table.

**Comment by christianCallelero** [comment]
Ah ok, so thats why its not working. Yeah it seems creating a new table
will work. Thank you.
