### ISSUE TITLE
Database file is updated via the Internet

### ISSUE THREAD

**Issue by altairmizuchi** [requery/requery#709]
Hi guys!
Is there a way to download a database file from the Internet resource and then open it with your library?
If I just replace DB file (Context.getDatabasePath(String name)) with newly downloaded can I somehow re-init library?

**Comment by npurushe** [comment]
Hi yes, you should make sure the database file is fully downloaded before accessing it. (Creating the `DatabaseSource`). If you intend to try to replace it you have to make sure the `DatabaseSource` is closed and you have no outstanding references to anything accessing it (queries/cursors etc).
