### ISSUE TITLE
Recommended way to store array of ints

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#71]
The API I work with returns an array of integers. What is the best way to store these with Requery? Realm recommended creating a class that held the primitive (thus creating a FK relation to a table of ints), is that the right solution here?

Something like this:

```
public interface RequeryInt {
    @Key
    int getValue();
}
```

**Comment by npurushe** [comment]
You could do this with [Converters](https://github.com/requery/requery/wiki/Converters). For instance you can define your converter as <int[], String> and then store it as comma separated values and then add that converter to the int[] field.

**Comment by austynmahoney** [comment]
Would I have to use `int[]` and not `List<Integer>`? I'd prefer to use the collection API if at all possible.

What would the converter return from `#mappedType()` for a `List<Integer>` if I created on for it?

Thanks for the quick answers!

**Comment by npurushe** [comment]
Yes you can use any type, basically when you are using Converters you can transform the raw db value (string,int,float etc) into any type you like.

**Comment by austynmahoney** [comment]
Because of Type Erasure, I am not sure how to create a converter for `List<Integer>`. Gson has a class called `TypeToken` that enables List objects of a certain type to be converted. Without something like that, I'm not sure how you would do that in a `Converter`.

http://stackoverflow.com/questions/2390662/java-how-do-i-get-a-class-literal-from-a-generic-type

```java
public class ListLongConverter implements Converter<ArrayList<Long>, String> {
    @Override
    public Class<ArrayList<Long>> mappedType() {
        return ArrayList<Long>.class; // Doesn't compile
    }
}
```

**Comment by npurushe** [comment]
Yeah that's one of the downsides of Java you'll have to use the erased type and cast e.g.

```java
    @Override
    public Class<ArrayList<Long>> mappedType() {
        return (Class)ArrayList.class;
    }

**Comment by austynmahoney** [comment]
Would this map any ArrayList to this Converter, or does it check some other way?

**Comment by npurushe** [comment]
There is now a full example in the test code https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/IntegerListConverter.java
