### ISSUE TITLE
ManyToOne, how  it is works? is Broken?

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#710]
Hi, I'm trying to use ManyToOne relationship withOut OneToMany in the references but is failing for some reason this is my schema in koltin:

`@Entity
interface Transaction:Persistable {

    @get:Key
    @get:Generated
    var idtransaction: Long

    var currency: String

    @get:Column(name = "date_transaction")
    var dateTransaction: Date

    var detail: String?

    var idplace: Long?

    var idplatform: Int?

    var referenceid: String?

    //uni-directional many-to-one association to SysUser
    @get:ManyToOne
    var sysUser: SysUser

    //uni-directional many-to-one association to TransactionStatus
   @get:ManyToOne
    var transactionStatus: TransactionStatus

    //uni-directional many-to-one association to TransactionType
    @get:ManyToOne
    var transactionType: TransactionType

    var deposit: Boolean
    var fee: Double

}`

and for example this is one of the class(entity) reference:
`@Entity
@Table(name="transaction_type")
interface TransactionType :Persistable{

    @get:Key
    @get:Column(name = "idtransaction_type")
    var idtransactionType: Int
    var description: String?
}`

but I notice that the query es wrong:

`eforeExecuteQuery org.postgresql.jdbc.PgStatement@30a9e239 sql:
select idtransaction, currency, date_transaction, deposit, detail, fee, idplace, idplatform, referenceid, sysUser, transactionStatus, transactionType from Transaction `
 and is throwing the exception:

`Unexpected exception in route
io.requery.sql.StatementExecutionException: Exception executing statement: select idtransaction, currency, date_transaction, deposit, detail, fee, idplace, idplatform, referenceid, sysUser, transactionStatus, transactionType from Transaction 
	at io.requery.sql.StatementExecutionException.closing(StatementExecutionException.java:39)`

Is there an example how to use ManyToOne reationship?

regards.

**Comment by steelxtreme** [comment]
Solved by adding annotation

`@get:Column( name="")`

i.e:

`@Entity
interface Transaction : Persistable {

    @get:Key
    @get:Generated
    var idtransaction: Long

    var currency: String

    @get:Column(name = "date_transaction")
    var dateTransaction: Date

    var detail: String?

    var idplace: Long?

    var idplatform: Int?

    var referenceid: String?

    //uni-directional many-to-one association to SysUser
    @get:ForeignKey
    @get:ManyToOne
    @get:Column(name = "idsys_user")
    var sysUser: SysUser

    //uni-directional many-to-one association to TransactionStatus
    @get:ForeignKey
    @get:ManyToOne
    @get:Column(name = "idtransaction_status")
    var transactionStatus: TransactionStatus

    //uni-directional many-to-one association to TransactionType
    @get:ManyToOne
    @get:ForeignKey
    @get:Column(name = "idtransaction_type")
    var transactionType: TransactionType

    var deposit: Boolean
    var fee: Double

}`

**Comment by npurushe** [comment]
Thanks for posting your resolution, closing for now

**Comment by richehmer** [comment]
I received this error message from deployed code (server running locally worked fine). There were a lot of moving parts, but I noticed the deployed code had drop/created a stale entity model. Setting the field name "fixed" the problem, its almost as if switching the name triggered a clean build.
