### ISSUE TITLE
Unidrectional OneToOne

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#714]
Hi,

I have a unidirectional OneToOne mapping and I'm trying to update that association. However, I always (sometimes?) get the exception "io.requery.PersistenceException: 1-1 relationship can only be removed from the owning side" and I'm not entirely sure why and how I can reproduce it.
I figured the owning side is the one who is specifiying `@OneToOne` and `@ForeignKey`. I've also set the cascade actions to `DELETE` and `SAVE`.

Any ideas?

**Comment by npurushe** [comment]
This happens if you are setting the one-to-one relation to null from the non-owning side and then updating it (the owning side is the side with foreign key). When you say unidirectional have you defined the non-owning side to the One-to-One mapping?

**Comment by Agraphie** [comment]
I will close this for now, because I cannot reproduce this issue anymore. If I found a propery way to reproduce it I will re-open this.
