### ISSUE TITLE
'Cannot choose among the following candidates' error

### ISSUE THREAD

**Issue by oleonov** [requery/requery#719]
I want to use delete with `where`, but it seems its not working somewhy. What's wrong?
![2017-11-09 14-28-06](https://user-images.githubusercontent.com/1391018/32603325-5781c2c4-c55a-11e7-8274-35b0f00e425c.png)

**Comment by npurushe** [comment]
How have you defined `data`? possibly you're missing the generic type parameter which can lead to this.
