### ISSUE TITLE
Mapping implementation

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#72]
I'm trying to implement `Mapping` on Android and I am not sure I am doing it right.

Is it okay to create another `Platform` in `DatabaseSource#onCreateMapping`? It looks like it is already created in the constructor, but is marked private. Should this field be `protected` instead?

Also, could a `Mapping` be provided at configuration time using the Builder pattern? It seems unnecessary to create a `DatabaseSource` just to set a `Mapping`.

```
public class ExampleDatabaseSource extends DatabaseSource {
    // Constructors...

    @Override
    protected Mapping onCreateMapping() {
        return new ExampleMapping(new SQLite());
    }
}
```

```
public class ExampleMapping extends DefaultMapping {
    public ExampleMapping(Platform platform) {
        super(platform);
        // Joda Time converters
        addConverter(new LocalDateConverter());
        addConverter(new DateTimeConverter());
    }
}
```

**Comment by npurushe** [comment]
Yes it's ok to create another platform instance. Yup I think this could be improved some will look into it thanks!
