### ISSUE TITLE
Using SQLite views

### ISSUE THREAD

**Issue by zwieback** [requery/requery#721]
Hi.
I want to use SQLite views to optimize queries. Is there any example of using it?

Explanation: in the example requery generates only 2 queries:
```sql
select count(*) from Person
select id, UUID, address, age, birthday, email, name from Person order by lower(name)
```
But if I add one field (linked entity) to the `person_item` layout, for example `person.address.city`:
```xml
<TextView
    android:id="@+id/address"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:text="@{person.address.city}"/>
```
Then requery generates many queries (2 per record):
```sql
select count(*) from Person
select id, UUID, address, age, birthday, email, name from Person order by lower(name)

select address from Person where id =?
select id, city, country, line1, line2, state, zip from Address where id = ?
select address from Person where id =?
select id, city, country, line1, line2, state, zip from Address where id = ?
...
```

**Comment by npurushe** [comment]
You can mark an `@Entity` with `@View` to indicate it maps to a view not a table. However requery can't automatically generate views at this time, that has to be defined in your table create script. Alternatively you could also lazily map fields using RxJava Observables in code.

**Comment by zwieback** [comment]
Thanks, Nikhil.
