### ISSUE TITLE
KotlinEntityDataStore java.lang.IllegalStateException data.insert(entities, keyClass.java) must not be null

### ISSUE THREAD

**Issue by AntonyGolovin** [requery/requery#722]
I have `IllegalStateException` at this line of code https://github.com/requery/requery/blob/master/requery-kotlin/src/main/kotlin/io/requery/sql/KotlinEntityDataStore.kt#L124. 

Non-null `Iterable<K>` was expected as a return type but `null` was returned. 

Library version: 1.4.1.

**Comment by npurushe** [comment]
Hi thanks for reporting, yes this method should return an empty set instead of null in this case
