### ISSUE TITLE
About andrdoid, update some classes, append fields, how to be compatible with old versions

### ISSUE THREAD

**Issue by Aiushtha** [requery/requery#724]
```
//Suppose this is version 1.1
@Entity
interface Person : Parcelable, Persistable {
    @get:Key
    @get:Generated
    val id: Int
    var name: String
    var email: String
    var birthday: Date
    var age: Int
    @get:ForeignKey
    @get:OneToOne
    var address: Address?
    @get:OneToMany(mappedBy = "owner")
    val phoneNumbers: MutableSet<Phone>
    @get:Column(unique = true)
    var uuid: UUID

   //----------------------------------------------
   var company: String  //<--this is version1.2 append field
    
}
```
If the "company" field is added to the business requirements, how to upgrade from 1.1 version gracefully to 1.2?, how to update the database ?

**Comment by npurushe** [comment]
In android you can simply increment the schema version and that field will be added. Note this only works for simple additions mostly, for more complex changes like renaming, changes in constraints you will have create a sql update script as part of the schema upgrade.

**Comment by Aiushtha** [comment]
I see. Thank you for your answer.
