### ISSUE TITLE
Inconsistent INTEGER type mapping with raw queries (at least on Android)

### ISSUE THREAD

**Issue by Magister** [requery/requery#728]
The same column of type INTEGER in raw query can be mapped to Long or to Integer.

The problem occurs because type mapping is stored in `Map` class, and the type mapping method:
https://github.com/requery/requery/blob/14a8ac29a4a97872878ae773fc8c96d3e7c10dbb/requery/src/main/java/io/requery/sql/GenericMapping.java#L249
Just iterates through that map to get mapped type.

Types map looks like this:
```
0 = {AbstractMap$SimpleEntry@8270} "class java.sql.Timestamp" -> "TIMESTAMP"
1 = {AbstractMap$SimpleEntry@8271} "class java.lang.Boolean" -> "BOOLEAN"
2 = {AbstractMap$SimpleEntry@8272} "class java.lang.String" -> "VARCHAR(255)"
3 = {AbstractMap$SimpleEntry@8273} "class java.math.BigDecimal" -> "DECIMAL"
4 = {AbstractMap$SimpleEntry@8274} "float" -> "FLOAT"
5 = {AbstractMap$SimpleEntry@8275} "class java.lang.Double" -> "REAL"
6 = {AbstractMap$SimpleEntry@8276} "interface java.sql.Blob" -> "BLOB"
7 = {AbstractMap$SimpleEntry@8277} "interface java.sql.Clob" -> "CLOB"
8 = {AbstractMap$SimpleEntry@8278} "class java.lang.Byte" -> "TINYINT"
9 = {AbstractMap$SimpleEntry@8279} "short" -> "SMALLINT"
10 = {AbstractMap$SimpleEntry@8280} "class java.lang.Short" -> "SMALLINT"
11 = {AbstractMap$SimpleEntry@8281} "class [B" -> "VARBINARY(null)"
12 = {AbstractMap$SimpleEntry@8282} "class java.sql.Date" -> "DATE"
13 = {AbstractMap$SimpleEntry@8283} "int" -> "INTEGER"
14 = {AbstractMap$SimpleEntry@8284} "class java.lang.Integer" -> "INTEGER"
15 = {AbstractMap$SimpleEntry@8285} "class java.lang.Long" -> "INTEGER"
16 = {AbstractMap$SimpleEntry@8286} "boolean" -> "BOOLEAN"
17 = {AbstractMap$SimpleEntry@8287} "class java.lang.Float" -> "FLOAT"
18 = {AbstractMap$SimpleEntry@8288} "long" -> "INTEGER"
19 = {AbstractMap$SimpleEntry@8289} "byte" -> "TINYINT"
20 = {AbstractMap$SimpleEntry@8290} "class java.sql.Time" -> "TIME"
21 = {AbstractMap$SimpleEntry@8291} "double" -> "REAL"
22 = {AbstractMap$SimpleEntry@8292} "class java.util.Date" -> "DATE"
```
So, you see - SQL INTEGER type corresponds to Long and to Integer java types.

As `Map` does not guarantee consistent iteration order, we get different results in different situations - at least, the same code on API-22 returns Integer, while on API-19 - Long. Maybe there are other factors.

So it's impossible to use raw queries with `Long` or `Integer` fields - app just crashes because of incompatible types.

P.S. for now my work-around was to use custom Mapping class.

**Comment by Magister** [comment]
Well, thanks for fixing, but I'm not sure your solution is good.
`return o1.getName().compareTo(o2.getName());`
would sort Integer first, then Long. As sqlite's INTEGER type can hold 8 bytes, and Java's Integer - just 4 bytes, this can lead to data loss.

It would be more correct to convert sqlite's INTEGER always to Java's Long.

**Comment by npurushe** [comment]
Yup sure will look into a way to prefer long for SQLite
