### ISSUE TITLE
RxJava `observableResult()` accumulating iterators until complete

### ISSUE THREAD

**Issue by maxxx** [requery/requery#731]
I confronted with behavior that query with "observableResult()" will accumulate iterators in itself until close. It can take a lot of memory for long-live observables and cause OOM exception with app crash.

For example select lis of entities:
```
dataStore
.select(CarEntity.class)
.where(CarEntity.DRIVER_ID.eq(driverId))
.get()
.observableResult()
.observeOn(Schedulers.io())
.map(cars -> cars.toList())
.subscribe(...);
```
On every CarEntity related commit 
`.map(cars -> cars.toList())`
will be called which leads to creation of Iterator, see BaseResult.toList() implementation.

So, is there any way to get only current (last) iterator and do not store history of them? Do not use " Queue<CloseableIterator<E>> iterators" at all

**Comment by maxxx** [comment]
i have found that 
`.iterator(0, Integer.MAX_VALUE);`
instead of 
`.toList()`
gives expected behavior

**Comment by npurushe** [comment]
Thanks for reporting will be fixed in the next update
