### ISSUE TITLE
Converters and generics

### ISSUE THREAD

**Issue by a-merkle** [requery/requery#74]
Hi, it's me again. :) I just tried to use a converter for a generic field, e.g.
```java
@Entity
public abstract class TestTable {
	@Column
	@Convert(ValueConverter.class)
	ArrayList<Integer> values;
}
```
```java
public class ValueConverter implements Converter<ArrayList<Integer>, String> {
    @Override
	public Class<ArrayList<Integer>> mappedType() {
		return (Class) ArrayList.class;
	}

...

}
```
Requery generates the class `TestTableEntity` but it doesn't compile because of this line:
```java
new AttributeBuilder<TestTableEntity, ArrayList<Integer>>("values", ArrayList<Integer>.class)
```
Aren't generics supported by converters or am I missing something?

**Comment by npurushe** [comment]
Yup looks like a bug there currently when the type is a collection

**Comment by npurushe** [comment]
Should work in the beta12 version

**Comment by npurushe** [comment]
There is now a full example in the test code https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/IntegerListConverter.java
