### ISSUE TITLE
@SerializedName can't work

### ISSUE THREAD

**Issue by lsqlebai** [requery/requery#740]
@Superclass
interface AbstractBaseBean : Persistable, Serializable {
    @get:Key
    @get:SerializedName("id") 
    var uuid: String
}
genration code lost gson annotation , when i use toJson or fromJson the mapping annotation @SerializedName can't work

**Comment by npurushe** [comment]
Annotations aren't copied from an interface type to the generated code. To work around this you can use an abstract class and add annotations to the fields themselves.
