### ISSUE TITLE
Default field value in kotlin

### ISSUE THREAD

**Issue by absimas** [requery/requery#741]
I'm trying to set a default value to a List field but can only do it in java:

```
@Entity
public class Test2 {

  @Key
  @Generated
  int id;
  @Convert(MutableStringListConverter.class)
  List<String> imageUrls = new ArrayList<>();

}
```

However, in Kotlin:

```
@Entity
abstract class Test {

  @get:Key
  @get:Generated
  abstract val id: Int
  @get:Convert(MutableStringListConverter::class)
  var imageUrls: MutableList<String> = mutableListOf()

}
```

Results in `imageUrls` being skipped as an entity field altogether.

---

```
abstract var imageUrls: MutableList<String>
```
results in the correct form but then, the variable is null upon instantiation:
```
TestEntity().imageUrls == null
```

---

Is there any way I can do this with an abstract entity class in kotlin?

P.S. tried marking the field as open as well as initializing the value in the primary constructor to no avail.

**Comment by masc3d** [comment]
the equivalent to 
```
List<String> imageUrls = new ArrayList<>();
``` 
would be 
```
@JvmField var imageUrls: MutableList<String> = mutableListOf()
```

**Comment by masc3d** [comment]
If you want to use properties, you could use a factory extension method:
```
fun TestEntity.Companion.create(
	imageUrls = mutableListOf()
) =
   TestEntity().also {
      it.imageUrls = imageUrls
   }
```

**Comment by absimas** [comment]
Right. `@JvmField` annotation was exactly what I needed. Thanks @masc3d.
