### ISSUE TITLE
Is there a way to get a list of attributes for an Entity programmatically

### ISSUE THREAD

**Issue by uchennafokoye** [requery/requery#744]
For instance I have `PersonEntity` with a `getId()`, `getName()`, `getAge()`. Is there a way to say something like `PersonEntity.getAttributes()` or `personEntity.getAttributes()`?

**Comment by npurushe** [comment]
Hi the generated entity has a static field called `$TYPE` of type `Type<PersonEntity>` from that you can get a list of [attributes](http://requery.github.io/javadoc/io/requery/meta/Type.html#getAttributes--)
