### ISSUE TITLE
Issues with quering the database

### ISSUE THREAD

**Issue by mario** [requery/requery#746]
Please see screenshots :(
![screen shot 2018-01-15 at 19 45 57](https://user-images.githubusercontent.com/5810/34957184-cbacba12-fa2c-11e7-8585-76cc95b08c1e.png)

**Comment by mario** [comment]
The query is as follows:

    public List getUsers() {
        Result findUsersQueryResult = dataStore.select(User.class).where(UserEntity.SCHEDULED_FOR_DELETION.notEqual
                (true))
                .get();

        return findUsersQueryResult.toList();
    }

**Comment by mario** [comment]
The crashes all happen on Android 8.

**Comment by mario** [comment]
implementation 'io.requery:requery:1.4.1'
    implementation 'io.requery:requery-android:1.4.1'
    annotationProcessor 'io.requery:requery-processor:1.4.1'

**Comment by npurushe** [comment]
Hi in the exception stack trace you should have the statement that is trying to be compiled can you post that here? Thanks

looks like you error is from sqlcipher trying to open the connection not from the actual query itself

**Comment by mario** [comment]
@npurushe I have nothing like that since this is from the Google Play console which I guess doesn't reveal the whole thing. It's strange. 

I also forgot to mention that these errors all happen on One Plus devices (in particular, One Plus 2, One Plus 5, and One Plus 3)

Thanks for coming back to me - I've since moved to 1.5.0, so will see if it happens again.

**Comment by mario** [comment]
1.5 fixes it. Thanks @npurushe.
