### ISSUE TITLE
Cannot use function like max() for NamedExpression

### ISSUE THREAD

**Issue by Magister** [requery/requery#749]
In requery 1.5.0 I cannot use expressions like
```
datastore.select(
    NamedExpression.of("id", Long.class).max().as("max_id"),
    ...
).from(...)...
```
because of symbol `max()` is not found.
In 1.4 everything worked ok.

Looks like that was broken in b5dd28cc05918da5e2964d69a8c5dd53f95bfa33

**Comment by npurushe** [comment]
Thanks for reporting there is a `NamedNumericExpression` that has the right type but the constructor isn't exposed, it can only be created for ints through NamedExpression.ofInteger, will ad d more type options to fix this.

**Comment by Magister** [comment]
But `max()` can also be used for different types, not just numbers. For example, when applied to `String` field it will compare strings alphabetically to get max one.
Why remove it from `NamedExpression`?

**Comment by npurushe** [comment]
The goal was to separate different types of operators based on the expression type, if `max` makes sense on string will look into adding it on the base expression type, thanks!
