### ISSUE TITLE
Entities not building after updating to beta12

### ISSUE THREAD

**Issue by yCarbon** [requery/requery#75]
After upgrading to beta12, my project will no longer build.

I receive the following in the gradle build messages:

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.TypeSpec.classBuilder(Lcom/squareup/javapoet/ClassName;)Lcom/squareup/javapoet/TypeSpec$Builder;
```

I can have `requery`, and `requery-android` at beta12 and `requery-processor` at beta11 and the project will build fine. But upgrading `requery-processor` to beta12 will stop it from building.

**Comment by ZeDzislaw** [comment]
+1

**Comment by npurushe** [comment]
Thanks for reporting. I would guess you have another annotation processor that is depending on an older version of JavaPoet. To work around this I will shadow the dependency in the jar, like Dagger 2 does.

**Comment by npurushe** [comment]
Please try the beta13 version which shadows the JavaPoet depdency
