### ISSUE TITLE
Using NumericExpression/StringExpression with mapped fields

### ISSUE THREAD

**Issue by pdjstone** [requery/requery#752]
In #217 you refactored some methods from the Functional interface into NumericExpression/StringExpression. This has caused some issues for me when moving from Requery 1.4.1 to 1.5.0. 

I'm using Converters to map e.g. java.time.Instant to Long. In 1.4.1 I could do MyEntity.TIMESTAMP.max() but this no longer works because my timestamp field is being generated as a QueryAttribute instead of a NumericAttribute. A similar problem occurs for string operations on fields that map to strings.

I tried casting e.g. ((NumericAttribute<MyEntity, Instant>)MyEntity.TIMESTAMP).max() but this causes java.lang.ClassCastException: io.requery.meta.ImmutableAttribute cannot be cast to io.requery.meta.NumericAttribute.

Any ideas? For now I'm going back to 1.4.1

**Comment by npurushe** [comment]
Hi thanks for reporting will release 1.5.1 shortly with changes to address this.
