### ISSUE TITLE
Documentation. How to setup datasource for postgres?

### ISSUE THREAD

**Issue by bastman** [requery/requery#759]
Could you please add a section in the Wiki that explains how to setup datasources / configurations for different databases (postgres, mysql, ...).

I'm close to giving up advocating for requery, since it lacks that crucial examples. 
I spent a full weekend trying to figure out how to get basic things done. 

Therefore, I'd be glad if you could help me with this.

Thanks
/Seb

**Comment by npurushe** [comment]
Hi this test class includes instantiating the `DataSource` for all major databases 
https://github.com/requery/requery/blob/master/requery-test/src/test/java/io/requery/test/DatabaseType.java#L44
