### ISSUE TITLE
No way to clear the cache of EntityDataStore

### ISSUE THREAD

**Issue by 0xnm** [requery/requery#760]
Say there is an app with "user logged in"/"user not logged in" scopes. And on logout app removes everything from db by simply doing:

SchemaModifier schemaModifier = new SchemaModifier(databaseSource.getConfiguration());
schemaModifier.createTables(TableCreationMode.DROP_CREATE);

So the next time user logs in, fresh data is inserted, no more data from old user exists in db. The issue is, however, that there is an `entityCache` in `EntityDataStore`, which is not accessible outside, hence cannot be cleared. We can access `entityCache` by calling `databaseSource.getConfiguration().getCache()`, but the thing is that `Configuration`, which was used here:

        Configuration configuration = new ConfigurationBuilder(databaseSource, Models.DEFAULT)
                .build();
        store = new EntityDataStore<>(configuration);

is not saved to `databaseSource`, so it will be different configuration, not the same as used in `EntityDataStore`.

Can we have an API to access entity cache from `EntityDataStore` or maybe there is another way of dropping all the tables (I guess it is feasible by calling `databaseSource.close()` and then creating new `DatabaseSource`?)

**Comment by npurushe** [comment]
You should use a new `EntityDataStore` and not reuse it for cases such as that. You could keep a reference to the EntityCache from creating the Configuration and clear it but that would lead to unpredictable side effects.

**Comment by Magister** [comment]
> You could keep a reference to the EntityCache from creating the Configuration and clear it but that would lead to unpredictable side effects.

Hmm.... I do this in my project, what exactly side effect may happen? I did not notice any one so far, maybe missed something?
