### ISSUE TITLE
Documentation about how RxJava support

### ISSUE THREAD

**Issue by molikto** [requery/requery#78]
Hello.

This is just a question not an issue. But can you explain how RxJava query works? Because you said `4) Table changes only` for `Squidb`. As I understand, they will re-run the query everytime things changed in a table. How does your RxJava queries works? Does it rerun the query or do you update the query results incrementally?

**Comment by npurushe** [comment]
requery `toSelfObservable()` works the same way, however it may be improved in the future to apply to only the query criteria. In addition to that any `Result` type can be converted to an `Observable` via `toObservable()` also there is an wrapper class `SingleEntityStore` that returns all operations as rx `Single`

**Comment by npurushe** [comment]
Hope that answers your question! feel free to follow up if that is not clear.
