### ISSUE TITLE
Jackson Nullpointer with Junction table

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#781]
Hi, how can i handle this kind of errors:

io.vertx.core.json.EncodeException: Failed to encode as JSON: (was java.lang.NullPointerException) (through reference chain: com.cps.entity.ClientEntity["clientCities"])

is there a way to put default values or an annotation to allow null values?

**Comment by Agraphie** [comment]
Hi,

can you please provide a (minimal) example of your entities necessary to recreate the issue?

**Comment by steelxtreme** [comment]
Please fell free to close this, is duplicated with #713, I could solved it by defining an interface for the junctiontable : 

`@Entity
@Table(name = "client_city")
interface ClientCity:Persistable {

    @get:Key
    @get:ForeignKey(references = Client::class ,update = ReferentialAction.CASCADE)
    var idclient: Long
    @get:Key
    @get:ForeignKey(references = Country::class ,update = ReferentialAction.CASCADE)
    var idcountry: Long

    @get:Key
    @get:ForeignKey(references = City::class ,update = ReferentialAction.CASCADE)
    var idcity: Long


}`

and in client : 

`    @get:JunctionTable(type = ClientCity::class)
    var  clientCities: List<City>?
`
