### ISSUE TITLE
Basic Usage Problem

### ISSUE THREAD

**Issue by Memorion** [requery/requery#784]
I'm having trouble using requery the way the samples suggest.

for example, the queries like `int count = data.count(Person.class).get().value();` don't work for me because `.get()` returns `Object` instead of `Person`.

I put together the smallest example I could come up with https://github.com/Memorion/requery-issue/blob/master/src/main/java/com/example/Example.java

I'm using requery 1.5.1 in my [build.gradle](https://github.com/Memorion/requery-issue/blob/master/build.gradle)

Thanks in advance!

**Comment by npurushe** [comment]
In your example the parameter types have been erased from the `data` variable:

```EntityDataStore data = new EntityDataStore<Persistable>(configuration);```
should be 
```EntityDataStore<Persistable> data = new EntityDataStore<Persistable>(configuration);```

**Comment by Memorion** [comment]
Thanks! I kind of assumed it was something simple like that
