### ISSUE TITLE
update existing table

### ISSUE THREAD

**Issue by pzhin** [requery/requery#790]
Hi
I have an issue with updating schema. For example, i have such class
```
@Entity
@Table(name = "foos")
abstract class Foo {
    String bar;
}
```
and after some time i decide to add another field
```
@Entity
@Table(name = "foos")
abstract class Foo {
    String bar;
    String baz;
}
```
I expect that it will be added automatically but it did not happend. I call `createTables` somewhere in my initialization code but it do nothing.
```
        SchemaModifier tables = new SchemaModifier(configuration);
        tables.createTables(TableCreationMode.CREATE_NOT_EXISTS);
```
What should i do to add new column? Is it possible to remove columns without manual actions?

Thanks

**Comment by npurushe** [comment]
`TableCreationMode.CREATE_NOT_EXISTS` will only create tables that don't exist, in this case you need to add a column to an existing table, you can use `SchemeModifier.addColumn` for this. Hope that helps thanks!
