### ISSUE TITLE
Creating entities with Kotlin data class

### ISSUE THREAD

**Issue by vadimh77** [requery/requery#791]
Can you provide a sample of a Kotlin data class **with relation** that will generate an entity?

I am able to do that with interfaces but no success with data classes.

Tnx

**Comment by hi4c0ck** [comment]
There lots of limitations with data classes, so interfaces is only way  with kotlin (either, in java interfaces also more flexible then abstract classes )

**Comment by npurushe** [comment]
Yes this would void the immutability of data classes so only columns can be mapped 1:1 on to a data class.
