### ISSUE TITLE
Is requery nonblocking from top to bottom?

### ISSUE THREAD

**Issue by happyyangyuan** [requery/requery#795]
We all know that the JDBC is blocking. Are all threads nonblocking with requery nonblocking api?

**Comment by debop** [comment]
Check out `io.requery.async.CompletableEntityStore` 
If you use Kotlin, you can make custom `suspend` method for non-blocking

**Comment by npurushe** [comment]
There are several options to get non blocking behavior, one option is the Java 8 `CompletableEntityStore`, the others are the RxJava 2.0 `ReactiveEntityStore`. Internally the JDBC API is used which unfortunately is blocking, but this hidden through those APIs through the use of pooled or dedicated threads all of which is configurable of course.
