### ISSUE TITLE
Drop JPA, Use Requery

### ISSUE THREAD

**Issue by debop** [requery/requery#797]
Simple data insert benchmark
Linux Mint 18.3, Java 8, H2 DB

y-axis is ms/op
<img width="481" alt="jpa vs requery insert benchmark" src="https://user-images.githubusercontent.com/1469381/42520281-dad3b636-84a0-11e8-8c40-65333678cdd0.png">

**Comment by npurushe** [comment]
Thanks for the info, might be better to post this in an article/blog post, github issues is for issues with the library, thanks!
