### ISSUE TITLE
Wrong behavior when using var on readonly fields in Kotlin

### ISSUE THREAD

**Issue by lehmanju** [requery/requery#799]
Related to #680

When using the modifier ```var``` instead of ```val``` on implicit or explicit read-only fields, no setter methods get generated if you use abstract classes resulting in an error that they are missing. However, if you use interfaces they will get generated. In both cases Kapt generates method stubs for getters **and** setters.

Requery should result in an error if ```var``` instead of ```val``` is used on read-only fields. This should also apply for interfaces. One just needs to test whether a specific setter is present or not.

Correct behavior would be:
1. test whether field should be read-only
1.1 if it is check for present setters and throw an error *or* 
1.2 overwrite and proceed as normal

Example:
```kotlin
@get:Key
@get:Generated
var id: Int
```
results in (by kapt)
```java
@io.requery.Generated()
@io.requery.Key()
public abstract int getId();

public abstract void setId(int p0);
```
but ```setId()``` wont get overriden because ```id``` is generated and therefore read-only.

**Comment by AndroidDeveloperLB** [comment]
Any way to overcome this?
I get an error: "error: Element "id" is read-only but has setter (Kotlin: change var to val)" .
It was possible before to change the id.
Now I can't. 

Example of what I tried:

```kt
@Entity
interface TLThemeResource : Parcelable, Persistable {
    @get:Key
    @set:Key
    @get:Generated
    var id: Long
...
}
```
