### ISSUE TITLE
Entities beginning with letter "m"

### ISSUE THREAD

**Issue by vtuan10** [requery/requery#8]
I'm having trouble setting up my entity-classes which begin with a 'm':
```
@Entity
abstract class AbstractManufacture {
    @Key
    @Generated
    int id;

    @OneToMany(mappedBy = "manufacture")
    Set<Product> products;
}
```
```
@Entity
abstract class AbstractProduct {
    @Key
    @Generated
    int id;

    @ManyToOne
    Manufacture manufacture;
}
```

Compiling fails with error: "cannot find symbol variable MANUFACTURE" in the generated class "Manufacture".
I looked into the generated class "Product" which seems to have problems generating setters and getters for "Manufacture", the 'm' is missing:

```
public static final Attribute<Product, Manufacture> ANUFACTURE = 
    new AttributeBuilder<Product, Manufacture>("manufacture", Manufacture.class)
   ....
```
and
```
    public Manufacture getAnufacture() {
        return $proxy.get(ANUFACTURE);
    }

    public void setAnufacture(Manufacture anufacture) {
        $proxy.set(ANUFACTURE, anufacture);
    }
```

**Comment by npurushe** [comment]
Thanks for reporting. Fix in progress

**Comment by npurushe** [comment]
Hi this should be fixed in the latest snapshot, problem was bad attempt at detecting mSomething style names. Thanks!
