### ISSUE TITLE
Writing UUID into PostgreSQL results in error

### ISSUE THREAD

**Issue by nlochschmidt** [requery/requery#824]
When I try to save an entity with a `java.util.UUID` field into a Postgres column of type `UUID` I get an error: 
```
org.postgresql.util.PSQLException Caused by: : ERROR: column "id" is of type uuid but expression is of type bytea
```
When stepping through the relevant parts of requery in the debugger, I can see that the platform is correctly detected and the UUID type is registered in https://github.com/requery/requery/blob/1.5.1/requery/src/main/java/io/requery/sql/platform/PostgresSQL.java#L86. However while binding the parameters, the `UUIDConverter` gets invoked and the UUID is converted into a byte array: https://github.com/requery/requery/blob/1.5.1/requery/src/main/java/io/requery/converter/UUIDConverter.java#L45. The platform-specific `UUIDType` is then not invoked at all. Do I need to configure something to make this work correctly?

I am only using a Postgres database, so can I maybe somehow disable the UUIDConverter completely?

I am using requery 1.5.1 and Postgres 10.4.

**Comment by camuthig** [comment]
Can we get a patch release pushed with this fix? I don't know if you have any release cycle plans or not, but it would be really helpful to get this released.

**Comment by hsyed** [comment]
getting with 1.6.0:

```
ERROR: column "customer_id" is of type uuid but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 79
```
