### ISSUE TITLE
Question: is it possible to use upsert to update/insert without an id?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [requery/requery#825]
Supposed I have just 3 fields in a table:

```
@Entity
interface TLPhoneToTheme : Parcelable, Persistable {
    @get:Key
    @get:Generated
    var id: Long
    @get:Index("phone_index")
    @get:Column(unique = true, nullable = false)
    var phoneNumber: String
    var themeId: String
}

```

So `phoneNumber` is unique, and `id` is auto-generated.

What if I want to update/add an item to the table? I don't know the id, because for this I would have to use selection, which loses the point of using `upsert`, as I could know for sure that the item exists, and use `update` instead (all in transaction of course) ...

Is it possible to update/insert without the id in this case?

I tried this:

```
            dataStore.withTransaction {
                for (phoneNumber in phoneNumbers) {
                    val phoneToThemeEntity = TLPhoneToThemeEntity()
                    phoneToThemeEntity.phoneNumber = phoneNumber
                    phoneToThemeEntity.themeId = themeId
                    dataStore.upsert(phoneToThemeEntity).blockingGet()
                }
            }.blockingGet()
```

But if I use this on items that already exist, it say that ` UNIQUE constraint failed`, even though the point for it being unique is that it will use it for the updating of the items...

Or I'm using it incorrectly?

**Comment by npurushe** [comment]
Upsert and generated keys don't really mix see #183

**Comment by AndroidDeveloperLB** [comment]
@npurushe So what is suggested? Do I really have to have a transaction, that will make the query and then update/insert myself, manually?

I thought that maybe Upsert is meant exactly for this...

Is there maybe another API for this scenario?
