### ISSUE TITLE
Please release 1.5.2

### ISSUE THREAD

**Issue by debop** [requery/requery#827]
Hi @npurushe 
Please release 1.5.2, we wait for long time ^^
If you have any problem, I can help you.

**Comment by npurushe** [comment]
Yes this is being worked on there are a few issues to resolve first

**Comment by debop** [comment]
Okay. I hope it works out.

**Comment by tasn** [comment]
Hey, any updates on this? Because requery hasn't been released in a while it's still stuck on Kotlin 1.2 which is causing compatibility issues with other libraries using 1.3...

**Comment by npurushe** [comment]
These changes were included in version 1.6.0
