### ISSUE TITLE
Question: how to have a unique Int key, while the key from outside is actually a string?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [requery/requery#828]
Suppose there is a server that sends us entities that their keys are strings, but as we know, an integer key is better (and can help later with uniqueness for the UI, example is the RecyclerView).

How can we save the entities in a way so that they will have an auto-generated Int key, while the real key from outside (that is unique) is a string?

I know we can have the fields fine ( I mean I know how we can create the table), but how can we save it correctly, and manage them?

I also know that I can do a transaction each time I come up with a new instance of such an entity, that I can make a query about whether its real key exists, and then choose if I should update or insert, but is it the  best approach? 

BTW, I think this is a bit similar to another question I've asked, here: https://github.com/requery/requery/issues/825

**Comment by npurushe** [comment]
I think you want to avoid introducing another key if the object already has a unique key from the server.  If you are using temporary objects you may want to use placeholder prefixes or something to that effect, something you can easily filter on

**Comment by AndroidDeveloperLB** [comment]
But how could I use it in adapter, if it's a String? Isn't there a way to auto-generate an Integer ID on the table that has this unique String ID ? 
Can't I have 2 IDS ?
