### ISSUE TITLE
Prepopulated Database

### ISSUE THREAD

**Issue by Glurt** [requery/requery#83]
I'm interested in using this to replace Realm but I'm wondering if it's possible to partially pre-populate the database with some generic data.

If so could you perhaps add a small example?

**Comment by npurushe** [comment]
Do you mean bundle a prepopulated database in your app or just insert data once when the app first starts? For the latter the example project does that https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/CreatePeople.java

**Comment by Glurt** [comment]
Preferably the former but if that isn't possible I can certainly go the second way.

**Comment by npurushe** [comment]
Sure, although that is something you will do in your app code. You can run a script or code snippet to populate a db and add that db file as an asset in your app. Then on your app first run copy that db file into the data directory. These particular steps aren't provided by this library as it's generally very application specific as what data is inserted and how it's bundled. But requery can map onto any existing sqlite db where ever its from.

**Comment by Glurt** [comment]
I'll go with the second option, there's only a small amount of data I need in there and I'd rather not increase the size of my apk with a bundled sqlite file.

Thanks
