### ISSUE TITLE
Parcelable entity class error

### ISSUE THREAD

**Issue by jnwsczh** [requery/requery#84]
Hope to get your help,But My English is very rotten, do not know can you understand it?Thank you
Entity is `public abstract class Tables implements Parcelable`
Send the Entity：`intent.putExtra("table",tables);`
Receiving the Entity：`TableEntity tables =this.getIntent().getParcelableExtra("table");`
Error info
```
 Caused by: java.lang.IllegalArgumentException: 19140577594376268 is not a constant in 
io.requery.proxy.PropertyState
at java.lang.Enum.valueOf(Enum.java:192)
at io.requery.proxy.PropertyState.valueOf(PropertyState.java:19)
at io.requery.android.EntityParceler.readFromParcel(EntityParceler.java:63)
```
If the Entity is Serializable
The receiving entity will go wrong 
Error info：
$proxy is NULL

**Comment by npurushe** [comment]
Thanks for reporting! looks like a bug

**Comment by jnwsczh** [comment]
Oh oh, looking forward to your update.

**Comment by npurushe** [comment]
After parceling the entity how do you intend to use it? unfortunately right now after parceling it becomes detached from the entity store and can't be updated or persisted again. But that is something that could be changed potentially

**Comment by npurushe** [comment]
Please try the updated beta14 version

**Comment by jnwsczh** [comment]
Thank you .
parceling?I do not know of do not understand .
 I intend to show in the data within the entity in another Activity
It seems that I need to learn English . Haha ☺

**Comment by jnwsczh** [comment]
Hello, 14 version of the same BUG

**Comment by npurushe** [comment]
Hey sorry about that this was because of #86 will update a new build soon that contains the change

**Comment by npurushe** [comment]
The beta15 version contains this fix
