### ISSUE TITLE
toBlocking().value() equivalent migration to AndroidX RxJava2

### ISSUE THREAD

**Issue by mkiisoft** [requery/requery#842]
Hello, guys!

I'm having a code with lots of "toBlocking().value()" over the update() method from SingleEntityStore. I need to know which is the new equivalent over ReactiveEntityStore and I believe ReactiveEntityStore is the new equivalent to SingleEntityStore, right?

BTW, if this is not the best logic to update a record, it would be great to know with ReactiveEntityStore... either if "update()" method it's enough or needs something extra like the blocking value one.

Thanks in advance!

**Comment by npurushe** [comment]
These were replaced with various `blockingXXX` cals e.g. `blockingSingle()`
