### ISSUE TITLE
Examples of Converters

### ISSUE THREAD

**Issue by feliperaymundo** [requery/requery#85]
Good morning, could you please show me an example of how could I use jodatime in android for storing dates and times using requery?And could you lable this as Question, please.

Another suggestion, could you make a wiki page with all issues labeled Question? It will help a lot.

**Comment by npurushe** [comment]
Sure the most asked questions will be added to a section of the wiki. 

For time conversions you want to use the [Converter](https://github.com/requery/requery/wiki/Converters) API. For Jodatime the API is similar to the new Time API in Java 8. So you can look at the requery builtin converts that work on the Java 8 Time API, e.g. [LocalDateTimeConverter](https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/converter/LocalDateTimeConverter.java) as an example on how to do conversions.

**Comment by npurushe** [comment]
Closing this for now, feel free to follow up with any additional questions.
