### ISSUE TITLE
Incorrect assembly of requery-android

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#86]
For compilation of requery-android-1.0.0-beta14 library the old source code is used of 05.04.2016. For example there is no "Resolve #72 onCreateMapping is provided platform instance". But at the same time contains an actual code in requery-android-1.0.0-beta14-source.jar. I found this problem for the version 1.0.0-beta13.

**Comment by npurushe** [comment]
Looks like assembleRelease task is not running, will fix thanks!

**Comment by npurushe** [comment]
The beta15 version contains this fix
