### ISSUE TITLE
Observable Lists

### ISSUE THREAD

**Issue by Glurt** [requery/requery#87]
Could you provide more explanation on returning observables containing lists?

For example: 
`datastore.select(Account.class).get()`

This will return a `Result<Account>` object containing all accounts. I then have two options, _toList()_ which returns a `List<Account>` or _toObservable()_ which returns `Observable<Account>`.

Is there a way of combining both methods to return `Observable<List<Account>>` without using Observable.from()?

**Comment by feliperaymundo** [comment]
Could you provide an example 'bout why you need to do this, because I don't understand. The difference from one to another is an Observable are an RxJava class for binding (I'm using it on  Android)

**Comment by Glurt** [comment]
Let's say I wanted to get a list of all accounts that match the query as an observable. 

How do I do that?

**Comment by feliperaymundo** [comment]
You could achieve this using the toSingle() method.

**Comment by npurushe** [comment]
If you use Observable.from just the List you will get a list that is just emitted once. Is that what you need? Or are you expecting that the List is emitted multiple times based on some criteria?

**Comment by Glurt** [comment]
Currently I'm doing something like:

`return Observable.just(dataStore.select(Account.class).get().toList())`

But if this is what is necessary in order to query for lists, can you really say that you have RxJava support?

**Comment by npurushe** [comment]
Yes because RxJava Observables are about a stream of elements, converting the result into a list first is usually almost always defeating the purpose of using Observable sequences. If you have Observable<Account> then that can be a true sequence over the database result set, while Observable<List<Account>> is not. What's the use case for needing an observable list, and when would the list be emitted again through the Observable?

**Comment by Glurt** [comment]
Ah it appears I've misunderstood, I see that Observable<Account> will actually do what I want. I need to do some more reading around Rx and Observables.

Thanks for clarifying.
