### ISSUE TITLE
Subscribe for changes just work for the first change if unsubscribe is made

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#88]
I'm using requery within my android application, and I've a viewpager hosting Fragments, when the fragment call onViewCreated I create a subscription for PodcastEntity where STARRED field is true:

```java
@Override
public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {

    starredSubscription = getData().select(PodcastEntity.class)
            .where(PodcastEntity.STARRED.eq(true))
            .get()
            .toSelfObservable()
            .subscribe(podcastEntities -> {
                getActivity().runOnUiThread(() -> refreshList(podcastEntities.toList()));
            });
}
```
I store the subscription in a field for later unsubscribing:

```java

@Override
public void onDestroyView() {
    super.onDestroyView();
    if(starredSubscription != null) {
        starredSubscription.unsubscribe();
        starredSubscription = null;
    }
}
```
Because the fragment view gets destroyed as i'm using FragmentPagerAdapter, so I unsubscribe for not running view related methods.

In a toggle button I change the status of my model:
```java
podcast.setStarred(!podcast.isStarred());
getData().update(podcast).subscribe();
```

In the first subscription it gives me all starred models on subscribe success callback, If I toggle any entity status I get another callback with all models less the one I've changed.

The problems comes when I unregister and register for the `starredSubscription` after changed more than 2 entities, for a unknown reason the first callback right after the subscription I get all entities LESS THE FIRST one i've changed, and I hope to receive only the starred ones. But if I call again the method to update more one entity I receive the correct objects in callback.

For a detailed example, let's say I have 5 Podcast object saved in database, which all of those are starred:
Podcast 1 (Starred = True)
Podcast 2 (Starred = True)
Podcast 3 (Starred = True)
Podcast 4 (Starred = True)
Podcast 5 (Starred = True)

If I change Podcast 1 to Starred = False I get the numbers [2, 3, 4, 5] in subscription for starred, if i do it again for number 3 and 4, I get the numbers [2, 5].
If I unsubscribe and subscribe again I receive the [2, 3, 4, 5] numbers in callback, and if I change the number 5 to starred false I receive the 2 only in callback.
In this case I hope in the second subscription to receive the [2, 5], which was the objects that previously was Starred.

It's a bug or I've missed the concept of rx observables?

**Comment by npurushe** [comment]
Hi thanks for reporting. When you unsubscribe and then subscribe again you haven't changed the starred status of any of your elements, in the mean time? If not then the first emitted sequence should be exactly what matches the query just [2,5], if you just run the query first before subscribing to test that, is the query returning just [2,5]?

**Comment by YuriHeupa** [comment]
I'm sure in the mean time I haven't changed the status, before unsubscribing I iterated over this:
```java
getData().select(PodcastEntity.class).where(PodcastEntity.STARRED.eq(true)).get().toList()
``` 
And the result is the same as observable subscription.

**Comment by npurushe** [comment]
In your DatabaseSource try `setLoggingEnabled(true)`, then from the log you can see all the sql statements that are executed. You should see your podcast items star value changed as update statements and then the select query run after, is that the case?

**Comment by YuriHeupa** [comment]
I've change 2 star values to false and this logged:
```
I/requery: beforeExecuteUpdate update Podcast set starred = ? where uuid = ?  sql: update Podcast set starred = ? where uuid = ? 
I/requery: afterExecuteUpdate
I/requery: beforeExecuteQuery select uuid, starred, title from Podcast where starred = ?  sql: select uuid, starred, title from Podcast where starred = ? 
I/requery: afterExecuteQuery
I/requery: beforeExecuteUpdate update Podcast set starred = ? where uuid = ?  sql: update Podcast set starred = ? where uuid = ? 
I/requery: afterExecuteUpdate
I/requery: beforeExecuteQuery select uuid, starred, title from Podcast where starred = ?  sql: select uuid, starred, title from Podcast where starred = ? 
I/requery: afterExecuteQuery
```

**Comment by npurushe** [comment]
That looks correct. Now if you unsubscribe and subscribe again, the result of `select uuid, starred, title from Podcast where starred = ?` will be the same if nothing was changed in the database. Is that true?

**Comment by YuriHeupa** [comment]
If I unsubscribe and subscribe on update success method, the observable receive the correct list, looks the problem comes when I unsubscribe on `onDestroyView` and I subscribe again on `onViewCreated`, this time I receive a strange value.

**Comment by npurushe** [comment]
Sure but unsubscribing/subscribing won't change the result of the query. If you execute just the query manually in onViewCreated does it have what you expect or is that query the same as what you get from the observable?

**Comment by YuriHeupa** [comment]
The query is the same as I get from the observable, even making it manually
in onViewCreated

2016-04-16 1:53 GMT-03:00 Nikhil Purushe <notifications@github.com>:

**Comment by npurushe** [comment]
Can you try again with the beta15 version? Made some changes there to the way the updates are published that may help on this issue.

**Comment by YuriHeupa** [comment]
With the beta15 version now the event receive the correct query, but now i'm getting a lot of ANR's, for avoid this problem I've set this on my observable:
```java
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
```
And now everything is ok.

p.s. Even with older version if I use the above snippet the correct query is sent to observable.

**Comment by npurushe** [comment]
Great! glad its working. Will be sure to cover this in documentation.
