### ISSUE TITLE
Correct datetime types on PostgreSQL

### ISSUE THREAD

**Issue by raphaelm** [requery/requery#894]
Hi,

we're using requery for a project that supports both SQLite and PostgreSQL. We have a few columns that we defined as ``Date`` on Java level which works perfectly with SQLite. However on PostgreSQL, it creates a column of type ``date`` and therefore silently throws all time information away! What is the recommended way to store a datetime with requery on PostgreSQL?

Best
Raphael

**Comment by npurushe** [comment]
You should use `java.sql.Timestamp` which has both a date and timestamp in Postgres
