### ISSUE TITLE
Issue with entity mapping

### ISSUE THREAD

**Issue by miomao656** [requery/requery#9]
Hi i have 

```
@Entity
public interface State {

    @Key
    @Generated
    int getId();

    String getPostCode();

    void setPostCode(String line1);

    String getName();

    void setName(String line2);

    @OneToMany(mappedBy = "state")
    Result<City> getCities();
}
```

```
@Entity
public interface City {

    @Key
    @Generated
    int getId();

    String getPTT();

    void setPTT(String ptt);

    String getName();

    void setName(String name);

    @ManyToOne
    State getState();

    void setState(State state);

    @OneToMany(mappedBy = "city")
    Result<Street> getStreets();
}
```

and 

```
@Entity
public interface Street {

    @Key
    @Generated
    int getId();

    String getName();

    void setName(String name);

    @ManyToOne
    City getCity();

    void setCity(City city);
}
```
 
When i try to compile it just give errors like this 

> Error:(26, 11) Note: mapping: requerytest.CityEntity.state -> requerytest.StateEntity.cities
> Error:(31, 20) Note: mapping: requerytest.CityEntity.streets -> requerytest.StreetEntity.city
> Note: mapping: requerytest.StreetEntity.city -> requerytest.CityEntity.streets
> Note: mapping: requerytest.StateEntity.cities -> requerytest.CityEntity.state
> Note: mapping: requerytest.CityEntity.state -> requerytest.StateEntity.cities
> Note: mapping: requerytest.CityEntity.streets -> requerytest.StreetEntity.city
> Note: mapping: requerytest.StreetEntity.city -> requerytest.CityEntity.streets
> Note: mapping: requerytest.StateEntity.cities -> requerytest.CityEntity.state
> Note: mapping: requerytest.CityEntity.state -> requerytest.StateEntity.cities
> Note: mapping: requerytest.CityEntity.streets -> .requerytest.StreetEntity.city

I can't make out anything from these errors. Am i doing something wrong?

**Comment by gholz** [comment]
I'm having the same error, but they do not break the build and everything works as expected.

**Comment by npurushe** [comment]
Thanks for reporting. I noticed that Intellij is incorrectly reporting the annotation processor [notes](https://docs.oracle.com/javase/7/docs/api/javax/tools/Diagnostic.Kind.html#NOTE) as errors sometimes. Can you post which version of Intellij you are using? thanks

**Comment by miomao656** [comment]
Sometimes it compiles without issue, I am using Android Studio 2.0 beta 5

**Comment by npurushe** [comment]
In the latest snapshot I've removed the note messages for now as they were just purely informational. I'll reopen to followup and create an issue in the Android development tracker/Intellij issue tracker also.

**Comment by npurushe** [comment]
https://code.google.com/p/android/issues/detail?id=201547

**Comment by npurushe** [comment]
Going to resolve this one for now.
