### ISSUE TITLE
Remove ParcelConverter

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#91]
As stated [here](https://developer.android.com/intl/es/reference/android/os/Parcel.html)

> Parcel is not a general-purpose serialization mechanism. This class (and the corresponding Parcelable API for placing arbitrary objects into a Parcel) is designed as a high-performance IPC transport. As such, it is not appropriate to place any Parcel data in to persistent storage: changes in the underlying implementation of any of the data in the Parcel can render older data unreadable.

Therefore it is a bad idea at all to do it like suggested [here](https://github.com/requery/requery/wiki/Android)
> ParcelConverter is a builtin Converter that allows you to easily store Android's Parcelable objects into a SQLite BLOB column. Here's an example of storing an Android Parcelable Location object in an Entity:

So I think the best and least confusing would be to remove the `ParcelConverter` at all.

**Comment by npurushe** [comment]
Yes this true sure, however if you defining your own Parcel class then it lies in your area of control. Will update the documentation about this and if it nots really used then will deprecate it.
