### ISSUE TITLE
Not possible to use autovalue static factory model

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#92]
When trying to insert a model similar to [this](https://github.com/requery/requery/blob/1.0.0-beta14/requery-test/src/main/java/io/requery/test/modelautovalue/Phone.java)

```java
@Entity @AutoValue public abstract class NewTodo {

   @NonNull public static NewTodo create(long id, String task) {
      return new AutoValue_NewTodo(id, task);
   }

   @Key @Generated
   public abstract long id();

   @NonNull public abstract String task();
}
```

its not usable at all. When you set the id to -1 when creating you cant insert it at all.

```java
NewTodo newTodo = NewTodo.create(-1, "task");
      store.insert(newTodo).subscribe(result -> {
         assertThat(result).isEqualTo(newTodo);
      });
````

Leads to this being generated in `NewTodoType`:
```java
new LongProperty<NewTodo>() {
        @Override
        public Long get(NewTodo entity) {
            return entity.id();
        }

        @Override
        public void set(NewTodo entity, Long value) {
            throw new UnsupportedOperationException();
        }

        @Override
        public long getLong(NewTodo entity) {
            return entity.id();
        }

        @Override
        public void setLong(NewTodo entity, long value) {
            throw new UnsupportedOperationException();
        }
    })
```

which immediately throws an `UnsupportedOperationException`.

**Comment by npurushe** [comment]
An @AutoValue class is immutable so if you have a generated key it is not possible to modify the entity to contain the key, so throwing the exception is by design. Instead use the insert [overload](http://requery.github.io/javadoc/io/requery/BlockingEntityStore.html#insert-E-java.lang.Class-) that takes the key type and returns the generated key after insertion but doesn't modify the entity.

**Comment by npurushe** [comment]
[example](https://github.com/requery/requery/blob/master/requery-test/src/test/java/io/requery/test/AutoValueModelTest.java#L132)

**Comment by PaulWoitaschek** [comment]
Thanks!
