### ISSUE TITLE
Support Annotations?

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#97]
I usually face the problem that with all the single classes [here](https://github.com/requery/requery/blob/master/requery/src/main/java/io/requery/rx/SingleEntityStore.java) I simply forget to call `subscribe()` so they don't have any effect.

This can easily be solved by adding the [`@CheckResult`](https://developer.android.com/intl/es/reference/android/support/annotation/CheckResult.html) support annotation.

I would be happy to make a pull request, however that would involve adding the support annotation dependency `compile 'com.android.support:support-annotations:x.y.z'`.

So I wanted to check with you first: Are you fine with that?

**Comment by npurushe** [comment]
The main module is a pure Java library and shouldn't contain any Android specific dependencies. An alternative is JSR-305 @CheckReturnValue and appears to be treated by [Android lint the same as CheckResult](https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/SupportAnnotationDetector.java#293) but requires some experimentation as to wether it can be added without forcing all consumers of the library to now depend on it. Another way is an optional Android only interface. Will research the options and see what is the best.

**Comment by npurushe** [comment]
Will be in the next update works in IntelliJ/Android Studio and Android Lint
