### ISSUE TITLE
Inserting a model with several relationships into db not being observed correctly

### ISSUE THREAD

**Issue by Pr0bability** [requery/requery#98]
Hello,

I have a problem when inserting a model containing several relationships (OneToOne, OneToMany) into the database. First, the message "I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>" is displayed.

On several occasions, mostly when inserting first such item into database, the insertion is not being observed correctly (by that I mean neither onCompleted/onError nor onNext is called in the subscriber subscribed to the insertion).

The model is an abstract class:
```java
public abstract class AbstractMedication implements Parcelable, Persistable {

    @Key @Generated
    int id;

    String name;

    int type;

    int size;

    boolean used;

    int foodInstructions;

    int dosage;

    long startDate;

    long endDate;

    int timeType;

    @OneToOne
    @ForeignKey
    MedicationInterval medicationInterval;

    @OneToOne
    @ForeignKey
    MedicationDays medicationDays;

    @OneToMany(mappedBy = "medication", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<MedicationTimes> medicationTimes;

    @OneToMany(mappedBy = "medication", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<MedicationRefill> medicationRefills;

    @OneToMany(mappedBy = "medication", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<HistoryEvent> historyEvents;
}
```

I have ensured that medicationTimes, medicationRefills and historyEvents all have a link back to the medication (but their not implemented as abstract classes, can the problem be there?).

**Comment by npurushe** [comment]
You can ignore 'I/art: Rejecting re-init' it's a harmless informational message. So you have a subscriber on your insert (an rx.Single) and it's not called, but the the item is inserted into the database?

**Comment by Pr0bability** [comment]
Yes, the weird part is that the subscriber usually works, but sometimes, with completely the same data, it does not. This only ever happened on the first insert, the others worked (so far, but I haven't done extensive testing yet).

**Comment by Pr0bability** [comment]
Tested out subscribing on another thread and on the main thread, both proved to have the same issue.

**Comment by npurushe** [comment]
Are they any messages in the log about 'no such table' or other errors? Possibly similar to #63 ?

**Comment by Pr0bability** [comment]
I have looked through the logs but I haven't seen that. Also, I haven't mentioned the data is actually inserted, as it is in the database, just not observed.

**Comment by npurushe** [comment]
How are you subscribing to the rx.Single with just the `subscribe` method or something else?

**Comment by Pr0bability** [comment]
This is the code:

```java
public void createNewMedication(Medication medication) {
        Log.d("NewMedicationPresenter", "createNewMedication");
        mSubscriptionMedication = mDataManager.newMedication(medication)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(med -> createNewPendingEvent(med)
    }
```

I have tried having the new pending event in onCompleted, but that didn't work either. Actually trying to log all three subscriber methods haven't worked (neither log got shown).

**Comment by npurushe** [comment]
And `newMedication ` just does an insert? Do you ever unsubscribe `mSubscriptionMedication`? that would cause it to not get triggered potentially.

**Comment by Pr0bability** [comment]
Here is the code:

```java
public Observable<Medication> newMedication(Medication medication) {
        return mDatabaseHelper.newMedication(medication);
    }
```

```java
public Observable<Medication> newMedication(Medication medication) {
        return mDb.insert(medication).toObservable();
    }
```

But where would I unsubscribe? I have to react on the insert somehow, the only place I can do that is in the subscriber, which doesn't get called in this instance. It doesn't make sense that an unsubscribe would do this, as it works most of the time.

**Comment by npurushe** [comment]
I mean't do you ever call unsubscribe on your mSubscriptionMedication such as onStop/onPause. The only cases you would not get the subscribe event are a) if you unsubscribe or b) there is an error and onError will be called.

**Comment by Pr0bability** [comment]
Yes, of course, I call unsubscribe on onDestroy (I think). That is the weird part, no method gets called, as I have a log in all three subscriber methods. But only on the first insert.

**Comment by npurushe** [comment]
Sure, glad you found the issue
